import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport:{width:1280,height:900}, storageState:'/tmp/e2e-work/auth.json' });
const page = await ctx.newPage();
await page.goto('https://smarter.poker/hub/club-arena/', { waitUntil:'domcontentloaded', timeout:45000 });
await page.waitForTimeout(8000);
await page.locator('text=CLUB JAQK').first().click().catch(e=>console.log('club click fail', e.message.slice(0,80)));
await page.waitForTimeout(7000);
console.log('URL:', page.url());
await page.screenshot({ path:'/tmp/e2e-shots/arena-01-club.png' });
const txt=(await page.innerText('body')).replace(/\n{2,}/g,'\n');
console.log('BODY (first 1200):\n'+txt.slice(0,1200));
const links = await page.locator('a').evaluateAll(els => els.map(e=>({h:e.getAttribute('href'),t:(e.innerText||'').replace(/\s+/g,' ').slice(0,50)})).filter(x=>x.h&&/table|tourn|game/i.test(x.h)).slice(0,12));
console.log('LINKS:', JSON.stringify(links));
await browser.close();
