import { chromium } from 'playwright';
import fs from 'fs';
const AUTH='/tmp/e2e-work/auth.json';
const b=await chromium.launch({headless:true});
const ctx=await b.newContext({viewport:{width:1280,height:900}, ...(fs.existsSync(AUTH)?{storageState:AUTH}:{})});
const p=await ctx.newPage();
const errs=[];
p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message.slice(0,160)));
p.on('console',m=>{if(m.type()==='error')errs.push('CONSOLE: '+m.text().slice(0,160));});
p.on('requestfailed',r=>errs.push('REQFAIL: '+r.url().slice(-70)+' '+(r.failure()?.errorText||'')));
await p.goto('https://smarter.poker/hub/club-arena/',{waitUntil:'domcontentloaded',timeout:45000});
await p.waitForTimeout(12000);
console.log('URL:',p.url());
console.log('BODY LEN:',(await p.innerText('body')).length);
console.log('HTML LEN:',(await p.content()).length);
console.log('ROOT CHILDREN:',await p.evaluate(()=>document.getElementById('root')?.childElementCount ?? 'no #root'));
console.log('ERRORS:'); errs.slice(0,10).forEach(e=>console.log('  '+e));
await p.screenshot({path:'/tmp/e2e-shots/probe-blank.png'});
await b.close();
