/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * 📄 PDF EXPORT — Document Generation Utilities
 * ═══════════════════════════════════════════════════════════════════════════════
 */

/**
 * Export settlement report as PDF
 */
export async function exportSettlementPDF(data: {
  periodNumber: number;
  year: number;
  startDate: string;
  endDate: string;
  totalRake: number;
  totalBBJ: number;
  clubWires: Array<{
    clubName: string;
    netPlayerPL: number;
    grossRake: number;
    unionTax: number;
    agentCommissions: number;
    finalWire: number;
    direction: string;
  }>;
  agentPayouts: Array<{
    agentName: string;
    rakeGenerated: number;
    commissionRate: number;
    grossCommission: number;
    netPayout: number;
  }>;
}): Promise<Blob> {
  // Generate HTML content for PDF
  const html = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Settlement Report - Period ${data.periodNumber} (${data.year})</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        h1 { color: #4169E1; border-bottom: 2px solid #4169E1; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background: #f5f5f5; font-weight: 600; }
        .positive { color: #22c55e; }
        .negative { color: #ef4444; }
        .summary { background: #f0f4ff; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .summary-row { display: flex; justify-content: space-between; margin: 10px 0; }
        .summary-label { font-weight: 500; }
        .summary-value { font-weight: 700; font-size: 1.2em; }
        .footer { margin-top: 40px; text-align: center; color: #888; font-size: 12px; }
    </style>
</head>
<body>
    <h1> Settlement Report</h1>
    <p><strong>Period:</strong> ${data.periodNumber} | <strong>Year:</strong> ${data.year}</p>
    <p><strong>Period:</strong> ${data.startDate} → ${data.endDate}</p>
    
    <div class="summary">
        <div class="summary-row">
            <span class="summary-label">Total Rake Collected</span>
            <span class="summary-value">${data.totalRake.toLocaleString()}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Total BBJ Contribution</span>
            <span class="summary-value">${data.totalBBJ.toLocaleString()}</span>
        </div>
    </div>

    <h2> Club Wires</h2>
    <table>
        <thead>
            <tr>
                <th>Club</th>
                <th>Net Player P/L</th>
                <th>Gross Rake</th>
                <th>Union Tax</th>
                <th>Agent Commissions</th>
                <th>Final Wire</th>
                <th>Direction</th>
            </tr>
        </thead>
        <tbody>
            ${data.clubWires
              .map(
                (club) => `
                <tr>
                    <td>${club.clubName}</td>
                    <td class="${club.netPlayerPL >= 0 ? 'positive' : 'negative'}">${club.netPlayerPL.toLocaleString()}</td>
                    <td>${club.grossRake.toLocaleString()}</td>
                    <td>${club.unionTax.toLocaleString()}</td>
                    <td>${club.agentCommissions.toLocaleString()}</td>
                    <td><strong>${Math.abs(club.finalWire).toLocaleString()}</strong></td>
                    <td>${club.direction === 'PAY_TO_UNION' ? '→ Pay to Union' : '← Collect from Union'}</td>
                </tr>
            `
              )
              .join('')}
        </tbody>
    </table>

    <h2>Agent Payouts</h2>
    <table>
        <thead>
            <tr>
                <th>Agent</th>
                <th>Rake Generated</th>
                <th>Commission Rate</th>
                <th>Gross Commission</th>
                <th>Net Payout</th>
            </tr>
        </thead>
        <tbody>
            ${data.agentPayouts
              .map(
                (agent) => `
                <tr>
                    <td>${agent.agentName}</td>
                    <td>${agent.rakeGenerated.toLocaleString()}</td>
                    <td>${(agent.commissionRate * 100).toFixed(1)}%</td>
                    <td>${agent.grossCommission.toLocaleString()}</td>
                    <td><strong class="positive">${agent.netPayout.toLocaleString()}</strong></td>
                </tr>
            `
              )
              .join('')}
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Club Arena on ${new Date().toLocaleDateString()}</p>
    </div>
</body>
</html>
    `;

  // Use browser print API to generate PDF
  const blob = await htmlToPdfBlob(html);
  return blob;
}

/**
 * Export hand history to PDF
 */
export async function exportHandHistoryPDF(data: {
  handId: string;
  tableName: string;
  stakes: string;
  date: string;
  players: Array<{ name: string; stack: number; position: string }>;
  actions: Array<{ player: string; action: string; amount?: number; street: string }>;
  result: { winners: string[]; pot: number };
  communityCards: string[];
}): Promise<Blob> {
  const html = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hand History - ${data.handId}</title>
    <style>
        body { font-family: 'Courier New', monospace; padding: 40px; color: #333; font-size: 14px; }
        h1 { color: #4169E1; font-size: 1.5em; }
        .meta { color: #666; margin-bottom: 20px; }
        .section { margin: 20px 0; padding: 15px; background: #f5f5f5; border-radius: 8px; }
        .action { margin: 5px 0; }
        .action-player { font-weight: bold; }
        .action-bet { color: #22c55e; }
        .action-fold { color: #888; }
        .action-raise { color: #ef4444; }
        .cards { font-size: 1.2em; letter-spacing: 2px; }
        .winner { color: #22c55e; font-weight: bold; }
    </style>
</head>
<body>
    <h1> Hand #${data.handId}</h1>
    <div class="meta">
        <p><strong>Table:</strong> ${data.tableName} | <strong>Stakes:</strong> ${data.stakes}</p>
        <p><strong>Date:</strong> ${data.date}</p>
    </div>

    <div class="section">
        <strong>Players:</strong>
        ${data.players.map((p) => `<div>${p.position}: ${p.name} (${p.stack})</div>`).join('')}
    </div>

    <div class="section">
        <strong>Community Cards:</strong>
        <div class="cards">${data.communityCards.join(' ')}</div>
    </div>

    <div class="section">
        <strong>Actions:</strong>
        ${data.actions
          .map(
            (a) => `
            <div class="action">
                <span class="action-player">${a.player}</span>: 
                <span class="action-${a.action.toLowerCase()}">${a.action}${a.amount ? ` ${a.amount}` : ''}</span>
                (${a.street})
            </div>
        `
          )
          .join('')}
    </div>

    <div class="section">
        <strong>Result:</strong>
        <div class="winner">${data.result.winners.join(', ')} wins ${data.result.pot}</div>
    </div>
</body>
</html>
    `;

  return htmlToPdfBlob(html);
}

/**
 * Convert HTML string to PDF blob using print API
 */
async function htmlToPdfBlob(html: string): Promise<Blob> {
  return new Promise((resolve, reject) => {
    // Create a hidden iframe
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);

    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if (!doc) {
      document.body.removeChild(iframe);
      reject(new Error('Could not access iframe document'));
      return;
    }

    doc.open();
    doc.write(html);
    doc.close();

    // Wait for content to render
    setTimeout(() => {
      try {
        iframe.contentWindow?.print();
        // Note: In a real app, you'd use a library like jsPDF or html2pdf
        // For now, we trigger the browser print dialog
        document.body.removeChild(iframe);

        // Return a placeholder blob (actual PDF generation would use jsPDF)
        const blob = new Blob([html], { type: 'text/html' });
        resolve(blob);
      } catch (error) {
        document.body.removeChild(iframe);
        reject(error);
      }
    }, 500);
  });
}

/**
 * Download a blob as a file
 */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export data to CSV
 */
export function escapeCSVCell(value: unknown): string {
  let text = String(value ?? '');

  // Spreadsheet applications execute cells beginning with these characters as
  // formulas. A roster contains user-controlled aliases, usernames and notes,
  // so neutralise the formula while preserving the visible text.
  if (/^[\t\r ]*[=+\-@]/.test(text)) text = `'${text}`;

  return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function buildCSV<T extends object>(
  data: T[],
  columns?: Array<{ key: keyof T; label: string }>
): string {
  if (data.length === 0) return '';
  const cols = columns || Object.keys(data[0]).map((key) => ({ key: key as keyof T, label: key }));
  const header = cols.map((column) => escapeCSVCell(column.label)).join(',');
  const rows = data.map((row) => cols.map((column) => escapeCSVCell(row[column.key])).join(','));
  return [header, ...rows].join('\r\n');
}

export function exportToCSV<T extends object>(
  data: T[],
  filename: string,
  columns?: Array<{ key: keyof T; label: string }>
) {
  if (data.length === 0) return;

  const csv = buildCSV(data, columns);
  const blob = new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, filename);
}

export default {
  exportSettlementPDF,
  exportHandHistoryPDF,
  exportToCSV,
  downloadBlob,
};
