from pathlib import Path
import json,re
work=Path(__file__).parent
def q(x):return '"'+x.replace('"','""')+'"'
def literal(x):return "'"+x.replace("'","''")+"'"
tables={}
for path in [work/'tables.json']:
 for row in json.loads(path.read_text()):tables[row['oid']]=row
funcs={}
for path in [work/'functions.json']:
 for row in json.loads(path.read_text()):funcs[row['oid']]=row
out=['SET check_function_bodies=off;','CREATE SCHEMA auth;','CREATE SCHEMA extensions;',
 'CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE ROLE supabase_auth_admin;',
 'CREATE EXTENSION pgcrypto WITH SCHEMA extensions;CREATE EXTENSION "uuid-ossp" WITH SCHEMA extensions;',
 'SET search_path=public,extensions;']
for schema in sorted({x['schema_name'] for x in funcs.values()}-{'public','auth','extensions'}):out.append('CREATE SCHEMA '+q(schema)+';')
for typ in json.loads((work/'types.json').read_text()):
 name=q(typ['schema_name'])+'.'+q(typ['name'])
 if typ['typtype']=='e':out.append('CREATE TYPE '+name+' AS ENUM('+','.join(literal(x) for x in typ['labels'])+');')
 else:raise RuntimeError('Unhandled domain requires exact constraints: '+name)
defaults=[];constraints=[];indexes=[];seqs=set();identity_seqs=set()
for row in tables.values():
 name=q(row['schema_name'])+'.'+q(row['name']);cols=[]
 if row['relkind'] not in ('r','p'):raise RuntimeError('Non-table requires exact definition: '+name)
 for col in row['columns']:
  line=q(col['name'])+' '+col['type']
  if col['generated']:line+=' GENERATED ALWAYS AS ('+col['default']+') STORED'
  elif col['default']:
   defaults.append('ALTER TABLE '+name+' ALTER COLUMN '+q(col['name'])+' SET DEFAULT '+col['default']+';')
   seqs.update(s if '.' in s else 'public.'+s for s in re.findall(r"nextval\('([^']+)'::regclass\)",col['default']))
  elif col['identity']:
   line+=' GENERATED BY DEFAULT AS IDENTITY'
   identity_seqs.add(row['schema_name']+'.'+row['name']+'_'+col['name']+'_seq')
  if col['notnull']:line+=' NOT NULL'
  cols.append(line)
 out.append('CREATE TABLE '+name+'('+',\n'.join(cols)+');')
 for con in row['constraints'] or []:
  if con['type']=='t':continue # emitted once via exact CREATE CONSTRAINT TRIGGER
  constraints.append((con['type']=='f','ALTER TABLE '+name+' ADD CONSTRAINT '+q(con['name'])+' '+con['definition']+';'))
 for idx in row['unique_indexes'] or []:indexes.append(idx['definition'].rstrip(';')+';')
for seq in sorted(seqs):out.append('CREATE SEQUENCE '+'.'.join(q(x) for x in seq.split('.'))+';')
for seq in json.loads((work/'sequences.json').read_text()):
 name=seq['schema_name']+'.'+seq['name']
 if name not in seqs|identity_seqs:
  out.append('CREATE SEQUENCE '+q(seq['schema_name'])+'.'+q(seq['name'])+' AS '+seq['type']+
   ' INCREMENT '+str(seq['seqincrement'])+' MINVALUE '+str(seq['seqmin'])+' MAXVALUE '+str(seq['seqmax'])+
   ' START '+str(seq['seqstart'])+' CACHE '+str(seq['seqcache'])+(' CYCLE' if seq['seqcycle'] else ' NO CYCLE')+';')
for row in funcs.values():out.append(row['definition'].rstrip().rstrip(';')+';')
out+=defaults
out+=[x[1] for x in sorted(constraints,key=lambda x:x[0])]+indexes
for trg in json.loads((work/'triggers-round-3.json').read_text()):
 if trg['function_oid'] not in funcs:raise RuntimeError('Missing trigger function '+trg['tgname'])
 out.append(trg['definition'].rstrip(';')+';')
 if trg['tgenabled']=='D':out.append('ALTER TABLE '+trg['table_name']+' DISABLE TRIGGER '+q(trg['tgname'])+';')
 elif trg['tgenabled']=='A':out.append('ALTER TABLE '+trg['table_name']+' ENABLE ALWAYS TRIGGER '+q(trg['tgname'])+';')
 elif trg['tgenabled']=='R':out.append('ALTER TABLE '+trg['table_name']+' ENABLE REPLICA TRIGGER '+q(trg['tgname'])+';')
for row in tables.values():
 name=q(row['schema_name'])+'.'+q(row['name'])
 if row['relrowsecurity']:out.append('ALTER TABLE '+name+' ENABLE ROW LEVEL SECURITY;')
 if row['relforcerowsecurity']:out.append('ALTER TABLE '+name+' FORCE ROW LEVEL SECURITY;')
out.append("SELECT 'native schema catalog loaded, not lifecycle execution proof' AS stage;")
(work/'schema.sql').write_text('\n'.join(out)+'\n')
print('Built isolated catalog fixture:',len(tables),'tables,',len(funcs),'functions,',len(json.loads((work/'triggers-round-3.json').read_text())),'triggers')
