-- Production table definitions (columns, defaults, CHECK/PK/UNIQUE constraints and indexes; no foreign keys, triggers or rows)
-- captured read-only from kuklfnapbkmacvwxktbh on 2026-09-28 for the weekly-close-scale harness.
CREATE TABLE public.accounting_cash_accrual_cutover(singleton boolean DEFAULT true NOT NULL, starts_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);
CREATE TABLE public.accounting_cash_bank_receipts(rake_record_id uuid NOT NULL, union_id uuid, club_id uuid NOT NULL, union_transaction_id uuid, club_ledger_id uuid, banked_at timestamp with time zone NOT NULL, amount numeric NOT NULL);
CREATE TABLE public.accounting_cash_rake_sources(id uuid DEFAULT gen_random_uuid() NOT NULL, rake_record_id uuid NOT NULL, player_id uuid NOT NULL, club_id uuid NOT NULL, union_id uuid, coordinator_union_id uuid, earned_at timestamp with time zone NOT NULL, rake_credit numeric NOT NULL, contract jsonb NOT NULL, recorded_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);
CREATE TABLE public.accounting_invoice_counters(year integer NOT NULL, next_number bigint NOT NULL);
CREATE TABLE public.accounting_invoice_deliveries(invoice_id uuid NOT NULL, recipient_id uuid NOT NULL, message_id uuid NOT NULL, notification_id uuid NOT NULL, delivered_at timestamp with time zone DEFAULT now() NOT NULL, delivery_mode text DEFAULT 'immediate'::text NOT NULL);
CREATE TABLE public.accounting_rakeback_period_calculations(id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, period_id uuid NOT NULL, accounting_version integer DEFAULT 2 NOT NULL, source_fingerprint text NOT NULL, club_id uuid NOT NULL, player_id uuid NOT NULL, coordinator_union_id uuid, period_start date NOT NULL, period_end date NOT NULL, rake_generated numeric NOT NULL, rakeback_amount numeric NOT NULL, display_rate numeric NOT NULL, payer_kind text NOT NULL, payer_user_id uuid, source_allocations jsonb NOT NULL, recorded_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);
CREATE TABLE public.accounting_routed_settlement_runs(union_id uuid, period_start timestamp with time zone NOT NULL, period_end timestamp with time zone NOT NULL, round_no integer NOT NULL, routing_version integer DEFAULT 3 NOT NULL, source_fingerprint text NOT NULL, result jsonb NOT NULL, completed_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL, standalone_club_id uuid, scope_kind text GENERATED ALWAYS AS (
CASE
    WHEN (union_id IS NULL) THEN 'club'::text
    ELSE 'union'::text
END) STORED NOT NULL, scope_id uuid GENERATED ALWAYS AS (COALESCE(union_id, standalone_club_id)) STORED NOT NULL);
CREATE TABLE public.accounting_tournament_fee_batches(rake_record_id uuid NOT NULL, tournament_id uuid NOT NULL, source_fingerprint text NOT NULL, status text DEFAULT 'captured'::text NOT NULL, source_version integer DEFAULT 2 NOT NULL, source_manifest jsonb, rake_amount numeric NOT NULL, captured_at timestamp with time zone DEFAULT transaction_timestamp() NOT NULL);
CREATE TABLE public.accounting_tournament_fee_recognitions(tournament_id uuid NOT NULL, recognized_at timestamp with time zone NOT NULL, status text NOT NULL, net_rake numeric NOT NULL, union_id uuid, bank_club_id uuid, union_wallet_transaction_id uuid, bank_journal_id uuid, source_fingerprint text NOT NULL, plan jsonb NOT NULL);
CREATE TABLE public.accounting_tournament_fee_sources(id uuid DEFAULT gen_random_uuid() NOT NULL, rake_record_id uuid NOT NULL, tournament_id uuid NOT NULL, player_id uuid NOT NULL, club_id uuid NOT NULL, union_id uuid, coordinator_union_id uuid, game_type text NOT NULL, registration_id uuid NOT NULL, source_charge_ledger_id uuid NOT NULL, source_entitlement_id uuid NOT NULL, charged_at timestamp with time zone NOT NULL, rake_credit numeric NOT NULL, contract jsonb NOT NULL, recorded_at timestamp with time zone DEFAULT transaction_timestamp() NOT NULL);
CREATE TABLE public.accounting_tournament_recognized_sources(source_id uuid NOT NULL, tournament_id uuid NOT NULL, recognized_at timestamp with time zone NOT NULL, disposition text NOT NULL, rake_credit numeric NOT NULL);
CREATE TABLE public.agent_commission_settlements(id uuid DEFAULT gen_random_uuid() NOT NULL, club_id uuid NOT NULL, user_id uuid NOT NULL, union_id uuid, period_start timestamp with time zone NOT NULL, period_end timestamp with time zone NOT NULL, amount numeric NOT NULL, rows_count integer DEFAULT 0 NOT NULL, paid_at timestamp with time zone DEFAULT now() NOT NULL, settlement_ref text);
CREATE TABLE public.agent_commission_unsettled_rollup(club_id uuid NOT NULL, user_id uuid NOT NULL, owed numeric DEFAULT 0 NOT NULL, rows_behind bigint DEFAULT 0 NOT NULL, oldest_unsettled timestamp with time zone, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.agent_commissions(id uuid DEFAULT gen_random_uuid() NOT NULL, club_id uuid NOT NULL, user_id uuid NOT NULL, amount numeric DEFAULT 0, commission_rate numeric DEFAULT 0.1, source_type text DEFAULT 'rake'::text, source_id uuid, notes text, created_at timestamp with time zone DEFAULT now(), settled_at timestamp with time zone);
CREATE TABLE public.ca_settlements(id uuid DEFAULT gen_random_uuid() NOT NULL, settlement_type text NOT NULL, external_ref text NOT NULL, state text DEFAULT 'open'::text NOT NULL, club_id uuid, union_id uuid, table_id uuid, tournament_id uuid, hand_id uuid, idempotency_key text, correlation_id uuid, epoch_id integer DEFAULT fn_ca_current_epoch(), totals jsonb DEFAULT '{}'::jsonb NOT NULL, error_detail text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.chip_ledger(id uuid DEFAULT gen_random_uuid() NOT NULL, performed_by uuid, from_type text NOT NULL, from_entity_id uuid, from_label text, to_type text NOT NULL, to_entity_id uuid, to_label text, amount numeric(15,2) NOT NULL, category text DEFAULT 'transfer'::text NOT NULL, description text, notes text, club_id uuid, union_id uuid, table_id uuid, hand_id uuid, tournament_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, idempotency_key text, correlation_id uuid, causation_id uuid, settlement_id text, epoch_id integer, actor_service text, db_role text, pre_from_balance numeric, post_from_balance numeric, pre_to_balance numeric, post_to_balance numeric, status text DEFAULT 'posted'::text NOT NULL, metadata jsonb, chain_seq bigint, prev_hash text, row_hash text);
CREATE TABLE public.club_members(club_id uuid NOT NULL, user_id uuid NOT NULL, role text DEFAULT 'player'::text, agent_id uuid, joined_at timestamp with time zone DEFAULT now(), parent_agent_id uuid, invited_by uuid, notes text, last_active_at timestamp with time zone, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), is_bot boolean DEFAULT false, status text DEFAULT 'active'::text, chip_balance numeric(20,2) DEFAULT 0 NOT NULL, diamonds integer DEFAULT 0 NOT NULL, is_active boolean DEFAULT true, orange_ball_status text DEFAULT 'inactive'::text, rank_level integer DEFAULT 1, credit_limit numeric(15,2) DEFAULT 0, credit_used numeric(15,2) DEFAULT 0, nickname text, last_active timestamp with time zone DEFAULT now(), tier text DEFAULT 'bronze'::text, trust_score integer DEFAULT 50, sessions_played integer DEFAULT 0, promo_balance numeric(14,2) DEFAULT 0, chips_won bigint DEFAULT 0, chips_lost bigint DEFAULT 0, commission_rate numeric(5,2) DEFAULT 0, rakeback_rate numeric(5,2) DEFAULT 0, hands_played integer DEFAULT 0, total_rake_paid bigint DEFAULT 0, biggest_pot bigint DEFAULT 0, locked_chips integer DEFAULT 0, player_rakeback_pct numeric(5,4) DEFAULT 0.0000, held_chips numeric DEFAULT 0, display_name text, is_prepaid boolean DEFAULT true, promo_received_total numeric(14,2) DEFAULT 0, promo_wagered numeric(14,2) DEFAULT 0, promo_playthrough_required numeric(14,2) DEFAULT 0, missions_completed integer DEFAULT 0, membership_lifecycle_status text DEFAULT 'active'::text NOT NULL, departed_at timestamp with time zone, departed_by uuid, departure_reason text);
CREATE TABLE public.clubs(id uuid DEFAULT uuid_generate_v4() NOT NULL, name text NOT NULL, description text, owner_id uuid, created_at timestamp with time zone DEFAULT now(), is_union boolean DEFAULT false, club_id integer DEFAULT (((10000)::double precision + floor((random() * (90000)::double precision))))::integer, avatar_url text, is_public boolean DEFAULT true, requires_approval boolean DEFAULT false, gps_restricted boolean DEFAULT false, settings jsonb DEFAULT '{"rake_cap": 15, "max_buy_in_bb": 200, "min_buy_in_bb": 40, "allow_straddle": true, "time_bank_seconds": 30, "allow_run_it_twice": true, "default_rake_percent": 5}'::jsonb, updated_at timestamp with time zone DEFAULT now(), union_id uuid, color_theme text DEFAULT 'royal-blue'::text, slug text, chip_treasury numeric(18,2) DEFAULT 100000, total_rake numeric(18,2) DEFAULT 0 NOT NULL, online_count integer DEFAULT 0, game_types text[] DEFAULT ARRAY['NLH'::text], member_count integer DEFAULT 0, table_count integer DEFAULT 0, promo_balance numeric(14,2) DEFAULT 0, code text, rake_percent numeric(5,2) DEFAULT 5.0, rake_cap_bb numeric(8,2) DEFAULT 3.0, max_tables integer DEFAULT 20, max_members integer DEFAULT 500, status text DEFAULT 'active'::text, hands_played bigint DEFAULT 0, logo_url text, banner_url text, game_variants text[] DEFAULT ARRAY['nlh'::text], settlement_locked boolean DEFAULT false, settlement_locked_until timestamp with time zone, auto_settlement_enabled boolean DEFAULT true, auto_settlement_day text DEFAULT 'monday'::text, auto_settlement_hour integer DEFAULT 10, club_commission_rate numeric(5,4) DEFAULT 0.9000, insurance_balance numeric(14,2) DEFAULT 0, bbj_enabled boolean, player_level integer DEFAULT 1, hierarchy_level integer DEFAULT 1, level integer DEFAULT 1, player_threshold_current integer DEFAULT 0, player_threshold_next integer DEFAULT 30, hierarchy_units numeric(10,2) DEFAULT 0, hierarchy_units_rounded_up integer DEFAULT 0, hierarchy_threshold_current integer DEFAULT 0, hierarchy_threshold_next integer DEFAULT 2, tags text[] DEFAULT '{}'::text[], average_rating numeric(3,2) DEFAULT 0, game_type text DEFAULT 'Texas Holdem'::text, settlement_lock_until timestamp with time zone, card_image_url text, active_players integer DEFAULT 0, default_rake_percent numeric(5,2) DEFAULT '-1'::integer, rake_cap numeric(18,4) DEFAULT '-1'::integer, min_buyin_bb integer DEFAULT 20, max_buyin_bb integer DEFAULT 200, allow_straddle boolean DEFAULT true, allow_run_it_twice boolean DEFAULT true, allow_rabbit_hunt boolean DEFAULT false, logo text, is_private boolean DEFAULT false, min_buy_in numeric(18,4) DEFAULT 0, max_buy_in numeric(18,4) DEFAULT 0, default_game_type text DEFAULT 'NLHE'::text, allow_insurance boolean DEFAULT false, auto_approve_agents boolean DEFAULT false, auto_settlement boolean DEFAULT false, active_tables integer DEFAULT 0, admin_count integer DEFAULT 0, super_agent_count integer DEFAULT 0, agent_count integer DEFAULT 0, chip_pool numeric(18,2) DEFAULT 0 NOT NULL, bbj_rake_enabled boolean DEFAULT true, spins_enabled boolean DEFAULT false, spins_preseed_amount integer DEFAULT 0, spins_wallet_funding text DEFAULT 'PROMO'::text, ticker_enabled boolean DEFAULT true NOT NULL, guarantee_treasury_floor numeric DEFAULT 0 NOT NULL, guarantee_enforcement_enabled boolean DEFAULT true NOT NULL, tagline text, opening_checklist_started_at timestamp with time zone, lobby_message text, lobby_message_updated_at timestamp with time zone, message_revision bigint DEFAULT 1 NOT NULL, lifecycle_status text DEFAULT 'active'::text NOT NULL, retired_at timestamp with time zone, retired_by uuid, retirement_reason text, asset text DEFAULT 'chips'::text NOT NULL, is_platform boolean DEFAULT false NOT NULL);
CREATE TABLE public.notifications(id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, type text NOT NULL, title text NOT NULL, message text, data jsonb DEFAULT '{}'::jsonb, read boolean DEFAULT false, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), is_read boolean DEFAULT false, action_url text, metadata jsonb DEFAULT '{}'::jsonb, actor_id uuid, link text, read_at timestamp with time zone);
CREATE TABLE public.rakeback_period_payouts(id uuid DEFAULT gen_random_uuid() NOT NULL, rakeback_period_id uuid NOT NULL, club_id uuid NOT NULL, user_id uuid NOT NULL, user_rake_contribution numeric(20,4) NOT NULL, rakeback_pct numeric(5,2) NOT NULL, payout_amount numeric(20,4) NOT NULL, currency text DEFAULT 'CHIPS'::text NOT NULL, wallet_transaction_id uuid, status text DEFAULT 'paid'::text NOT NULL, paid_at timestamp with time zone, failure_reason text, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.rakeback_periods(id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid, club_id uuid NOT NULL, period_start date NOT NULL, period_end date NOT NULL, rake_generated numeric(15,2) DEFAULT 0, rakeback_rate numeric(5,4) DEFAULT 0.10, rakeback_amount numeric(15,2) DEFAULT 0, status text DEFAULT 'pending'::text, paid_at timestamp with time zone, created_at timestamp with time zone DEFAULT now(), rakeback_earned numeric(15,2) DEFAULT 0, total_rake_paid numeric(15,2) DEFAULT 0, deferred_reason text, deferred_at timestamp with time zone, defer_count integer DEFAULT 0 NOT NULL);
CREATE TABLE public.settlement_invoices(id uuid DEFAULT gen_random_uuid() NOT NULL, club_id uuid NOT NULL, period_id uuid, invoice_type text NOT NULL, from_entity_type text NOT NULL, from_entity_id text NOT NULL, to_entity_type text NOT NULL, to_entity_id text NOT NULL, gross_amount numeric(12,2) DEFAULT 0 NOT NULL, net_amount numeric(12,2) DEFAULT 0 NOT NULL, deductions numeric(12,2) DEFAULT 0 NOT NULL, breakdown jsonb DEFAULT '{}'::jsonb, status text DEFAULT 'generated'::text NOT NULL, chip_transfer_id uuid, chips_transferred boolean DEFAULT false, transferred_at timestamp with time zone, message_sent boolean DEFAULT false, message_sent_at timestamp with time zone, notes text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), due_at timestamp with time zone, invoice_number text, adjusts_invoice_id uuid, overdue_at timestamp with time zone, reminders_sent integer DEFAULT 0 NOT NULL, last_reminder_at timestamp with time zone, source_ledger_id uuid, source_credit_invoice_id uuid, source_credit_payment_id uuid, source_credit_reduction_operation_id uuid);
CREATE TABLE public.settlement_locks(id uuid DEFAULT gen_random_uuid() NOT NULL, club_id uuid NOT NULL, lock_type text DEFAULT 'weekly_settlement'::text NOT NULL, locked_at timestamp with time zone DEFAULT now() NOT NULL, unlock_at timestamp with time zone NOT NULL, unlocked_at timestamp with time zone, is_active boolean DEFAULT true NOT NULL, lock_reason text DEFAULT 'Weekly auto-settlement in progress'::text, settlement_period_id uuid, metadata jsonb DEFAULT '{}'::jsonb, created_at timestamp with time zone DEFAULT now());
CREATE TABLE public.settlement_periods(id uuid DEFAULT gen_random_uuid() NOT NULL, club_id uuid, union_id uuid, period_number integer NOT NULL, year integer NOT NULL, start_at timestamp with time zone NOT NULL, end_at timestamp with time zone NOT NULL, status text DEFAULT 'open'::text, total_rake_collected numeric(15,2) DEFAULT 0, total_bbj_contributions numeric(15,2) DEFAULT 0, total_player_winnings numeric(15,2) DEFAULT 0, total_player_losses numeric(15,2) DEFAULT 0, total_hands_dealt integer DEFAULT 0, settled_at timestamp with time zone, settled_by uuid, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), total_commissions_paid numeric(12,2) DEFAULT 0, notes text, seated_stack_snapshot numeric);
CREATE TABLE public.social_messages(id uuid DEFAULT gen_random_uuid() NOT NULL, conversation_id uuid, sender_id uuid, content text NOT NULL, message_type text DEFAULT 'text'::text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), is_edited boolean DEFAULT false, is_deleted boolean DEFAULT false, read_at timestamp with time zone, media_metadata jsonb, request_id uuid);
CREATE TABLE public.union_accounting_runs(union_id uuid, period_start timestamp with time zone NOT NULL, period_end timestamp with time zone NOT NULL, scheduled_at timestamp with time zone NOT NULL, status text NOT NULL, attempts integer DEFAULT 0 NOT NULL, started_at timestamp with time zone, finished_at timestamp with time zone, result jsonb DEFAULT '{}'::jsonb NOT NULL, standalone_club_id uuid, scope_kind text GENERATED ALWAYS AS (
CASE
    WHEN (union_id IS NOT NULL) THEN 'union'::text
    ELSE 'club'::text
END) STORED NOT NULL, scope_id uuid GENERATED ALWAYS AS (COALESCE(union_id, standalone_club_id)) STORED NOT NULL, last_scheduler_visit_at timestamp with time zone);
CREATE TABLE public.union_admins(id uuid DEFAULT gen_random_uuid() NOT NULL, union_id uuid NOT NULL, user_id uuid NOT NULL, role text DEFAULT 'union_admin'::text NOT NULL, permissions jsonb DEFAULT '{"manage_clubs": true, "manage_settlements": true}'::jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.union_clubs(id uuid DEFAULT gen_random_uuid() NOT NULL, union_id uuid NOT NULL, club_id uuid NOT NULL, joined_at timestamp with time zone DEFAULT now(), club_commission_rate numeric(5,4) DEFAULT 0.9000, rate_cash numeric, rate_mtt numeric, rate_sng numeric, rate_spin numeric, rate_satellite numeric);
CREATE TABLE public.union_settlement_floor(union_id uuid NOT NULL, earliest_period_start timestamp with time zone NOT NULL, reason text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.union_settlement_rounds(id uuid DEFAULT gen_random_uuid() NOT NULL, union_id uuid NOT NULL, period_start timestamp with time zone NOT NULL, period_end timestamp with time zone NOT NULL, round_no integer NOT NULL, round_name text NOT NULL, payers integer DEFAULT 0 NOT NULL, payees integer DEFAULT 0 NOT NULL, amount numeric(20,2) DEFAULT 0 NOT NULL, shortfalls integer DEFAULT 0 NOT NULL, detail jsonb, executed_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.unions(id uuid DEFAULT gen_random_uuid() NOT NULL, name text NOT NULL, description text, owner_id uuid NOT NULL, avatar_url text, is_public boolean DEFAULT true, member_count integer DEFAULT 0, club_count integer DEFAULT 0, total_rake numeric(15,2) DEFAULT 0 NOT NULL, settings jsonb DEFAULT '{"shared_player_pool": true, "revenue_share_percent": 10, "cross_club_tournaments": true}'::jsonb, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), union_code integer, main_bbj_balance numeric(14,2) DEFAULT 0, backup_bbj_balance numeric(14,2) DEFAULT 0, promo_fund_balance numeric(14,2) DEFAULT 0, code text, insurance_balance numeric(14,2) DEFAULT 0, chip_balance numeric(20,4) DEFAULT 0 NOT NULL, rake_wallet numeric(20,4) DEFAULT 0 NOT NULL, bbj_wallet numeric(20,4) DEFAULT 0 NOT NULL, promo_wallet numeric(20,4) DEFAULT 0 NOT NULL, auto_settlement boolean DEFAULT false, level integer DEFAULT 1, player_level integer DEFAULT 1, hierarchy_level integer DEFAULT 1, total_players integer DEFAULT 0, total_admins integer DEFAULT 0, total_super_agents integer DEFAULT 0, total_agents integer DEFAULT 0, hierarchy_units numeric(10,2) DEFAULT 0, hierarchy_units_rounded_up integer DEFAULT 0, player_threshold_current integer DEFAULT 30, player_threshold_next integer DEFAULT 34, hierarchy_threshold_current integer DEFAULT 2, hierarchy_threshold_next integer DEFAULT 2, promo_funded_from_bbj numeric DEFAULT 0 NOT NULL, promo_funded_from_bank numeric DEFAULT 0 NOT NULL, slug text NOT NULL);
CREATE TABLE public.wallet_transactions(id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, wallet_type text NOT NULL, amount numeric(15,2) NOT NULL, type text NOT NULL, category text NOT NULL, description text, related_entity_id uuid, table_id uuid, hand_id uuid, created_at timestamp with time zone DEFAULT now(), balance_after numeric, terminal_closed_at timestamp with time zone);
ALTER TABLE public.accounting_cash_accrual_cutover ADD CONSTRAINT accounting_cash_accrual_cutover_pkey PRIMARY KEY (singleton);
ALTER TABLE public.accounting_cash_accrual_cutover ADD CONSTRAINT accounting_cash_accrual_cutover_singleton_check CHECK (singleton);
ALTER TABLE public.accounting_cash_bank_receipts ADD CONSTRAINT accounting_cash_bank_receipts_amount_check CHECK (((amount > (0)::numeric) AND (amount = round(amount, 2)) AND ((amount)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))));
ALTER TABLE public.accounting_cash_bank_receipts ADD CONSTRAINT accounting_cash_bank_receipts_check CHECK ((((union_id IS NOT NULL) AND (union_transaction_id IS NOT NULL) AND (club_ledger_id IS NULL)) OR ((union_id IS NULL) AND (union_transaction_id IS NULL) AND (club_ledger_id IS NOT NULL))));
ALTER TABLE public.accounting_cash_bank_receipts ADD CONSTRAINT accounting_cash_bank_receipts_club_ledger_id_key UNIQUE (club_ledger_id);
ALTER TABLE public.accounting_cash_bank_receipts ADD CONSTRAINT accounting_cash_bank_receipts_pkey PRIMARY KEY (rake_record_id);
ALTER TABLE public.accounting_cash_bank_receipts ADD CONSTRAINT accounting_cash_bank_receipts_union_transaction_id_key UNIQUE (union_transaction_id);
ALTER TABLE public.accounting_cash_rake_sources ADD CONSTRAINT accounting_cash_rake_sources_pkey PRIMARY KEY (id);
ALTER TABLE public.accounting_cash_rake_sources ADD CONSTRAINT accounting_cash_rake_sources_rake_credit_check CHECK (((rake_credit >= (0)::numeric) AND (rake_credit = round(rake_credit, 2)) AND ((rake_credit)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))));
ALTER TABLE public.accounting_cash_rake_sources ADD CONSTRAINT accounting_cash_rake_sources_rake_record_id_player_id_key UNIQUE (rake_record_id, player_id);
ALTER TABLE public.accounting_invoice_counters ADD CONSTRAINT accounting_invoice_counters_next_number_check CHECK ((next_number > 0));
ALTER TABLE public.accounting_invoice_counters ADD CONSTRAINT accounting_invoice_counters_pkey PRIMARY KEY (year);
ALTER TABLE public.accounting_invoice_deliveries ADD CONSTRAINT accounting_invoice_deliveries_delivery_mode_check CHECK ((delivery_mode = ANY (ARRAY['immediate'::text, 'weekly_detail'::text])));
ALTER TABLE public.accounting_invoice_deliveries ADD CONSTRAINT accounting_invoice_deliveries_message_id_key UNIQUE (message_id);
ALTER TABLE public.accounting_invoice_deliveries ADD CONSTRAINT accounting_invoice_deliveries_notification_id_key UNIQUE (notification_id);
ALTER TABLE public.accounting_invoice_deliveries ADD CONSTRAINT accounting_invoice_deliveries_pkey PRIMARY KEY (invoice_id, recipient_id);
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_cal_period_id_source_fingerprint_key UNIQUE (period_id, source_fingerprint);
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculation_accounting_version_check CHECK ((accounting_version = 2));
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculation_source_allocations_check CHECK ((jsonb_typeof(source_allocations) = 'array'::text));
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculations_check CHECK (((payer_kind = 'agent'::text) = (payer_user_id IS NOT NULL)));
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculations_check1 CHECK ((rakeback_amount <= rake_generated));
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculations_display_rate_check CHECK (((display_rate >= (0)::numeric) AND (display_rate <= (1)::numeric) AND (display_rate = round(display_rate, 4))));
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculations_payer_kind_check CHECK ((payer_kind = ANY (ARRAY['club'::text, 'agent'::text])));
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculations_pkey PRIMARY KEY (id);
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculations_rake_generated_check CHECK ((((rake_generated)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])) AND (rake_generated >= (0)::numeric) AND (rake_generated = round(rake_generated, 2))));
ALTER TABLE public.accounting_rakeback_period_calculations ADD CONSTRAINT accounting_rakeback_period_calculations_rakeback_amount_check CHECK ((((rakeback_amount)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text])) AND (rakeback_amount >= (0)::numeric) AND (rakeback_amount = round(rakeback_amount, 2))));
ALTER TABLE public.accounting_routed_settlement_runs ADD CONSTRAINT accounting_routed_run_one_scope CHECK ((num_nonnulls(union_id, standalone_club_id) = 1));
ALTER TABLE public.accounting_routed_settlement_runs ADD CONSTRAINT accounting_routed_settlement_runs_check CHECK ((period_start < period_end));
ALTER TABLE public.accounting_routed_settlement_runs ADD CONSTRAINT accounting_routed_settlement_runs_pkey PRIMARY KEY (scope_kind, scope_id, period_start, period_end, round_no);
ALTER TABLE public.accounting_routed_settlement_runs ADD CONSTRAINT accounting_routed_settlement_runs_round_no_check CHECK ((round_no = ANY (ARRAY[2, 3])));
ALTER TABLE public.accounting_routed_settlement_runs ADD CONSTRAINT accounting_routed_settlement_runs_routing_version_check CHECK ((routing_version = 3));
ALTER TABLE public.accounting_tournament_fee_batches ADD CONSTRAINT accounting_tournament_fee_batches_check CHECK (((status = 'legacy_unverified'::text) OR (jsonb_typeof(source_manifest) = 'object'::text)));
ALTER TABLE public.accounting_tournament_fee_batches ADD CONSTRAINT accounting_tournament_fee_batches_pkey PRIMARY KEY (rake_record_id);
ALTER TABLE public.accounting_tournament_fee_batches ADD CONSTRAINT accounting_tournament_fee_batches_rake_amount_check CHECK (((rake_amount > (0)::numeric) AND (rake_amount = round(rake_amount, 2)) AND ((rake_amount)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))));
ALTER TABLE public.accounting_tournament_fee_batches ADD CONSTRAINT accounting_tournament_fee_batches_source_version_check CHECK ((source_version = 2));
ALTER TABLE public.accounting_tournament_fee_batches ADD CONSTRAINT accounting_tournament_fee_batches_status_check CHECK ((status = ANY (ARRAY['captured'::text, 'legacy_unverified'::text])));
ALTER TABLE public.accounting_tournament_fee_recognitions ADD CONSTRAINT accounting_tournament_fee_recognitions_net_rake_check CHECK (((net_rake >= (0)::numeric) AND (net_rake = round(net_rake, 2)) AND ((net_rake)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))));
ALTER TABLE public.accounting_tournament_fee_recognitions ADD CONSTRAINT accounting_tournament_fee_recog_union_wallet_transaction_id_key UNIQUE (union_wallet_transaction_id);
ALTER TABLE public.accounting_tournament_fee_recognitions ADD CONSTRAINT accounting_tournament_fee_recognitions_bank_journal_id_key UNIQUE (bank_journal_id);
ALTER TABLE public.accounting_tournament_fee_recognitions ADD CONSTRAINT accounting_tournament_fee_recognitions_check CHECK (((net_rake = (0)::numeric) OR (bank_club_id IS NOT NULL)));
ALTER TABLE public.accounting_tournament_fee_recognitions ADD CONSTRAINT accounting_tournament_fee_recognitions_check1 CHECK ((((net_rake = (0)::numeric) AND (union_wallet_transaction_id IS NULL) AND (bank_journal_id IS NULL)) OR ((net_rake > (0)::numeric) AND ((((union_wallet_transaction_id IS NOT NULL))::integer + ((bank_journal_id IS NOT NULL))::integer) = 1))));
ALTER TABLE public.accounting_tournament_fee_recognitions ADD CONSTRAINT accounting_tournament_fee_recognitions_pkey PRIMARY KEY (tournament_id);
ALTER TABLE public.accounting_tournament_fee_recognitions ADD CONSTRAINT accounting_tournament_fee_recognitions_status_check CHECK ((status = ANY (ARRAY['recognized'::text, 'cancelled'::text, 'banked_accrual_deferred'::text])));
ALTER TABLE public.accounting_tournament_fee_sources ADD CONSTRAINT accounting_tournament_fee_sources_pkey PRIMARY KEY (id);
ALTER TABLE public.accounting_tournament_fee_sources ADD CONSTRAINT accounting_tournament_fee_sources_rake_credit_check CHECK (((rake_credit >= (0)::numeric) AND (rake_credit = round(rake_credit, 2)) AND ((rake_credit)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))));
ALTER TABLE public.accounting_tournament_fee_sources ADD CONSTRAINT accounting_tournament_fee_sources_rake_record_id_player_id_key UNIQUE (rake_record_id, player_id);
ALTER TABLE public.accounting_tournament_fee_sources ADD CONSTRAINT accounting_tournament_fee_sources_source_entitlement_id_key UNIQUE (source_entitlement_id);
ALTER TABLE public.accounting_tournament_recognized_sources ADD CONSTRAINT accounting_tournament_recognized_sources_disposition_check CHECK ((disposition = ANY (ARRAY['earned'::text, 'refunded'::text])));
ALTER TABLE public.accounting_tournament_recognized_sources ADD CONSTRAINT accounting_tournament_recognized_sources_pkey PRIMARY KEY (source_id);
ALTER TABLE public.accounting_tournament_recognized_sources ADD CONSTRAINT accounting_tournament_recognized_sources_rake_credit_check CHECK (((rake_credit >= (0)::numeric) AND (rake_credit = round(rake_credit, 2)) AND ((rake_credit)::text <> ALL (ARRAY['NaN'::text, 'Infinity'::text, '-Infinity'::text]))));
ALTER TABLE public.agent_commission_settlements ADD CONSTRAINT agent_commission_settlements_amount_check CHECK (((amount >= (0)::numeric) AND (amount = round(amount, 2))));
ALTER TABLE public.agent_commission_settlements ADD CONSTRAINT agent_commission_settlements_check CHECK ((period_end > period_start));
ALTER TABLE public.agent_commission_settlements ADD CONSTRAINT agent_commission_settlements_club_id_user_id_period_start_p_key UNIQUE (club_id, user_id, period_start, period_end);
ALTER TABLE public.agent_commission_settlements ADD CONSTRAINT agent_commission_settlements_pkey PRIMARY KEY (id);
ALTER TABLE public.agent_commission_settlements ADD CONSTRAINT chk_amount_is_two_decimal_places CHECK (((amount IS NULL) OR (amount = round(amount, 2))));
ALTER TABLE public.agent_commission_unsettled_rollup ADD CONSTRAINT agent_commission_unsettled_rollup_pkey PRIMARY KEY (club_id, user_id);
ALTER TABLE public.agent_commissions ADD CONSTRAINT agent_commissions_pkey PRIMARY KEY (id);
ALTER TABLE public.agent_commissions ADD CONSTRAINT chk_amount_is_two_decimal_places CHECK (((amount IS NULL) OR (amount = round(amount, 2))));
ALTER TABLE public.agent_commissions ADD CONSTRAINT ck_whole_cents CHECK (((created_at < '2026-09-07 22:00:00+00'::timestamp with time zone) OR (amount = round(amount, 2)))) NOT VALID;
ALTER TABLE public.ca_settlements ADD CONSTRAINT ca_settlements_pkey PRIMARY KEY (id);
ALTER TABLE public.ca_settlements ADD CONSTRAINT ca_settlements_settlement_type_external_ref_key UNIQUE (settlement_type, external_ref);
ALTER TABLE public.ca_settlements ADD CONSTRAINT ca_settlements_state_check CHECK ((state = ANY (ARRAY['open'::text, 'locked_for_calculation'::text, 'calculated'::text, 'validated'::text, 'ledger_posted'::text, 'post_commit_verified'::text, 'final'::text, 'failed'::text])));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_category_check CHECK ((category = ANY (ARRAY['buyin'::text, 'cashout'::text, 'rake'::text, 'commission'::text, 'transfer'::text, 'player_funding'::text, 'agent_funding'::text, 'mint'::text, 'burn'::text, 'legacy_seed_reconcile'::text, 'rakeback'::text, 'settlement'::text, 'tournament_buyin'::text, 'tournament_prize'::text, 'bounty'::text, 'adjustment'::text, 'refund'::text, 'addon'::text, 'rebuy'::text, 'table_cashout'::text, 'tournament_refund'::text, 'bbj_contribution'::text, 'bbj_payout'::text, 'promo'::text, 'promo_release'::text, 'promo_send'::text, 'credit_draw'::text, 'credit_repayment'::text, 'insurance'::text, 'spin_entry'::text, 'spin_prize'::text, 'overlay'::text, 'correction'::text, 'reversal'::text, 'escrow_hold'::text, 'escrow_release'::text, 'treasury_transfer'::text, 'horse_funding'::text, 'fee'::text, 'eco'::text, 'pnl_settlement'::text, 'union_send'::text, 'cashier_send'::text, 'cashier_claim_back'::text, 'ticket_issue'::text, 'ticket_redeem'::text, 'club_opening_allocation'::text, 'leaderboard_payout'::text, 'club_bank_send'::text, 'club_bank_claim'::text, 'agent_send'::text, 'agent_claim'::text, 'union_settlement'::text, 'wheel_prize'::text, 'plinko_prize'::text, 'crash_prize'::text, 'crossing_prize'::text, 'mines_prize'::text]))) NOT VALID;
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_exact_scale CHECK ((amount = round(amount, 2))) NOT VALID;
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_from_type_check CHECK ((from_type = ANY (ARRAY['player_wallet'::text, 'club_treasury'::text, 'union_bank'::text, 'agent_wallet'::text, 'system_mint'::text, 'system_burn'::text, 'table_stack'::text, 'promo_wallet'::text, 'club_wallet'::text, 'union_wallet'::text, 'bbj_pool'::text, 'spin_reserve'::text, 'insurance_bank'::text, 'escrow'::text, 'prize_liability'::text, 'bounty_liability'::text, 'rakeback_payable'::text, 'refund_payable'::text, 'settlement_suspense'::text, 'issuance_reserve'::text, 'chip_retirement'::text, 'credit_facility'::text, 'credit_receivable'::text, 'opening_setup'::text, 'leaderboard_round'::text]))) NOT VALID;
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_no_diamond_category_check CHECK (((category !~* '^diamond'::text) AND (category !~* '_diamond'::text)));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_pkey PRIMARY KEY (id);
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_positive_amount CHECK ((amount > (0)::numeric));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_status_check CHECK ((status = ANY (ARRAY['posted'::text, 'correction'::text, 'reversal'::text])));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chip_ledger_to_type_check CHECK ((to_type = ANY (ARRAY['player_wallet'::text, 'club_treasury'::text, 'union_bank'::text, 'agent_wallet'::text, 'system_mint'::text, 'system_burn'::text, 'table_stack'::text, 'promo_wallet'::text, 'club_wallet'::text, 'union_wallet'::text, 'bbj_pool'::text, 'spin_reserve'::text, 'insurance_bank'::text, 'escrow'::text, 'prize_liability'::text, 'bounty_liability'::text, 'rakeback_payable'::text, 'refund_payable'::text, 'settlement_suspense'::text, 'issuance_reserve'::text, 'chip_retirement'::text, 'credit_facility'::text, 'credit_receivable'::text, 'opening_setup'::text, 'leaderboard_round'::text]))) NOT VALID;
ALTER TABLE public.chip_ledger ADD CONSTRAINT chk_post_from_balance_is_two_decimal_places CHECK (((post_from_balance IS NULL) OR (post_from_balance = round(post_from_balance, 2))));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chk_post_to_balance_is_two_decimal_places CHECK (((post_to_balance IS NULL) OR (post_to_balance = round(post_to_balance, 2))));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chk_pre_from_balance_is_two_decimal_places CHECK (((pre_from_balance IS NULL) OR (pre_from_balance = round(pre_from_balance, 2))));
ALTER TABLE public.chip_ledger ADD CONSTRAINT chk_pre_to_balance_is_two_decimal_places CHECK (((pre_to_balance IS NULL) OR (pre_to_balance = round(pre_to_balance, 2))));
ALTER TABLE public.chip_ledger ADD CONSTRAINT ck_whole_cents CHECK (((created_at < '2026-09-07 22:00:00+00'::timestamp with time zone) OR (amount = round(amount, 2)))) NOT VALID;
ALTER TABLE public.club_members ADD CONSTRAINT chk_held_chips_is_two_decimal_places CHECK (((held_chips IS NULL) OR (held_chips = round(held_chips, 2))));
ALTER TABLE public.club_members ADD CONSTRAINT club_members_bot_house_only CHECK (((NOT COALESCE(is_bot, false)) OR fn_ca_house_board_allows_automation(club_id)));
ALTER TABLE public.club_members ADD CONSTRAINT club_members_chip_balance_nonneg CHECK ((chip_balance >= (0)::numeric));
ALTER TABLE public.club_members ADD CONSTRAINT club_members_membership_lifecycle_check CHECK ((membership_lifecycle_status = ANY (ARRAY['active'::text, 'departed'::text])));
ALTER TABLE public.club_members ADD CONSTRAINT club_members_pkey PRIMARY KEY (club_id, user_id);
ALTER TABLE public.club_members ADD CONSTRAINT club_members_promo_balance_nonneg CHECK ((promo_balance >= (0)::numeric));
ALTER TABLE public.club_members ADD CONSTRAINT club_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'co_owner'::text, 'admin'::text, 'super_agent'::text, 'agent'::text, 'sub_agent'::text, 'player'::text])));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_asset_known CHECK ((asset = ANY (ARRAY['chips'::text, 'diamonds'::text])));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_chip_pool_nonneg CHECK ((chip_pool >= (0)::numeric));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_chip_treasury_nonneg CHECK ((chip_treasury >= (0)::numeric));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_club_id_key UNIQUE (club_id);
ALTER TABLE public.clubs ADD CONSTRAINT clubs_default_rake_percent_range CHECK (((default_rake_percent IS NULL) OR (default_rake_percent = ('-1'::integer)::numeric) OR ((default_rake_percent >= (0)::numeric) AND (default_rake_percent <= (10)::numeric)))) NOT VALID;
ALTER TABLE public.clubs ADD CONSTRAINT clubs_description_character_limit CHECK ((char_length(COALESCE(description, ''::text)) <= 500));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_insurance_balance_nonneg CHECK ((insurance_balance >= (0)::numeric));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_lifecycle_status_check CHECK ((lifecycle_status = ANY (ARRAY['active'::text, 'retired'::text])));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_lobby_message_character_limit CHECK ((char_length(COALESCE(lobby_message, ''::text)) <= 240));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_message_revision_positive CHECK ((message_revision > 0));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_name_not_blank CHECK ((btrim(name) <> ''::text));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_pkey PRIMARY KEY (id);
ALTER TABLE public.clubs ADD CONSTRAINT clubs_promo_balance_nonneg CHECK ((promo_balance >= (0)::numeric));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_rake_cap_range CHECK (((rake_cap IS NULL) OR (rake_cap = ('-1'::integer)::numeric) OR ((rake_cap >= (0)::numeric) AND (rake_cap <= (10)::numeric)))) NOT VALID;
ALTER TABLE public.clubs ADD CONSTRAINT clubs_tagline_character_limit CHECK ((char_length(COALESCE(tagline, ''::text)) <= 72));
ALTER TABLE public.clubs ADD CONSTRAINT clubs_tagline_length CHECK (((tagline IS NULL) OR (char_length(tagline) <= 72)));
ALTER TABLE public.clubs ADD CONSTRAINT poker_arena_diamond_identity CHECK ((((asset = 'chips'::text) AND (NOT is_platform)) OR ((asset = 'diamonds'::text) AND is_platform AND (union_id IS NULL) AND (NOT COALESCE(is_union, false)) AND (COALESCE(chip_treasury, (0)::numeric) = (0)::numeric) AND (COALESCE(chip_pool, (0)::numeric) = (0)::numeric) AND (COALESCE(promo_balance, (0)::numeric) = (0)::numeric) AND (COALESCE(insurance_balance, (0)::numeric) = (0)::numeric))));
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT chk_payout_amount_is_two_decimal_places CHECK (((payout_amount IS NULL) OR (payout_amount = round(payout_amount, 2))));
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT ck_whole_cents CHECK (((created_at < '2026-09-07 22:00:00+00'::timestamp with time zone) OR (payout_amount = round(payout_amount, 2)))) NOT VALID;
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT rakeback_period_payouts_payout_amount_check CHECK ((payout_amount >= (0)::numeric));
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT rakeback_period_payouts_pkey PRIMARY KEY (id);
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT rakeback_period_payouts_rakeback_pct_check CHECK (((rakeback_pct >= (0)::numeric) AND (rakeback_pct <= (100)::numeric)));
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT rakeback_period_payouts_rakeback_period_id_user_id_key UNIQUE (rakeback_period_id, user_id);
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT rakeback_period_payouts_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'paid'::text, 'clawed_back'::text, 'failed'::text])));
ALTER TABLE public.rakeback_period_payouts ADD CONSTRAINT rakeback_period_payouts_user_rake_contribution_check CHECK ((user_rake_contribution >= (0)::numeric));
ALTER TABLE public.rakeback_periods ADD CONSTRAINT ck_whole_cents CHECK (((created_at < '2026-09-07 22:00:00+00'::timestamp with time zone) OR ((rakeback_amount = round(rakeback_amount, 2)) AND (rake_generated = round(rake_generated, 2))))) NOT VALID;
ALTER TABLE public.rakeback_periods ADD CONSTRAINT rakeback_periods_pkey PRIMARY KEY (id);
ALTER TABLE public.rakeback_periods ADD CONSTRAINT rakeback_periods_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'open'::text, 'closed'::text, 'claiming'::text, 'claimed'::text, 'paid'::text, 'expired'::text])));
ALTER TABLE public.rakeback_periods ADD CONSTRAINT rakeback_periods_user_id_club_id_period_start_period_end_key UNIQUE (user_id, club_id, period_start, period_end);
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_source_credit_payment_id_key UNIQUE (source_credit_payment_id);
ALTER TABLE public.settlement_invoices ADD CONSTRAINT accounting_invoice_credit_reduction_source_unique UNIQUE (source_credit_reduction_operation_id);
ALTER TABLE public.settlement_invoices ADD CONSTRAINT accounting_invoice_has_one_source CHECK ((((source_credit_reduction_operation_id IS NULL) AND (invoice_type <> 'credit_limit_change'::text) AND ((num_nonnulls(source_ledger_id, source_credit_invoice_id, source_credit_payment_id) <= 1) AND ((period_id IS NOT NULL) OR (num_nonnulls(source_ledger_id, source_credit_invoice_id, source_credit_payment_id) = 1)))) OR ((source_credit_reduction_operation_id IS NOT NULL) AND (invoice_type = 'credit_limit_change'::text) AND (period_id IS NULL) AND (num_nonnulls(source_ledger_id, source_credit_invoice_id, source_credit_payment_id) = 0))));
ALTER TABLE public.settlement_invoices ADD CONSTRAINT ck_whole_cents CHECK (((created_at < '2026-09-07 22:00:00+00'::timestamp with time zone) OR ((net_amount = round(net_amount, 2)) AND (gross_amount = round(gross_amount, 2))))) NOT VALID;
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_from_entity_type_check CHECK ((from_entity_type = ANY (ARRAY['union'::text, 'club'::text, 'agent'::text, 'player'::text])));
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_invoice_type_check CHECK ((invoice_type = ANY (ARRAY['union_to_club'::text, 'club_to_agent'::text, 'agent_to_subagent'::text, 'agent_to_player'::text, 'union_club_pnl'::text, 'club_to_union'::text, 'union_weekly_squareup'::text, 'union_weekly_credit_note'::text, 'transaction_receipt'::text, 'club_weekly_accounting'::text, 'cashier_cashout'::text, 'accounting_correction'::text, 'credit_limit_change'::text])));
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_pkey PRIMARY KEY (id);
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_source_credit_invoice_id_key UNIQUE (source_credit_invoice_id);
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_source_ledger_id_key UNIQUE (source_ledger_id);
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'generated'::text, 'paid'::text, 'cancelled'::text, 'overdue'::text, 'disputed'::text])));
ALTER TABLE public.settlement_invoices ADD CONSTRAINT settlement_invoices_to_entity_type_check CHECK ((to_entity_type = ANY (ARRAY['club'::text, 'agent'::text, 'player'::text, 'union'::text])));
ALTER TABLE public.settlement_locks ADD CONSTRAINT settlement_locks_pkey PRIMARY KEY (id);
ALTER TABLE public.settlement_periods ADD CONSTRAINT settlement_periods_pkey PRIMARY KEY (id);
ALTER TABLE public.settlement_periods ADD CONSTRAINT settlement_periods_status_check CHECK ((status = ANY (ARRAY['open'::text, 'processing'::text, 'settled'::text, 'disputed'::text, 'closed'::text])));
ALTER TABLE public.social_messages ADD CONSTRAINT social_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.union_accounting_runs ADD CONSTRAINT union_accounting_runs_pkey PRIMARY KEY (scope_kind, scope_id, period_start, period_end);
ALTER TABLE public.union_accounting_runs ADD CONSTRAINT union_accounting_runs_status_check CHECK ((status = ANY (ARRAY['running'::text, 'complete'::text, 'failed'::text])));
ALTER TABLE public.union_accounting_runs ADD CONSTRAINT union_accounting_runs_attempts_check CHECK ((attempts >= 0));
ALTER TABLE public.union_accounting_runs ADD CONSTRAINT union_accounting_runs_union_id_period_start_period_end_key UNIQUE (union_id, period_start, period_end);
ALTER TABLE public.union_accounting_runs ADD CONSTRAINT union_accounting_runs_check CHECK ((isfinite(period_start) AND isfinite(period_end) AND (period_start < period_end)));
ALTER TABLE public.union_accounting_runs ADD CONSTRAINT accounting_run_has_one_scope CHECK (((union_id IS NULL) <> (standalone_club_id IS NULL)));
ALTER TABLE public.union_accounting_runs ADD CONSTRAINT union_accounting_runs_last_scheduler_visit_at_check CHECK (((last_scheduler_visit_at IS NULL) OR isfinite(last_scheduler_visit_at)));
ALTER TABLE public.union_admins ADD CONSTRAINT union_admins_role_check CHECK ((role = ANY (ARRAY['union_lead'::text, 'union_admin'::text])));
ALTER TABLE public.union_admins ADD CONSTRAINT union_admins_pkey PRIMARY KEY (id);
ALTER TABLE public.union_admins ADD CONSTRAINT union_admins_union_id_user_id_key UNIQUE (union_id, user_id);
ALTER TABLE public.union_clubs ADD CONSTRAINT union_clubs_game_rates_are_fractions CHECK ((((rate_cash IS NULL) OR ((rate_cash >= (0)::numeric) AND (rate_cash <= (1)::numeric))) AND ((rate_mtt IS NULL) OR ((rate_mtt >= (0)::numeric) AND (rate_mtt <= (1)::numeric))) AND ((rate_sng IS NULL) OR ((rate_sng >= (0)::numeric) AND (rate_sng <= (1)::numeric))) AND ((rate_spin IS NULL) OR ((rate_spin >= (0)::numeric) AND (rate_spin <= (1)::numeric))) AND ((rate_satellite IS NULL) OR ((rate_satellite >= (0)::numeric) AND (rate_satellite <= (1)::numeric)))));
ALTER TABLE public.union_clubs ADD CONSTRAINT union_clubs_pkey PRIMARY KEY (id);
ALTER TABLE public.union_clubs ADD CONSTRAINT union_clubs_union_id_club_id_key UNIQUE (union_id, club_id);
ALTER TABLE public.union_settlement_floor ADD CONSTRAINT union_settlement_floor_pkey PRIMARY KEY (union_id);
ALTER TABLE public.union_settlement_rounds ADD CONSTRAINT union_settlement_rounds_pkey PRIMARY KEY (id);
ALTER TABLE public.union_settlement_rounds ADD CONSTRAINT union_settlement_rounds_union_id_period_start_period_end_ro_key UNIQUE (union_id, period_start, period_end, round_no);
ALTER TABLE public.unions ADD CONSTRAINT chk_chip_balance_is_two_decimal_places CHECK (((chip_balance IS NULL) OR (chip_balance = round(chip_balance, 2))));
ALTER TABLE public.unions ADD CONSTRAINT chk_rake_wallet_is_two_decimal_places CHECK (((rake_wallet IS NULL) OR (rake_wallet = round(rake_wallet, 2))));
ALTER TABLE public.unions ADD CONSTRAINT unions_code_unique UNIQUE (code);
ALTER TABLE public.unions ADD CONSTRAINT unions_pkey PRIMARY KEY (id);
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_type_check CHECK ((type = ANY (ARRAY['credit'::text, 'debit'::text])));
ALTER TABLE public.wallet_transactions ADD CONSTRAINT chk_balance_after_is_two_decimal_places CHECK (((balance_after IS NULL) OR (balance_after = round(balance_after, 2)))) NOT VALID;
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_amount_non_negative CHECK ((amount >= (0)::numeric)) NOT VALID;
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_category_check CHECK ((category = ANY (ARRAY['buyin'::text, 'cashout'::text, 'promo'::text, 'rake'::text, 'transfer'::text, 'tournament_buyin'::text, 'tournament_winnings'::text, 'tournament_cashout'::text, 'horse_refill'::text, 'deposit'::text, 'withdrawal'::text, 'refund'::text, 'bbj'::text, 'bonus'::text, 'mint'::text, 'settlement'::text, 'commission'::text, 'INSURANCE'::text, 'prize'::text, 'rebuy'::text, 'addon'::text, 'funding'::text, 'promotion'::text, 'rakeback'::text, 'bounty'::text, 'addon_refund'::text, 'bounty_own'::text, 'prize_reversal'::text, 'leaderboard_payout'::text]))) NOT VALID;
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_wallet_type_check CHECK ((wallet_type = ANY (ARRAY['PLAYER'::text, 'BUSINESS'::text, 'PROMO'::text, 'CLUB'::text, 'UNION'::text, 'PLATFORM'::text])));
CREATE INDEX idx_accounting_cash_bank_receipts_club_id_fk ON public.accounting_cash_bank_receipts USING btree (club_id);
CREATE INDEX accounting_cash_bank_receipts_union_period ON public.accounting_cash_bank_receipts USING btree (union_id, banked_at);
CREATE INDEX accounting_cash_rake_sources_coordinator_period ON public.accounting_cash_rake_sources USING btree (coordinator_union_id, earned_at, club_id);
CREATE INDEX accounting_cash_rake_sources_period ON public.accounting_cash_rake_sources USING btree (club_id, earned_at, player_id);
CREATE INDEX accounting_cash_rake_sources_bank_period ON public.accounting_cash_rake_sources USING btree (union_id, earned_at) WHERE (union_id IS NOT NULL);
CREATE INDEX idx_cash_rake_sources_player ON public.accounting_cash_rake_sources USING btree (player_id);
CREATE INDEX accounting_rakeback_period_calculations_latest ON public.accounting_rakeback_period_calculations USING btree (period_id, id DESC);
CREATE INDEX idx_accounting_rakeback_period_calculations_club_id_fk ON public.accounting_rakeback_period_calculations USING btree (club_id);
CREATE INDEX accounting_tournament_fee_recognitions_week ON public.accounting_tournament_fee_recognitions USING btree (recognized_at) INCLUDE (tournament_id);
CREATE INDEX accounting_tournament_fee_sources_coordinator_event ON public.accounting_tournament_fee_sources USING btree (coordinator_union_id, tournament_id) WHERE (coordinator_union_id IS NOT NULL);
CREATE INDEX accounting_tournament_fee_sources_club_event ON public.accounting_tournament_fee_sources USING btree (club_id, tournament_id);
CREATE INDEX accounting_tournament_fee_sources_event ON public.accounting_tournament_fee_sources USING btree (tournament_id, rake_record_id);
CREATE INDEX accounting_tournament_recognized_sources_event ON public.accounting_tournament_recognized_sources USING btree (tournament_id) INCLUDE (source_id, recognized_at, disposition, rake_credit);
CREATE INDEX accounting_tournament_recognized_sources_week ON public.accounting_tournament_recognized_sources USING btree (recognized_at, tournament_id);
CREATE INDEX agent_commission_settlements_pair_idx ON public.agent_commission_settlements USING btree (club_id, user_id, period_start, period_end);
CREATE INDEX idx_agent_commissions_user ON public.agent_commissions USING btree (user_id);
CREATE INDEX idx_agent_commissions_club_id ON public.agent_commissions USING btree (club_id);
CREATE INDEX idx_agent_commissions_source_lookup ON public.agent_commissions USING btree (source_id, source_type, club_id) WHERE (source_id IS NOT NULL);
CREATE UNIQUE INDEX uq_agent_commissions_source ON public.agent_commissions USING btree (user_id, source_id, source_type) WHERE (source_id IS NOT NULL);
CREATE INDEX agent_commissions_open_idx ON public.agent_commissions USING btree (club_id, user_id, created_at) INCLUDE (amount, id) WHERE (settled_at IS NULL);
CREATE INDEX agent_commissions_unsettled_idx ON public.agent_commissions USING btree (club_id, user_id) INCLUDE (amount, created_at) WHERE (settled_at IS NULL);
CREATE INDEX idx_agent_commissions_club_created ON public.agent_commissions USING btree (club_id, created_at) INCLUDE (user_id, amount, settled_at);
CREATE INDEX agent_commissions_user_recent_idx ON public.agent_commissions USING btree (user_id, created_at DESC);
CREATE INDEX idx_ca_settlements_final_updated_at ON public.ca_settlements USING btree (updated_at) WHERE (state = 'final'::text);
CREATE INDEX idx_ca_settlements_table_hand ON public.ca_settlements USING btree (table_id, hand_id);
CREATE INDEX idx_ca_settlements_updated_at ON public.ca_settlements USING btree (updated_at);
CREATE INDEX idx_chip_ledger_to_entity_created ON public.chip_ledger USING btree (to_entity_id, created_at DESC);
CREATE INDEX chip_ledger_bbj_incoming_other_labels ON public.chip_ledger USING btree (to_entity_id, created_at) WHERE ((to_type = 'bbj_pool'::text) AND ((to_label ~~ 'bbj_pools.%'::text) OR (from_label ~~ 'bbj_pools.%'::text)) AND (((to_label = ANY (ARRAY['bbj_pools.main_balance'::text, 'bbj_pools.backup_balance'::text, 'bbj_pools.promo_balance'::text])) AND (octet_length(to_label) <= 64)) IS NOT TRUE));
CREATE INDEX idx_chip_ledger_overlay_by_tournament ON public.chip_ledger USING btree (tournament_id) INCLUDE (amount) WHERE ((tournament_id IS NOT NULL) AND (category = 'overlay'::text) AND (to_type = 'prize_liability'::text));
CREATE INDEX idx_chip_ledger_club_to_created ON public.chip_ledger USING btree (club_id, to_entity_id, created_at);
CREATE INDEX idx_chip_ledger_performed_by ON public.chip_ledger USING btree (performed_by);
CREATE INDEX idx_chip_ledger_created_at ON public.chip_ledger USING btree (created_at);
CREATE INDEX idx_chip_ledger_club_created_desc ON public.chip_ledger USING btree (club_id, created_at DESC);
CREATE UNIQUE INDEX chip_ledger_chain_seq_key ON public.chip_ledger USING btree (chain_seq);
CREATE INDEX ix_chip_ledger_settlement ON public.chip_ledger USING btree (settlement_id) WHERE (settlement_id IS NOT NULL);
CREATE INDEX idx_chip_ledger_satellite_pool_from ON public.chip_ledger USING btree (from_entity_id) WHERE ((from_type = 'prize_liability'::text) AND (category = 'tournament_buyin'::text));
CREATE INDEX chip_ledger_bbj_from_pool_meter ON public.chip_ledger USING btree (from_entity_id, created_at) WHERE ((from_type = 'bbj_pool'::text) AND ((to_label ~~ 'bbj_pools.%'::text) OR (from_label ~~ 'bbj_pools.%'::text)));
CREATE INDEX idx_chip_ledger_tournament_category ON public.chip_ledger USING btree (tournament_id, category) WHERE (tournament_id IS NOT NULL);
CREATE INDEX idx_chip_ledger_cashier_totals_cover ON public.chip_ledger USING btree (club_id, created_at DESC) INCLUDE (id, amount, from_entity_id, to_entity_id) WHERE ((status = 'posted'::text) AND (category = ANY (ARRAY['buyin'::text, 'addon'::text, 'rebuy'::text, 'tournament_prize'::text, 'bounty'::text, 'refund'::text, 'spin_entry'::text, 'spin_prize'::text, 'promo'::text, 'promo_send'::text, 'treasury_transfer'::text, 'transfer'::text, 'player_funding'::text, 'agent_funding'::text, 'overlay'::text, 'reversal'::text, 'correction'::text, 'adjustment'::text, 'leaderboard_payout'::text])));
CREATE INDEX idx_chip_ledger_rebuy_probe ON public.chip_ledger USING btree (from_entity_id, tournament_id, created_at) WHERE ((category = 'rebuy'::text) AND (from_type = 'player_wallet'::text) AND (to_type = 'prize_liability'::text) AND (status = 'posted'::text));
CREATE INDEX idx_chip_ledger_reviewed_overlay_returns ON public.chip_ledger USING btree (tournament_id) INCLUDE (amount) WHERE ((tournament_id IS NOT NULL) AND (category = 'reversal'::text) AND (from_type = 'prize_liability'::text) AND (from_entity_id = tournament_id) AND ((metadata ->> 'kind'::text) = 'reviewed_void_overlay_return'::text));
CREATE INDEX chip_ledger_bbj_incoming_banks_cover ON public.chip_ledger USING btree (to_entity_id, created_at) INCLUDE (to_label, amount) WHERE ((to_type = 'bbj_pool'::text) AND (to_label = ANY (ARRAY['bbj_pools.main_balance'::text, 'bbj_pools.backup_balance'::text, 'bbj_pools.promo_balance'::text])) AND (octet_length(to_label) <= 64));
CREATE UNIQUE INDEX ux_chip_ledger_idempotency_key ON public.chip_ledger USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX idx_chip_ledger_promo_to ON public.chip_ledger USING btree (to_entity_id, created_at DESC) WHERE (to_type = 'promo_wallet'::text);
CREATE INDEX idx_chip_ledger_to_entity ON public.chip_ledger USING btree (to_entity_id);
CREATE INDEX idx_chip_ledger_club_from_created ON public.chip_ledger USING btree (club_id, from_entity_id, created_at);
CREATE INDEX chip_ledger_bbj_to_pool_meter ON public.chip_ledger USING btree (to_entity_id, created_at) WHERE ((to_type = 'bbj_pool'::text) AND ((to_label ~~ 'bbj_pools.%'::text) OR (from_label ~~ 'bbj_pools.%'::text)));
CREATE INDEX idx_chip_ledger_from_entity_created ON public.chip_ledger USING btree (from_entity_id, created_at DESC);
CREATE INDEX idx_chip_ledger_promo_from ON public.chip_ledger USING btree (from_entity_id, created_at DESC) WHERE (from_type = 'promo_wallet'::text);
CREATE INDEX idx_club_members_agent_id ON public.club_members USING btree (agent_id);
CREATE INDEX club_members_cashier_tree_idx ON public.club_members USING btree (club_id, agent_id, user_id) INCLUDE (role, status, chip_balance) WHERE (COALESCE(status, 'active'::text) = ANY (ARRAY['active'::text, 'approved'::text]));
CREATE INDEX idx_club_members_active_lifecycle ON public.club_members USING btree (club_id, user_id) WHERE (membership_lifecycle_status = 'active'::text);
CREATE INDEX idx_club_members_user ON public.club_members USING btree (user_id);
CREATE INDEX idx_cm_club_role_status ON public.club_members USING btree (club_id, role, status);
CREATE INDEX idx_club_members_club_status ON public.club_members USING btree (club_id, status);
CREATE INDEX idx_club_members_search_scope ON public.club_members USING btree (club_id, user_id) WHERE (status = ANY (ARRAY['active'::text, 'approved'::text]));
CREATE INDEX idx_club_members_user_active ON public.club_members USING btree (user_id, club_id) WHERE (status = ANY (ARRAY['active'::text, 'approved'::text]));
CREATE UNIQUE INDEX idx_clubs_slug ON public.clubs USING btree (slug) WHERE (slug IS NOT NULL);
CREATE INDEX idx_clubs_union_id ON public.clubs USING btree (union_id);
CREATE INDEX idx_clubs_owner ON public.clubs USING btree (owner_id);
CREATE UNIQUE INDEX ca_clubs_one_platform_club ON public.clubs USING btree (is_platform) WHERE is_platform;
CREATE UNIQUE INDEX idx_clubs_name_lower ON public.clubs USING btree (lower(name));
CREATE INDEX idx_clubs_active_lifecycle ON public.clubs USING btree (id) WHERE (lifecycle_status = 'active'::text);
CREATE UNIQUE INDEX idx_clubs_code ON public.clubs USING btree (code);
CREATE UNIQUE INDEX poker_arena_one_diamond_identity ON public.clubs USING btree (asset) WHERE (asset = 'diamonds'::text);
CREATE INDEX idx_notifications_user_all ON public.notifications USING btree (user_id, created_at DESC);
CREATE INDEX idx_notifications_actor_id ON public.notifications USING btree (actor_id);
CREATE UNIQUE INDEX notifications_pa_leak_audit_job_unique ON public.notifications USING btree (((data ->> 'paAuditJobId'::text))) WHERE ((type = 'personal_assistant_audit_complete'::text) AND (data ? 'paAuditJobId'::text));
CREATE INDEX idx_notifications_user_unread ON public.notifications USING btree (user_id, read, created_at DESC) WHERE (read = false);
CREATE UNIQUE INDEX notifications_daily_mission_cycle_unique ON public.notifications USING btree (user_id, ((data ->> 'cycle_date'::text))) WHERE ((type = 'daily_challenge'::text) AND ((data ->> 'source'::text) = 'club_arena_daily_missions'::text));
CREATE INDEX idx_notifications_user_id_id ON public.notifications USING btree (user_id, id);
CREATE UNIQUE INDEX idx_notif_dedup_friend_request ON public.notifications USING btree (user_id, type, ((data ->> 'sender_id'::text))) WHERE (type = 'friend_request'::text);
CREATE INDEX idx_notifications_user_type_read ON public.notifications USING btree (user_id, type, read, created_at DESC);
CREATE UNIQUE INDEX idx_notif_dedup_group_friend ON public.notifications USING btree (user_id, type, ((data ->> 'group_id'::text)), ((data ->> 'friend_id'::text))) WHERE (type = 'home_group_friend_joined'::text);
CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX idx_rakeback_payouts_club_status ON public.rakeback_period_payouts USING btree (club_id, status);
CREATE INDEX idx_rakeback_payouts_user ON public.rakeback_period_payouts USING btree (user_id, created_at DESC);
CREATE INDEX idx_rakeback_periods_status ON public.rakeback_periods USING btree (status);
CREATE INDEX idx_rakeback_periods_user ON public.rakeback_periods USING btree (user_id);
CREATE INDEX rakeback_periods_due_idx ON public.rakeback_periods USING btree (club_id, period_end) WHERE (status = 'pending'::text);
CREATE INDEX rakeback_periods_drain_order_idx ON public.rakeback_periods USING btree (club_id, defer_count, period_end, id) WHERE (status = 'pending'::text);
CREATE INDEX idx_rakeback_periods_club ON public.rakeback_periods USING btree (club_id);
CREATE UNIQUE INDEX settlement_invoices_number_uidx ON public.settlement_invoices USING btree (invoice_number) WHERE (invoice_number IS NOT NULL);
CREATE INDEX idx_invoices_type ON public.settlement_invoices USING btree (invoice_type, status);
CREATE INDEX idx_invoices_club_period ON public.settlement_invoices USING btree (club_id, period_id);
CREATE INDEX settlement_invoices_due_open_idx ON public.settlement_invoices USING btree (due_at) WHERE ((invoice_type = 'union_weekly_squareup'::text) AND (status = ANY (ARRAY['generated'::text, 'overdue'::text])));
CREATE UNIQUE INDEX uq_settlement_invoices_squareup ON public.settlement_invoices USING btree (club_id, period_id, invoice_type) WHERE (invoice_type = 'union_weekly_squareup'::text);
CREATE UNIQUE INDEX accounting_one_club_weekly_statement ON public.settlement_invoices USING btree (club_id, period_id) WHERE (invoice_type = 'club_weekly_accounting'::text);
CREATE INDEX settlement_invoices_adjusts_idx ON public.settlement_invoices USING btree (adjusts_invoice_id) WHERE (adjusts_invoice_id IS NOT NULL);
CREATE INDEX idx_settlement_locks_club_id_fk ON public.settlement_locks USING btree (club_id);
CREATE UNIQUE INDEX idx_one_active_lock_per_club ON public.settlement_locks USING btree (club_id) WHERE (is_active = true);
CREATE UNIQUE INDEX settlement_periods_standalone_week ON public.settlement_periods USING btree (club_id, start_at, end_at) WHERE ((union_id IS NULL) AND (club_id IS NOT NULL));
CREATE UNIQUE INDEX settlement_periods_club_union_window_uidx ON public.settlement_periods USING btree (club_id, union_id, start_at, end_at);
CREATE INDEX idx_settlement_periods_club ON public.settlement_periods USING btree (club_id);
CREATE UNIQUE INDEX settlement_periods_one_open_per_club_uidx ON public.settlement_periods USING btree (COALESCE(club_id, '00000000-0000-0000-0000-000000000000'::uuid)) WHERE (status = 'open'::text);
CREATE INDEX idx_messages_conversation ON public.social_messages USING btree (conversation_id, created_at DESC);
CREATE INDEX idx_social_messages_has_metadata ON public.social_messages USING btree (conversation_id, created_at) WHERE (media_metadata IS NOT NULL);
CREATE UNIQUE INDEX social_messages_sender_request_once ON public.social_messages USING btree (sender_id, request_id) WHERE (request_id IS NOT NULL);
CREATE INDEX idx_social_messages_sender_id ON public.social_messages USING btree (sender_id);
CREATE INDEX idx_union_accounting_runs_standalone_club_id_fk ON public.union_accounting_runs USING btree (standalone_club_id);
CREATE INDEX idx_union_clubs_club_id ON public.union_clubs USING btree (club_id);
CREATE UNIQUE INDEX unions_slug_key ON public.unions USING btree (slug);
CREATE UNIQUE INDEX idx_unions_union_code ON public.unions USING btree (union_code) WHERE (union_code IS NOT NULL);
CREATE INDEX idx_unions_owner_id ON public.unions USING btree (owner_id);
CREATE INDEX idx_wallet_tx_tournament_receipts_cover ON public.wallet_transactions USING btree (related_entity_id) INCLUDE (type, category, amount) WHERE ((related_entity_id IS NOT NULL) AND (((type = 'debit'::text) AND (category = ANY (ARRAY['tournament_buyin'::text, 'rebuy'::text, 'addon'::text]))) OR ((type = 'credit'::text) AND (category = ANY (ARRAY['refund'::text, 'prize'::text, 'bounty'::text])))));
CREATE INDEX idx_wallet_transactions_user_created ON public.wallet_transactions USING btree (user_id, created_at DESC);
CREATE INDEX idx_wallet_tx_club_data_cash_user_window ON public.wallet_transactions USING btree (user_id, created_at) INCLUDE (type, amount, table_id) WHERE ((category = ANY (ARRAY['buyin'::text, 'cashout'::text])) AND (table_id IS NOT NULL));
CREATE INDEX idx_wallet_tx_created_at ON public.wallet_transactions USING btree (created_at);
CREATE INDEX idx_wallet_tx_club_data_player_window ON public.wallet_transactions USING btree (user_id, created_at) INCLUDE (category, type, amount, table_id, related_entity_id) WHERE (((category = ANY (ARRAY['buyin'::text, 'cashout'::text])) AND (table_id IS NOT NULL)) OR ((category = ANY (ARRAY['tournament_buyin'::text, 'prize'::text, 'bounty'::text])) AND (related_entity_id IS NOT NULL)));
CREATE INDEX idx_wallet_tx_user_diamond ON public.wallet_transactions USING btree (user_id) INCLUDE (amount) WHERE ((type = 'credit'::text) AND (category = ANY (ARRAY['diamond_purchase'::text, 'diamond_reward'::text, 'diamond_refund'::text])));
CREATE INDEX idx_wallet_tx_user_diamond_spend ON public.wallet_transactions USING btree (user_id) INCLUDE (amount) WHERE ((type = 'debit'::text) AND (category = ANY (ARRAY['diamond_deduction'::text, 'vip_purchase'::text, 'mint'::text])));
CREATE INDEX idx_wallet_tx_club_data_tournament_user_window ON public.wallet_transactions USING btree (user_id, created_at) INCLUDE (category, amount, related_entity_id) WHERE ((category = ANY (ARRAY['tournament_buyin'::text, 'prize'::text, 'bounty'::text])) AND (related_entity_id IS NOT NULL));
CREATE INDEX idx_wallet_tx_table_created ON public.wallet_transactions USING btree (table_id, created_at) WHERE (table_id IS NOT NULL);
CREATE INDEX idx_wallet_transactions_user ON public.wallet_transactions USING btree (user_id);
CREATE INDEX idx_wt_bbj_promo_payout ON public.wallet_transactions USING btree (category) INCLUDE (amount) WHERE ((category = 'promotion'::text) AND (description = 'BBJ promo pool payout'::text));
CREATE INDEX idx_wallet_tx_entity_cat_created ON public.wallet_transactions USING btree (related_entity_id, category, created_at) WHERE (related_entity_id IS NOT NULL);
CREATE INDEX idx_wallet_tx_table_cat ON public.wallet_transactions USING btree (table_id, category) WHERE (table_id IS NOT NULL);
CREATE INDEX idx_wallet_tx_prize_credits_by_entity ON public.wallet_transactions USING btree (related_entity_id) INCLUDE (amount) WHERE ((type = 'credit'::text) AND (category = 'prize'::text) AND (related_entity_id IS NOT NULL));

-- The earning-source view, verbatim.
CREATE VIEW public.accounting_payable_earning_sources AS  SELECT 'cash_rake_accrual'::text AS source_type,
    s.id AS source_id,
    s.rake_record_id,
    NULL::uuid AS tournament_id,
    s.player_id,
    s.club_id,
    s.union_id,
    s.coordinator_union_id,
    s.earned_at,
    s.rake_credit,
    s.contract
   FROM accounting_cash_rake_sources s
UNION ALL
 SELECT 'tournament_fee_accrual'::text AS source_type,
    s.id AS source_id,
    s.rake_record_id,
    s.tournament_id,
    s.player_id,
    s.club_id,
    s.union_id,
    s.coordinator_union_id,
    rs.recognized_at AS earned_at,
    s.rake_credit,
    s.contract
   FROM ((accounting_tournament_fee_sources s
     JOIN accounting_tournament_recognized_sources rs ON (((rs.source_id = s.id) AND (rs.tournament_id = s.tournament_id))))
     JOIN accounting_tournament_fee_recognitions r ON ((r.tournament_id = s.tournament_id)))
  WHERE ((rs.disposition = 'earned'::text) AND (r.status = 'recognized'::text) AND (rs.rake_credit = s.rake_credit) AND (rs.recognized_at = r.recognized_at) AND (NOT (s.union_id IS DISTINCT FROM r.union_id)));;

-- The cash evidence tables fn_assert_cash_commission_period reads (captured the same way).
CREATE SEQUENCE IF NOT EXISTS public.hand_id_seq;
CREATE TABLE public.accounting_cash_accrual_batches(rake_record_id uuid NOT NULL, hand_id uuid NOT NULL, earned_at timestamp with time zone NOT NULL, source_fingerprint text NOT NULL, status text NOT NULL, plan jsonb, recorded_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL);
CREATE TABLE public.rake_attributions(id uuid DEFAULT gen_random_uuid() NOT NULL, hand_id uuid NOT NULL, player_id uuid NOT NULL, rake_amount numeric NOT NULL, agent_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, rake_record_id uuid, table_id uuid, club_id uuid, gross_contribution numeric, returned_uncalled numeric DEFAULT 0 NOT NULL, eligible_contribution numeric, contribution_weight numeric, weighted_rake_credit numeric, bbj_attributed_contribution numeric DEFAULT 0 NOT NULL, rake_method text);
CREATE TABLE public.rake_records(id uuid DEFAULT gen_random_uuid() NOT NULL, hand_id uuid, table_id uuid, club_id uuid, rake_amount numeric(18,4) DEFAULT 0 NOT NULL, bbj_contribution numeric(18,4) DEFAULT 0, pot_size numeric(18,4), num_players integer, created_at timestamp with time zone DEFAULT now(), player_contributions jsonb, global_hand_id bigint DEFAULT nextval('hand_id_seq'::regclass), is_tournament boolean DEFAULT false NOT NULL, tournament_id uuid, source text DEFAULT 'cash_game'::text, metadata jsonb, rake_method text DEFAULT 'DEALT_EQUAL'::text NOT NULL, returned_uncalled jsonb, terminal_closed_at timestamp with time zone);
ALTER TABLE public.accounting_cash_accrual_batches ADD CONSTRAINT accounting_cash_accrual_batches_status_check CHECK ((status = ANY (ARRAY['accrued'::text, 'legacy_unverified'::text])));
ALTER TABLE public.accounting_cash_accrual_batches ADD CONSTRAINT accounting_cash_accrual_batches_check CHECK (((status = 'accrued'::text) = (plan IS NOT NULL)));
ALTER TABLE public.accounting_cash_accrual_batches ADD CONSTRAINT accounting_cash_accrual_batches_hand_id_key UNIQUE (hand_id);
ALTER TABLE public.accounting_cash_accrual_batches ADD CONSTRAINT accounting_cash_accrual_batches_pkey PRIMARY KEY (rake_record_id);
ALTER TABLE public.rake_attributions ADD CONSTRAINT ck_whole_cents CHECK (((created_at < '2026-09-07 22:00:00+00'::timestamp with time zone) OR ((rake_amount = round(rake_amount, 2)) AND (weighted_rake_credit = round(weighted_rake_credit, 2))))) NOT VALID;
ALTER TABLE public.rake_attributions ADD CONSTRAINT chk_rake_amount_is_two_decimal_places CHECK (((rake_amount IS NULL) OR (rake_amount = round(rake_amount, 2))));
ALTER TABLE public.rake_attributions ADD CONSTRAINT rake_attributions_pkey PRIMARY KEY (id);
ALTER TABLE public.rake_attributions ADD CONSTRAINT rake_attributions_rake_amount_check CHECK ((rake_amount >= (0)::numeric));
ALTER TABLE public.rake_records ADD CONSTRAINT chk_rake_amount_is_two_decimal_places CHECK (((rake_amount IS NULL) OR (rake_amount = round(rake_amount, 2))));
ALTER TABLE public.rake_records ADD CONSTRAINT ck_whole_cents CHECK (((created_at < '2026-09-07 22:00:00+00'::timestamp with time zone) OR ((rake_amount = round(rake_amount, 2)) AND (bbj_contribution = round(bbj_contribution, 2))))) NOT VALID;
ALTER TABLE public.rake_records ADD CONSTRAINT rake_records_pkey PRIMARY KEY (id);
ALTER TABLE public.rake_records ADD CONSTRAINT rake_records_rake_method_check CHECK ((rake_method = ANY (ARRAY['DEALT_EQUAL'::text, 'WEIGHTED_CONTRIBUTED'::text])));
CREATE INDEX accounting_cash_accrual_batches_earned ON public.accounting_cash_accrual_batches USING btree (earned_at, status);
CREATE UNIQUE INDEX uq_rake_attributions_hand_player ON public.rake_attributions USING btree (hand_id, player_id);
CREATE INDEX rake_attributions_club_record ON public.rake_attributions USING btree (club_id, rake_record_id) INCLUDE (player_id, weighted_rake_credit, hand_id);
CREATE INDEX idx_rake_attributions_hand_id ON public.rake_attributions USING btree (hand_id);
CREATE INDEX idx_rake_attributions_player_id ON public.rake_attributions USING btree (player_id, created_at DESC);
CREATE INDEX idx_rake_attributions_club_created ON public.rake_attributions USING btree (club_id, created_at) INCLUDE (player_id, rake_amount);
CREATE INDEX idx_rake_attributions_rake_record_id ON public.rake_attributions USING btree (rake_record_id);
CREATE INDEX idx_rake_records_contribs_gin ON public.rake_records USING gin (player_contributions);
CREATE INDEX idx_rake_records_club_created ON public.rake_records USING btree (club_id, created_at) WHERE (rake_amount > (0)::numeric);
CREATE INDEX idx_rake_records_tournament ON public.rake_records USING btree (tournament_id) WHERE (tournament_id IS NOT NULL);
CREATE INDEX idx_rake_records_table_id ON public.rake_records USING btree (table_id);
CREATE INDEX idx_rake_records_club_id_fk ON public.rake_records USING btree (club_id);
CREATE INDEX idx_rake_records_date ON public.rake_records USING btree (created_at);
CREATE INDEX idx_rake_records_club_data_tournament_window ON public.rake_records USING btree (created_at, tournament_id) INCLUDE (rake_amount, metadata) WHERE (is_tournament AND (rake_amount <> (0)::numeric) AND (tournament_id IS NOT NULL));
CREATE INDEX idx_rake_records_satellite_seat_source ON public.rake_records USING btree (source) WHERE (source = 'fn_award_satellite_seat'::text);
CREATE INDEX idx_rake_records_created_at_id ON public.rake_records USING btree (created_at, id);
CREATE INDEX idx_rake_records_relink ON public.rake_records USING btree (table_id, ((metadata ->> 'hand_number'::text))) WHERE (hand_id IS NULL);
CREATE UNIQUE INDEX uq_rake_records_hand_id ON public.rake_records USING btree (hand_id) WHERE (hand_id IS NOT NULL);
