awk '/onConfirmRebuy={async \(\) => \{/{
  print "        onConfirmRebuy={async () => {"
  print "          if (!tableState.tournamentId || !userId) return;"
  print "          setRebuyProcessing(true);"
  print "          try {"
  print "            const token = rebuyPromptTokenRef.current ?? beginRebuyPrompt();"
  print "            await tournamentService.processRebuy(tableState.tournamentId, userId, token);"
  print "            rebuyJustSucceededRef.current = true;"
  print "            toast?.success(\"Rebuy successful - chips added to your stack\");"
  print "            setShowRebuyModal(false);"
  print "            endRebuyPrompt();"
  print "            bustHoldRef.current.pendingExit = null;"
  print "            releaseBustHold();"
  print "          } catch (err: any) {"
  print "            toast?.error(err.message || \"Rebuy failed\");"
  print "          } finally {"
  print "            setRebuyProcessing(false);"
  print "          }"
  print "        }}"
  print "        onCloseRebuyModal={() => {"
  print "          setShowRebuyModal(false);"
  print "          endRebuyPrompt();"
  print "          releaseBustHold();"
  print "          if (tableId && userId) {"
  print "            GameServerAPI.notifyServerRejectRebuy(tableId).catch(console.error);"
  print "            if ("
  print "              tableState.isTournament &&"
  print "              (tableState.players[tableState.heroSeat - 1]?.stack ?? 0) <= 0"
  print "            ) {"
  print "              heroSeatRef.current = 0;"
  print "              setTableState((prev) => ({ ...prev, heroSeat: 0 }));"
  print "              if (tableState.tournamentId) {"
  print "                goToLobbyWithResultRef.current?.(0, 0, 1500);"
  print "              }"
  print "            }"
  print "          }"
  print "        }}"
  skip=1
  next
}
skip && /^        \/\/ Rebuy/ { skip=0 }
skip { next }
1' src/pages/TablePage.tsx > temp.tsx && mv temp.tsx src/pages/TablePage.tsx
