#!/usr/bin/env bash
#
# refresh-fail2ban-allowlist.sh — keep fail2ban from banning our own CI.
#
# ── The incident this exists to prevent ──────────────────────────────────────
# fail2ban was installed on 2026-08-15 in response to a confirmed root
# compromise. It was configured with the sshd jail in `mode = aggressive`,
# maxretry = 4, bantime = 24h. Correct settings for an internet-facing box.
#
# What nobody checked was what our own deploy pipeline looks like to that
# filter. `ssh-keyscan -H host` opens FIVE parallel connections offering
# different host key types. Four of them disconnect pre-auth, producing
# "Connection closed [preauth]" and "Unable to negotiate ... no matching host
# key type". The aggressive filter counts every one. Five hits in the same
# second against maxretry=4 means the GitHub Actions runner is banned for 24
# hours before it ever authenticates.
#
# The result was a deploy pipeline that worked or timed out depending on
# whether the ban action landed before or after the real SSH connection — a
# coin flip, on every deploy, with no error message that pointed anywhere near
# the cause. The primary fix was removing ssh-keyscan from the workflows and
# pinning the host key. This script is the second layer: even if some future
# workflow reintroduces preauth noise, GitHub's ranges are never bannable.
#
# Run weekly — GitHub rotates these ranges.
#
set -euo pipefail

JAIL_D=/etc/fail2ban/jail.d
OUT="$JAIL_D/00-allowlist.local"
META="${META_URL:-https://api.github.com/meta}"

command -v jq >/dev/null 2>&1 || { apt-get update -qq && apt-get install -y -qq jq; }
mkdir -p "$JAIL_D"

RAW=$(curl -sf --max-time 20 "$META" || echo "")
if [ -z "$RAW" ]; then
  echo "WARN: could not fetch $META — leaving the existing allowlist in place"
  exit 0
fi

# `actions` covers GitHub-hosted runners. IPv4 only: the sshd jail bans by the
# address family it saw, and adding v6 ranges here is harmless but noisy.
RANGES=$(echo "$RAW" | jq -r '.actions[]?' | grep -E '^[0-9]+\.' | tr '\n' ' ')
if [ -z "$RANGES" ]; then
  echo "WARN: $META returned no IPv4 actions ranges — leaving the existing allowlist in place"
  exit 0
fi
COUNT=$(echo "$RANGES" | wc -w | tr -d ' ')

TMP="$OUT.tmp.$$"
{
  echo "# GENERATED by infra/security/refresh-fail2ban-allowlist.sh — do not edit by hand."
  echo "# Last refreshed: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "#"
  echo "# GitHub-hosted Actions runner ranges, from ${META} (.actions)."
  echo "# Without this, fail2ban can ban the deploy pipeline. See the header of"
  echo "# the generating script for the 2026-08-15 incident."
  echo "[DEFAULT]"
  echo "ignoreip = 127.0.0.1/8 ::1 $RANGES"
} > "$TMP"
mv -f "$TMP" "$OUT"

if fail2ban-client reload >/dev/null 2>&1; then
  echo "OK: allowlisted $COUNT GitHub Actions ranges; fail2ban reloaded"
else
  echo "WARN: wrote $OUT but fail2ban-client reload failed"
  exit 1
fi
