import {it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {reviewDailySelection} from '../../../services/horseDailyCorrectiveReview/batch.ts';
import {runHorseDailyCorrectiveReview} from '../../../scripts/horseDailyCorrectiveReview.ts';
import {HorseDecisionJournalStore} from '../../../services/horseDecisionJournal/store.ts';
import {DAY,fakeRow,page,privateFixture,receipt,gapRow,dayState,passReceipt} from './fixture.mjs';
async function withFixture(options,body){const f=privateFixture(options);try{await body(f);}finally{f.cleanup();}}
it('actual private lifecycle, signed source, matching alternative and core yield inactive finding',()=>withFixture({},async f=>{const before=readFileSync(join(f.manifest.journalDirectory,'horse-decisions.sqlite'));const r=await reviewDailySelection(f.manifest,f.source,f.trust,f.selection);expect(r.status).toBe('reviewed_selection');expect(r.rows[0].status).toBe('reviewed_retained_menu');expect(r.rows[0].actor.decisions[0].disposition).toBe('finding');expect(r.rows[0].actor.decisions[0].candidate.activationAllowed).toBe(false);expect(r.fullWindow).toBe(false);expect(r.sourcePopulationVerified).toBe(false);expect(r.gtoVerified).toBe(false);expect(readFileSync(join(f.manifest.journalDirectory,'horse-decisions.sqlite'))).toEqual(before);}));
it('actual matched menu can retain chosen action without corrective candidate',()=>withFixture({changeReference:r=>{for(const a of r.alternatives){a.mean=0;a.lower=0;a.upper=0;}}},async f=>{const r=await reviewDailySelection(f.manifest,f.source,f.trust,f.selection);expect(r.status).toBe('reviewed_selection');expect(r.rows[0].actor.decisions[0].disposition).toBe('non_finding');expect(r.rows[0].actor.decisions[0].candidate).toBeNull();}));
for(const [name,options] of [['observational',{changeReference:r=>r.causal=false}],['wrong_input',{changeReference:r=>r.binding.inputDigest='b'.repeat(64)}],['incomplete_reference',{changeReference:r=>r.complete=false}],['legacy_lifecycle',{legacy:true}],['wrong_accepted_id',{changeHand:h=>h.committedHandId='30000000-0000-4000-8000-000000000009'}],['wrong_accepted_fence',{changeHand:h=>h.fence=h.fence.replace(':12:',':13:')}],['wrong_payload',{changeCommitment:c=>c.payloadDigest='b'.repeat(64)}]])it(`actual core or accepted join refuses ${name}`,()=>withFixture(options,async f=>{const r=await reviewDailySelection(f.manifest,f.source,f.trust,f.selection);expect(r.status).toBe('incomplete');expect(r.rows[0].status).toBe('pending');expect(r.rows[0].actor).toBeNull();}));
for(const [name,mutate] of [['missing_mapping',f=>f.manifest.mappings=[]],['wrong_table',f=>f.row.tableId='10000000-0000-4000-8000-000000000009'],['wrong_queue_hash',f=>f.row.payloadHash='c'.repeat(64)],['wrong_actor',f=>f.row.horseId='20000000-0000-4000-8000-000000000009'],['unknown_eligibility',f=>f.row.eligibility='unknown'],['source_gap',f=>f.row.gaps=['review_source_changed']],['format_gap',f=>f.row.gaps=['review_format_changed']],['wrong_bb',f=>f.row.bigBlind='2'],['wrong_gross',f=>f.row.committedBb='22'],['missing_authority',f=>delete f.manifest.mappings[0].authorityPath],['wrong_trust',f=>f.trust.correctiveKeyDigest='d'.repeat(64)]])it(`pending row ${name}`,()=>withFixture({},async f=>{mutate(f);const r=await reviewDailySelection(f.manifest,f.source,f.trust,f.selection);expect(r.status).toBe('incomplete');expect(r.rows[0].status).toBe('pending');expect(r.rows[0].actor).toBeNull();}));
for(const value of [false,undefined,[],{},'false',1])it(`synthetic permission requires literal true ${JSON.stringify(value)}`,()=>withFixture({},async f=>{f.trust.allowSynthetic=value;expect((await reviewDailySelection(f.manifest,f.source,f.trust,f.selection)).rows[0].reason).toBe('qualified_authority_unavailable');}));
it('trust cannot change across source await',()=>withFixture({},async f=>{f.trust.allowSynthetic=false;const source=async()=>{f.trust.allowSynthetic=true;return page([f.row]);};expect((await reviewDailySelection(f.manifest,source,f.trust,f.selection)).rows[0].reason).toBe('qualified_authority_unavailable');}));
it('input manifest mutation cannot change captured table mapping',()=>withFixture({},async f=>{const source=async()=>{f.manifest.mappings[0].tableId='10000000-0000-4000-8000-000000000009';return page([f.row]);};expect((await reviewDailySelection(f.manifest,source,f.trust,f.selection)).status).toBe('reviewed_selection');}));
it('source cannot replace expected UTC day and matching output',()=>withFixture({},async f=>{const source=async request=>{request.day='2026-09-11';return {...page([f.row]),day:request.day};};const r=await reviewDailySelection(f.manifest,source,f.trust,f.selection);expect(r.status).toBe('incomplete');expect(r.reasons).toContain('daily_source_unavailable');expect(r.rows).toEqual([]);}));
it('two pages are finite and unresolved selection never succeeds',()=>withFixture({},async f=>{f.manifest.mappings=[];const source=vi.fn(async request=>{const start=request.after?9:1;return page(Array.from({length:8},(_,i)=>fakeRow(start+i)),request.after,true);});const r=await reviewDailySelection(f.manifest,source,f.trust,f.selection);expect(source).toHaveBeenCalledTimes(2);expect(r.rows).toHaveLength(16);expect(r.selectionExhausted).toBe(false);expect(r.status).toBe('incomplete');expect(r.reasons).toContain('daily_selection_page_limit');}));
it('empty selection and missing day never establishes complete population',()=>withFixture({},async f=>{const r=await reviewDailySelection(f.manifest,async()=>({...page(),dayObservation:'missing'}),f.trust,f.selection);expect(r.status).toBe('incomplete');expect(r.reasons).toContain('daily_source_observation_missing');expect(r.reasons).toContain('no_retained_review_rows');expect(r.fullWindow).toBe(false);}));
it('source failure after valid page retains partial records but refuses success and closes store',()=>withFixture({},async f=>{const close=vi.spyOn(HorseDecisionJournalStore.prototype,'close');try{let calls=0;const rows=[f.row,...Array.from({length:7},(_,i)=>fakeRow(i+2))];const r=await reviewDailySelection(f.manifest,async request=>{if(calls++)throw Error('private-error');return page(rows,request.after,true);},f.trust,f.selection);expect(r.status).toBe('incomplete');expect(r.rows[0].status).toBe('reviewed_retained_menu');expect(r.reasons).toContain('daily_source_unavailable');expect(close).toHaveBeenCalledTimes(1);expect(JSON.stringify(r)).not.toContain('private-error');}finally{close.mockRestore();}}));
it('actual private CLI writes scoped synthetic result only through injected test authority and refuses overwrite',()=>withFixture({},async f=>{const output=join(f.dir,'result.json');const result=await runHorseDailyCorrectiveReview([f.manifestPath,output],{},{source:f.source,trust:f.trust,selectionSource:f.selection});expect(result.code).toBe(0);const stored=JSON.parse(readFileSync(output,'utf8'));expect(stored.rows[0].evidenceClass).toBe('synthetic_fixture');expect(result.output).not.toContain(f.row.horseId);expect(result.output).not.toContain(f.row.handId);expect(stored.activationAllowed).toBe(false);expect(stored.fullWindow).toBe(false);const again=await runHorseDailyCorrectiveReview([f.manifestPath,output],{},{source:f.source,trust:f.trust,selectionSource:f.selection});expect(again.code).toBe(3);expect(JSON.parse(readFileSync(output,'utf8'))).toEqual(stored);}));
it('production CLI trust path refuses fixture signer despite pinned test public key',()=>withFixture({},async f=>{const r=await runHorseDailyCorrectiveReview([f.manifestPath,join(f.dir,'production-refusal.json')],{HORSE_CORRECTIVE_REVIEW_TRUSTED_KEY_SHA256:f.trust.correctiveKeyDigest},{source:f.source,selectionSource:f.selection});expect(r.code).toBe(2);}));
it('explicit cursor makes later selections reachable and preserves retry position for pending rows',()=>withFixture({},async f=>{const before=fakeRow(16);f.manifest.after={playedAt:before.playedAt,handId:before.handId,horseId:before.horseId};const source=vi.fn(async req=>page([fakeRow(17)],req.after,false));const r=await reviewDailySelection(f.manifest,source,f.trust,f.selection);expect(source.mock.calls[0][0].after).toEqual(f.manifest.after);expect(r.rows[0].queueCursor.handId).toBe(fakeRow(17).handId);expect(r.rows[0].retryAfter).toEqual(f.manifest.after);expect(r.resumeCursor).toEqual(r.rows[0].queueCursor);expect(r.status).toBe('incomplete');}));
it('changed payload on a cached hand never reuses the first actor review as authority',()=>withFixture({},async f=>{const second={...f.row,horseId:'ffffffff-ffff-4fff-8fff-ffffffffffff',payloadHash:'c'.repeat(64)};const r=await reviewDailySelection(f.manifest,async()=>page([f.row,second]),f.trust,f.selection);expect(r.rows[0].status).toBe('reviewed_retained_menu');expect(r.rows[1].reason).toBe('queued_source_changed');expect(r.rows[1].actor).toBeNull();expect(r.status).toBe('incomplete');}));
it('source cannot mutate a retained nonnull expected cursor',()=>withFixture({},async f=>{const cursor={playedAt:'2026-09-10T00:00:00.000001Z',handId:f.row.handId,horseId:f.row.horseId};f.manifest.after=cursor;const source=async req=>{req.after.handId='ffffffff-ffff-4fff-8fff-ffffffffffff';return page([f.row],req.after);};const r=await reviewDailySelection(f.manifest,source,f.trust,f.selection);expect(r.reasons).toContain('daily_source_unavailable');expect(r.startCursor).toEqual(cursor);expect(r.rows).toEqual([]);}));
it('third hand cannot exceed reserved evidence budget and remains explicitly retryable',()=>withFixture({},async f=>{const rows=[f.row,fakeRow(2),fakeRow(3)];f.manifest.mappings=rows.map(r=>({...f.manifest.mappings[0],handId:r.handId}));const r=await reviewDailySelection(f.manifest,async()=>page(rows),f.trust,f.selection);expect(r.rows[2].reason).toBe('batch_evidence_budget_exhausted');expect(r.rows[2].retryAfter.handId).toBe(rows[1].handId);expect(r.status).toBe('incomplete');}));
it('CLI cannot swap admitted output path during the source await',()=>withFixture({},async f=>{const original=join(f.dir,'original.json'),replacement=join(f.dir,'replacement.json');const args=[f.manifestPath,original];const source=async()=>{args[1]=replacement;return page([f.row]);};const r=await runHorseDailyCorrectiveReview(args,{},{source,trust:f.trust,selectionSource:f.selection});expect(r.code).toBe(0);expect(JSON.parse(readFileSync(original,'utf8')).status).toBe('reviewed_selection');expect(()=>readFileSync(replacement)).toThrow();}));
it('changing production key configuration still cannot admit synthetic fixtures',()=>withFixture({},async f=>{const environment={HORSE_CORRECTIVE_REVIEW_TRUSTED_KEY_SHA256:f.trust.correctiveKeyDigest};const source=async()=>{environment.HORSE_CORRECTIVE_REVIEW_TRUSTED_KEY_SHA256='b'.repeat(64);return page([f.row]);};const r=await runHorseDailyCorrectiveReview([f.manifestPath,join(f.dir,'captured-env.json')],environment,{source,selectionSource:f.selection});expect(r.code).toBe(2);expect(JSON.parse(readFileSync(join(f.dir,'captured-env.json'),'utf8')).rows[0].reason).toBe('qualified_authority_unavailable');}));
it('actual HTTP adapter → CLI → retained store → signed core → private result positive route',()=>withFixture({},async f=>{const {createDailyReviewSource}=await import('../../../services/horseDailyCorrectiveReview/source.ts');const fetcher=vi.fn(async()=>new Response(JSON.stringify(page([f.row]))));const source=createDailyReviewSource({SUPABASE_URL:'https://synthetic.invalid',SUPABASE_SERVICE_ROLE_KEY:'synthetic-not-a-secret'},fetcher);const output=join(f.dir,'whole-route.json');const r=await runHorseDailyCorrectiveReview([f.manifestPath,output],{},{source,trust:f.trust,selectionSource:f.selection});expect(r.code).toBe(0);expect(fetcher).toHaveBeenCalledTimes(1);expect(JSON.parse(readFileSync(output,'utf8')).rows[0].actor.decisions[0].candidate.status).toBe('proposed_inactive');}));
it('accepted-only gross commitment cannot manufacture discretionary decision coverage',()=>withFixture({changeRecords:records=>records.filter(r=>r.kind==='accepted_hand')},async f=>{const r=await reviewDailySelection(f.manifest,f.source,f.trust,f.selection);expect(r.status).toBe('incomplete');expect(r.rows[0].status).toBe('pending');expect(r.rows[0].actor).toBeNull();expect(r.gtoVerified).toBe(false);}));

// P14.3: the selection receipt surfaces gap-only hands the review page cannot show.
it('missing-source and late-arrival hands are explicit pending rows and refuse aggregate success',()=>withFixture({},async f=>{const gaps=[gapRow(1,['accepted_commitment_facts_missing']),gapRow(2,['late_arrival_after_pass:1']),gapRow(3,['dealt_roster_invalid','horse_identity_unknown'])];
 const r=await reviewDailySelection(f.manifest,f.source,f.trust,async()=>receipt(gaps));
 expect(r.rows[0].status).toBe('reviewed_retained_menu');expect(r.status).toBe('incomplete');
 expect(r.sourceGaps.map(g=>[g.kind,g.status,g.handId])).toEqual([['missing_source','pending',gaps[0].handId],['late_arrival','pending',gaps[1].handId],['source_gap','pending',gaps[2].handId]]);
 expect(r.sourceGaps[1].retryAfter).toEqual({playedAt:gaps[0].playedAt,handId:gaps[0].handId});
 expect(r.selection).toMatchObject({status:'read',exhausted:true,missingSourceRows:1,lateArrivalRows:1,sourceGapRows:1,sourceCoverage:'not_established'});
 expect(r.reasons).toEqual(expect.arrayContaining(['daily_missing_source_rows','daily_late_arrival_rows','daily_source_gap_rows']));
 expect(r.fullWindow).toBe(false);expect(r.sourcePopulationVerified).toBe(false);}));
it('pass receipts and day state are carried, and a clean receipt keeps the reviewed outcome',()=>withFixture({},async f=>{const r=await reviewDailySelection(f.manifest,f.source,f.trust,f.selection);
 expect(r.status).toBe('reviewed_selection');expect(r.selection.passes).toHaveLength(1);expect(r.selection.passes[0].sourceCoverage).toBe('not_established');expect(r.selection.dayState.pass).toBe(1);expect(r.sourceGaps).toEqual([]);expect(r.sourcePopulationVerified).toBe(false);}));
for(const [name,selection,expected] of [
 ['not supplied',undefined,'daily_selection_receipt_not_read'],
 ['unavailable',async()=>{throw Error('private-error');},'daily_selection_unavailable'],
 ['malformed',async()=>({...receipt(),sourceCoverage:'complete'}),'daily_selection_unavailable'],
 ['day never observed',async()=>receipt([],null,false,{dayState:null,passes:[]}),'daily_selection_day_missing'],
 ['pass in progress',async()=>receipt([],null,false,{dayState:dayState({pass:2,finishedAt:null})}),'daily_selection_pass_in_progress'],
 ['no completed pass',async()=>receipt([],null,false,{passes:[]}),'daily_selection_no_completed_pass'],
])it(`selection receipt ${name} refuses aggregate success`,()=>withFixture({},async f=>{const r=await reviewDailySelection(f.manifest,f.source,f.trust,selection);expect(r.rows[0].status).toBe('reviewed_retained_menu');expect(r.status).toBe('incomplete');expect(r.reasons).toContain(expected);expect(JSON.stringify(r)).not.toContain('private-error');}));
it('two gap pages are finite, resumable from the manifest and a changed pass set is named',()=>withFixture({},async f=>{const first=Array.from({length:8},(_,i)=>gapRow(i+1,['accepted_commitment_facts_missing'])),second=Array.from({length:8},(_,i)=>gapRow(i+9,['late_arrival_after_pass:1']));
 const selection=vi.fn(async req=>req.after?receipt(second,req.after,true,{passes:[passReceipt(1,{handGaps:1})]}):receipt(first,null,true));
 const r=await reviewDailySelection(f.manifest,f.source,f.trust,selection);expect(selection).toHaveBeenCalledTimes(2);expect(r.sourceGaps).toHaveLength(16);
 expect(r.selection.exhausted).toBe(false);expect(r.selection.resumeCursor).toEqual({playedAt:second[7].playedAt,handId:second[7].handId});
 expect(r.reasons).toEqual(expect.arrayContaining(['daily_selection_receipt_page_limit','daily_selection_changed_between_pages']));
 f.manifest.selectionAfter=r.selection.resumeCursor;const resumed=vi.fn(async req=>receipt([],req.after));const again=await reviewDailySelection(f.manifest,f.source,f.trust,resumed);
 expect(resumed.mock.calls[0][0].after).toEqual(r.selection.resumeCursor);expect(again.selection.startCursor).toEqual(r.selection.resumeCursor);expect(again.status).toBe('reviewed_selection');}));
it('selection source cannot mutate the retained expected gap cursor',()=>withFixture({},async f=>{const g=gapRow(1,['x']);f.manifest.selectionAfter={playedAt:g.playedAt,handId:g.handId};
 const r=await reviewDailySelection(f.manifest,f.source,f.trust,async req=>{req.after.handId='ffffffff-ffff-4fff-8fff-ffffffffffff';return receipt([],req.after);});
 expect(r.reasons).toContain('daily_selection_unavailable');expect(r.selection.startCursor).toEqual({playedAt:g.playedAt,handId:g.handId});}));
it('CLI reads the selection receipt through the injected source and reports gap counts only',()=>withFixture({},async f=>{const output=join(f.dir,'gaps.json');
 const r=await runHorseDailyCorrectiveReview([f.manifestPath,output],{},{source:f.source,trust:f.trust,selectionSource:async()=>receipt([gapRow(1,['hand_without_commit'])])});
 expect(r.code).toBe(2);expect(JSON.parse(r.output).sourceGaps).toBe(1);expect(r.output).not.toContain(gapRow(1,[]).handId);expect(JSON.parse(readFileSync(output,'utf8')).sourceGaps[0].kind).toBe('missing_source');}));
it('an unreadable gap row is its own pending kind and refuses aggregate success',()=>withFixture({},async f=>{const g=gapRow(1,['daily_gap_reasons_unavailable'],{tableId:null});
 const r=await reviewDailySelection(f.manifest,f.source,f.trust,async()=>receipt([g]));expect(r.sourceGaps[0]).toMatchObject({kind:'reasons_unavailable',status:'pending',tableId:null,reasons:['daily_gap_reasons_unavailable']});
 expect(r.selection.unreadableGapRows).toBe(1);expect(r.selection.missingSourceRows).toBe(0);expect(r.reasons).toContain('daily_gap_reasons_unavailable');expect(r.status).toBe('incomplete');}));
