import { supabase } from '../lib/supabase';

/**
 * 🏛️ SETTLEMENT SERVICE
 * Handles Union Cross-Club Wires and Monday Payouts.
 * 
 * FORMULA:
 * Wire = (Net Player P/L) + (Gross Rake Return) - (Union Tax 10%)
 */
export const SettlementService = {

    /**
     * CALCULATE UNION SETTLEMENT
     * @param clubId 
     * @param netPlayerPL (Sum of all player wins/losses vs Union pool)
     * @param grossRake (Total rake generated by club players)
     */
    calculateUnionWire(clubId: string, netPlayerPL: number, grossRake: number) {
        const unionTax = grossRake * 0.10; // 10% Tax

        // The Formula
        const finalWire = netPlayerPL + grossRake - unionTax;

        return {
            clubId,
            netPlayerPL,
            grossRake,
            unionTax,
            finalWire,
            action: finalWire >= 0 ? 'COLLECT_FROM_UNION' : 'PAY_TO_UNION'
        };
    },

    /**
     * EXECUTE MONDAY PAYOUT
     * 1. Check if Sunday Invoice is Paid (for Agents).
     * 2. Inject Rakeback/Commissions.
     */
    async executePayout(settlementId: string) {
        // 1. Fetch Settlement
        const { data: settlement, error } = await supabase
            .from('settlements')
            .select('*')
            .eq('id', settlementId)
            .single();

        if (error) throw error;
        // In a real system, we might require Debt to be PAID first.
        // For testing/internal build, we proceed.

        // 2. PAY COMMISSIONS TO AGENTS
        // We assume we have a way to get total commissions due for this settlement period
        // For now, we simulate a payout to the specific agent associated with this settlement (if any)

        if (settlement.agent_id && settlement.commission_amount > 0) {
            const { error: payoutError } = await supabase.rpc('system_payout_commission', {
                p_agent_id: settlement.agent_id,
                p_amount: settlement.commission_amount
            });

            if (payoutError) throw payoutError;
        }

        // 3. UPDATE STATUS
        await supabase
            .from('settlements')
            .update({ status: 'COMPLETED', payouts_processed_at: new Date().toISOString() })
            .eq('id', settlementId);

        return { success: true, message: "Payouts Injected & Settlement Completed" };
    }
};
