-- Installed definition of the owner agreement RPC, September 21. Source:
-- supabase/migrations/20260914102113_road_crossing_and_mines_keep_each_round_under_seal.sql:247-269,
-- copied verbatim (never redefined since; 20260921052548 names it only in a comment).
-- The capture predates it; migration 20260921202834 pins its md5 before replacing it.
-- No production player data. daily-burn-provenance.json carries the witness.
SET check_function_bodies=off;
CREATE OR REPLACE FUNCTION public.fn_diamond_spins_owner_terms(p_club_id uuid,p_agree boolean DEFAULT false)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE h uuid; k text; v_owner uuid; receipt public.diamond_spins_owner_consents;
 terms text:='I Authorize Diamond Spins For This Host. Player Diamond Entries Go To My Owner Diamond Wallet. Chip Prizes Use The BBJ-Funded Promo Wallet First, With The Union Main Bank Covering Any Shortfall, Or The Club Main Bank For A Standalone Club. My Owner Diamond Wallet Pays For Awarded Throwables, Time Banks, Rabbit Hunts, Eligible One-Day VIP Cards, And VIP Diamond Multiplier Rewards At Their Recorded Diamond Cost. A Reward Must Be Funded Before It Is Awarded.';
BEGIN
 IF auth.uid() IS NULL THEN RETURN jsonb_build_object('ok',false,'error','Sign In First'); END IF;
 SELECT host_id,host_kind INTO h,k FROM public.fn_wheel_host(p_club_id);
 IF h IS NULL THEN RETURN jsonb_build_object('ok',false,'error','That Club Could Not Be Found'); END IF;
 v_owner:=public.fn_diamond_game_owner(h,k);
 IF v_owner IS NULL THEN RETURN jsonb_build_object('ok',false,'error','The Host Wallet Owner Is Not Set'); END IF;
 IF auth.uid() IS DISTINCT FROM v_owner AND NOT public.fn_wheel_can_operate(h,k,auth.uid()) THEN
  RETURN jsonb_build_object('ok',false,'error','Only This Host Can Read Its Agreement'); END IF;
 IF p_agree IS TRUE THEN
  IF auth.uid() IS DISTINCT FROM v_owner THEN
   RETURN jsonb_build_object('ok',false,'error','The Wallet Owner Must Accept This Agreement'); END IF;
  INSERT INTO public.diamond_spins_owner_consents(host_id,host_kind,owner_id,terms_version,terms_text)
   VALUES(h,k,v_owner,'diamond-spins-2026-09-14-v1',terms) ON CONFLICT DO NOTHING;
 END IF;
 SELECT * INTO receipt FROM public.diamond_spins_owner_consents c WHERE c.host_id=h
  AND c.owner_id=v_owner AND c.terms_version='diamond-spins-2026-09-14-v1';
 RETURN jsonb_build_object('ok',true,'host_id',h,'host_kind',k,'is_owner',auth.uid()=v_owner,
  'accepted',receipt.host_id IS NOT NULL,'accepted_at',receipt.accepted_at,'terms',terms,
  'terms_version','diamond-spins-2026-09-14-v1');
END $$;
REVOKE ALL ON FUNCTION public.fn_diamond_spins_owner_terms(uuid,boolean) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.fn_diamond_spins_owner_terms(uuid,boolean) TO authenticated,service_role;

-- The trial balance report (fn_ca_diamond_trial_balance, already captured in
-- daily-custody-preimages.sql) reads two objects the capture never needed:
-- the house ledger table (20260903002841:73-83, verbatim, empty here) and the
-- engine spend reader (20260908123428:100-111 as made SECURITY INVOKER by
-- 20260908124528:39) over the captured ca_diamond_engine_spend. Both are read only; the probe runs the report before and
-- after a settled day and requires it to balance.
CREATE TABLE IF NOT EXISTS public.ca_diamond_house_ledger (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at            timestamptz NOT NULL DEFAULT now(),
    delta         numeric(20,0) NOT NULL,
    balance_after numeric(20,0) NOT NULL,
    reason        text NOT NULL,
    reference     text NOT NULL UNIQUE,
    user_id       uuid,
    tournament_id uuid
);
ALTER TABLE public.ca_diamond_house_ledger ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.fn_ca_diamond_engine_spent(p_period text, p_engine text)
RETURNS bigint
LANGUAGE sql STABLE SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  -- The frozen baseline plus everything appended since. One number, one definition, read by the
  -- rule and by the report alike.
  SELECT COALESCE((SELECT b.spent_diamonds FROM public.diamond_reward_budgets b
                    WHERE b.period = p_period AND b.engine = p_engine), 0)
       + COALESCE((SELECT SUM(s.amount) FROM public.ca_diamond_engine_spend s
                    WHERE s.period = p_period AND s.engine = p_engine), 0);
$$;
REVOKE ALL ON FUNCTION public.fn_ca_diamond_engine_spent(text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_ca_diamond_engine_spent(text, text) TO service_role;
DO $w$ BEGIN
 IF md5(pg_get_functiondef('public.fn_diamond_spins_owner_terms(uuid,boolean)'::regprocedure))<>'3240b38f3ac4818a7e6ada0342a4dd1c' THEN
  RAISE EXCEPTION 'Daily burn fixture witness failed: fn_diamond_spins_owner_terms is not the 20260914102113 definition';
 END IF;
END $w$;
