/**
 * ═══════════════════════════════════════════════════════════════════════════════
 *  THE OTHER HALF OF THE PHANTOM-COLUMN QUESTION
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * check-phantom-columns asks whether a written column EXISTS. Nothing asked
 * whether the columns a table REQUIRES were supplied. Postgres refuses both
 * statements just as completely, both errors land in a catch, and both controls
 * silently do nothing.
 *
 * Four instances, all found by hand on 2026-08-28:
 *
 *   audit_trail.actor_role, .target_type   the agent audit trail wrote nothing
 *   referrals.referral_code_used           bonuses paid, referral never recorded
 *   club_announcements.author_id           creating an announcement never worked
 *   credit_requests.club_id                every credit increase request threw
 *
 * The first two are why this is not a nice-to-have: they were ALSO
 * phantom-column bugs, and repointing the wrong names - the fix that passes
 * review - would have left both inserts failing exactly as before.
 *
 * These pins exercise the checker's PARSER, because the parser is the whole
 * game. A first pass that read only `name:` pairs reported fourteen violations,
 * twelve of which were shorthand properties or spreads. A gate that cries wolf
 * twelve times out of fourteen is one nobody keeps.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { pathToFileURL } from 'url';
import { sliceMethod } from './helpers/sourceWindow';

const read = (p: string) => readFileSync(resolve(__dirname, '..', p), 'utf8');

type Keys = (body: string) => { keys: Set<string>; unknowable: boolean };
let topLevelKeys: Keys;

beforeAll(async () => {
  const href = pathToFileURL(
    resolve(__dirname, '..', 'scripts/ci/check-required-columns.mjs')
  ).href;
  const mod = await import(/* @vite-ignore */ href);
  topLevelKeys = mod.topLevelKeys;
});

describe('the parser reads an object literal, not a line', () => {
  it('counts shorthand properties, which is what the naive pass missed', () => {
    // `{ club_id: uuid, title, content }` supplies THREE columns. Reading only
    // `name:` pairs saw one, and reported a table with three required columns
    // as missing two of them.
    const { keys, unknowable } = topLevelKeys('{ club_id: uuid, title, content }');
    expect([...keys].sort()).toEqual(['club_id', 'content', 'title']);
    expect(unknowable).toBe(false);
  });

  it('is not fooled by a brace, comma or colon inside a string', () => {
    const { keys } = topLevelKeys("{ a: 'x, y: z}', b: 1 }");
    expect([...keys].sort()).toEqual(['a', 'b']);
  });

  it('does not mistake a nested object’s keys for its own', () => {
    const { keys } = topLevelKeys('{ outer: { inner: 1, other: 2 }, second: 3 }');
    expect([...keys].sort()).toEqual(['outer', 'second']);
  });

  it('refuses to judge a payload that spreads another object', () => {
    /**
     * HorseOrchestrator writes `...buyInColumns(config.buyIn)`, which supplies
     * buy_in_amount and buy_in_fee at runtime. Six such sites exist and all six
     * are correct. Guessing would have made them the first six entries in the
     * allowlist, and an allowlist that opens with six false alarms is one
     * nobody reads.
     */
    const { unknowable } = topLevelKeys('{ name: n, ...buyInColumns(x) }');
    expect(unknowable).toBe(true);
  });

  it('refuses to judge a computed key', () => {
    expect(topLevelKeys('{ [dynamic]: 1, other: 2 }').unknowable).toBe(true);
  });
});

describe('the gate is real, wired and currently at zero', () => {
  it('has a manifest generated from the live schema, not hand-written', () => {
    const p = 'scripts/ci/supabase-required-columns-manifest.json';
    expect(existsSync(resolve(__dirname, '..', p))).toBe(true);
    const m = JSON.parse(read(p));
    expect(m._comment).toContain('Do NOT hand-edit');
    // The two that were actually broken, so a manifest that silently lost its
    // contents cannot pass this.
    expect(m.required.club_announcements).toContain('author_id');
    expect(m.required.credit_requests).toContain('club_id');
  });

  it('is regenerated by the same generator the daily refresh runs', () => {
    // Hand-patching one entry at a time is what produced the manifest drift
    // this repo has already paid for three times in one session.
    const gen = read('scripts/ci/gen-schema-manifest.mjs');
    expect(gen).toContain('fn_required_columns_manifest');
    expect(gen).toContain('supabase-required-columns-manifest.json');
  });

  it('blocks in CI and on pre-push', () => {
    expect(read('.github/workflows/ci.yml')).toContain(
      'node scripts/ci/check-required-columns.mjs'
    );
    expect(read('.husky/pre-push')).toContain('check-required-columns.mjs');
  });

  it('needs no allowlist, because there is nothing left to forgive', () => {
    // The strongest form a gate can take. If this file ever appears, the
    // question to ask is what stopped being fixable.
    expect(existsSync(resolve(__dirname, '..', 'scripts/ci/required-columns.allowlist.json'))).toBe(
      false
    );
  });
});

describe('the two writes that were broken now supply what they must', () => {
  it('an announcement carries its author', () => {
    const src = read('src/pages/AdminDashboardPage.tsx');
    expect(src).toContain('author_id: user!.id');
    // And refuses readably rather than sending a write that cannot land.
    expect(src).toContain('Your session could not be identified');
  });

  it('a credit request carries its club', () => {
    const src = read('src/services/CreditService.ts');
    const account = sliceMethod(src, 'async getCreditAccount(');
    const request = sliceMethod(src, 'async requestCreditIncrease(');
    expect(account).toMatch(/\.select\(\s*'id, user_id, club_id,/);
    expect(request).toMatch(
      /!account\.clubId\s*\|\|\s*account\.userId\s*!==\s*actor\s*\|\|\s*account\.agentId\s*!==\s*agentId/
    );
    expect(request).toMatch(
      /creditRequestService\.submitRequest\(actor,\s*\{\s*clubId:\s*account\.clubId,\s*approverId:\s*owner\.owner_id/
    );
    expect(request).not.toMatch(/\.from\('credit_requests'\)/);
    const insert = sliceMethod(
      read('src/services/CreditRequestService.ts'),
      'async submitRequest('
    );
    expect(insert).toMatch(/!request\.clubId\s*\|\|/);
    expect(insert).toMatch(
      /\.from\('credit_requests'\)\s*\.insert\(\{\s*requester_id:\s*requesterId,\s*approver_id:\s*request\.approverId,\s*club_id:\s*request\.clubId,/
    );
    expect(insert).toMatch(/data\.club_id\s*!==\s*request\.clubId/);
  });
});
