"""Exact pure diagnostic query constructors; no execution on import."""
def literal(s):
    return "'" + s.replace("'", "''") + "'"

def function_query(signature):
    return "SELECT COALESCE((SELECT jsonb_build_object('body_md5',md5(p.prosrc),'definition_md5',md5(pg_get_functiondef(p.oid)),'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'settings',p.proconfig,'security_definer',p.prosecdef,'volatility',p.provolatile,'identity_arguments',pg_get_function_identity_arguments(p.oid),'arguments',pg_get_function_arguments(p.oid),'result',pg_get_function_result(p.oid),'language',(SELECT lanname FROM pg_language WHERE oid=p.prolang),'strict',p.proisstrict,'leakproof',p.proleakproof,'parallel',p.proparallel,'cost',p.procost,'rows',p.prorows,'kind',p.prokind,'returns_set',p.proretset,'raw_pg_proc',to_jsonb(p)) FROM pg_proc p WHERE p.oid=to_regprocedure(" + literal(signature) + ")),'null'::jsonb)"

def relation_extra_query(name):
    return "SELECT COALESCE((SELECT jsonb_build_object('raw_pg_class',to_jsonb(c),'attributes',COALESCE((SELECT jsonb_agg(to_jsonb(a)||jsonb_build_object('collation_identity',a.attcollation::regcollation::text,'type_identity',a.atttypid::regtype::text) ORDER BY a.attnum) FROM pg_attribute a WHERE a.attrelid=c.oid AND a.attnum>0),'[]'::jsonb),'all_triggers_including_RI',COALESCE((SELECT jsonb_agg(to_jsonb(t)||jsonb_build_object('definition',pg_get_triggerdef(t.oid),'function_identity',t.tgfoid::regprocedure::text) ORDER BY t.tgname) FROM pg_trigger t WHERE t.tgrelid=c.oid),'[]'::jsonb),'constraint_records',COALESCE((SELECT jsonb_agg(to_jsonb(k)||jsonb_build_object('definition',pg_get_constraintdef(k.oid),'definition_pretty',pg_get_constraintdef(k.oid,true)) ORDER BY k.conname) FROM pg_constraint k WHERE k.conrelid=c.oid),'[]'::jsonb),'index_records',COALESCE((SELECT jsonb_agg(to_jsonb(i)||jsonb_build_object('definition',pg_get_indexdef(i.indexrelid),'predicate',pg_get_expr(i.indpred,i.indrelid),'expressions',pg_get_expr(i.indexprs,i.indrelid)) ORDER BY i.indexrelid) FROM pg_index i WHERE i.indrelid=c.oid),'[]'::jsonb)) FROM pg_class c WHERE c.oid=to_regclass(" + literal(name) + ")),'null'::jsonb)"
