/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * ♠ CLUB ARENA — Type-Safe Bus Event Constants
 * ═══════════════════════════════════════════════════════════════════════════════
 * Centralized event name constants for MasterBus emit/subscribe.
 * Prevents typos and enables IDE autocompletion.
 *
 * Usage:
 *   import { BUS } from '../constants/busEvents';
 *   masterBus.emit(BUS.CLUB_UPDATED, payload);
 *   masterBus.subscribe(BUS.CLUB_UPDATED, handler);
 */

export const BUS = {
  // ── Club lifecycle ──
  CLUB_JOINED: 'CLUB_JOINED',
  CLUB_LEFT: 'CLUB_LEFT',
  CLUB_UPDATED: 'CLUB_UPDATED',
  CLUB_DELETED: 'CLUB_DELETED',
  CLUB_SETTINGS_UPDATED: 'CLUB_SETTINGS_UPDATED',

  // ── Table events ──
  TABLE_CREATED: 'TABLE_CREATED',
  TABLE_UPDATED: 'TABLE_UPDATED',
  TABLE_DELETED: 'TABLE_DELETED',
  TABLE_JOINED: 'TABLE_JOINED',
  TABLE_LEFT: 'TABLE_LEFT',
  TABLE_SEATED: 'TABLE_SEATED',

  // ── Tournament events ──
  TOURNAMENT_UPDATED: 'TOURNAMENT_UPDATED',
  TOURNAMENT_STARTED: 'TOURNAMENT_STARTED',
  TOURNAMENT_ENDED: 'TOURNAMENT_ENDED',
  TOURNAMENT_REGISTERED: 'TOURNAMENT_REGISTERED',
  TOURNAMENT_UNREGISTERED: 'TOURNAMENT_UNREGISTERED',

  // ── Financial events ──
  BALANCE_UPDATED: 'BALANCE_UPDATED',
  WALLET_UPDATED: 'WALLET_UPDATED',
  GOLD_BALANCE_CHANGED: 'GOLD_BALANCE_CHANGED',
  DIAMOND_BALANCE_CHANGED: 'DIAMOND_BALANCE_CHANGED',
  CHIP_BALANCE_CHANGED: 'CHIP_BALANCE_CHANGED',
  CASHOUT_REQUESTED: 'CASHOUT_REQUESTED',
  CASHOUT_APPROVED: 'CASHOUT_APPROVED',
  CASHOUT_DENIED: 'CASHOUT_DENIED',
  DEPOSIT_COMPLETED: 'DEPOSIT_COMPLETED',
  RAKEBACK_CLAIMED: 'RAKEBACK_CLAIMED',

  // ── Member / Social events ──
  MEMBER_UPDATED: 'MEMBER_UPDATED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  FRIEND_REQUEST_SENT: 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_DECLINED: 'FRIEND_REQUEST_DECLINED',
  FRIEND_REMOVED: 'FRIEND_REMOVED',
  PRESENCE_CHANGED: 'PRESENCE_CHANGED',

  // ── Messaging events ──
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  CONVERSATION_UPDATED: 'CONVERSATION_UPDATED',
  NOTIFICATION_RECEIVED: 'NOTIFICATION_RECEIVED',

  // ── Game / Table action events ──
  HAND_COMPLETED: 'HAND_COMPLETED',
  PLAYER_ACTION: 'PLAYER_ACTION',
  GAME_STATE_CHANGED: 'GAME_STATE_CHANGED',

  // ── Gamification events ──
  ACHIEVEMENT_UNLOCKED: 'ACHIEVEMENT_UNLOCKED',
  CHALLENGE_COMPLETED: 'CHALLENGE_COMPLETED',
  CHALLENGE_UPDATED: 'CHALLENGE_UPDATED',
  XP_EARNED: 'XP_EARNED',
  LEVEL_UP: 'LEVEL_UP',

  // ── Admin events ──
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
  ANNOUNCEMENT_POSTED: 'ANNOUNCEMENT_POSTED',
  DISPUTE_UPDATED: 'DISPUTE_UPDATED',
  PROMOTION_UPDATED: 'PROMOTION_UPDATED',
} as const;

/** Type for any valid bus event name */
export type BusEventName = (typeof BUS)[keyof typeof BUS];
