BEGIN;
DO $$ BEGIN IF current_database()<>'satellite_qualification_verified' THEN RAISE EXCEPTION 'Private fixture'; END IF; END $$;
CREATE TABLE public.poker_diamond_custody("id" uuid DEFAULT gen_random_uuid() NOT NULL,"user_id" uuid NOT NULL,"arena_id" uuid NOT NULL,"purpose" text NOT NULL,"target_id" uuid NOT NULL,"entry_key" text NOT NULL,"balance" bigint DEFAULT 0 NOT NULL,"state" text DEFAULT 'reserved'::text NOT NULL,"created_at" timestamp with time zone DEFAULT now() NOT NULL,"released_at" timestamp with time zone,"seat_id" uuid,"seat_joined_at" timestamp with time zone,"occupancy_id" uuid);
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_arena_id_fkey" FOREIGN KEY (arena_id) REFERENCES clubs(id) ON DELETE RESTRICT;
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_balance_check" CHECK (((balance >= 0) AND (balance <= 2147483647)));
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_check" CHECK (((state = 'released'::text) = (released_at IS NOT NULL)));
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_check1" CHECK (((state <> 'released'::text) OR (balance = 0)));
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_entry_key_check" CHECK (((length(entry_key) >= 1) AND (length(entry_key) <= 160)));
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_pkey" PRIMARY KEY (id);
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_purpose_check" CHECK ((purpose = ANY (ARRAY['cash_seat'::text, 'tournament_entry'::text])));
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_state_check" CHECK ((state = ANY (ARRAY['reserved'::text, 'active'::text, 'released'::text])));
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_custody_user_id_purpose_target_id_entry_key_key" UNIQUE (user_id, purpose, target_id, entry_key);
ALTER TABLE public.poker_diamond_custody ADD CONSTRAINT "poker_diamond_seat_identity_complete" CHECK ((((seat_id IS NULL) AND (seat_joined_at IS NULL) AND (occupancy_id IS NULL)) OR ((purpose = 'cash_seat'::text) AND (seat_id IS NOT NULL) AND (seat_joined_at IS NOT NULL) AND (occupancy_id IS NOT NULL))));
CREATE INDEX poker_diamond_custody_seat ON public.poker_diamond_custody USING btree (seat_id) WHERE (seat_id IS NOT NULL);
CREATE UNIQUE INDEX poker_diamond_one_open_entry ON public.poker_diamond_custody USING btree (user_id, purpose, target_id) WHERE (state <> 'released'::text);
CREATE INDEX poker_diamond_custody_arena ON public.poker_diamond_custody USING btree (arena_id);
CREATE INDEX poker_diamond_custody_user_state ON public.poker_diamond_custody USING btree (user_id, state);
CREATE UNIQUE INDEX poker_diamond_custody_occupancy ON public.poker_diamond_custody USING btree (occupancy_id) WHERE (occupancy_id IS NOT NULL);
ALTER TABLE public.poker_diamond_custody ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.poker_diamond_custody FROM PUBLIC,anon,authenticated,service_role;
GRANT ALL ON public.poker_diamond_custody TO service_role;
GRANT SELECT ON public.poker_diamond_custody TO authenticated;
COMMIT;