/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * EVENT-SOURCED HAND ENGINE — Event Definitions
 * ═══════════════════════════════════════════════════════════════════════════════
 * Keystone Upgrade #1 — deterministic, replayable Club Arena engine (FOUNDATION).
 *
 * A typed, versioned event union describing the FULL lifecycle of a single hand.
 * These events are the single source of truth: folding them through HandReducer
 * reconstructs the exact hand state (stacks, pot, bets, board, toAct).
 *
 * DESIGN RULES
 *  - Every event carries a monotonic per-hand `seq` (0-based) and a `ts`
 *    (epoch ms). Timestamps are PASSED IN by the recorder — never generated by
 *    the pure reducer.
 *  - Every event carries a schema `v` for forward migration.
 *  - Chip model (differs from the legacy HandController, matches the invariant
 *    the task requires): `bet` = live wager on the felt for the current street;
 *    `pot` = chips already swept from prior streets. Bets are swept into the pot
 *    on StreetAdvanced / PotAwarded. Invariant: Σstack + Σbet + pot + rake
 *    == initial buy-in total, at ALL times (see ChipConservationVerifier).
 *
 * NOT YET WIRED into the live engine — see ShadowRecorder.ts + README.md.
 */

import type { Card, ActionType } from '../../types.js';

/** Bump when the event shape changes in a non-backward-compatible way. */
export const HAND_EVENT_SCHEMA_VERSION = 1 as const;
export type HandEventSchemaVersion = typeof HAND_EVENT_SCHEMA_VERSION;

/** Betting streets. `showdown` is a state, not a dealt street. */
export type Street = 'preflop' | 'flop' | 'turn' | 'river';

// ─────────────────────────────────────────────────────────────────────────────
// Common metadata carried on every event
// ─────────────────────────────────────────────────────────────────────────────

export interface EventMeta {
  /** Monotonic per-hand sequence number, starting at 0. */
  seq: number;
  /** Epoch milliseconds. Passed in by the caller — NEVER generated in pure code. */
  ts: number;
  /** Schema version for forward migration. */
  v: HandEventSchemaVersion;
  /** Identifies the hand this event belongs to. */
  handId: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Payload sub-shapes
// ─────────────────────────────────────────────────────────────────────────────

export interface EventPlayerSeat {
  seat: number;
  userId: string;
  /** Chips this player has at the START of the hand (their buy-in slice). */
  stack: number;
}

export interface Stakes {
  smallBlind: number;
  bigBlind: number;
  ante?: number;
}

export type BlindKind = 'small_blind' | 'big_blind' | 'ante' | 'straddle' | 'kill_blind';

export interface BlindPosting {
  seat: number;
  kind: BlindKind;
  amount: number;
}

export interface DealtHand {
  seat: number;
  cards: Card[];
}

export interface RevealedHand {
  seat: number;
  userId: string;
  cards: Card[];
}

export interface Payout {
  seat: number;
  userId: string;
  amount: number;
  /** 0 = main pot, 1+ = side pots. */
  potIndex?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// The event union — one variant per lifecycle phase
// ─────────────────────────────────────────────────────────────────────────────

export interface HandStarted extends EventMeta {
  type: 'HandStarted';
  /** Deterministic deck seed. The deck is derived from this via a shuffle fn. */
  seed: number;
  handNumber: number;
  buttonSeat: number;
  players: EventPlayerSeat[];
  stakes: Stakes;
}

export interface BlindsPosted extends EventMeta {
  type: 'BlindsPosted';
  postings: BlindPosting[];
}

export interface HoleCardsDealt extends EventMeta {
  type: 'HoleCardsDealt';
  cardsPerPlayer: number;
  /**
   * Explicit deal, as recorded from the live engine. When omitted, the reducer
   * deals deterministically from the seed-derived deck (deriveDeck()).
   */
  hands?: DealtHand[];
}

export interface PlayerActed extends EventMeta {
  type: 'PlayerActed';
  seat: number;
  action: ActionType;
  /**
   * For `bet`/`raise`: the TOTAL wager the seat has on the felt AFTER the action
   * (the new bet level for the street). For `call`/`check`/`fold`/`all_in`/
   * `discard`: ignored — the chip delta is derived from state.
   */
  amount: number;
}

export interface StreetAdvanced extends EventMeta {
  type: 'StreetAdvanced';
  street: Street;
  /**
   * The FULL board after this street (flop=3, turn=4, river=5). When omitted the
   * reducer deals the street from the seed-derived deck.
   */
  board?: Card[];
}

export interface ShowdownRevealed extends EventMeta {
  type: 'ShowdownRevealed';
  reveals: RevealedHand[];
}

export interface PotAwarded extends EventMeta {
  type: 'PotAwarded';
  payouts: Payout[];
  /** Rake + fees removed from the pot (documented, verified chip sink). */
  rake?: number;
}

export interface HandEnded extends EventMeta {
  type: 'HandEnded';
  handNumber: number;
}

export type HandEvent =
  | HandStarted
  | BlindsPosted
  | HoleCardsDealt
  | PlayerActed
  | StreetAdvanced
  | ShowdownRevealed
  | PotAwarded
  | HandEnded;

export type HandEventType = HandEvent['type'];

/** Event body without the auto-stamped metadata — what a recorder supplies. */
export type HandEventBody =
  | Omit<HandStarted, keyof EventMeta>
  | Omit<BlindsPosted, keyof EventMeta>
  | Omit<HoleCardsDealt, keyof EventMeta>
  | Omit<PlayerActed, keyof EventMeta>
  | Omit<StreetAdvanced, keyof EventMeta>
  | Omit<ShowdownRevealed, keyof EventMeta>
  | Omit<PotAwarded, keyof EventMeta>
  | Omit<HandEnded, keyof EventMeta>;

/** Ordered list of every event type — handy for exhaustive checks / tooling. */
export const HAND_EVENT_TYPES: readonly HandEventType[] = [
  'HandStarted',
  'BlindsPosted',
  'HoleCardsDealt',
  'PlayerActed',
  'StreetAdvanced',
  'ShowdownRevealed',
  'PotAwarded',
  'HandEnded',
] as const;
