CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY,email text);
CREATE TABLE ca_detector_registry(
source text NOT NULL,
owner text NOT NULL,
sla_hours integer DEFAULT 24 NOT NULL,
status text DEFAULT 'active'::text NOT NULL,
auto_resolve_hours integer,
retired_by text,
note text DEFAULT ''::text NOT NULL,
updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE ca_drift_incidents(
id uuid DEFAULT gen_random_uuid() NOT NULL,
detected_at timestamp with time zone DEFAULT now() NOT NULL,
deadline_at timestamp with time zone DEFAULT (now() + '00:20:00'::interval) NOT NULL,
classification text DEFAULT 'unknown'::text NOT NULL,
severity text DEFAULT 'critical'::text NOT NULL,
layer text DEFAULT 'unknown'::text NOT NULL,
status text DEFAULT 'open'::text NOT NULL,
source text NOT NULL,
dedupe_key text NOT NULL,
union_id uuid,
club_id uuid,
entity_type text,
entity_id uuid,
table_id uuid,
tournament_id uuid,
hand_id uuid,
settlement_id text,
wallet_ids uuid[],
transaction_ids uuid[],
currency text DEFAULT 'club_chips'::text NOT NULL,
expected_amount numeric,
actual_amount numeric,
discrepancy_amount numeric DEFAULT 0 NOT NULL,
ledger_balanced boolean,
suspected_cause text,
auto_repair_status text DEFAULT 'pending'::text NOT NULL,
escalation_level integer DEFAULT 0 NOT NULL,
past_target boolean DEFAULT false NOT NULL,
occurrences integer DEFAULT 1 NOT NULL,
last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
acknowledged_by uuid,
acknowledged_at timestamp with time zone,
assigned_to uuid,
root_cause text,
correction_ref text,
resolution text,
resolved_by uuid,
resolved_at timestamp with time zone,
metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE ca_incident_events(
id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
incident_id uuid NOT NULL,
at timestamp with time zone DEFAULT now() NOT NULL,
kind text NOT NULL,
actor uuid,
actor_label text,
detail jsonb DEFAULT '{}'::jsonb NOT NULL
);
CREATE TABLE ca_incident_file_failures(
id uuid DEFAULT gen_random_uuid() NOT NULL,
occurred_at timestamp with time zone DEFAULT now() NOT NULL,
source text,
dedupe_key text,
classification text,
severity text,
discrepancy numeric,
sqlstate text,
message text,
db_role text DEFAULT CURRENT_USER NOT NULL,
app_name text DEFAULT COALESCE(current_setting('application_name'::text, true), ''::text) NOT NULL
);
CREATE TABLE financial_alerts(
id uuid DEFAULT gen_random_uuid() NOT NULL,
severity text NOT NULL,
source text NOT NULL,
message text NOT NULL,
context jsonb DEFAULT '{}'::jsonb,
resolved boolean DEFAULT false NOT NULL,
resolved_at timestamp with time zone,
created_at timestamp with time zone DEFAULT now() NOT NULL,
resolved_by uuid,
resolution text
);
ALTER TABLE ca_detector_registry ADD CONSTRAINT ca_detector_registry_auto_resolve_hours_check CHECK (((auto_resolve_hours IS NULL) OR (auto_resolve_hours > 0)));
ALTER TABLE ca_detector_registry ADD CONSTRAINT ca_detector_registry_pkey PRIMARY KEY (source);
ALTER TABLE ca_detector_registry ADD CONSTRAINT ca_detector_registry_sla_hours_check CHECK ((sla_hours > 0));
ALTER TABLE ca_detector_registry ADD CONSTRAINT ca_detector_registry_status_check CHECK ((status = ANY (ARRAY['active'::text, 'retired'::text])));
ALTER TABLE ca_drift_incidents ADD CONSTRAINT ca_drift_incidents_auto_repair_status_check CHECK ((auto_repair_status = ANY (ARRAY['pending'::text, 'running'::text, 'repaired'::text, 'manual_needed'::text, 'not_applicable'::text])));
ALTER TABLE ca_drift_incidents ADD CONSTRAINT ca_drift_incidents_classification_check CHECK ((classification = ANY (ARRAY['ledger_imbalance'::text, 'settlement_error'::text, 'duplicate_payment'::text, 'missing_payment'::text, 'projection_delay'::text, 'cache_mismatch'::text, 'reporting_mismatch'::text, 'delayed_event'::text, 'duplicate_event'::text, 'rounding_error'::text, 'incorrect_rake'::text, 'incorrect_weighted_rake'::text, 'incorrect_rakeback'::text, 'bbj_error'::text, 'treasury_error'::text, 'credit_line_error'::text, 'cross_club_posting'::text, 'cross_union_posting'::text, 'unauthorized_adjustment'::text, 'historical_migration'::text, 'unknown'::text])));
ALTER TABLE ca_drift_incidents ADD CONSTRAINT ca_drift_incidents_layer_check CHECK ((layer = ANY (ARRAY['ledger'::text, 'projection'::text, 'cache'::text, 'reporting'::text, 'settlement'::text, 'unknown'::text])));
ALTER TABLE ca_drift_incidents ADD CONSTRAINT ca_drift_incidents_pkey PRIMARY KEY (id);
ALTER TABLE ca_drift_incidents ADD CONSTRAINT ca_drift_incidents_severity_check CHECK ((severity = ANY (ARRAY['critical'::text, 'warning'::text, 'info'::text])));
ALTER TABLE ca_drift_incidents ADD CONSTRAINT ca_drift_incidents_status_check CHECK ((status = ANY (ARRAY['open'::text, 'acknowledged'::text, 'reconciling'::text, 'resolved'::text])));
ALTER TABLE ca_incident_events ADD CONSTRAINT ca_incident_events_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES ca_drift_incidents(id);
ALTER TABLE ca_incident_events ADD CONSTRAINT ca_incident_events_kind_check CHECK ((kind = ANY (ARRAY['created'::text, 'recurred'::text, 'notified'::text, 'escalated'::text, 'status_change'::text, 'repair_action'::text, 'comment'::text, 'assigned'::text, 'acknowledged'::text, 'resolved'::text, 'reopened'::text, 'notify_failed'::text, 'notify_withheld'::text])));
ALTER TABLE ca_incident_events ADD CONSTRAINT ca_incident_events_pkey PRIMARY KEY (id);
ALTER TABLE ca_incident_file_failures ADD CONSTRAINT ca_incident_file_failures_pkey PRIMARY KEY (id);
ALTER TABLE financial_alerts ADD CONSTRAINT financial_alerts_pkey PRIMARY KEY (id);
ALTER TABLE financial_alerts ADD CONSTRAINT financial_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id);
ALTER TABLE financial_alerts ADD CONSTRAINT financial_alerts_severity_check CHECK ((severity = ANY (ARRAY['critical'::text, 'warning'::text, 'info'::text])));

CREATE UNIQUE INDEX incident_open_key ON ca_drift_incidents(dedupe_key) WHERE status <> 'resolved';
CREATE TABLE clubs(id uuid PRIMARY KEY,union_id uuid,name text);
CREATE TABLE union_clubs(club_id uuid,union_id uuid);
CREATE TABLE tables(id uuid PRIMARY KEY,club_id uuid);
CREATE TABLE tournaments(id uuid PRIMARY KEY,club_id uuid);
CREATE TABLE profiles(id uuid PRIMARY KEY,is_horse boolean);
CREATE TABLE ca_cert_accounts(user_id uuid,active boolean);
CREATE TABLE unions(id uuid PRIMARY KEY,name text);
INSERT INTO clubs VALUES('fade0000-0000-0000-0000-000000000001',NULL,'Native proof');
INSERT INTO tournaments SELECT lpad(to_hex(i),32,'0')::uuid,'fade0000-0000-0000-0000-000000000001' FROM generate_series(101,140)i;
