-- UNAPPLIED COACTIVATION CANDIDATE. Requires prospective source marker in this transaction.
DO $preflight$
DECLARE r record;v record;
BEGIN
SELECT * INTO STRICT v FROM pg_proc WHERE oid='public.fn_agent_claim_commission(uuid,uuid,integer)'::regprocedure;
IF md5(v.prosrc) IS DISTINCT FROM 'ecd40da476bd8dd829d381fb2ee5a03e' OR pg_get_userbyid(v.proowner) IS DISTINCT FROM 'postgres' OR ARRAY(SELECT u::text FROM unnest(v.proacl) u ORDER BY 1) IS DISTINCT FROM ARRAY(SELECT u::text FROM unnest('{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}'::aclitem[]) u ORDER BY 1) OR v.proconfig IS DISTINCT FROM ARRAY['search_path=public']::text[] OR NOT v.prosecdef OR v.proisstrict OR v.provolatile IS DISTINCT FROM 'v'::char THEN RAISE EXCEPTION 'Legacy commission owner or privilege drift: fn_agent_claim_commission(uuid,uuid,integer)'; END IF;
SELECT * INTO STRICT v FROM pg_proc WHERE oid='public.fn_agent_unsettled_commission(uuid,uuid)'::regprocedure;
IF md5(v.prosrc) IS DISTINCT FROM '65099653461a48858b024c1a022409f2' OR pg_get_userbyid(v.proowner) IS DISTINCT FROM 'postgres' OR ARRAY(SELECT u::text FROM unnest(v.proacl) u ORDER BY 1) IS DISTINCT FROM ARRAY(SELECT u::text FROM unnest('{postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}'::aclitem[]) u ORDER BY 1) OR v.proconfig IS DISTINCT FROM ARRAY['search_path=public']::text[] OR NOT v.prosecdef OR v.proisstrict OR v.provolatile IS DISTINCT FROM 's'::char THEN RAISE EXCEPTION 'Legacy commission owner or privilege drift: fn_agent_unsettled_commission(uuid,uuid)'; END IF;
SELECT * INTO STRICT v FROM pg_proc WHERE oid='public.fn_settle_round2_club_to_agents(uuid,timestamp with time zone,timestamp with time zone)'::regprocedure;
IF md5(v.prosrc) IS DISTINCT FROM '6b6e58eb5eaba25f7ff3fd69e742cb01' OR pg_get_userbyid(v.proowner) IS DISTINCT FROM 'postgres' OR ARRAY(SELECT u::text FROM unnest(v.proacl) u ORDER BY 1) IS DISTINCT FROM ARRAY(SELECT u::text FROM unnest('{postgres=X/postgres,service_role=X/postgres}'::aclitem[]) u ORDER BY 1) OR v.proconfig IS DISTINCT FROM ARRAY['search_path=public']::text[] OR NOT v.prosecdef OR v.proisstrict OR v.provolatile IS DISTINCT FROM 'v'::char THEN RAISE EXCEPTION 'Legacy commission owner or privilege drift: fn_settle_round2_club_to_agents(uuid,timestamp with time zone,timestamp with time zone)'; END IF;
SELECT * INTO STRICT v FROM pg_proc WHERE oid='public.fn_agent_commission_rollup_recompute(jsonb)'::regprocedure;
IF md5(v.prosrc) IS DISTINCT FROM '1eb584cfa02c95e986afc44a4c4c491b' OR pg_get_userbyid(v.proowner) IS DISTINCT FROM 'postgres' OR ARRAY(SELECT u::text FROM unnest(v.proacl) u ORDER BY 1) IS DISTINCT FROM ARRAY(SELECT u::text FROM unnest('{postgres=X/postgres,service_role=X/postgres}'::aclitem[]) u ORDER BY 1) OR v.proconfig IS DISTINCT FROM ARRAY['search_path=public']::text[] OR v.prosecdef IS DISTINCT FROM false THEN RAISE EXCEPTION 'Legacy commission rollup drift: fn_agent_commission_rollup_recompute(jsonb)'; END IF;
SELECT * INTO STRICT v FROM pg_proc WHERE oid='public.trg_agent_commission_rollup_insert()'::regprocedure;
IF md5(v.prosrc) IS DISTINCT FROM 'f7f79c3ec742a8826d6df00a3cb621c0' OR pg_get_userbyid(v.proowner) IS DISTINCT FROM 'postgres' OR ARRAY(SELECT u::text FROM unnest(v.proacl) u ORDER BY 1) IS DISTINCT FROM ARRAY(SELECT u::text FROM unnest('{postgres=X/postgres,service_role=X/postgres}'::aclitem[]) u ORDER BY 1) OR v.proconfig IS DISTINCT FROM ARRAY['search_path=public']::text[] OR v.prosecdef IS DISTINCT FROM true THEN RAISE EXCEPTION 'Legacy commission rollup drift: trg_agent_commission_rollup_insert()'; END IF;
IF md5(pg_get_viewdef('public.agent_commissions_unsettled'::regclass,true)) IS DISTINCT FROM '97f8b377b578f7f4ca583280ba0715b5' OR (SELECT reloptions FROM pg_class WHERE oid='public.agent_commissions_unsettled'::regclass) IS DISTINCT FROM ARRAY['security_invoker=true']::text[] THEN RAISE EXCEPTION 'Legacy unpaid commission view drift'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.agent_commissions_legacy_open_source_idx') AND indrelid='public.agent_commissions'::regclass AND indisready AND indisvalid AND pg_get_indexdef(indexrelid)='CREATE INDEX agent_commissions_legacy_open_source_idx ON public.agent_commissions USING btree (club_id, user_id, created_at) WHERE ((settled_at IS NULL) AND (commission_capture_version IS NULL))') THEN RAISE EXCEPTION 'Legacy source exclusion index is not ready'; END IF;
END $preflight$;
