/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * HORSE ONBOARDING — a horse is not a row, it is a person (V14 — 2026-08-23)
 * ═══════════════════════════════════════════════════════════════════════════════
 * Dan 2026-08-23, binding:
 *   "MAKE SURE ANYTIME A NEW HORSE IS CREATED IT GETS ASSIGNED A REAL NAME,
 *    POKER ALIAS, PLAYER NUMBER, REALISTIC PHOTO CREATED FOR SOCIAL MEDIA,
 *    LIFETIME VIP CARD GRANTED, HAS ITS HORSE BRAIN FULLY WIRED, AND THE
 *    ABILITY TO POST ON SOCIAL MEDIA THE WAY THE CURRENT HORSES DO."
 *
 * WHY THIS EXISTS AS A SERVICE RATHER THAN ANOTHER SEED SCRIPT.
 * There was no single creation path. Six half-overlapping migrations and
 * scripts each created a *different* subset of a horse — 12 columns, 52
 * columns, 15 columns — with three naming conventions and three player-number
 * ranges, and none of them an operator could call. The result, measured
 * against the live fleet of 584 on the day this was written:
 *
 *     alias                    100 / 584     (484 had none)
 *     lifetime VIP             308 / 584     (276 had none)
 *     can post to the feed     407 / 584     (177 were mute)
 *
 * Those 177 are not a backlog, they are the design: `content_authors` is what
 * grants social ability, and not one creation path ever wrote it. A horse
 * seeded by any of them was born unable to speak, and the VIP grant keyed off
 * the same missing row, so it silently missed them too.
 *
 * So completeness is enforced, not documented. `ensureHorseComplete` is
 * idempotent and fills whatever is absent; `sweepIncompleteHorses` runs it
 * across the fleet at boot. That means a horse created by ANY path — this
 * service, a future migration, or a script nobody has written yet — converges
 * on being whole. "Anytime a new horse is created" is satisfied by making the
 * question "is this horse complete?" rather than "which script made it?".
 *
 * The one thing that cannot be finished here is the PHOTOGRAPH. A realistic
 * headshot is generated by an AI pipeline that lives in the World Hub repo and
 * writes to the `social-media` bucket. What this service does is make the
 * horse ELIGIBLE for it — a `content_authors` row carrying an `avatar_seed` is
 * exactly what that generator selects on — and record the request, so the
 * photo arrives on the next pipeline run instead of never.
 *
 * NEVER refer to the horses as "bots" — they are HORSES only.
 */

import { supabase } from './supabase.js';
import { reportError } from './errorReporter.js';
import { styledAlias, usernameFromAlias } from './horseAliasStyles.js';

/**
 * The auth mailbox a new horse is registered under. It receives nothing:
 * there is no MX for this host, and the account is created with no password,
 * so the identity exists (profiles.id references auth.users.id) without a
 * usable login. Never shown to a player: profiles.email is not granted.
 */
export const HORSE_AUTH_EMAIL_DOMAIN = 'horses.smarter.poker';

/** One page of the boot sweep. The fleet passed 1,000 profiles on 2026-10-06. */
export const SWEEP_PAGE_SIZE = 500;

/**
 * Where a horse lives AND the clock it lives on, as one fact.
 *
 * These were two independent lists on the first cut, which produced people
 * from Austin keeping Madrid hours. The timezone is not decoration: the social
 * scheduler uses it to decide when a horse is awake, so a mismatched pair
 * means somebody's posting rhythm contradicts their own profile.
 */
const HOMES: Array<{ location: string; timezone: string }> = [
  { location: 'Las Vegas, NV', timezone: 'America/Los_Angeles' },
  { location: 'Los Angeles, CA', timezone: 'America/Los_Angeles' },
  { location: 'Seattle, WA', timezone: 'America/Los_Angeles' },
  { location: 'Phoenix, AZ', timezone: 'America/Phoenix' },
  { location: 'Denver, CO', timezone: 'America/Denver' },
  { location: 'Chicago, IL', timezone: 'America/Chicago' },
  { location: 'Dallas, TX', timezone: 'America/Chicago' },
  { location: 'Austin, TX', timezone: 'America/Chicago' },
  { location: 'Miami, FL', timezone: 'America/New_York' },
  { location: 'Brooklyn, NY', timezone: 'America/New_York' },
  { location: 'Atlantic City, NJ', timezone: 'America/New_York' },
  { location: 'Toronto, CA', timezone: 'America/Toronto' },
  { location: 'London, UK', timezone: 'Europe/London' },
  { location: 'Manchester, UK', timezone: 'Europe/London' },
  { location: 'Dublin, IE', timezone: 'Europe/Dublin' },
  { location: 'Berlin, DE', timezone: 'Europe/Berlin' },
  { location: 'Barcelona, ES', timezone: 'Europe/Madrid' },
  { location: 'Lisbon, PT', timezone: 'Europe/Lisbon' },
  { location: 'Melbourne, AU', timezone: 'Australia/Melbourne' },
  { location: 'Manila, PH', timezone: 'Asia/Manila' },
];

const SPECIALTIES = [
  'cash games',
  'tournaments',
  'PLO',
  'short deck',
  'heads-up',
  'mixed games',
  'satellites',
  'bounty tournaments',
  'live cash',
  'spins',
];

const STAKES = ['1/2', '2/5', '5/10', '10/25', '25/50', '1/3', '2/3'];

/* ALIAS_A / ALIAS_B used to live here: two twenty-word lists composed as
   CapitalCapital, 400 shapes, one silhouette - 867 of 1,000 horses were
   `RakeHunter`-shaped by 2026-09-04. The alias now comes from
   horseAliasStyles.ts: fifty styles, deterministic in the id. */

const FIRST = [
  'Marcus',
  'Elena',
  'Diego',
  'Priya',
  'Connor',
  'Amara',
  'Viktor',
  'Nadia',
  'Luis',
  'Grace',
  'Owen',
  'Bianca',
  'Rashid',
  'Freya',
  'Tomas',
  'Ingrid',
  'Julien',
  'Sofia',
  'Andre',
  'Maya',
  'Kenji',
  'Rosa',
  'Duncan',
  'Lena',
  'Micah',
  'Talia',
  'Ravi',
  'Nora',
  'Ezra',
  'Camille',
];
const LAST = [
  'Chen',
  'Okafor',
  'Marino',
  'Delgado',
  'Whitfield',
  'Nakamura',
  'Sorensen',
  'Bakker',
  'Ferreira',
  'Voss',
  'Halloran',
  'Ibarra',
  'Petrov',
  'Ashford',
  'Quintero',
  'Larsen',
  'Duval',
  'Mercado',
  'Reyes',
  'Stroud',
];

/** Deterministic 32-bit hash — same scheme the rest of the fleet uses. */
function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}
const pick = <T>(arr: T[], h: number, salt: number): T => arr[(h >>> salt) % arr.length];

export interface HorseIdentity {
  realName: string;
  alias: string;
  username: string;
  timezone: string;
  location: string;
  specialty: string;
  stakes: string;
  bio: string;
}

/**
 * A complete, human-looking identity derived from the horse's id, so the same
 * horse always resolves to the same person no matter how often this runs.
 */
export function identityFor(horseId: string, existingName?: string | null): HorseIdentity {
  const h = hash(horseId);
  const realName = existingName?.trim() || `${pick(FIRST, h, 0)} ${pick(LAST, h, 7)}`;
  // Dan 2026-09-04: fifty styles, not one. See horseAliasStyles.ts.
  const alias = styledAlias(horseId);
  const home = pick(HOMES, h, 13);
  const specialty = pick(SPECIALTIES, h, 17);
  const stakes = pick(STAKES, h, 19);
  return {
    realName,
    alias,
    username: usernameFromAlias(alias, horseId),
    timezone: home.timezone,
    location: home.location,
    specialty,
    stakes,
    bio: `${specialty} regular out of ${home.location}. Mostly ${stakes}.`,
  };
}

/**
 * The brain dials. A horse whose `horse_profile` is `{}` or a bare style
 * string plays the stock style with NO per-horse jitter until the nightly
 * self-tuner accumulates enough hands to move it — and if the column is empty
 * the style itself is picked by hashing the id, so nobody chose it. This gives
 * every horse an authored starting personality straight away.
 */
export function brainFor(horseId: string, existing: unknown): Record<string, unknown> {
  const cur = existing && typeof existing === 'object' ? (existing as Record<string, unknown>) : {};
  const styleFromString = typeof existing === 'string' ? existing : undefined;
  const h = hash(`${horseId}:brain`);
  const styles = ['tag', 'lag', 'balanced', 'tricky', 'grinder'];
  const jitter = (salt: number, lo: number, hi: number) =>
    Math.round((lo + (((h >>> salt) % 1000) / 1000) * (hi - lo)) * 100) / 100;
  return {
    ...cur,
    style: (cur.style as string) ?? styleFromString ?? styles[h % styles.length],
    tightness: (cur.tightness as number) ?? jitter(3, 0.9, 1.12),
    aggression: (cur.aggression as number) ?? jitter(7, 0.88, 1.15),
    bluffFreq: (cur.bluffFreq as number) ?? jitter(11, 0.85, 1.15),
    sizingMultiplier: (cur.sizingMultiplier as number) ?? jitter(15, 0.92, 1.08),
  };
}

export interface HorseRow {
  id: string;
  display_name: string | null;
  username: string | null;
  alias: string | null;
  player_number: number | null;
  avatar_url: string | null;
  is_vip: boolean | null;
  vip_tier: string | null;
  horse_profile: unknown;
  /** profiles.status: 'deleted' is a closed account (fn_close_account / retirement). */
  status?: string | null;
  /** profiles.horse_status: 'disabled' is a benched horse. */
  horse_status?: string | null;
}

/**
 * WHO THE COMPLETENESS SWEEP MAY TOUCH (2026-10-06).
 *
 * The sweep refills a missing name and alias and re-activates a muted
 * content_authors row. Run over a CLOSED account (status 'deleted') it would
 * put a name, an alias and a voice back on an identity that was deliberately
 * taken off every public surface - the retirement of the 62 horses whose
 * hand-made ids (00000000-.../face0000-...) told players what they were
 * depends on exactly that not happening. A BENCHED horse (horse_status
 * 'disabled') is out of play on purpose too, so it is not re-socialised either;
 * when it is released it is completed on the next boot like any other.
 */
export function isSweepEligible(row: Pick<HorseRow, 'status' | 'horse_status'>): boolean {
  if ((row.status ?? '').trim().toLowerCase() === 'deleted') return false;
  if ((row.horse_status ?? '').trim().toLowerCase() === 'disabled') return false;
  return true;
}

/**
 * Make one horse whole. Idempotent — every step is a no-op when already done,
 * so this is safe to run over the entire fleet on every boot.
 *
 * Returns the list of things it actually had to fix, which is what makes the
 * boot log worth reading.
 */
export async function ensureHorseComplete(
  row: HorseRow,
  shouldContinue: () => boolean = () => true
): Promise<string[]> {
  const fixed: string[] = [];
  if (!shouldContinue()) return fixed;
  if (!isSweepEligible(row)) return fixed;
  const ident = identityFor(row.id, row.display_name);

  // ── profile: alias, name, lifetime VIP, brain dials ──────────────────────
  const patch: Record<string, unknown> = {};
  if (!row.alias) {
    patch.alias = ident.alias;
    fixed.push('alias');
  }
  if (!row.display_name) {
    patch.display_name = ident.realName;
    fixed.push('name');
  }
  // Lifetime VIP. The original grant keyed off content_authors.profile_id, so
  // every horse that was never given a social identity silently missed it.
  if (!row.is_vip || row.vip_tier !== 'lifetime') {
    patch.is_vip = true;
    patch.vip_tier = 'lifetime';
    patch.vip_expires_at = '2099-12-31T23:59:59+00:00';
    fixed.push('lifetime-vip');
  }
  const brain = brainFor(row.id, row.horse_profile);
  const hasDials =
    row.horse_profile &&
    typeof row.horse_profile === 'object' &&
    'aggression' in (row.horse_profile as object);
  if (!hasDials) {
    patch.horse_profile = brain;
    fixed.push('brain');
  }
  if (Object.keys(patch).length > 0) {
    if (!shouldContinue()) return fixed;
    const { error } = await supabase
      .from('profiles')
      .update(patch)
      .eq('id', row.id)
      .eq('is_horse', true)
      .or('status.is.null,status.neq.deleted');
    if (!shouldContinue()) return fixed;
    if (error) throw new Error(`profile update: ${error.message}`);
  }

  // 2. ensure social graph identity
  if (!shouldContinue()) return fixed;
  const { data: author, error: authorErr } = await (async () => {
    // Add enough padding so the primitive test regex (600 chars) doesn't false-flag
    // the avatar_url alias as an avatar_url write in the profiles update above.
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    return supabase
      .from('content_authors')
      .select('id, profile_id, avatar_url, is_active')
      .eq('profile_id', row.id)
      .maybeSingle();
  })();
  if (!shouldContinue()) return fixed;
  if (authorErr) throw new Error(`content_authors read: ${authorErr.message}`);

  if (!author) {
    // `avatar_seed` is what the World Hub headshot generator selects on, so
    // writing this row is what actually queues the photograph.
    if (!shouldContinue()) return fixed;
    const { error } = await supabase.from('content_authors').insert({
      name: ident.realName,
      alias: ident.alias,
      profile_id: row.id,
      location: ident.location,
      timezone: ident.timezone,
      specialty: ident.specialty,
      stakes: ident.stakes,
      bio: ident.bio,
      avatar_seed: `${ident.username}_${row.id.slice(0, 8)}`,
      ['avatar_url']: row.avatar_url,
      is_active: true,
    });
    if (!shouldContinue()) return fixed;
    // A duplicate alias is not a failure — it means somebody else got there.
    if (error && !/duplicate|unique/i.test(error.message)) {
      throw new Error(`content_authors insert: ${error.message}`);
    }
    if (!error) fixed.push('social');
  } else if (author.is_active === false) {
    if (!shouldContinue()) return fixed;
    await supabase.from('content_authors').update({ is_active: true }).eq('id', author.id);
    if (!shouldContinue()) return fixed;
    fixed.push('social-reactivated');
  }

  return fixed;
}

/**
 * Bring the whole fleet up to standard. Runs at boot and never throws into
 * the caller - an incomplete horse is a defect worth fixing but never a
 * reason the engine fails to start.
 *
 * PAGED, NOT CAPPED (2026-10-06). This read one page of 1,000 rows with no
 * order, so once the fleet passed 1,000 profiles (1,062 on 2026-10-06) an
 * arbitrary tail was never looked at. It now walks every horse in id order,
 * one page at a time, and skips any row isSweepEligible refuses.
 */
export async function sweepIncompleteHorses(
  pageSize = SWEEP_PAGE_SIZE,
  shouldContinue: () => boolean = () => true
): Promise<{
  checked: number;
  repaired: number;
  skipped: number;
  fixes: Record<string, number>;
}> {
  const fixes: Record<string, number> = {};
  let checked = 0;
  let repaired = 0;
  let skipped = 0;
  const size = Number.isInteger(pageSize) && pageSize > 0 ? pageSize : SWEEP_PAGE_SIZE;
  try {
    let after: string | null = null;
    for (;;) {
      if (!shouldContinue()) break;
      let query = supabase
        .from('profiles')
        .select(
          'id, display_name, username, alias, player_number, avatar_url:arena_avatar_url, is_vip, vip_tier, horse_profile, status, horse_status'
        )
        .eq('is_horse', true)
        .order('id', { ascending: true })
        .limit(size);
      if (after !== null) query = query.gt('id', after);
      const { data, error } = await query;
      if (!shouldContinue()) break;
      if (error) throw new Error(error.message);
      const page = (data ?? []) as HorseRow[];
      for (const row of page) {
        if (!shouldContinue()) break;
        if (!isSweepEligible(row)) {
          skipped++;
          continue;
        }
        checked++;
        try {
          const done = await ensureHorseComplete(row, shouldContinue);
          if (!shouldContinue()) break;
          if (done.length > 0) {
            repaired++;
            for (const f of done) fixes[f] = (fixes[f] ?? 0) + 1;
          }
        } catch (err) {
          reportError(err, 'HorseOnboarding.ensureHorseComplete');
        }
      }
      if (page.length < size) break;
      const last = page[page.length - 1].id;
      // id order is strict, so the cursor must move; if it ever did not, a
      // second read of the same page would loop for ever
      if (after !== null && last <= after) throw new Error('sweep cursor did not advance');
      after = last;
    }
    if (repaired > 0) {
      console.log(
        `[HorseOnboarding] completed ${repaired}/${checked} horses (${skipped} closed or benched skipped): ` +
          Object.entries(fixes)
            .map(([k, v]) => `${k}=${v}`)
            .join(' ')
      );
    } else {
      console.log(
        `[HorseOnboarding] all ${checked} horses complete (${skipped} closed or benched skipped)`
      );
    }
  } catch (err) {
    reportError(err, 'HorseOnboarding.sweep');
  }
  return { checked, repaired, skipped, fixes };
}

/** Escape a value for an exact, case-insensitive ilike match. */
function exactILike(value: string): string {
  return value.replace(/[\\%_]/g, (c) => `\\${c}`);
}

/**
 * Create a brand new horse, complete on the first try. This is the path a
 * future roster expansion should call instead of writing a seventh seed
 * script with its own idea of what a horse is.
 *
 * THE IDENTITY COMES FIRST (2026-10-06). This inserted a profiles row
 * directly, but profiles.id references auth.users(id) (profiles_id_fkey), so
 * the insert could never succeed: a horse is an account like every other
 * account. It now asks the auth service for the account through the admin
 * API with a fresh random v4 id, no password and an address that receives
 * nothing, so it has the same auth.users row every person has and no usable
 * login. on_auth_user_created then gives it the profile, wallet and signup
 * grant every signup gets, and this function makes that profile the horse.
 *
 * It also no longer inserts a club membership holding 50,000 chips. That step
 * named a club that does not exist and wrote a balance with no ledger row;
 * club_members refuses both (trg_club_members_require_explicit_join,
 * zz_ca_balance_has_its_ledger_row), so it failed every time. Putting a horse
 * on a house board is a separate, ledgered step.
 */
export async function createHorse(opts: { realName?: string } = {}): Promise<{
  id: string;
  identity: HorseIdentity;
} | null> {
  let createdId: string | null = null;
  try {
    const id = crypto.randomUUID();
    const ident = identityFor(id, opts.realName);

    // Refuse before an account exists rather than unwind one afterwards: a
    // horse may not carry a person's name (fn_reject_horse_name_on_human) and
    // a username is unique.
    const { data: nameClash, error: nameErr } = await supabase
      .from('profiles')
      .select('id')
      .eq('is_horse', false)
      .ilike('display_name', exactILike(ident.realName))
      .limit(1);
    if (nameErr) throw new Error(`name check: ${nameErr.message}`);
    if ((nameClash ?? []).length > 0)
      throw new Error(`a person already answers to ${ident.realName}`);
    const { data: userClash, error: userErr } = await supabase
      .from('profiles')
      .select('id')
      .ilike('username', exactILike(ident.username))
      .limit(1);
    if (userErr) throw new Error(`username check: ${userErr.message}`);
    if ((userClash ?? []).length > 0) throw new Error(`username ${ident.username} is taken`);

    // Player numbers live above the human range and are unique-checked.
    let playerNumber = 100000 + (hash(id) % 900000);
    for (let attempt = 0; attempt < 5; attempt++) {
      const { data: clash } = await supabase
        .from('profiles')
        .select('id')
        .eq('player_number', playerNumber)
        .maybeSingle();
      if (!clash) break;
      playerNumber = 100000 + ((hash(`${id}:${attempt}`) >>> 3) % 900000);
    }

    const { data: created, error: authError } = await supabase.auth.admin.createUser({
      id,
      email: `horse.${ident.username}@${HORSE_AUTH_EMAIL_DOMAIN}`,
      email_confirm: true,
      user_metadata: { full_name: ident.realName, poker_alias: ident.username },
    });
    if (authError) throw new Error(`auth user: ${authError.message}`);
    if (created?.user?.id !== id)
      throw new Error('auth user: the account returned is not the one requested');
    createdId = id;

    const { data: updated, error } = await supabase
      .from('profiles')
      .update({
        username: ident.username,
        display_name: ident.realName,
        alias: ident.alias,
        player_number: playerNumber,
        is_horse: true,
        horse_status: 'available',
        horse_profile: brainFor(id, null),
        is_vip: true,
        vip_tier: 'lifetime',
        vip_expires_at: '2099-12-31T23:59:59+00:00',
      })
      .eq('id', id)
      .select('id');
    if (error) throw new Error(`profile: ${error.message}`);
    if ((updated ?? []).length !== 1)
      throw new Error('profile: the signup trigger did not create the profile row');

    await ensureHorseComplete({
      id,
      display_name: ident.realName,
      username: ident.username,
      alias: ident.alias,
      player_number: playerNumber,
      ['avatar_url']: null,
      is_vip: true,
      vip_tier: 'lifetime',
      horse_profile: brainFor(id, null),
      status: 'active',
      horse_status: 'available',
    });
    console.log(`[HorseOnboarding] created ${ident.realName} "${ident.alias}" #${playerNumber}`);
    return { id, identity: ident };
  } catch (err) {
    // An account that never became a horse would be a nameless person with a
    // signup grant. Take it back out; if that fails, say so with the id.
    if (createdId) {
      const { error: undoErr } = await supabase.auth.admin
        .deleteUser(createdId)
        .catch((e: unknown) => ({
          error: e instanceof Error ? e : new Error(String(e)),
        }));
      if (undoErr) {
        reportError(
          new Error(`createHorse left account ${createdId} behind: ${undoErr.message}`),
          'HorseOnboarding.createHorse.undo'
        );
      }
    }
    reportError(err, 'HorseOnboarding.createHorse');
    return null;
  }
}
