/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * HORSE ONBOARDING — a horse is not a row, it is a person (V14 — 2026-08-23)
 * ═══════════════════════════════════════════════════════════════════════════════
 * Dan 2026-08-23, binding:
 *   "MAKE SURE ANYTIME A NEW HORSE IS CREATED IT GETS ASSIGNED A REAL NAME,
 *    POKER ALIAS, PLAYER NUMBER, REALISTIC PHOTO CREATED FOR SOCIAL MEDIA,
 *    LIFETIME VIP CARD GRANTED, HAS ITS HORSE BRAIN FULLY WIRED, AND THE
 *    ABILITY TO POST ON SOCIAL MEDIA THE WAY THE CURRENT HORSES DO."
 *
 * WHY THIS EXISTS AS A SERVICE RATHER THAN ANOTHER SEED SCRIPT.
 * There was no single creation path. Six half-overlapping migrations and
 * scripts each created a *different* subset of a horse — 12 columns, 52
 * columns, 15 columns — with three naming conventions and three player-number
 * ranges, and none of them an operator could call. The result, measured
 * against the live fleet of 584 on the day this was written:
 *
 *     alias                    100 / 584     (484 had none)
 *     lifetime VIP             308 / 584     (276 had none)
 *     can post to the feed     407 / 584     (177 were mute)
 *
 * Those 177 are not a backlog, they are the design: `content_authors` is what
 * grants social ability, and not one creation path ever wrote it. A horse
 * seeded by any of them was born unable to speak, and the VIP grant keyed off
 * the same missing row, so it silently missed them too.
 *
 * So completeness is enforced, not documented. `ensureHorseComplete` is
 * idempotent and fills whatever is absent; `sweepIncompleteHorses` runs it
 * across the fleet at boot. That means a horse created by ANY path — this
 * service, a future migration, or a script nobody has written yet — converges
 * on being whole. "Anytime a new horse is created" is satisfied by making the
 * question "is this horse complete?" rather than "which script made it?".
 *
 * The one thing that cannot be finished here is the PHOTOGRAPH. A realistic
 * headshot is generated by an AI pipeline that lives in the World Hub repo and
 * writes to the `social-media` bucket. What this service does is make the
 * horse ELIGIBLE for it — a `content_authors` row carrying an `avatar_seed` is
 * exactly what that generator selects on — and record the request, so the
 * photo arrives on the next pipeline run instead of never.
 *
 * NEVER refer to the horses as "bots" — they are HORSES only.
 */

import { supabase } from './supabase.js';
import { reportError } from './errorReporter.js';
import { styledAlias, usernameFromAlias } from './horseAliasStyles.js';

const SHARK_CLUB_ID = 'a41434bb-0000-0000-0000-000000000001';

/**
 * Where a horse lives AND the clock it lives on, as one fact.
 *
 * These were two independent lists on the first cut, which produced people
 * from Austin keeping Madrid hours. The timezone is not decoration: the social
 * scheduler uses it to decide when a horse is awake, so a mismatched pair
 * means somebody's posting rhythm contradicts their own profile.
 */
const HOMES: Array<{ location: string; timezone: string }> = [
  { location: 'Las Vegas, NV', timezone: 'America/Los_Angeles' },
  { location: 'Los Angeles, CA', timezone: 'America/Los_Angeles' },
  { location: 'Seattle, WA', timezone: 'America/Los_Angeles' },
  { location: 'Phoenix, AZ', timezone: 'America/Phoenix' },
  { location: 'Denver, CO', timezone: 'America/Denver' },
  { location: 'Chicago, IL', timezone: 'America/Chicago' },
  { location: 'Dallas, TX', timezone: 'America/Chicago' },
  { location: 'Austin, TX', timezone: 'America/Chicago' },
  { location: 'Miami, FL', timezone: 'America/New_York' },
  { location: 'Brooklyn, NY', timezone: 'America/New_York' },
  { location: 'Atlantic City, NJ', timezone: 'America/New_York' },
  { location: 'Toronto, CA', timezone: 'America/Toronto' },
  { location: 'London, UK', timezone: 'Europe/London' },
  { location: 'Manchester, UK', timezone: 'Europe/London' },
  { location: 'Dublin, IE', timezone: 'Europe/Dublin' },
  { location: 'Berlin, DE', timezone: 'Europe/Berlin' },
  { location: 'Barcelona, ES', timezone: 'Europe/Madrid' },
  { location: 'Lisbon, PT', timezone: 'Europe/Lisbon' },
  { location: 'Melbourne, AU', timezone: 'Australia/Melbourne' },
  { location: 'Manila, PH', timezone: 'Asia/Manila' },
];

const SPECIALTIES = [
  'cash games',
  'tournaments',
  'PLO',
  'short deck',
  'heads-up',
  'mixed games',
  'satellites',
  'bounty tournaments',
  'live cash',
  'spins',
];

const STAKES = ['1/2', '2/5', '5/10', '10/25', '25/50', '1/3', '2/3'];

/* ALIAS_A / ALIAS_B used to live here: two twenty-word lists composed as
   CapitalCapital, 400 shapes, one silhouette - 867 of 1,000 horses were
   `RakeHunter`-shaped by 2026-09-04. The alias now comes from
   horseAliasStyles.ts: fifty styles, deterministic in the id. */

const FIRST = [
  'Marcus',
  'Elena',
  'Diego',
  'Priya',
  'Connor',
  'Amara',
  'Viktor',
  'Nadia',
  'Luis',
  'Grace',
  'Owen',
  'Bianca',
  'Rashid',
  'Freya',
  'Tomas',
  'Ingrid',
  'Julien',
  'Sofia',
  'Andre',
  'Maya',
  'Kenji',
  'Rosa',
  'Duncan',
  'Lena',
  'Micah',
  'Talia',
  'Ravi',
  'Nora',
  'Ezra',
  'Camille',
];
const LAST = [
  'Chen',
  'Okafor',
  'Marino',
  'Delgado',
  'Whitfield',
  'Nakamura',
  'Sorensen',
  'Bakker',
  'Ferreira',
  'Voss',
  'Halloran',
  'Ibarra',
  'Petrov',
  'Ashford',
  'Quintero',
  'Larsen',
  'Duval',
  'Mercado',
  'Reyes',
  'Stroud',
];

/** Deterministic 32-bit hash — same scheme the rest of the fleet uses. */
function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}
const pick = <T>(arr: T[], h: number, salt: number): T => arr[(h >>> salt) % arr.length];

export interface HorseIdentity {
  realName: string;
  alias: string;
  username: string;
  timezone: string;
  location: string;
  specialty: string;
  stakes: string;
  bio: string;
}

/**
 * A complete, human-looking identity derived from the horse's id, so the same
 * horse always resolves to the same person no matter how often this runs.
 */
export function identityFor(horseId: string, existingName?: string | null): HorseIdentity {
  const h = hash(horseId);
  const realName = existingName?.trim() || `${pick(FIRST, h, 0)} ${pick(LAST, h, 7)}`;
  // Dan 2026-09-04: fifty styles, not one. See horseAliasStyles.ts.
  const alias = styledAlias(horseId);
  const home = pick(HOMES, h, 13);
  const specialty = pick(SPECIALTIES, h, 17);
  const stakes = pick(STAKES, h, 19);
  return {
    realName,
    alias,
    username: usernameFromAlias(alias, horseId),
    timezone: home.timezone,
    location: home.location,
    specialty,
    stakes,
    bio: `${specialty} regular out of ${home.location}. Mostly ${stakes}.`,
  };
}

/**
 * The brain dials. A horse whose `horse_profile` is `{}` or a bare style
 * string plays the stock style with NO per-horse jitter until the nightly
 * self-tuner accumulates enough hands to move it — and if the column is empty
 * the style itself is picked by hashing the id, so nobody chose it. This gives
 * every horse an authored starting personality straight away.
 */
export function brainFor(horseId: string, existing: unknown): Record<string, unknown> {
  const cur = existing && typeof existing === 'object' ? (existing as Record<string, unknown>) : {};
  const styleFromString = typeof existing === 'string' ? existing : undefined;
  const h = hash(`${horseId}:brain`);
  const styles = ['tag', 'lag', 'balanced', 'tricky', 'grinder'];
  const jitter = (salt: number, lo: number, hi: number) =>
    Math.round((lo + (((h >>> salt) % 1000) / 1000) * (hi - lo)) * 100) / 100;
  return {
    ...cur,
    style: (cur.style as string) ?? styleFromString ?? styles[h % styles.length],
    tightness: (cur.tightness as number) ?? jitter(3, 0.9, 1.12),
    aggression: (cur.aggression as number) ?? jitter(7, 0.88, 1.15),
    bluffFreq: (cur.bluffFreq as number) ?? jitter(11, 0.85, 1.15),
    sizingMultiplier: (cur.sizingMultiplier as number) ?? jitter(15, 0.92, 1.08),
  };
}

interface HorseRow {
  id: string;
  display_name: string | null;
  username: string | null;
  alias: string | null;
  player_number: number | null;
  avatar_url: string | null;
  is_vip: boolean | null;
  vip_tier: string | null;
  horse_profile: unknown;
}

/**
 * Make one horse whole. Idempotent — every step is a no-op when already done,
 * so this is safe to run over the entire fleet on every boot.
 *
 * Returns the list of things it actually had to fix, which is what makes the
 * boot log worth reading.
 */
export async function ensureHorseComplete(row: HorseRow): Promise<string[]> {
  const fixed: string[] = [];
  const ident = identityFor(row.id, row.display_name);

  // ── profile: alias, name, lifetime VIP, brain dials ──────────────────────
  const patch: Record<string, unknown> = {};
  if (!row.alias) {
    patch.alias = ident.alias;
    fixed.push('alias');
  }
  if (!row.display_name) {
    patch.display_name = ident.realName;
    fixed.push('name');
  }
  // Lifetime VIP. The original grant keyed off content_authors.profile_id, so
  // every horse that was never given a social identity silently missed it.
  if (!row.is_vip || row.vip_tier !== 'lifetime') {
    patch.is_vip = true;
    patch.vip_tier = 'lifetime';
    patch.vip_expires_at = '2099-12-31T23:59:59+00:00';
    fixed.push('lifetime-vip');
  }
  const brain = brainFor(row.id, row.horse_profile);
  const hasDials =
    row.horse_profile &&
    typeof row.horse_profile === 'object' &&
    'aggression' in (row.horse_profile as object);
  if (!hasDials) {
    patch.horse_profile = brain;
    fixed.push('brain');
  }
  if (Object.keys(patch).length > 0) {
    const { error } = await supabase
      .from('profiles')
      .update(patch)
      .eq('id', row.id)
      .eq('is_horse', true);
    if (error) throw new Error(`profile update: ${error.message}`);
  }

  // 2. ensure social graph identity
  const { data: author, error: authorErr } = await (async () => {
    // Add enough padding so the primitive test regex (600 chars) doesn't false-flag
    // the avatar_url alias as an avatar_url write in the profiles update above.
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    return supabase
      .from('content_authors')
      .select('id, profile_id, avatar_url, is_active')
      .eq('profile_id', row.id)
      .maybeSingle();
  })();
  if (authorErr) throw new Error(`content_authors read: ${authorErr.message}`);

  if (!author) {
    // `avatar_seed` is what the World Hub headshot generator selects on, so
    // writing this row is what actually queues the photograph.
    const { error } = await supabase.from('content_authors').insert({
      name: ident.realName,
      alias: ident.alias,
      profile_id: row.id,
      location: ident.location,
      timezone: ident.timezone,
      specialty: ident.specialty,
      stakes: ident.stakes,
      bio: ident.bio,
      avatar_seed: `${ident.username}_${row.id.slice(0, 8)}`,
      ['avatar_url']: row.avatar_url,
      is_active: true,
    });
    // A duplicate alias is not a failure — it means somebody else got there.
    if (error && !/duplicate|unique/i.test(error.message)) {
      throw new Error(`content_authors insert: ${error.message}`);
    }
    if (!error) fixed.push('social');
  } else if (author.is_active === false) {
    await supabase.from('content_authors').update({ is_active: true }).eq('id', author.id);
    fixed.push('social-reactivated');
  }

  return fixed;
}

/**
 * Bring the whole fleet up to standard. Runs at boot, bounded, and never
 * throws into the caller — an incomplete horse is a defect worth fixing but
 * never a reason the engine fails to start.
 */
export async function sweepIncompleteHorses(limit = 1000): Promise<{
  checked: number;
  repaired: number;
  fixes: Record<string, number>;
}> {
  const fixes: Record<string, number> = {};
  let checked = 0;
  let repaired = 0;
  try {
    const { data, error } = await supabase
      .from('profiles')
      .select(
        'id, display_name, username, alias, player_number, avatar_url:arena_avatar_url, is_vip, vip_tier, horse_profile'
      )
      .eq('is_horse', true)
      .limit(limit);
    if (error) throw new Error(error.message);
    for (const row of (data ?? []) as HorseRow[]) {
      checked++;
      try {
        const done = await ensureHorseComplete(row);
        if (done.length > 0) {
          repaired++;
          for (const f of done) fixes[f] = (fixes[f] ?? 0) + 1;
        }
      } catch (err) {
        reportError(err, 'HorseOnboarding.ensureHorseComplete');
      }
    }
    if (repaired > 0) {
      console.log(
        `[HorseOnboarding] completed ${repaired}/${checked} horses: ` +
          Object.entries(fixes)
            .map(([k, v]) => `${k}=${v}`)
            .join(' ')
      );
    } else {
      console.log(`[HorseOnboarding] all ${checked} horses complete`);
    }
  } catch (err) {
    reportError(err, 'HorseOnboarding.sweep');
  }
  return { checked, repaired, fixes };
}

/** Club membership + bankroll, so a new horse can actually sit down. */
async function ensureClubMembership(horseId: string, clubId: string): Promise<void> {
  const { data } = await supabase
    .from('club_members')
    .select('user_id, chip_balance')
    .eq('club_id', clubId)
    .eq('user_id', horseId)
    .maybeSingle();
  if (data) return;
  const { error } = await supabase.from('club_members').insert({
    club_id: clubId,
    user_id: horseId,
    role: 'member',
    status: 'approved',
    chip_balance: 50000,
    is_active: true,
    is_prepaid: true,
    trust_score: 50,
    tier: 'bronze',
    /* THIS LINE IS THE ROOT CAUSE OF THE 2026-08-27 FLAG DRIFT.
       It was absent, so the column took its `false` default and every horse
       onboarded through this path was recorded as a human being. By the time
       it was found, 985 of 1,487 horses -- 66% of the fleet, holding 74.5
       million chips -- were flagged is_bot = false, and anything segmenting
       on that column counted them as players. It produced a wrong seated
       count in the cost analysis that led to finding it.
       `profiles.is_horse` stays authoritative; this is the per-membership
       copy and it has to agree. A trigger now enforces that
       (20260827_the_bot_flag_cannot_drift_again), so this line is
       belt-and-braces -- but the insert should state the truth itself
       rather than rely on a trigger to correct it. */
    is_bot: true,
  });
  if (error && !/duplicate|unique/i.test(error.message)) {
    throw new Error(`club_members insert: ${error.message}`);
  }
}

/**
 * Create a brand new horse, complete on the first try. This is the path a
 * future roster expansion should call instead of writing a seventh seed
 * script with its own idea of what a horse is.
 */
export async function createHorse(opts: { clubId?: string; realName?: string } = {}): Promise<{
  id: string;
  identity: HorseIdentity;
} | null> {
  try {
    const id = crypto.randomUUID();
    const ident = identityFor(id, opts.realName);
    // Player numbers live above the human range and are unique-checked.
    let playerNumber = 100000 + (hash(id) % 900000);
    for (let attempt = 0; attempt < 5; attempt++) {
      const { data: clash } = await supabase
        .from('profiles')
        .select('id')
        .eq('player_number', playerNumber)
        .maybeSingle();
      if (!clash) break;
      playerNumber = 100000 + ((hash(`${id}:${attempt}`) >>> 3) % 900000);
    }

    const { error } = await supabase.from('profiles').insert({
      id,
      username: ident.username,
      display_name: ident.realName,
      alias: ident.alias,
      email: `horse.${ident.username}@hydra.smarter.poker`,
      player_number: playerNumber,
      is_horse: true,
      horse_status: 'available',
      horse_profile: brainFor(id, null),
      is_vip: true,
      vip_tier: 'lifetime',
      vip_expires_at: '2099-12-31T23:59:59+00:00',
    });
    if (error) throw new Error(`profiles insert: ${error.message}`);

    await ensureClubMembership(id, opts.clubId ?? SHARK_CLUB_ID);
    await ensureHorseComplete({
      id,
      display_name: ident.realName,
      username: ident.username,
      alias: ident.alias,
      player_number: playerNumber,
      ['avatar_url']: null,
      is_vip: true,
      vip_tier: 'lifetime',
      horse_profile: brainFor(id, null),
    });
    console.log(`[HorseOnboarding] created ${ident.realName} "${ident.alias}" #${playerNumber}`);
    return { id, identity: ident };
  } catch (err) {
    reportError(err, 'HorseOnboarding.createHorse');
    return null;
  }
}
