/* GENERATED by scripts/audio/build-throwable-cues.mjs from throwable-cues.manifest.json. DO NOT EDIT. */

export interface CueManifestEntry {
  /** True when no file ships yet and `fallback` (a legacy recipe key) plays instead. */
  placeholder: boolean;
  fallback?: string;
  license?: string;
}

export const THROWABLE_CUE_MANIFEST: Record<string, CueManifestEntry> = {
  pop_soft: { placeholder: false, license: 'CC0-1.0' },
  glass_clink_rattle: { placeholder: false, license: 'CC0-1.0' },
  drip_tick: { placeholder: false, license: 'CC0-1.0' },
  squirt_start: { placeholder: true, fallback: 'squirt' },
  squirt_loop: { placeholder: true, fallback: 'squirt' },
  drip: { placeholder: false, license: 'CC0-1.0' },
  splat_wet: { placeholder: true, fallback: 'splat_wet' },
  egg_crack: { placeholder: true, fallback: 'egg_crack' },
};

export const THROWABLE_CUE_ALLOWED_LICENSES: readonly string[] = [
  'CC0-1.0',
  'Sonniss-GDC-Royalty-Free',
  'Own-Recording',
];
