/**
 * Emit the one-off data migration that gives every horse a styled alias.
 *
 *   cd server && npx tsx scripts/generate-horse-alias-migration.ts > ../supabase/migrations/<stamp>_every_horse_gets_a_human_alias.sql
 *
 * Reads the fleet (id, alias) and every name already taken (alias + username
 * of every profile, case-insensitive) with the service role, then walks each
 * horse through styledAlias(id, attempt) until it lands on a name nobody else
 * holds - the fleet included, so no two horses at one table read the same.
 * Deterministic: the same fleet emits the same file.
 *
 * Data only. No DDL, so no PostgREST schema reload (CLAUDE.md, production
 * DDL policy). Wrapped in one transaction with the counts asserted so it
 * aborts rather than half-renames.
 */
import { createClient } from '@supabase/supabase-js';
import { styledAlias } from '../src/services/horseAliasStyles.js';

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required');
  process.exit(1);
}
const supabase = createClient(url, key, { auth: { persistSession: false } });

async function main(): Promise<void> {
  const taken = new Set<string>();
  const horses: Array<{ id: string; alias: string | null }> = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await supabase
      .from('profiles')
      .select('id, alias, username, is_horse')
      .range(from, from + 999);
    if (error) throw new Error(error.message);
    for (const row of data ?? []) {
      if (row.username) taken.add(String(row.username).toLowerCase());
      if (row.is_horse) horses.push({ id: row.id, alias: row.alias });
      else if (row.alias) taken.add(String(row.alias).toLowerCase());
    }
    if (!data || data.length < 1000) break;
  }
  horses.sort((a, b) => a.id.localeCompare(b.id));

  const rows: Array<[string, string]> = [];
  for (const h of horses) {
    let alias = '';
    for (let attempt = 0; attempt < 50; attempt++) {
      const cand = styledAlias(h.id, attempt);
      if (!taken.has(cand.toLowerCase())) {
        alias = cand;
        break;
      }
    }
    if (!alias) throw new Error(`no free alias for ${h.id} after 50 attempts`);
    taken.add(alias.toLowerCase());
    rows.push([h.id, alias]);
  }

  const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
  const values = rows.map(([id, alias]) => `  (${q(id)}::uuid, ${q(alias)})`).join(',\n');
  const out = `-- ═══════════════════════════════════════════════════════════════════════════
-- EVERY HORSE GETS A HUMAN ALIAS (Dan 2026-09-04)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Dan, verbatim: "EVERY HORSE POKER ALIAS IS ALL TO SIMILAR, TWO WORD NAMES,
-- WITH THE FIRST LETTER OF BOTH WORDS CAPITALIZED, NO ONE WORD NAMES, NO
-- VARIATION IN CAPITALIZATION OF ANY WORDS, NO NUMBERS SPACES OR CHARACTERS
-- ... GO THROUGH THE HORSE LIST, AND CHANGE ALL THE NAMES TO ALL BE RANDOM
-- AND CUSTOM."
--
-- Measured before this ran: ${horses.length} horses, 867 of them
-- CapitalCapital, 803 distinct aliases (two twenty-word lists composed as
-- A+B give 400 shapes, so 197 horses shared a name with another horse).
--
-- Generated by server/scripts/generate-horse-alias-migration.ts from
-- server/src/services/horseAliasStyles.ts (fifty styles, deterministic in
-- the horse id, stepped on collision). Every alias below is unique
-- case-insensitively against every alias and username on the platform,
-- humans included, and fits the 11-character seat plate.
--
-- Only profiles.alias moves. username, display_name (the horse's "real"
-- name) and content_authors.alias (the social handle) are untouched: the
-- arena resolves a player's name as alias -> username -> display_name
-- (playerDisplayName.ts / fn_arena_name), so this is the column the felt
-- shows. The engine reads the alias when it seats a player, so a horse
-- already seated shows its old name until it next sits or the hourly
-- restart reloads the fleet.
--
-- Data only, no DDL: no PostgREST schema reload. One transaction, asserted.

BEGIN;

CREATE TEMP TABLE zz_horse_alias (id uuid PRIMARY KEY, alias text NOT NULL) ON COMMIT DROP;
INSERT INTO zz_horse_alias (id, alias) VALUES
${values};

DO $$
DECLARE
  v_rows int;
  v_dupes int;
  v_clash int;
BEGIN
  SELECT count(*) INTO v_rows FROM zz_horse_alias;
  IF v_rows <> ${rows.length} THEN
    RAISE EXCEPTION 'expected ${rows.length} horses, staged %', v_rows;
  END IF;
  SELECT count(*) - count(DISTINCT lower(alias)) INTO v_dupes FROM zz_horse_alias;
  IF v_dupes <> 0 THEN
    RAISE EXCEPTION '% duplicate aliases in the staged set', v_dupes;
  END IF;
  -- Nobody outside the fleet may already hold one of these names.
  SELECT count(*) INTO v_clash
    FROM public.profiles p
    JOIN zz_horse_alias z ON lower(coalesce(p.alias, '')) = lower(z.alias)
                          OR lower(coalesce(p.username, '')) = lower(z.alias)
   WHERE NOT coalesce(p.is_horse, false);
  IF v_clash <> 0 THEN
    RAISE EXCEPTION '% staged aliases collide with a human alias or username', v_clash;
  END IF;
END $$;

UPDATE public.profiles p
   SET alias = z.alias
  FROM zz_horse_alias z
 WHERE p.id = z.id
   AND coalesce(p.is_horse, false);

DO $$
DECLARE
  v_updated int;
  v_camel int;
  v_distinct int;
BEGIN
  SELECT count(*) INTO v_updated FROM public.profiles p JOIN zz_horse_alias z ON z.id = p.id AND p.alias = z.alias;
  IF v_updated <> ${rows.length} THEN
    RAISE EXCEPTION 'expected ${rows.length} horses renamed, found %', v_updated;
  END IF;
  SELECT count(*) FILTER (WHERE alias ~ '^[A-Z][a-z]+[A-Z][a-z]+$'), count(DISTINCT lower(alias))
    INTO v_camel, v_distinct
    FROM public.profiles WHERE coalesce(is_horse, false);
  IF v_distinct < ${horses.length} THEN
    RAISE EXCEPTION 'the fleet still shares names: % distinct of ${horses.length}', v_distinct;
  END IF;
  IF v_camel > ${Math.floor(horses.length * 0.3)} THEN
    RAISE EXCEPTION 'the fleet is still one silhouette: % CapitalCapital', v_camel;
  END IF;
  RAISE NOTICE 'renamed % horses; % distinct; % CapitalCapital', v_updated, v_distinct, v_camel;
END $$;

COMMIT;
`;
  process.stdout.write(out);
  console.error(`generated ${rows.length} aliases`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
