"""Native funded Heads-Up admission, launch and refund rehearsal."""
from pathlib import Path
import json
import re

repo = Path(__file__).resolve().parents[2]
directory = repo / 'scripts/dev/fixtures/heads-up-funding'
event = 'c3000000-0000-4000-8000-000000000001'
club = 'c2000000-0000-4000-8000-000000000001'
table = 'c4000000-0000-4000-8000-000000000001'
launch_id = 'c5000000-0000-4000-8000-000000000001'
generation = 'c6000000-0000-4000-8000-000000000001'

def uid(n): return 'c1000000-0000-4000-8000-' + str(n).zfill(12)

def verify(q, fresh, overlap, register, check):
    functions = json.loads((directory/'captured-functions.json').read_text())
    functions += json.loads((directory/'dependencies.json').read_text())
    schema = json.loads((directory/'columns.json').read_text())
    support = json.loads((directory/'support-schema.json').read_text())
    functions += support['functions']
    authority = (repo/'supabase/migrations/20260909165629_satellite_settlement_has_one_atomic_authority.sql').read_text()

    def seat(user=1, number=1):
        return "SET test.actor='%s'; SELECT fn_take_seat_and_buy_in('%s',%s);" % (uid(user),table,number)

    def leave(user=1, request=1):
        return "SET test.actor='%s'; SELECT fn_leave_seat_and_refund('%s','c9000000-0000-4000-8000-%012d');" % (uid(user),table,request)

    def begin():
        return "SELECT fn_begin_tournament_launch_atomic('%s','%s',NULL,'%s');" % (event,launch_id,generation)

    def complete():
        return "SELECT fn_complete_tournament_launch_atomic('%s','%s','%s');" % (event,launch_id,generation)

    def install_schema():
        # Structural catalog only. No source database records are copied.
        columns = support['columns'] + schema['columns'] + json.loads((directory/'financial-columns.json').read_text())
        existing = json.loads(q("SELECT COALESCE(jsonb_object_agg(table_name,names),'{}') FROM (SELECT table_name,jsonb_agg(column_name) names FROM information_schema.columns WHERE table_schema='public' GROUP BY table_name) t;"))
        groups = {}
        for c in columns:
            groups.setdefault(c['table'], {})[c['name']] = c
        statements = []
        for name, items in groups.items():
            if name not in existing:
                statements.append('CREATE TABLE public."' + name + '"();')
            for c in items.values():
                if c['name'] in existing.get(name, []):
                    continue
                default = c.get('default')
                if default and 'nextval(' in default:
                    seq = re.search(r"nextval\('([^']+)'",default).group(1)
                    statements.append('CREATE SEQUENCE IF NOT EXISTS ' + seq + ';')
                suffix = ' DEFAULT ' + default if default else ''
                if c.get('generated'):
                    suffix = ' GENERATED ALWAYS AS (' + default + ') STORED'
                if c.get('identity'):
                    suffix = ' GENERATED BY DEFAULT AS IDENTITY'
                if c['not_null']: suffix += ' NOT NULL'
                statements.append('ALTER TABLE public."' + name + '" ADD COLUMN "' + c['name'] + '" ' + c['type'] + suffix + ';')
        q('\n'.join(statements))
        constraints = json.loads(q("SELECT jsonb_agg(conname) FROM pg_constraint;"))
        q('\n'.join('ALTER TABLE public.' + c['table'] + ' ADD CONSTRAINT "' + c['name'] + '" ' + c['definition'] + ';'
            for c in schema['constraints'] if c['name'] not in constraints and not c['definition'].startswith(('TRIGGER','FOREIGN KEY'))))

        for c in schema['columns']:
            if c['table'] not in ['tournament_launch_receipts','engine_tournament_leases']:
                continue
            clause = 'SET DEFAULT ' + c['default'] if c['default'] else 'DROP DEFAULT'
            q('ALTER TABLE public.' + c['table'] + ' ALTER COLUMN "' + c['name'] + '" ' + clause + '; ALTER TABLE public.' + c['table'] + ' ALTER COLUMN "' + c['name'] + '" ' + ('SET' if c['not_null'] else 'DROP') + ' NOT NULL;')

    def setup(name, chips=300, variant='nlh'):
        fresh('hu_' + name)
        q("ALTER TABLE tournament_unregistration_receipts ADD COLUMN start_authority text NOT NULL DEFAULT 'scheduled_clock'; CREATE TABLE IF NOT EXISTS hand_history(id uuid,tournament_id uuid,table_id uuid); INSERT INTO ca_settle_sources(source,note) VALUES('fn_unregister_from_tournament','isolated Heads-Up refund');")
        q((repo/'supabase/migrations/20260909222303_satellite_unregister_returns_its_funded_cash.sql').read_text())
        q((repo/'scripts/dev/fixtures/unregistration-funding/installed.sql').read_text())
        q("ALTER TABLE clubs ADD COLUMN name text NOT NULL DEFAULT 'Isolated Club'; ALTER TABLE clubs ALTER COLUMN name DROP DEFAULT;")
        install_schema()
        q("ALTER TABLE tournament_unregistration_receipts DROP CONSTRAINT IF EXISTS tournament_unregistration_receipts_check9;")
        refund_constraints = json.loads((directory/'refund-constraints.json').read_text())
        q('\n'.join('ALTER TABLE public.tournament_unregistration_receipts DROP CONSTRAINT IF EXISTS "' + c['name'] + '"; ALTER TABLE public.tournament_unregistration_receipts ADD CONSTRAINT "' + c['name'] + '" ' + c['definition'] + ';' for c in refund_constraints if c['definition'].startswith('CHECK')))
        q("CREATE SCHEMA IF NOT EXISTS realtime; CREATE TABLE probe_ready_events(payload jsonb,event text,topic text); CREATE FUNCTION realtime.send(payload jsonb,event text,topic text,private boolean) RETURNS void LANGUAGE sql AS $$ INSERT INTO probe_ready_events VALUES(payload,event,topic) $$; CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$ SELECT COALESCE(NULLIF(current_setting('test.role',true),''),'authenticated') $$;")
        q('SET check_function_bodies=off;\n' + '\n'.join(f['definition'] + ';' for f in functions) + '\nRESET check_function_bodies;')
        for name, tag in [('fn_unregister_from_tournament','unregister_request_wrapper'),('fn_leave_seat_and_refund','leave_request_wrapper')]:
            end = authority.index('$' + tag + '$;') + len(tag) + 3
            start = authority.rfind('CREATE OR REPLACE FUNCTION',0,authority.index('AS $' + tag + '$'))
            q(authority[start:end])
        expected = {f['signature']:f['body_md5'] for f in functions}
        actual = json.loads(q("SELECT jsonb_object_agg(p.oid::regprocedure::text,md5(p.prosrc)) FROM pg_proc p WHERE p.oid=ANY(ARRAY[" + ','.join("'public." + x + "'::regprocedure" for x in expected) + ']);'))
        assert actual == expected,(actual,expected)
        q("UPDATE tournaments SET max_players=2,buy_in_amount=190,buy_in_fee=10,variant='sng',tournament_type='SNG',game_type='%s',starting_chips=%s,start_time=now()-interval '1 day',blind_structure='[{\"level\":1,\"smallBlind\":5,\"bigBlind\":10,\"durationMinutes\":3}]',payout_structure='[{\"place\":1,\"percentage\":100}]';" % (variant,chips))
        q((directory/'triggers.sql').read_text())
        observed_triggers = json.loads(q("SELECT jsonb_object_agg(tgrelid::regclass::text||':'||tgname,jsonb_build_object('enabled',tgenabled,'definition',pg_get_triggerdef(oid))) FROM pg_trigger WHERE NOT tgisinternal;"))
        inventory = json.loads((directory/'trigger-inventory.json').read_text())
        selected = set(inventory['installed'])
        for t in inventory['inventory']:
            if t['table'] + ':' + t['name'] in selected:
                actual_trigger = observed_triggers[t['table'] + ':' + t['name']]
                assert actual_trigger == dict(enabled=t['enabled'],definition=t['definition']),(t,actual_trigger)
        q("INSERT INTO tables(id,club_id,tournament_id,name,game_type,game_variant,max_players,starting_chips,status,current_players) VALUES('%s','%s','%s','Isolated Heads-Up','tournament','%s',2,%s,'waiting',0); INSERT INTO engine_tournament_leases(tournament_id,instance_id,lease_generation,protocol_version) VALUES('%s','isolated-hu-probe','%s',2);" % (table,club,event,variant,chips,event,generation))

    def state():
        return json.loads(q("""SELECT jsonb_build_object(
        'wallets',(SELECT sum(chip_balance) FROM club_members),
        'escrow',COALESCE((SELECT prize_balance+bounty_balance+fee_balance FROM tournament_escrow),0),
        'prize',COALESCE((SELECT prize_balance FROM tournament_escrow),0),
        'fees',COALESCE((SELECT fee_balance FROM tournament_escrow),0),
        'entries',(SELECT count(*) FROM tournament_players),
        'seats',(SELECT count(*) FROM table_seats WHERE left_at IS NULL),
        'stack',COALESCE((SELECT sum(stack) FROM table_seats WHERE left_at IS NULL),0),
        'roster_stack',COALESCE((SELECT sum(chips) FROM tournament_players),0),
        'cached',(SELECT current_players FROM tournaments),
        'table_cached',(SELECT current_players FROM tables),
        'debits',(SELECT count(*) FROM wallet_transactions WHERE type='debit'),
        'credits',(SELECT count(*) FROM wallet_transactions WHERE type='credit'),
        'entitlements',(SELECT count(*) FROM tournament_refund_entitlements),
        'refunds',(SELECT count(*) FROM tournament_unregistration_receipts),
        'journal',(SELECT count(*) FROM chip_ledger),
        'charge_total',COALESCE((SELECT sum(amount) FROM chip_ledger WHERE from_type='player_wallet'),0),
        'refund_total',COALESCE((SELECT sum(amount) FROM chip_ledger WHERE to_type='player_wallet'),0),
        'draws',(SELECT count(*) FROM spin_reserve_ledger),
        'status',(SELECT status FROM tournaments));"""))

    def funded(count, chips=300, refunded=0):
        observed = state()
        assert observed == dict(wallets=2000-200*count,escrow=200*count,prize=190*count,
            fees=10*count,entries=count,seats=count,stack=chips*count,roster_stack=chips*count,
            cached=count,table_cached=count,debits=count+refunded,credits=refunded,
            entitlements=count+refunded,refunds=refunded,journal=count+2*refunded,charge_total=200*(count+refunded),refund_total=200*refunded,draws=0,status=observed['status']), observed
        assert observed['wallets'] + observed['escrow'] == 2000, observed
        return observed

    setup('first')
    response = json.loads(q(seat()))
    assert response.get('ok') is True, response
    funded(1)
    check('Heads-Up first seat binds the paid entry and exact starting stack')


    def snapshot():
        # Include every relation loaded into the fixture: a rollback must also
        # undo escrow journals, alerts and support writes, not only wallet totals.
        names = json.loads(q("SELECT jsonb_agg(c.relname ORDER BY c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r';"))
        return q('SELECT jsonb_object_agg(name,rows) FROM (' + ' UNION ALL '.join(
            "SELECT '%s' AS name,COALESCE(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]') AS rows FROM %s t" % (t,t)
            for t in names) + ') snapshot;')

    before = snapshot()
    for requested in [1,2]:
        replay = json.loads(q(seat(number=requested)))
        assert replay.get('already_seated') is True and replay.get('seat_number') == 1,replay
        assert snapshot() == before
    check('same-seat and changed-seat retries reuse one funded entry without moving it')

    for name, requested in [('same',1),('changed',2)]:
        setup('retry_' + name)
        a,b = overlap(seat(),seat(number=requested))
        assert a.get('ok') is True and b.get('already_seated') is True,(a,b)
        assert b.get('seat_number') == 1,b
        funded(1)
        check('overlapping ' + name + '-seat retry buys one entry and one stack')

    for variant in ['nlh','plo4']:
        for chips in [300,1000]:
            setup(variant + '_' + str(chips),chips,variant)
            assert json.loads(q(seat())).get('ok') is True
            a,b = overlap(seat(2,2),seat(3,2))
            assert a.get('ok') is True and a.get('starts_now') is True,(a,b)
            assert b.get('reason') == 'seat_taken',b
            funded(2,chips)
            ready = json.loads(q("SELECT jsonb_agg(payload) FROM probe_ready_events;"))
            assert ready and all(x['paid_seats']==2 for x in ready),ready
            assert json.loads(q(begin())).get('ok') is True
            complete_result = json.loads(q(complete()))
            assert complete_result.get('completed') is True,complete_result
            assert funded(2,chips)['status'] == 'RUNNING'
            before = snapshot()
            replay = json.loads(q(complete()))
            assert replay.get('replay') is True,replay
            assert snapshot() == before
            check(variant + ' ' + str(chips) + ': last seat race funds two entries and lease-bound launch replays unchanged')

    setup('seat_failure')
    before = snapshot()
    q("CREATE FUNCTION probe_paid_seat_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected paid seat failure'; END $$; CREATE TRIGGER zzzzzz_probe_paid_seat_failure AFTER INSERT ON table_seats FOR EACH ROW EXECUTE FUNCTION probe_paid_seat_failure();")
    q(seat(),'injected paid seat failure')
    assert snapshot() == before
    funded(0)
    check('failure after the funded seat write rolls back wallet ledger entitlement escrow roster and seat')

    setup('refund_failure')
    assert json.loads(q(seat())).get('ok') is True
    q("CREATE FUNCTION probe_hu_refund_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected HU refund receipt failure'; END $$; CREATE TRIGGER probe_hu_refund_failure BEFORE INSERT ON tournament_unregistration_receipts FOR EACH ROW EXECUTE FUNCTION probe_hu_refund_failure();")
    before = snapshot()
    q(leave(),'injected HU refund receipt failure')
    assert snapshot() == before
    funded(1)
    check('last refund receipt failure rolls back all financial and seat relations')

    setup('revival')
    assert json.loads(q(seat())).get('ok') is True
    first = json.loads(q("SELECT jsonb_build_object('seat',s.id,'occupancy',s.occupancy_id,'registration',p.id) FROM table_seats s CROSS JOIN tournament_players p;"))
    receipt = json.loads(q(leave()))
    assert receipt.get('refunded_chips') == 200,receipt
    funded(0,refunded=1)
    before = snapshot()
    replay = json.loads(q(leave()))
    assert replay.get('replayed') is True and replay.get('registration_id') == first['registration'],replay
    assert snapshot() == before
    assert json.loads(q(seat())).get('ok') is True
    second = json.loads(q("SELECT jsonb_build_object('seat',s.id,'occupancy',s.occupancy_id,'registration',p.id) FROM table_seats s CROSS JOIN tournament_players p;"))
    assert second['seat']==first['seat'] and second['occupancy']!=first['occupancy'] and second['registration']!=first['registration'],(first,second)
    funded(1,refunded=1)
    before = snapshot()
    q(leave(),'prior registration lifecycle')
    assert snapshot() == before
    check('refund replays exactly; physical seat revival buys a new registration and rejects an old refund')

    setup('start_wins')
    q(seat());q(seat(2,2));q(begin())
    a,b = overlap(complete(),leave())
    assert a.get('completed') is True and b.get('reason') == 'registration_closed',(a,b)
    assert funded(2)['status'] == 'RUNNING'
    check('refund waiting behind actual launch completion cannot unwind the started entry')

    setup('refund_wins')
    q(seat());q(seat(2,2));q(begin())
    a,b = overlap(leave(),complete())
    assert a.get('refunded_chips') == 200 and b.get('reason') == 'launch_roster_unproven',(a,b)
    assert funded(1,refunded=1)['status'] == 'REGISTERING'
    assert q("SELECT completed_at IS NULL FROM tournament_launch_receipts;") == 't'
    check('launch waiting behind the actual refund rechecks the surviving one-player field')

    setup('last_seat_then_launch')
    q(seat());q(begin())
    a,b = overlap(seat(2,2),complete())
    assert a.get('starts_now') is True and b.get('completed') is True,(a,b)
    assert funded(2)['status'] == 'RUNNING'
    check('launch waits for the funded last seat before proving and starting the field')

    setup('last_seat_then_refund')
    q(seat())
    a,b = overlap(seat(2,2),leave())
    assert a.get('starts_now') is True and b.get('refunded_chips') == 200,(a,b)
    assert funded(1,refunded=1)['status'] == 'REGISTERING'
    check('last-seat readiness does not itself start play or erase the prestart refund right')

    setup('launch_receipt_failure')
    q(seat());q(seat(2,2));q(begin())
    q("CREATE FUNCTION probe_hu_launch_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected HU launch receipt failure'; END $$; CREATE TRIGGER probe_hu_launch_failure BEFORE UPDATE OF completed_at ON tournament_launch_receipts FOR EACH ROW EXECUTE FUNCTION probe_hu_launch_failure();")
    before = snapshot()
    q(complete(),'injected HU launch receipt failure')
    assert snapshot() == before
    assert funded(2)['status'] == 'REGISTERING'
    check('last launch receipt failure rolls status and every proof relation back together')
