-- 20260829j_rake_bbj_collection_invariants_watchdog.sql
-- APPLIED TO PRODUCTION 2026-08-29 via Supabase MCP
-- (migration name: rake_bbj_collection_invariants_watchdog). Full body in the
-- Supabase migration history.
--
-- Dan 2026-08-29: "harden the rake and bbj process collection and tracking so
-- it can't regress or break ever." Tests prove the CODE is right at merge
-- time; this proves the DATA is right every hour, forever — including after a
-- config change, a bad deploy, a restart, or a hand-written SQL fix.
--
-- fn_rake_bbj_invariants(p_hours) returns one row per check, each one a bug
-- that shipped or a hole the hardening sweep found:
--   I1 drop taken with fewer than 3 players dealt in       (rule break)
--   I2 drop taken on a BBJ-ineligible variant              (rule break)
--   I3 rake + drop exceeds the pot                         (MINTS CHIPS)
--   I4 eligible flopped hand charged NO drop               (the 49% bug)
--   I5 drop collected but never banked to a pool           (CHIPS LOST)
--   I6 weighted hand whose ledger != rake collected        (attribution)
--   I7 raked hand with no banking row at all               (engine died)
--
-- fn_rake_bbj_audit(p_hours) runs them and files ONE financial_alerts row per
-- cycle when anything is non-zero — critical if a money check (I3/I5/I7) is
-- among them, warning otherwise. It reports; it never silently "fixes" money.
-- Both service_role only. Scheduled hourly at :38 via pg_cron
-- ('rake-bbj-invariant-audit-hourly'), advisory-locked like every other heal
-- and audit job here. Grace window: hands younger than 5 minutes are never
-- judged (settlement is not instant).
--
-- FIRST RUN AGAINST PRODUCTION: all seven checks returned ZERO violations.
SELECT 'applied via MCP as rake_bbj_collection_invariants_watchdog — see migration history' AS notice;
