-- BACKFILLED 2026-09-27 from supabase_migrations.schema_migrations.statements.
-- Applied to production as 20260820015701 "fn_rakeback_recompute_periods_fix_1000_row_truncation"; the .sql file was never committed
-- at the time. Everything below this header is byte-exact to what ran:
-- md5 e1f2184fa2163aa1fd8c85a150cd39ef of array_to_string(statements, chr(10)) || chr(10).
-- Do NOT re-apply; it is already live.

-- ═══ CRITICAL MONEY BUG (2026-08-20) — players were under-paid rakeback ═══
--
-- The settler recomputed each week's rake_generated by FETCHING the club's
-- rake_records for that week with `.limit(50000)` and summing in JavaScript.
-- PostgREST caps a response at 1000 rows, so it only ever saw the first ~1000
-- records of a week that actually holds 81,000-180,000. rake_generated was
-- therefore computed from well under 1% of the real data.
--
-- Measured on live pending periods before this fix:
--
--   user 1c1c12c2…  stored    23.17   actual   629.02   ->  3.7% recorded
--   user 00bc0957…  stored    24.54   actual   387.38   ->  6.3% recorded
--
-- It is worse than a proportional shortfall, because rake_generated also picks
-- the rakeback TIER (5/10/15/20/30% at 100/500/2000/10000). The first player
-- belongs in the 15% tier on 629.02 (= 94.35) but was recorded at 23.17, which
-- is the 5% tier (= 1.16). ~99% under-payment.
--
-- The cap cannot be raised from the client, so the computation moves to the
-- database, where there is no row ceiling.
--
-- The arithmetic is replicated EXACTLY, not approximated:
--   * equalShareCents: base = floor(total_cents / n), and the first `remainder`
--     users each get one extra cent. "First" means the order the engine sees,
--     which is Object.entries() over the parsed JSON — i.e. jsonb's stored key
--     order. jsonb sorts keys by (length, bytes); every key here is a 36-char
--     UUID, so that reduces to plain lexicographic, which is what ORDER BY on
--     the key text gives. Same split, same cent, same player.
--   * n counts only contributors with a POSITIVE contribution, matching the
--     engine's `.filter(([, amt]) => Number(amt) > 0)`.
--   * the tier ladder matches RAKEBACK_TIERS and fn_close_settlement_period.
--
-- Rows for a user who already holds a period row under a DIFFERENT club are
-- skipped rather than attempted: rakeback_periods has a second unique key on
-- (user_id, period_start) spanning all clubs, so those inserts already failed
-- with a 409. Skipping keeps behaviour identical while letting the rest of the
-- set-based insert succeed instead of aborting on the first collision.

CREATE OR REPLACE FUNCTION public.fn_rakeback_recompute_periods(
  p_club_id      uuid,
  p_period_start date,
  p_period_end   date,
  p_user_ids     uuid[] DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
SET statement_timeout = '300s'
AS $$
DECLARE
  v_written integer := 0;
  v_users   integer := 0;
BEGIN
  IF p_club_id IS NULL OR p_period_start IS NULL OR p_period_end IS NULL THEN
    RETURN jsonb_build_object('written', 0, 'error', 'missing params');
  END IF;

  WITH shares AS (
    SELECT (k.key)::uuid AS user_id,
           (round(r.rake_amount * 100)::bigint / c.n)
           + CASE WHEN row_number() OVER (PARTITION BY r.id ORDER BY k.key)
                       <= (round(r.rake_amount * 100)::bigint % c.n)
                  THEN 1 ELSE 0 END AS cents
      FROM rake_records r
      CROSS JOIN LATERAL (
        SELECT count(*)::bigint AS n
          FROM jsonb_each(r.player_contributions) e
         WHERE (e.value)::numeric > 0
      ) c
      JOIN LATERAL jsonb_each(r.player_contributions) k
        ON (k.value)::numeric > 0
     WHERE r.club_id = p_club_id
       AND r.created_at >= p_period_start::timestamptz
       AND r.created_at <  (p_period_end + 1)::timestamptz
       AND r.rake_amount > 0
       AND r.player_contributions IS NOT NULL
       AND c.n > 0
  ), totals AS (
    SELECT s.user_id, (SUM(s.cents)::numeric / 100) AS total_rake
      FROM shares s
     WHERE p_user_ids IS NULL OR s.user_id = ANY (p_user_ids)
     GROUP BY s.user_id
  ), eligible AS (
    SELECT t.user_id, t.total_rake,
           CASE WHEN t.total_rake >= 10000 THEN 0.30
                WHEN t.total_rake >=  2000 THEN 0.20
                WHEN t.total_rake >=   500 THEN 0.15
                WHEN t.total_rake >=   100 THEN 0.10
                ELSE 0.05 END AS rate
      FROM totals t
     WHERE NOT EXISTS (
       SELECT 1 FROM rakeback_periods rp
        WHERE rp.user_id = t.user_id
          AND rp.period_start = p_period_start
          AND rp.club_id <> p_club_id
     )
  ), ins AS (
    INSERT INTO rakeback_periods (
      user_id, club_id, period_start, period_end,
      rake_generated, rakeback_rate, rakeback_earned, rakeback_amount,
      total_rake_paid, status
    )
    SELECT e.user_id, p_club_id, p_period_start, p_period_end,
           round(e.total_rake, 2), e.rate,
           round(e.total_rake * e.rate, 2), round(e.total_rake * e.rate, 2),
           round(e.total_rake, 2), 'pending'
      FROM eligible e
    ON CONFLICT (user_id, club_id, period_start, period_end) DO UPDATE
      SET rake_generated  = EXCLUDED.rake_generated,
          rakeback_rate   = EXCLUDED.rakeback_rate,
          rakeback_earned = EXCLUDED.rakeback_earned,
          rakeback_amount = EXCLUDED.rakeback_amount,
          total_rake_paid = EXCLUDED.total_rake_paid
      WHERE rakeback_periods.status = 'pending'
    RETURNING 1
  )
  SELECT count(*) INTO v_written FROM ins;

  SELECT count(*) INTO v_users FROM (
    SELECT 1 FROM rakeback_periods
     WHERE club_id = p_club_id AND period_start = p_period_start
  ) q;

  RETURN jsonb_build_object('written', v_written, 'rows_in_period', v_users);
END $$;

REVOKE ALL ON FUNCTION public.fn_rakeback_recompute_periods(uuid, date, date, uuid[]) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_rakeback_recompute_periods(uuid, date, date, uuid[]) TO service_role;
