-- Diamond Accounting Standard, Lane E: every earn engine has a budget line,
-- a per-user per-day cap ledger, catalogs keep history, and the trivia
-- tournament cut is banked instead of burned by omission.
--
-- Standard references: DR7 (every earn engine has a budget line and a per-user
-- per-day cap in the database), DR14 (nothing is burned by omission), D21
-- (earn engines are budgets, not faucets; the catalog that prices awards is
-- versioned and every edit logged).
--
-- LOG-ONLY. Nothing here refuses a movement. The budget ledger and the cap
-- ledger record what happened and file an incident when a line is crossed;
-- the trigger is wrapped so it can never abort an insert into the journal.
--
-- BUDGET AND CAP NUMBERS ARE PROPOSED PLACEHOLDERS, NOT DAN'S NUMBERS.
-- 2,500,000 per engine per month is the constant already inside
-- award_diamonds_v2 (c_platform_budget), reused here so that no engine starts
-- life at zero and files a false incident on its first award. The daily caps
-- are what the code enforces today where it enforces anything at all
-- (catalog_v2 110 = the non-VIP daily cap in award_diamonds_v2; trivia 2,000 =
-- the largest solo award ceiling in trivia_diamond_award_limits). Every other
-- engine is NULL, meaning uncapped today, which is a statement of fact about
-- the code and not a recommendation. Dan sets the real numbers.
--
-- One migration, one transaction, applied once.

BEGIN;

SET LOCAL lock_timeout = '4s';

-- ---------------------------------------------------------------------------
-- 1. The cap catalog: what a single engine may award one player in one
--    America/Chicago day. NULL means "no cap is enforced anywhere today".
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.diamond_engine_daily_caps (
    engine               text PRIMARY KEY,
    max_per_user_per_day integer,
    note                 text,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT diamond_engine_daily_caps_positive
        CHECK (max_per_user_per_day IS NULL OR max_per_user_per_day > 0)
);

COMMENT ON TABLE public.diamond_engine_daily_caps IS
  'DR7. Per-engine, per-user, per-day diamond ceiling. PROPOSED PLACEHOLDERS seeded from what the code enforces today: catalog_v2 110 (award_diamonds_v2 non-VIP daily cap), trivia 2000 (largest solo award in trivia_diamond_award_limits). NULL means uncapped in code today. Dan sets the real numbers.';

-- ---------------------------------------------------------------------------
-- 2. The per-user per-day award ledger (DR7). Log-only: written by the
--    journal trigger, read by the incident check, refuses nothing.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.diamond_user_daily_awards (
    user_id    uuid        NOT NULL,
    engine     text        NOT NULL,
    day        date        NOT NULL,
    awarded    bigint      NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, engine, day)
);

COMMENT ON TABLE public.diamond_user_daily_awards IS
  'DR7. One row per (player, engine, America/Chicago day) with the diamonds that engine credited that player that day. Written by trg_ca_diamond_earn_ledger on diamond_transactions. Horses are players (CLAUDE.md 10.5): this table never filters is_horse.';

CREATE INDEX IF NOT EXISTS diamond_user_daily_awards_day_idx
    ON public.diamond_user_daily_awards (day DESC, engine);

-- ---------------------------------------------------------------------------
-- 3. The house ledger (DR14). ca_diamond_house already exists from the
--    foundation migration; it had no ledger, so a credit to it could not be
--    explained. This is that explanation.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.ca_diamond_house_ledger (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at            timestamptz NOT NULL DEFAULT now(),
    delta         numeric(20,0) NOT NULL,
    balance_after numeric(20,0) NOT NULL,
    reason        text NOT NULL,
    reference     text NOT NULL UNIQUE,
    user_id       uuid,
    tournament_id uuid
);

COMMENT ON TABLE public.ca_diamond_house_ledger IS
  'DR14. Every movement of ca_diamond_house.balance, with the reference that makes it idempotent. First writer: enter_trivia_tournament_v2, which banks the entry-fee cut it used to burn by omission.';

-- ---------------------------------------------------------------------------
-- 4. Catalog history (D21). Three catalogs price every diamond award on the
--    platform and none of them could say what they used to say.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.diamond_reward_catalog_history (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op         text NOT NULL,
    old_row    jsonb,
    new_row    jsonb,
    changed_at timestamptz NOT NULL DEFAULT now(),
    db_role    text NOT NULL DEFAULT CURRENT_USER,
    app_name   text NOT NULL DEFAULT COALESCE(current_setting('application_name', true), '')
);

CREATE TABLE IF NOT EXISTS public.daily_challenge_catalog_history (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op         text NOT NULL,
    old_row    jsonb,
    new_row    jsonb,
    changed_at timestamptz NOT NULL DEFAULT now(),
    db_role    text NOT NULL DEFAULT CURRENT_USER,
    app_name   text NOT NULL DEFAULT COALESCE(current_setting('application_name', true), '')
);

CREATE TABLE IF NOT EXISTS public.trivia_diamond_award_limits_history (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op         text NOT NULL,
    old_row    jsonb,
    new_row    jsonb,
    changed_at timestamptz NOT NULL DEFAULT now(),
    db_role    text NOT NULL DEFAULT CURRENT_USER,
    app_name   text NOT NULL DEFAULT COALESCE(current_setting('application_name', true), '')
);

COMMENT ON TABLE public.diamond_reward_catalog_history IS
  'D21. Append-only record of every edit to diamond_reward_catalog, with the db role and application that made it.';
COMMENT ON TABLE public.daily_challenge_catalog_history IS
  'D21. Append-only record of every edit to daily_challenge_catalog.';
COMMENT ON TABLE public.trivia_diamond_award_limits_history IS
  'D21. Append-only record of every edit to trivia_diamond_award_limits.';

-- ---------------------------------------------------------------------------
-- 5. Engine attribution. Pure function from the shape of a journal row to the
--    name of the engine that wrote it. The shapes are the ones lane 3
--    documented in
--    docs/audits/2026-09-02-diamond-economy/lane3-earn-engines-and-transfers.md.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_ca_diamond_engine_of(
    p_type             text,
    p_transaction_type text,
    p_source           text,
    p_description      text,
    p_reference_id     text
) RETURNS text
LANGUAGE sql
IMMUTABLE
AS $fn$
    SELECT CASE
        -- Reference shapes are the most specific evidence a row carries.
        WHEN starts_with(p_reference_id, 'trivia_tourn_')     THEN 'trivia_tournaments'
        WHEN starts_with(p_reference_id, 'trivia_session_')   THEN 'trivia'
        WHEN starts_with(p_reference_id, 'trivia_wheel_')     THEN 'trivia'
        WHEN starts_with(p_reference_id, 'challenge_claim')   THEN 'daily_challenges'
        WHEN starts_with(p_reference_id, 'streak_milestone_') THEN 'share_streak'
        WHEN starts_with(p_reference_id, 'signup:')           THEN 'signup'
        WHEN starts_with(p_reference_id, 'easter_egg_')       THEN 'catalog_v2'
        WHEN starts_with(p_reference_id, 'video_favorite_')   THEN 'catalog_v2'
        WHEN starts_with(p_reference_id, 'vip_stipend_')      THEN 'catalog_v2'

        -- source is set by exactly three writers and each names its engine.
        WHEN p_source = 'complete_daily_challenge' THEN 'memory_game'
        WHEN p_source = 'handle_new_user'          THEN 'signup'
        WHEN p_source = 'union'                    THEN 'union_grant'

        -- transaction_type where it is set, falling back to type.
        WHEN COALESCE(p_transaction_type, p_type) IN (
                'referral_bonus', 'referral_bonus_reversal', 'referral_qualified',
                'referral_referee', 'referral_vip_conversion')             THEN 'referrals'
        WHEN COALESCE(p_transaction_type, p_type) = 'signup_bonus'         THEN 'signup'
        WHEN COALESCE(p_transaction_type, p_type) = 'union_grant'          THEN 'union_grant'
        WHEN COALESCE(p_transaction_type, p_type) IN (
                'pvp_refund', 'pvp_win', 'pvp_tie_refund', 'trivia_run',
                'trivia_daily_bonus', 'daily_trivia', 'trivia_reward',
                'trivia_prize_wheel', 'endless_reward', 'survival_reward',
                'mixed_reward', 'time_attack_reward', 'trivia_double_win')  THEN 'trivia'
        WHEN COALESCE(p_transaction_type, p_type) IN (
                'tournament_prize', 'tournament_entry_refund',
                'tournament_cancel_refund')                                THEN 'trivia_tournaments'
        WHEN COALESCE(p_transaction_type, p_type) = 'daily_challenge_claim' THEN 'daily_challenges'
        WHEN COALESCE(p_transaction_type, p_type) = 'streak_reward'        THEN 'share_streak'
        WHEN COALESCE(p_transaction_type, p_type) IN (
                'daily_login', 'easter_egg', 'training_reward',
                'video_favorite', 'vip_stipend')                           THEN 'catalog_v2'
        WHEN COALESCE(p_transaction_type, p_type) IN (
                'credit', 'earn', 'bonus')                                 THEN 'legacy_credit'

        -- award_diamonds_v2 stamps this description on every row it writes.
        WHEN p_description LIKE 'Diamond Rewards v2:%'                      THEN 'catalog_v2'

        ELSE 'other'
    END;
$fn$;

COMMENT ON FUNCTION public.fn_ca_diamond_engine_of(text, text, text, text, text) IS
  'DR7. Maps one diamond_transactions row to the earn engine that wrote it, from the reference shape, then the source, then the type, then the description. Unknown maps to other. Pure; safe to run over history.';

REVOKE ALL ON FUNCTION public.fn_ca_diamond_engine_of(text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fn_ca_diamond_engine_of(text, text, text, text, text) TO service_role, authenticated;

-- ---------------------------------------------------------------------------
-- 6. The budget and cap ledger (DR7), LOG-ONLY.
--
--    It never refuses. Everything it does is wrapped in a handler that turns
--    any failure into an incident, because a bookkeeping table must never be
--    able to stop a player being paid.
--
--    Rows that are not promotional issuance are skipped: a purchase, a
--    transfer between two players, a refund, an admin adjustment and an arena
--    movement are all transfers between accounts rather than new issuance, so
--    charging them to an earn budget would be double counting.
--
--    Signup grants arrive with issuance_class 'seeded' or 'promotional'
--    (Lane B, the Mint) and are counted against the 'signup' engine.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_ca_diamond_earn_ledger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
DECLARE
    v_engine  text;
    v_period  text;
    v_day     date;
    v_budget  bigint;
    v_spent   bigint;
    v_awarded bigint;
    v_cap     integer;
    v_at      timestamptz;
BEGIN
    BEGIN
        -- Not promotional issuance: skip.
        IF COALESCE(NEW.issuance_class, '') IN ('purchased', 'transferred', 'refund', 'admin', 'arena') THEN
            RETURN NULL;
        END IF;
        IF COALESCE(NEW.type, '') = 'purchase' OR COALESCE(NEW.transaction_type, '') = 'purchase' THEN
            RETURN NULL;
        END IF;

        v_at     := COALESCE(NEW.created_at, now());
        v_engine := public.fn_ca_diamond_engine_of(
                        NEW.type, NEW.transaction_type, NEW.source,
                        NEW.description, NEW.reference_id);
        v_period := to_char((v_at AT TIME ZONE 'America/Chicago'), 'YYYY-MM');
        v_day    := (v_at AT TIME ZONE 'America/Chicago')::date;

        -- (a) the engine's budget line for the period. A period that does not
        --     exist yet inherits the engine's most recent budget, or the
        --     2,500,000 placeholder if the engine has never had one.
        INSERT INTO public.diamond_reward_budgets (period, engine, budget_diamonds, spent_diamonds, updated_at)
        VALUES (
            v_period,
            v_engine,
            COALESCE(
                (SELECT b.budget_diamonds
                   FROM public.diamond_reward_budgets b
                  WHERE b.engine = v_engine
                    AND b.period < v_period
                  ORDER BY b.period DESC
                  LIMIT 1),
                2500000),
            NEW.amount,
            now())
        ON CONFLICT (period, engine) DO UPDATE
           SET spent_diamonds = diamond_reward_budgets.spent_diamonds + EXCLUDED.spent_diamonds,
               updated_at     = now()
        RETURNING budget_diamonds, spent_diamonds INTO v_budget, v_spent;

        IF v_spent > v_budget THEN
            PERFORM public.fn_ca_diamond_incident(
                'DR7:engine_over_budget', 'warning', NEW.user_id, NEW.amount,
                'fn_ca_diamond_earn_ledger',
                jsonb_build_object(
                    'engine', v_engine, 'period', v_period,
                    'budget_diamonds', v_budget, 'spent_diamonds', v_spent,
                    'journal_id', NEW.id, 'reference_id', NEW.reference_id));
        END IF;

        -- (b) the player's day total for that engine.
        INSERT INTO public.diamond_user_daily_awards (user_id, engine, day, awarded, updated_at)
        VALUES (NEW.user_id, v_engine, v_day, NEW.amount, now())
        ON CONFLICT (user_id, engine, day) DO UPDATE
           SET awarded    = diamond_user_daily_awards.awarded + EXCLUDED.awarded,
               updated_at = now()
        RETURNING awarded INTO v_awarded;

        -- (c) the per-user per-day cap, where one is set.
        SELECT c.max_per_user_per_day
          INTO v_cap
          FROM public.diamond_engine_daily_caps c
         WHERE c.engine = v_engine;

        IF v_cap IS NOT NULL AND v_awarded > v_cap THEN
            PERFORM public.fn_ca_diamond_incident(
                'DR7:user_over_daily_cap', 'warning', NEW.user_id, NEW.amount,
                'fn_ca_diamond_earn_ledger',
                jsonb_build_object(
                    'engine', v_engine, 'day', v_day,
                    'max_per_user_per_day', v_cap, 'awarded_today', v_awarded,
                    'journal_id', NEW.id, 'reference_id', NEW.reference_id));
        END IF;

    EXCEPTION WHEN OTHERS THEN
        -- (e) never raise. A budget line is bookkeeping; the award already
        --     happened and the player keeps it.
        PERFORM public.fn_ca_diamond_incident(
            'DR7:ledger_write_failed', 'warning', NEW.user_id, NEW.amount,
            'fn_ca_diamond_earn_ledger',
            jsonb_build_object(
                'sqlstate', SQLSTATE, 'sqlerrm', SQLERRM,
                'journal_id', NEW.id, 'reference_id', NEW.reference_id));
    END;

    RETURN NULL;
END;
$fn$;

COMMENT ON FUNCTION public.fn_ca_diamond_earn_ledger() IS
  'DR7 LOG-ONLY. AFTER INSERT on diamond_transactions for positive amounts: charges the engine budget line, adds to the per-user per-day total, and files DR7:engine_over_budget / DR7:user_over_daily_cap incidents. Never refuses; any failure becomes DR7:ledger_write_failed.';

REVOKE ALL ON FUNCTION public.fn_ca_diamond_earn_ledger() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_ca_diamond_earn_ledger ON public.diamond_transactions;
CREATE TRIGGER trg_ca_diamond_earn_ledger
    AFTER INSERT ON public.diamond_transactions
    FOR EACH ROW
    WHEN (NEW.amount > 0)
    EXECUTE FUNCTION public.fn_ca_diamond_earn_ledger();

-- ---------------------------------------------------------------------------
-- 7. Catalog history triggers (D21).
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_ca_diamond_catalog_history()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
DECLARE
    v_sql text;
BEGIN
    BEGIN
        v_sql := format(
            'INSERT INTO public.%I (op, old_row, new_row) VALUES ($1, $2, $3)',
            TG_TABLE_NAME || '_history');
        IF TG_OP = 'INSERT' THEN
            EXECUTE v_sql USING TG_OP, NULL::jsonb, to_jsonb(NEW);
        ELSIF TG_OP = 'DELETE' THEN
            EXECUTE v_sql USING TG_OP, to_jsonb(OLD), NULL::jsonb;
        ELSE
            EXECUTE v_sql USING TG_OP, to_jsonb(OLD), to_jsonb(NEW);
        END IF;
    EXCEPTION WHEN OTHERS THEN
        PERFORM public.fn_ca_diamond_incident(
            'D21:catalog_history_write_failed', 'warning', NULL, NULL,
            'fn_ca_diamond_catalog_history',
            jsonb_build_object('table', TG_TABLE_NAME, 'op', TG_OP,
                               'sqlstate', SQLSTATE, 'sqlerrm', SQLERRM));
    END;
    RETURN NULL;
END;
$fn$;

COMMENT ON FUNCTION public.fn_ca_diamond_catalog_history() IS
  'D21. AFTER INSERT OR UPDATE OR DELETE on a diamond pricing catalog: appends the old and new row to <table>_history. Never raises.';

REVOKE ALL ON FUNCTION public.fn_ca_diamond_catalog_history() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_ca_diamond_reward_catalog_history ON public.diamond_reward_catalog;
CREATE TRIGGER trg_ca_diamond_reward_catalog_history
    AFTER INSERT OR UPDATE OR DELETE ON public.diamond_reward_catalog
    FOR EACH ROW EXECUTE FUNCTION public.fn_ca_diamond_catalog_history();

DROP TRIGGER IF EXISTS trg_ca_daily_challenge_catalog_history ON public.daily_challenge_catalog;
CREATE TRIGGER trg_ca_daily_challenge_catalog_history
    AFTER INSERT OR UPDATE OR DELETE ON public.daily_challenge_catalog
    FOR EACH ROW EXECUTE FUNCTION public.fn_ca_diamond_catalog_history();

DROP TRIGGER IF EXISTS trg_ca_trivia_diamond_award_limits_history ON public.trivia_diamond_award_limits;
CREATE TRIGGER trg_ca_trivia_diamond_award_limits_history
    AFTER INSERT OR UPDATE OR DELETE ON public.trivia_diamond_award_limits
    FOR EACH ROW EXECUTE FUNCTION public.fn_ca_diamond_catalog_history();

-- ---------------------------------------------------------------------------
-- 8. Seed the budget lines and the cap catalog.
--    PROPOSED PLACEHOLDERS. See the header. Dan sets the real numbers.
-- ---------------------------------------------------------------------------

INSERT INTO public.diamond_reward_budgets (period, engine, budget_diamonds, spent_diamonds)
SELECT p.period, e.engine, 2500000, 0
  FROM (VALUES
        (to_char((now() AT TIME ZONE 'America/Chicago'), 'YYYY-MM')),
        (to_char(((now() AT TIME ZONE 'America/Chicago') + interval '1 month'), 'YYYY-MM'))
       ) AS p(period),
       (VALUES
        ('catalog_v2'), ('daily_challenges'), ('trivia'), ('trivia_tournaments'),
        ('referrals'), ('share_streak'), ('memory_game'), ('signup'),
        ('union_grant'), ('legacy_credit'), ('other')
       ) AS e(engine)
ON CONFLICT (period, engine) DO NOTHING;

INSERT INTO public.diamond_engine_daily_caps (engine, max_per_user_per_day, note) VALUES
    ('catalog_v2',         110,  'PROPOSED. What award_diamonds_v2 enforces today for a non-VIP (v_daily_cap 110; VIP 150). Dan sets the real number.'),
    ('trivia',             2000, 'PROPOSED. The largest solo award ceiling in trivia_diamond_award_limits. It is a per-award maximum today, not a per-day cap. Dan sets the real number.'),
    ('daily_challenges',   NULL, 'Uncapped in code today: claim_daily_challenge(s) pays the full snapshot with no daily or monthly ceiling. Dan has not ruled.'),
    ('trivia_tournaments', NULL, 'Uncapped in code today. The prize ceiling is 500,000 per award in trivia_diamond_award_limits.'),
    ('referrals',          NULL, 'Uncapped in code today and outside the award_diamonds_v2 daily and monthly caps. Dan has not ruled on capping referrals.'),
    ('share_streak',       NULL, 'Uncapped in code today; fn_award_share_streak_diamonds bypasses the v2 family cap.'),
    ('memory_game',        NULL, 'Uncapped per day in code today; bounded only by one completion per (user, challenge).'),
    ('signup',             NULL, 'One grant per auth user. No daily cap applies.'),
    ('union_grant',        NULL, 'Uncapped per day in code today; 100,000 per call is the only ceiling.'),
    ('legacy_credit',      NULL, 'The legacy blind credit functions enforce nothing.'),
    ('other',              NULL, 'Unattributed rows. A non-zero total here is itself the finding.')
ON CONFLICT (engine) DO NOTHING;

-- Foundation created ca_diamond_house with a single row id = 1; make certain
-- of it before enter_trivia_tournament_v2 starts crediting it.
INSERT INTO public.ca_diamond_house (id, balance) VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 9. award_diamonds_v2: the lost-update fix, plus the issuance class.
--
--    The profile row is read without a lock and written back as an absolute
--    value, so a concurrent writer between the read and the write is silently
--    overwritten (lane 3 section 5.2). Two edits, each asserted to match
--    exactly once against the LIVE body, and the whole 25,090 character
--    function is otherwise carried through unchanged: the patch is applied to
--    pg_get_functiondef() AT APPLY TIME rather than to a hand copied body, so
--    no other character can move, and the md5 guard aborts if the live body is
--    not the one this migration was written against.
--
--      edit 1: the profile SELECT takes FOR UPDATE.
--      edit 2: the journal INSERT names its counterparty and issuance class.
--
--    Lock order is unchanged in substance: this function already serialises
--    platform wide on the diamond_platform_budget period row, and that lock is
--    taken AFTER the profile read, so profile then budget remains the only
--    ordering and no new deadlock edge is introduced.
-- ---------------------------------------------------------------------------

DO $patch$
DECLARE
    v_oid      oid;
    v_old_def  text;
    v_new_def  text;
    v_old_a    text := E'      FROM public.profiles\n     WHERE id = p_user_id;';
    v_new_a    text := E'      FROM public.profiles\n     WHERE id = p_user_id\n       FOR UPDATE;';
    v_old_b    text;
    v_new_b    text;
    v_expected integer;
BEGIN
    v_old_b :=
        E'    INSERT INTO public.diamond_transactions (\n'
     || E'        user_id, amount, transaction_type, type, description,\n'
     || E'        balance_after, reference_id, metadata, created_at\n'
     || E'    ) VALUES (\n'
     || E'        p_user_id,\n'
     || E'        v_award,\n'
     || E'        p_action_key,\n'
     || E'        p_action_key,\n'
     || E'        format(''Diamond Rewards v2: %s%s'', p_action_key,\n'
     || E'               CASE WHEN v_capped THEN '' (capped)'' ELSE '''' END),\n'
     || E'        v_new_balance,\n'
     || E'        CASE WHEN v_reference_id = '''' THEN NULL ELSE v_reference_id END,\n'
     || E'        v_metadata,\n'
     || E'        v_now\n'
     || E'    );';

    v_new_b :=
        E'    INSERT INTO public.diamond_transactions (\n'
     || E'        user_id, amount, transaction_type, type, description,\n'
     || E'        balance_after, reference_id, metadata, created_at,\n'
     || E'        counterparty, issuance_class\n'
     || E'    ) VALUES (\n'
     || E'        p_user_id,\n'
     || E'        v_award,\n'
     || E'        p_action_key,\n'
     || E'        p_action_key,\n'
     || E'        format(''Diamond Rewards v2: %s%s'', p_action_key,\n'
     || E'               CASE WHEN v_capped THEN '' (capped)'' ELSE '''' END),\n'
     || E'        v_new_balance,\n'
     || E'        CASE WHEN v_reference_id = '''' THEN NULL ELSE v_reference_id END,\n'
     || E'        v_metadata,\n'
     || E'        v_now,\n'
     || E'        ''promo_budget:catalog_v2'',\n'
     || E'        ''promotional''\n'
     || E'    );';

    SELECT p.oid INTO v_oid
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'public'
       AND p.proname = 'award_diamonds_v2'
       AND pg_get_function_identity_arguments(p.oid)
           = 'p_user_id uuid, p_action_key text, p_reference_id text, p_target_id text, p_metadata jsonb';

    IF v_oid IS NULL THEN
        RAISE EXCEPTION 'Lane E: award_diamonds_v2(uuid,text,text,text,jsonb) not found';
    END IF;

    IF (SELECT md5(prosrc) FROM pg_proc WHERE oid = v_oid) <> '902c18015fd648bc50ca75525340c8e7' THEN
        RAISE EXCEPTION 'Lane E: award_diamonds_v2 body changed since this migration was written (expected md5 902c18015fd648bc50ca75525340c8e7). Re-read the live body before patching.';
    END IF;

    v_old_def := pg_get_functiondef(v_oid);

    -- Each target must occur exactly once, or the patch is not surgical.
    IF (length(v_old_def) - length(replace(v_old_def, v_old_a, ''))) / length(v_old_a) <> 1 THEN
        RAISE EXCEPTION 'Lane E: the profile read fragment does not occur exactly once in award_diamonds_v2';
    END IF;
    IF (length(v_old_def) - length(replace(v_old_def, v_old_b, ''))) / length(v_old_b) <> 1 THEN
        RAISE EXCEPTION 'Lane E: the journal insert fragment does not occur exactly once in award_diamonds_v2';
    END IF;

    v_new_def := replace(replace(v_old_def, v_old_a, v_new_a), v_old_b, v_new_b);

    -- The only characters that may differ are the ones the two edits add.
    v_expected := length(v_old_def)
                + (length(v_new_a) - length(v_old_a))
                + (length(v_new_b) - length(v_old_b));
    IF length(v_new_def) <> v_expected THEN
        RAISE EXCEPTION 'Lane E: the award_diamonds_v2 patch moved % characters, expected %',
            length(v_new_def) - length(v_old_def), v_expected - length(v_old_def);
    END IF;

    EXECUTE v_new_def;
END;
$patch$;

-- ---------------------------------------------------------------------------
-- 10. enter_trivia_tournament_v2: the entry fee cut is banked, not burned.
--
--     v_net := v_fee - floor(v_fee * 0.10) has always kept a slice of every
--     entry fee out of the prize pool and credited it to nothing: three
--     completed events collected 5,200 in fees, pooled 4,984, and 216
--     diamonds left the players and reached no account at all (lane 3, 4.2).
--     The cut now lands in ca_diamond_house with a ledger row (DR14).
--
--     Nothing else changes: the same VIP gate, the same fee, the same net to
--     the pool, the same references, the same return shape. The rate stays
--     floor(10 percent); whether it should be 10 percent rounded is Dan's
--     decision 8 in the standard and is NOT changed here.
--
--     This function is service_role only and has 0 calls in the last 30 days
--     (0 trivia_tourn_entry_% rows exist in the journal all time), so the
--     change cannot disturb live play.
-- ---------------------------------------------------------------------------

DO $guard$
BEGIN
    IF (SELECT md5(p.prosrc)
          FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'public' AND p.proname = 'enter_trivia_tournament_v2')
       IS DISTINCT FROM 'ae3917ca8ce919a41f448f224ac53dab' THEN
        RAISE EXCEPTION 'Lane E: enter_trivia_tournament_v2 body changed since this migration was written (expected md5 ae3917ca8ce919a41f448f224ac53dab)';
    END IF;
END;
$guard$;

CREATE OR REPLACE FUNCTION public.enter_trivia_tournament_v2(p_tournament_id uuid, p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
    v_t public.trivia_tournaments%ROWTYPE;
    v_profile public.profiles%ROWTYPE;
    v_fee int;
    v_net int;
    v_cut int;
    v_house_after numeric(20,0);
    v_count int;
    v_charge jsonb;
    v_entry public.trivia_tournament_entries%ROWTYPE;
BEGIN
    IF (SELECT auth.role()) <> 'service_role' THEN RAISE EXCEPTION 'service_role required'; END IF;
    SELECT * INTO v_t FROM public.trivia_tournaments WHERE id=p_tournament_id FOR UPDATE;
    IF NOT FOUND THEN RETURN jsonb_build_object('success',false,'error','tournament_not_found'); END IF;
    IF v_t.status NOT IN ('upcoming','registration','active')
       OR (v_t.status='active' AND COALESCE(v_t.current_round,0)>=1) THEN
        RETURN jsonb_build_object('success',false,'error','registration_closed');
    END IF;
    IF EXISTS (SELECT 1 FROM public.trivia_tournament_entries
                WHERE tournament_id=p_tournament_id AND user_id=p_user_id) THEN
        RETURN jsonb_build_object('success',false,'error','already_entered','duplicate',true);
    END IF;
    SELECT count(*)::int INTO v_count FROM public.trivia_tournament_entries
     WHERE tournament_id=p_tournament_id;
    IF v_t.max_players IS NOT NULL AND v_count >= v_t.max_players THEN
        RETURN jsonb_build_object('success',false,'error','tournament_full');
    END IF;
    SELECT * INTO v_profile FROM public.profiles WHERE id=p_user_id FOR UPDATE;
    IF NOT FOUND THEN RETURN jsonb_build_object('success',false,'error','profile_not_found'); END IF;
    IF NOT (COALESCE(v_profile.is_vip,false)
            AND (v_profile.vip_tier='lifetime' OR v_profile.vip_expires_at>now())) THEN
        RETURN jsonb_build_object('success',false,'error','vip_required');
    END IF;
    v_fee := GREATEST(COALESCE(v_t.entry_fee,0),0);
    v_net := v_fee - floor(v_fee*0.10)::int;
    IF v_fee > 0 THEN
        SELECT public.add_diamonds_to_balance(
            p_user_id,-v_fee,'tournament_entry',
            'Tournament entry - '||v_t.name,
            'trivia_tourn_entry_'||p_tournament_id::text||'_'||p_user_id::text
        ) INTO v_charge;
        IF COALESCE((v_charge->>'success')::boolean,false) IS NOT TRUE THEN
            RETURN jsonb_build_object('success',false,'error',
                COALESCE(v_charge->>'error','insufficient_diamonds'));
        END IF;
    END IF;
    INSERT INTO public.trivia_tournament_entries(tournament_id,user_id,score,created_at)
    VALUES(p_tournament_id,p_user_id,0,now()) RETURNING * INTO v_entry;
    UPDATE public.trivia_tournaments
       SET prize_pool=COALESCE(prize_pool,0)+v_net
     WHERE id=p_tournament_id
     RETURNING prize_pool INTO v_t.prize_pool;
    -- DR14: the slice of the fee that does not reach the prize pool reaches
    -- the house, with a ledger row, instead of vanishing.
    v_cut := v_fee - v_net;
    IF v_cut > 0 THEN
        UPDATE public.ca_diamond_house
           SET balance = balance + v_cut, updated_at = now()
         WHERE id = 1
         RETURNING balance INTO v_house_after;
        IF v_house_after IS NULL THEN
            PERFORM public.fn_ca_diamond_incident(
                'DR14:house_account_missing','critical',p_user_id,v_cut,
                'enter_trivia_tournament_v2',
                jsonb_build_object('tournament_id',p_tournament_id,'fee',v_fee,'net',v_net));
        ELSE
            INSERT INTO public.ca_diamond_house_ledger
                (delta, balance_after, reason, reference, user_id, tournament_id)
            VALUES (v_cut, v_house_after, 'trivia_tournament_entry_cut',
                    'trivia_tourn_cut_'||p_tournament_id::text||'_'||p_user_id::text,
                    p_user_id, p_tournament_id);
        END IF;
    END IF;
    v_count := v_count+1;
    RETURN jsonb_build_object('success',true,'entry',to_jsonb(v_entry),
        'new_balance',v_charge->'new_balance','new_prize_pool',v_t.prize_pool,
        'entries_count',v_count);
END;
$function$;

REVOKE ALL ON FUNCTION public.enter_trivia_tournament_v2(uuid, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enter_trivia_tournament_v2(uuid, uuid) TO service_role;

-- ---------------------------------------------------------------------------
-- 11. Grants and RLS. New tables are service_role only (brief rule 8).
-- ---------------------------------------------------------------------------

ALTER TABLE public.diamond_engine_daily_caps            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diamond_user_daily_awards            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ca_diamond_house_ledger              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diamond_reward_catalog_history       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_challenge_catalog_history      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trivia_diamond_award_limits_history  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.diamond_engine_daily_caps           FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.diamond_user_daily_awards           FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.ca_diamond_house_ledger             FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.diamond_reward_catalog_history      FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.daily_challenge_catalog_history     FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.trivia_diamond_award_limits_history FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.diamond_engine_daily_caps           TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.diamond_user_daily_awards           TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.ca_diamond_house_ledger             TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.diamond_reward_catalog_history      TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.daily_challenge_catalog_history     TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.trivia_diamond_award_limits_history TO service_role;

-- ---------------------------------------------------------------------------
-- 12. Post apply assertions. The migration aborts on its own violated
--     assumptions rather than reporting a success it did not achieve.
-- ---------------------------------------------------------------------------

DO $assert$
DECLARE
    v_n integer;
BEGIN
    SELECT count(*) INTO v_n
      FROM public.diamond_reward_budgets
     WHERE period IN (
            to_char((now() AT TIME ZONE 'America/Chicago'), 'YYYY-MM'),
            to_char(((now() AT TIME ZONE 'America/Chicago') + interval '1 month'), 'YYYY-MM'));
    IF v_n <> 22 THEN
        RAISE EXCEPTION 'Lane E assert: expected 22 budget lines for the current and next period, found %', v_n;
    END IF;

    SELECT count(*) INTO v_n FROM public.diamond_engine_daily_caps;
    IF v_n <> 11 THEN
        RAISE EXCEPTION 'Lane E assert: expected 11 daily cap rows, found %', v_n;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger
                    WHERE tgrelid = 'public.diamond_transactions'::regclass
                      AND tgname = 'trg_ca_diamond_earn_ledger') THEN
        RAISE EXCEPTION 'Lane E assert: trg_ca_diamond_earn_ledger missing on diamond_transactions';
    END IF;

    SELECT count(*) INTO v_n FROM pg_trigger
     WHERE tgname IN ('trg_ca_diamond_reward_catalog_history',
                      'trg_ca_daily_challenge_catalog_history',
                      'trg_ca_trivia_diamond_award_limits_history');
    IF v_n <> 3 THEN
        RAISE EXCEPTION 'Lane E assert: expected 3 catalog history triggers, found %', v_n;
    END IF;

    SELECT count(*) INTO v_n FROM information_schema.tables
     WHERE table_schema = 'public'
       AND table_name IN ('diamond_reward_catalog_history',
                          'daily_challenge_catalog_history',
                          'trivia_diamond_award_limits_history',
                          'diamond_user_daily_awards',
                          'diamond_engine_daily_caps',
                          'ca_diamond_house_ledger');
    IF v_n <> 6 THEN
        RAISE EXCEPTION 'Lane E assert: expected 6 new tables, found %', v_n;
    END IF;

    -- The lost update fix landed on the profile read: award_diamonds_v2 now
    -- holds two FOR UPDATE locks, the profile and the budget period row,
    -- where it held one.
    SELECT (length(p.prosrc) - length(replace(p.prosrc, 'FOR UPDATE', ''))) / length('FOR UPDATE')
      INTO v_n
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'public' AND p.proname = 'award_diamonds_v2';
    IF v_n <> 2 THEN
        RAISE EXCEPTION 'Lane E assert: award_diamonds_v2 should hold 2 FOR UPDATE clauses, found %', v_n;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'public' AND p.proname = 'award_diamonds_v2'
           AND p.prosrc LIKE '%promo_budget:catalog_v2%'
           AND p.prosrc LIKE '%issuance_class%') THEN
        RAISE EXCEPTION 'Lane E assert: award_diamonds_v2 does not stamp counterparty and issuance_class';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'public' AND p.proname = 'enter_trivia_tournament_v2'
           AND p.prosrc LIKE '%ca_diamond_house%') THEN
        RAISE EXCEPTION 'Lane E assert: enter_trivia_tournament_v2 does not credit ca_diamond_house';
    END IF;

    -- The attribution function agrees with the shapes lane 3 documented.
    IF public.fn_ca_diamond_engine_of('easter_egg','easter_egg',NULL,'Diamond Rewards v2: easter_egg','easter_egg_x_y') <> 'catalog_v2'
       OR public.fn_ca_diamond_engine_of('credit','union_grant','union','Union grant',NULL) <> 'union_grant'
       OR public.fn_ca_diamond_engine_of('daily_challenge_claim',NULL,NULL,NULL,'challenge_claim:1:diamonds') <> 'daily_challenges'
       OR public.fn_ca_diamond_engine_of('bonus',NULL,'complete_daily_challenge',NULL,NULL) <> 'memory_game'
       OR public.fn_ca_diamond_engine_of('mystery',NULL,NULL,NULL,NULL) <> 'other' THEN
        RAISE EXCEPTION 'Lane E assert: fn_ca_diamond_engine_of does not map the documented shapes';
    END IF;
END;
$assert$;

COMMIT;
