-- ═══════════════════════════════════════════════════════════════════════════════
-- MIDWAY UNION REALISTIC WEEKLY TOURNAMENT SCHEDULE (WHOLE DOLLARS)
-- ═══════════════════════════════════════════════════════════════════════════════

-- Clear the old schedules for Midway Union (fade0000-0000-0000-0000-000000000001)
DELETE FROM public.tournament_schedules WHERE club_id = 'fade0000-0000-0000-0000-000000000001';

INSERT INTO public.tournament_schedules
  (union_id, club_id, name, description, active, days_of_week, start_times_utc, interval_minutes, config)
SELECT
  k.mid, k.mid, v.name, v.descr, true, v.dow, v.times, v.intv, v.cfg::jsonb
FROM (
  VALUES
  ('$100 Freeroll • 12:00 AM', 'Monday Grind', '{0,1,2,3,4,5,6}'::int[], '{05:00}'::text[], NULL::int, '{"name": "$100 Freeroll \u2022 12:00 AM", "type": "mtt", "gameVariant": "nlh", "buyIn": 0, "guaranteedPrize": 100, "startingStack": 5000, "maxPlayers": 500, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 6, "tableSize": 9, "shortDescription": "Free Entry \u2022 $1 Rebuy / $0.90 To Pool \u2022 $1 Add-On / $0.90 To Pool", "bigBlindAnte": true, "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 6, "addOnAvailable": true, "addOnLevels": 6, "addonBreakMinutes": 3}'),
  ('Monday Graveyard PLO', 'Monday Grind', '{1}'::int[], '{07:30}'::text[], NULL::int, '{"name": "Monday Graveyard PLO", "type": "mtt", "gameVariant": "plo4", "buyIn": 5, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('$100 Freeroll • 6:00 AM', 'Monday Grind', '{0,1,2,3,4,5,6}'::int[], '{11:00}'::text[], NULL::int, '{"name": "$100 Freeroll \u2022 6:00 AM", "type": "mtt", "gameVariant": "nlh", "buyIn": 0, "guaranteedPrize": 100, "startingStack": 5000, "maxPlayers": 500, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 6, "tableSize": 9, "shortDescription": "Free Entry \u2022 $1 Rebuy / $0.90 To Pool \u2022 $1 Add-On / $0.90 To Pool", "bigBlindAnte": true, "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 6, "addOnAvailable": true, "addOnLevels": 6, "addonBreakMinutes": 3}'),
  ('Morning Grind Deepstack', 'Monday Grind', '{1}'::int[], '{14:00}'::text[], NULL::int, '{"name": "Morning Grind Deepstack", "type": "mtt", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 200, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('$100 Freeroll • 12:00 PM', 'Monday Grind', '{0,1,2,3,4,5,6}'::int[], '{17:00}'::text[], NULL::int, '{"name": "$100 Freeroll \u2022 12:00 PM", "type": "mtt", "gameVariant": "nlh", "buyIn": 0, "guaranteedPrize": 100, "startingStack": 5000, "maxPlayers": 500, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 6, "tableSize": 9, "shortDescription": "Free Entry \u2022 $1 Rebuy / $0.90 To Pool \u2022 $1 Add-On / $0.90 To Pool", "bigBlindAnte": true, "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 6, "addOnAvailable": true, "addOnLevels": 6, "addonBreakMinutes": 3}'),
  ('Monday Rebuy Rush', 'Monday Grind', '{1}'::int[], '{20:00}'::text[], NULL::int, '{"name": "Monday Rebuy Rush", "type": "mtt", "gameVariant": "nlh", "buyIn": 5, "guaranteedPrize": 250, "startingStack": 10000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 7, "addOnAvailable": true, "addOnLevels": 7, "addonBreakMinutes": 3}'),
  ('$100 Freeroll • 6:00 PM', 'Monday Grind', '{0,1,2,3,4,5,6}'::int[], '{23:00}'::text[], NULL::int, '{"name": "$100 Freeroll \u2022 6:00 PM", "type": "mtt", "gameVariant": "nlh", "buyIn": 0, "guaranteedPrize": 100, "startingStack": 5000, "maxPlayers": 500, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 6, "tableSize": 9, "shortDescription": "Free Entry \u2022 $1 Rebuy / $0.90 To Pool \u2022 $1 Add-On / $0.90 To Pool", "bigBlindAnte": true, "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 6, "addOnAvailable": true, "addOnLevels": 6, "addonBreakMinutes": 3}'),
  ('Monday Night Turbo', 'Monday Grind', '{1}'::int[], '{00:00}'::text[], NULL::int, '{"name": "Monday Night Turbo", "type": "mtt", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 250, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Five-Card Big Stack', 'Monday Grind', '{1}'::int[], '{01:00}'::text[], NULL::int, '{"name": "Five-Card Big Stack", "type": "mtt", "gameVariant": "plo5", "buyIn": 10, "guaranteedPrize": 300, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Monday Knockout', 'Monday Grind', '{1}'::int[], '{02:00}'::text[], NULL::int, '{"name": "Monday Knockout", "type": "progressive_bounty", "gameVariant": "nlh", "buyIn": 15, "guaranteedPrize": 600, "startingStack": 22000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 6.75}'),
  ('Monday Mystery', 'Monday Grind', '{1}'::int[], '{03:00}'::text[], NULL::int, '{"name": "Monday Mystery", "type": "mystery_bounty", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 400, "startingStack": 25000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 3.6, "mysteryBountyMin": 1, "mysteryBountyMax": 10}'),
  ('Six-Card Late Night', 'Monday Grind', '{1}'::int[], '{04:00}'::text[], NULL::int, '{"name": "Six-Card Late Night", "type": "mtt", "gameVariant": "plo6", "buyIn": 10, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('Turbo Tuesday Graveyard', 'Turbo Tuesday', '{2}'::int[], '{07:30}'::text[], NULL::int, '{"name": "Turbo Tuesday Graveyard", "type": "mtt", "gameVariant": "nlh", "buyIn": 1, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "No Guarantee", "bigBlindAnte": true}'),
  ('Breakfast Turbo', 'Turbo Tuesday', '{2}'::int[], '{14:00}'::text[], NULL::int, '{"name": "Breakfast Turbo", "type": "mtt", "gameVariant": "nlh", "buyIn": 5, "guaranteedPrize": 150, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Afternoon PLO Turbo', 'Turbo Tuesday', '{2}'::int[], '{20:00}'::text[], NULL::int, '{"name": "Afternoon PLO Turbo", "type": "mtt", "gameVariant": "plo4", "buyIn": 5, "guaranteedPrize": 150, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Turbo Tuesday Opener', 'Turbo Tuesday', '{2}'::int[], '{00:00}'::text[], NULL::int, '{"name": "Turbo Tuesday Opener", "type": "mtt", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 250, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('PLO8 Hi-Lo Turbo', 'Turbo Tuesday', '{2}'::int[], '{01:00}'::text[], NULL::int, '{"name": "PLO8 Hi-Lo Turbo", "type": "mtt", "gameVariant": "plo8", "buyIn": 10, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('Tuesday Bounty Hunt', 'Turbo Tuesday', '{2}'::int[], '{02:00}'::text[], NULL::int, '{"name": "Tuesday Bounty Hunt", "type": "bounty", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 400, "startingStack": 18000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 8, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 2.25}'),
  ('Turbo Tuesday PKO', 'Turbo Tuesday', '{2}'::int[], '{03:00}'::text[], NULL::int, '{"name": "Turbo Tuesday PKO", "type": "progressive_bounty", "gameVariant": "nlh", "buyIn": 15, "guaranteedPrize": 600, "startingStack": 22000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 6.75}'),
  ('Five-Card Nightcap', 'Turbo Tuesday', '{2}'::int[], '{04:00}'::text[], NULL::int, '{"name": "Five-Card Nightcap", "type": "mtt", "gameVariant": "plo5", "buyIn": 10, "guaranteedPrize": 200, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Midweek Five-Card Graveyard', 'Midweek Mix', '{3}'::int[], '{07:30}'::text[], NULL::int, '{"name": "Midweek Five-Card Graveyard", "type": "mtt", "gameVariant": "plo5", "buyIn": 5, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('Midweek Morning Stack', 'Midweek Mix', '{3}'::int[], '{14:00}'::text[], NULL::int, '{"name": "Midweek Morning Stack", "type": "mtt", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 200, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Wednesday Reload', 'Midweek Mix', '{3}'::int[], '{20:00}'::text[], NULL::int, '{"name": "Wednesday Reload", "type": "mtt", "gameVariant": "nlh", "buyIn": 5, "guaranteedPrize": 250, "startingStack": 10000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 7, "addOnAvailable": true, "addOnLevels": 7, "addonBreakMinutes": 3}'),
  ('Wednesday PLO Stack', 'Midweek Mix', '{3}'::int[], '{00:00}'::text[], NULL::int, '{"name": "Wednesday PLO Stack", "type": "mtt", "gameVariant": "plo4", "buyIn": 10, "guaranteedPrize": 300, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Midweek Bounty', 'Midweek Mix', '{3}'::int[], '{01:00}'::text[], NULL::int, '{"name": "Midweek Bounty", "type": "bounty", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 350, "startingStack": 18000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 8, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 2.25}'),
  ('Wednesday Feature', 'Midweek Mix', '{3}'::int[], '{02:00}'::text[], NULL::int, '{"name": "Wednesday Feature", "type": "mtt", "gameVariant": "nlh", "buyIn": 25, "guaranteedPrize": 750, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Midweek Mystery', 'Midweek Mix', '{3}'::int[], '{03:00}'::text[], NULL::int, '{"name": "Midweek Mystery", "type": "mystery_bounty", "gameVariant": "nlh", "buyIn": 15, "guaranteedPrize": 600, "startingStack": 25000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 5.4, "mysteryBountyMin": 1, "mysteryBountyMax": 10}'),
  ('Six-Card Deep Night', 'Midweek Mix', '{3}'::int[], '{04:00}'::text[], NULL::int, '{"name": "Six-Card Deep Night", "type": "mtt", "gameVariant": "plo6", "buyIn": 10, "guaranteedPrize": 0, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('Omaha Thursday Graveyard', 'Omaha Thursday', '{4}'::int[], '{07:30}'::text[], NULL::int, '{"name": "Omaha Thursday Graveyard", "type": "mtt", "gameVariant": "plo4", "buyIn": 5, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('PLO8 Morning Stack', 'Omaha Thursday', '{4}'::int[], '{14:00}'::text[], NULL::int, '{"name": "PLO8 Morning Stack", "type": "mtt", "gameVariant": "plo8", "buyIn": 10, "guaranteedPrize": 150, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Five-Card Reload', 'Omaha Thursday', '{4}'::int[], '{20:00}'::text[], NULL::int, '{"name": "Five-Card Reload", "type": "mtt", "gameVariant": "plo5", "buyIn": 10, "guaranteedPrize": 250, "startingStack": 10000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee", "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 7, "addOnAvailable": true, "addOnLevels": 7, "addonBreakMinutes": 3}'),
  ('Omaha Thursday Opener', 'Omaha Thursday', '{4}'::int[], '{00:00}'::text[], NULL::int, '{"name": "Omaha Thursday Opener", "type": "mtt", "gameVariant": "plo4", "buyIn": 10, "guaranteedPrize": 300, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Five-Card Bounty', 'Omaha Thursday', '{4}'::int[], '{01:00}'::text[], NULL::int, '{"name": "Five-Card Bounty", "type": "bounty", "gameVariant": "plo5", "buyIn": 15, "guaranteedPrize": 500, "startingStack": 18000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "FIVE", "lateRegistrationLevels": 8, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee", "bountyAmount": 3.375}'),
  ('Six-Card Feature', 'Omaha Thursday', '{4}'::int[], '{02:00}'::text[], NULL::int, '{"name": "Six-Card Feature", "type": "mtt", "gameVariant": "plo6", "buyIn": 25, "guaranteedPrize": 600, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Thursday Night PKO', 'Omaha Thursday', '{4}'::int[], '{03:00}'::text[], NULL::int, '{"name": "Thursday Night PKO", "type": "progressive_bounty", "gameVariant": "nlh", "buyIn": 15, "guaranteedPrize": 600, "startingStack": 22000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 6.75}'),
  ('PLO8 Hi-Lo Nightcap', 'Omaha Thursday', '{4,6}'::int[], '{04:00}'::text[], NULL::int, '{"name": "PLO8 Hi-Lo Nightcap", "type": "mtt", "gameVariant": "plo8", "buyIn": 10, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('Friday Graveyard', 'Friday Fight Night', '{5}'::int[], '{07:30}'::text[], NULL::int, '{"name": "Friday Graveyard", "type": "mtt", "gameVariant": "nlh", "buyIn": 5, "guaranteedPrize": 100, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Friday Morning PLO', 'Friday Fight Night', '{5}'::int[], '{14:00}'::text[], NULL::int, '{"name": "Friday Morning PLO", "type": "mtt", "gameVariant": "plo4", "buyIn": 10, "guaranteedPrize": 200, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Friday Rebuy Rush', 'Friday Fight Night', '{5}'::int[], '{20:00}'::text[], NULL::int, '{"name": "Friday Rebuy Rush", "type": "mtt", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 400, "startingStack": 10000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "isRebuy": true, "maxRebuys": 99, "rebuyLevels": 7, "addOnAvailable": true, "addOnLevels": 7, "addonBreakMinutes": 3}'),
  ('Friday Fight Night Opener', 'Friday Fight Night', '{5}'::int[], '{00:00}'::text[], NULL::int, '{"name": "Friday Fight Night Opener", "type": "mtt", "gameVariant": "nlh", "buyIn": 15, "guaranteedPrize": 600, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Friday Five-Card Bounty', 'Friday Fight Night', '{5}'::int[], '{01:00}'::text[], NULL::int, '{"name": "Friday Five-Card Bounty", "type": "bounty", "gameVariant": "plo5", "buyIn": 15, "guaranteedPrize": 500, "startingStack": 18000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "FIVE", "lateRegistrationLevels": 8, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee", "bountyAmount": 3.375}'),
  ('Friday Night Feature', 'Friday Fight Night', '{5}'::int[], '{02:00}'::text[], NULL::int, '{"name": "Friday Night Feature", "type": "mtt", "gameVariant": "nlh", "buyIn": 40, "guaranteedPrize": 1500, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Friday Fight Night PKO', 'Friday Fight Night', '{5}'::int[], '{03:00}'::text[], NULL::int, '{"name": "Friday Fight Night PKO", "type": "progressive_bounty", "gameVariant": "nlh", "buyIn": 25, "guaranteedPrize": 1000, "startingStack": 22000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 11.25}'),
  ('Friday Six-Card Nightcap', 'Friday Fight Night', '{5}'::int[], '{04:00}'::text[], NULL::int, '{"name": "Friday Six-Card Nightcap", "type": "mtt", "gameVariant": "plo6", "buyIn": 10, "guaranteedPrize": 0, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "No Guarantee"}'),
  ('Saturday Graveyard PLO', 'Saturday Stackfest', '{6}'::int[], '{07:30}'::text[], NULL::int, '{"name": "Saturday Graveyard PLO", "type": "mtt", "gameVariant": "plo4", "buyIn": 10, "guaranteedPrize": 100, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "FIVE", "lateRegistrationLevels": 7, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Saturday Morning Stack', 'Saturday Stackfest', '{6}'::int[], '{14:00}'::text[], NULL::int, '{"name": "Saturday Morning Stack", "type": "mtt", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 300, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Saturday Five-Card Stack', 'Saturday Stackfest', '{6}'::int[], '{20:00}'::text[], NULL::int, '{"name": "Saturday Five-Card Stack", "type": "mtt", "gameVariant": "plo5", "buyIn": 15, "guaranteedPrize": 500, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Saturday Stackfest Opener', 'Saturday Stackfest', '{6}'::int[], '{00:00}'::text[], NULL::int, '{"name": "Saturday Stackfest Opener", "type": "mtt", "gameVariant": "nlh", "buyIn": 25, "guaranteedPrize": 800, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Saturday Mystery', 'Saturday Stackfest', '{6}'::int[], '{01:00}'::text[], NULL::int, '{"name": "Saturday Mystery", "type": "mystery_bounty", "gameVariant": "nlh", "buyIn": 25, "guaranteedPrize": 1000, "startingStack": 25000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 9.0, "mysteryBountyMin": 1, "mysteryBountyMax": 10}'),
  ('Saturday Night Big Stack', 'Saturday Stackfest', '{6}'::int[], '{02:00}'::text[], NULL::int, '{"name": "Saturday Night Big Stack", "type": "mtt", "gameVariant": "nlh", "buyIn": 40, "guaranteedPrize": 2000, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Saturday Stackfest PKO', 'Saturday Stackfest', '{6}'::int[], '{03:00}'::text[], NULL::int, '{"name": "Saturday Stackfest PKO", "type": "progressive_bounty", "gameVariant": "nlh", "buyIn": 40, "guaranteedPrize": 1500, "startingStack": 22000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 18.0}'),
  ('Sunday Funday Graveyard', 'Sunday Funday', '{0}'::int[], '{07:30}'::text[], NULL::int, '{"name": "Sunday Funday Graveyard", "type": "mtt", "gameVariant": "nlh", "buyIn": 10, "guaranteedPrize": 150, "startingStack": 12000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "TURBO", "payoutPreset": "NINE", "lateRegistrationLevels": 7, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Sunday Morning PLO', 'Sunday Funday', '{0}'::int[], '{14:00}'::text[], NULL::int, '{"name": "Sunday Morning PLO", "type": "mtt", "gameVariant": "plo4", "buyIn": 15, "guaranteedPrize": 400, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Sunday Funday PLO5 Big Stack', 'Sunday Funday', '{0}'::int[], '{20:00}'::text[], NULL::int, '{"name": "Sunday Funday PLO5 Big Stack", "type": "mtt", "gameVariant": "plo5", "buyIn": 40, "guaranteedPrize": 1200, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}'),
  ('Sunday Funday Warm-Up', 'Sunday Funday', '{0}'::int[], '{00:00}'::text[], NULL::int, '{"name": "Sunday Funday Warm-Up", "type": "mtt", "gameVariant": "nlh", "buyIn": 40, "guaranteedPrize": 1500, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Sunday Funday Mystery', 'Sunday Funday', '{0}'::int[], '{01:00}'::text[], NULL::int, '{"name": "Sunday Funday Mystery", "type": "mystery_bounty", "gameVariant": "nlh", "buyIn": 50, "guaranteedPrize": 2500, "startingStack": 25000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 18.0, "mysteryBountyMin": 1, "mysteryBountyMax": 10}'),
  ('Sunday Funday Main Event', 'Sunday Funday', '{0}'::int[], '{02:00}'::text[], NULL::int, '{"name": "Sunday Funday Main Event", "type": "mtt", "gameVariant": "nlh", "buyIn": 100, "guaranteedPrize": 5000, "startingStack": 40000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "NINE", "lateRegistrationLevels": 10, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true}'),
  ('Sunday Funday High Roller PKO', 'Sunday Funday', '{0}'::int[], '{03:00}'::text[], NULL::int, '{"name": "Sunday Funday High Roller PKO", "type": "progressive_bounty", "gameVariant": "nlh", "buyIn": 75, "guaranteedPrize": 3500, "startingStack": 22000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "STANDARD", "payoutPreset": "NINE", "lateRegistrationLevels": 9, "tableSize": 9, "shortDescription": "Liquidity-Sized Guarantee", "bigBlindAnte": true, "bountyAmount": 33.75}'),
  ('Sunday Funday Six-Card Closer', 'Sunday Funday', '{0}'::int[], '{04:00}'::text[], NULL::int, '{"name": "Sunday Funday Six-Card Closer", "type": "mtt", "gameVariant": "plo6", "buyIn": 40, "guaranteedPrize": 1200, "startingStack": 30000, "maxPlayers": 300, "minPlayers": 4, "blindPreset": "SLOW", "payoutPreset": "FIVE", "lateRegistrationLevels": 9, "tableSize": 6, "shortDescription": "Liquidity-Sized Guarantee"}')
) AS v(name, descr, dow, times, intv, cfg)
CROSS JOIN (SELECT 'fade0000-0000-0000-0000-000000000001'::uuid AS mid) k;

DO $$
DECLARE
  n integer;
BEGIN
  SELECT count(*) INTO n
  FROM public.tournament_schedules
  WHERE club_id = 'fade0000-0000-0000-0000-000000000001' AND active;
  IF n < 59 THEN
    RAISE EXCEPTION 'midway weekly schedule seed incomplete: only % active rows', n;
  END IF;
END $$;
