-- Applied to production 2026-08-27 as `the_deal_is_provably_fair`.
--
-- Code review says the shuffle is right: secureShuffle is textbook Fisher-Yates
-- over secureRandomInt, which uses rejection sampling to eliminate modulo bias,
-- with node:crypto.randomInt (itself rejection-sampled) as the fallback. No
-- Math.random() exists in any card path.
--
-- Correct code is not a fair deal, though. fn_deal_fairness() measures the real
-- one. Result over 24h, 248,412 flop cards, chi-square vs a uniform deck:
--     nlh 59.3/51df   plo4 45.7/51   plo5 58.5/51   plo6 44.3/51
--     plo8 41.6/51    pineapple 49.3/51            short_deck 33.9/35
-- Every value sits at its degrees of freedom. No bias anywhere.
--
-- THE TRAP, which this audit fell into first. The obvious test - the five board
-- cards from completed boards - reports nlh at 169.7 and looks badly rigged. It
-- is not. Filtering to boards that REACHED THE RIVER selects on the cards: an
-- ace-high flop wins more pots immediately, so those hands end early and never
-- enter the sample. All four aces came out as the most under-represented cards
-- in the deck. That is a feature of poker, measured backwards.
--
-- Two more confounds that also produced false alarms here:
--   * Mixing variants - short_deck plays 36 cards and manufactures a huge
--     deviation when averaged with 52-card games.
--   * tables.game_type is the FORMAT (cash/tournament), not the deck.
--     hand_history.game_variant is the discriminator that matters.
--
-- Hence: FLOP ONLY, segmented by variant. The flop is dealt before any
-- post-flop decision, so reaching it cannot depend on what it is.
