-- ca_phase5_blocked_mint_daily_dedupe (prod 20260831201006). Canonical body lives in prod schema_migrations —
-- replace this marker byte-exact via scripts/dev/export-applied-migrations.sh.
-- Phase 5: tournament-mint-blocked warnings dedupe daily-global (31 per-table incidents for one root cause was notification spam).
