-- =======================================================================================
-- RETIRED - NEVER APPLIED (2026-09-12)
--
-- This file has NEVER run against production. Its version, 20260312002, is
-- also held by 20260312002_tournament_flights.sql, and Supabase keys
-- schema_migrations on the version: of two files sharing one, the second is
-- silently never applied (CLAUDE.md 4.5). `bulk_update_position_stats` is
-- absent from pg_proc and from scripts/ci/supabase-schema-manifest.json.
--
-- Its caller (PlayerPositionStatsService) logged 405 PGRST202 failures between
-- 2026-03-17 and 2026-03-23 and has since been deleted. The April triage in
-- 20260429e_x12_create_increment_union_wallet.sql recorded this RPC as DEFER
-- because "position_stats table doesn't exist" - a check against the wrong
-- name; the table is `player_position_stats` and it is live.
--
-- DO NOT APPLY THIS FILE. Position stats are written by the
-- hand_history_position_stats trigger -> fn_process_hand_position_stats, and
-- repaired by fn_backfill_position_stats(p_from, p_to). Applying this would
-- add a second, unsynchronised writer to the same counters.
--
-- Pinned by tests/a-position-stat-has-a-live-writer.law.test.ts.
-- =======================================================================================

-- =======================================================================================
-- MIGRATION: 20260312002_bulk_update_position_stats.sql
-- DESCRIPTION: RPC to batch-upsert player position stats generated by the TableEngine
--              at the end of a hand. Ensures high-performance O(1) database writes.
-- =======================================================================================

CREATE OR REPLACE FUNCTION public.bulk_update_position_stats(
    payload JSONB
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    item JSONB;
BEGIN
    FOR item IN SELECT * FROM jsonb_array_elements(payload)
    LOOP
        INSERT INTO public.player_position_stats (
            user_id, 
            position, 
            hands_played, 
            vpip_count, 
            pfr_count, 
            three_bet_count, 
            fold_to_three_bet_count,
            hands_won,
            total_profit
        )
        VALUES (
            (item->>'user_id')::UUID,
            item->>'position',
            COALESCE((item->>'hands_played')::INTEGER, 0),
            COALESCE((item->>'vpip_count')::INTEGER, 0),
            COALESCE((item->>'pfr_count')::INTEGER, 0),
            COALESCE((item->>'three_bet_count')::INTEGER, 0),
            COALESCE((item->>'fold_to_three_bet_count')::INTEGER, 0),
            COALESCE((item->>'hands_won')::INTEGER, 0),
            COALESCE((item->>'total_profit')::NUMERIC, 0)
        )
        ON CONFLICT (user_id, position) DO UPDATE
        SET 
            hands_played = player_position_stats.hands_played + EXCLUDED.hands_played,
            vpip_count = player_position_stats.vpip_count + EXCLUDED.vpip_count,
            pfr_count = player_position_stats.pfr_count + EXCLUDED.pfr_count,
            three_bet_count = player_position_stats.three_bet_count + EXCLUDED.three_bet_count,
            fold_to_three_bet_count = player_position_stats.fold_to_three_bet_count + EXCLUDED.fold_to_three_bet_count,
            hands_won = player_position_stats.hands_won + EXCLUDED.hands_won,
            total_profit = player_position_stats.total_profit + EXCLUDED.total_profit,
            updated_at = EXCLUDED.updated_at;
    END LOOP;
END;
$$;
