-- 20260830a_rake_polish_pack.sql
-- APPLIED TO PRODUCTION 2026-08-30 via Supabase MCP as three migrations:
--   bbj_drift_joins_by_hand_not_window
--   attribution_drift_watchdog_db_side_and_dead_column
--   player_rake_stats_rpcs
-- Full bodies in the Supabase migration history; recorded here for the repo.
--
-- POLISH 2 — the BBJ drift alarm stops crying wolf.
--   bbj_drift_since compared two TIME-WINDOWED sums: the received side was
--   filtered to `p_since - 6 hours`, so a slice banked later than that (every
--   back-dated self-heal) joined to NULL and read as money that never
--   arrived. It now joins BY HAND ID with no window on the received side.
--   Noise on a money channel is not harmless — 988 unresolved criticals is
--   how the nine real ones stayed invisible on 2026-08-22.
--   NOTE: the first apply attempt ABORTED on its own assert (9.63 chips
--   outstanding). That was real money — 24 hands whose slices were younger
--   than fn_bbj_repair_unbanked's 5-minute grace. The self-heal banked all 24;
--   the fix then shipped with drift reading 0.00. The assert did its job.
--
-- POLISH 3 — the attribution watchdog gets a second seat.
--   fn_rake_attribution_drift was read only inside the ENGINE's reconcile
--   cycle, sharing a failure domain with the thing it watches.
--   fn_rake_attribution_drift_audit runs the same query DB-side on pg_cron
--   ('rake-attribution-drift-audit-hourly', :47 — offset from the :38
--   invariant audit and :52 rake repair so the guards never contend).
--
-- POLISH 5 — the dead column.
--   bbj_contributions.player_id: NULL on every row ever written, populated by
--   no code path, and a trap for any future reader. Dropped behind a guard
--   that refuses if a single row ever held a value. Per-player BBJ
--   attribution lives in rake_attributions.bbj_attributed_contribution.
--   (Renaming the retired hands/hand_players/hand_actions family is
--   deliberately NOT done here — Dan said "eventually, after a quiet
--   quarter", and renaming live schema a day after it caused an outage is the
--   risk class we were told to avoid. They stay locked and commented.)
--
-- POLISH 1 — the weighted rake data reaches the player.
--   ca_player_rake_stats(p_user, p_days): rake paid, rake per 100 hands, rake
--   in big blinds, raked hands, average per raked hand.
--   ca_player_hand_rake_share(p_hand_id): one hand's rake and the CALLER'S
--   OWN share of it, read from rake_attributions with the canonical allocator
--   as the pre-ledger fallback.
--   Both derive identity from auth.uid() — never from a parameter — and
--   neither exposes another player's contribution.
SELECT 'applied via MCP — see migration history for the three bodies' AS notice;

-- Also applied 2026-08-30 as migration `rake_attributions_is_no_longer_deprecated`:
-- rake_attributions was legitimately on public.deprecated_tables (0 rows, no
-- writer) and is now the AUTHORITATIVE per-player rake ledger. Leaving it
-- listed would send the next reader back to recomputing from
-- player_contributions — the dual-implementation shape that caused the
-- equal-dealt bug. The DB row is deleted and
-- scripts/ci/check-deprecated-tables.mjs (which mirrors that table) is
-- corrected in the same commit. Caught by CI, which is exactly its job.
