-- Applied to production via Supabase MCP on 2026-08-20. Mirrored here as
-- applied (house rule: migrations are a record, not the source of truth).
--
-- fn_admin_update_agent wrote its credit_assignments audit row with
--     assigned_by = COALESCE(p_assigned_by, v_caller)
-- where p_assigned_by is supplied BY THE CALLER (CreditRequestService passes a
-- client-held approverId). The function's AUTHORISATION is sound -- it requires
-- auth.uid() and club owner/co_owner/admin -- but the audit trail recorded
-- whoever the client claimed rather than who actually acted, so an authorised
-- admin could attribute a credit-limit change to a colleague.
--
-- An audit row exists to answer "who did this". It records the authenticated
-- actor now. The parameter stays in the signature so existing callers keep
-- working; it is simply no longer trusted as the actor.
--
-- Every other guard is unchanged and was re-verified after applying:
-- authentication required, club-admin check, status/role/rate validation, and
-- the "credit limit cannot exceed parent agent limit" rule.
--
-- The only behavioural line, in the audit INSERT:
--     VALUES (p_agent_id, v_caller, v_old_limit, p_credit_limit, p_credit_reason);
-- (was COALESCE(p_assigned_by, v_caller) in the second position)
--
-- Full body as applied is recoverable with:
--   select pg_get_functiondef('public.fn_admin_update_agent'::regproc);
