-- APPLIED TO PRODUCTION 2026-08-20 via Supabase MCP execute_sql (NOT
-- apply_migration: CREATE INDEX CONCURRENTLY cannot run inside the migration
-- transaction). Mirror only — recorded here so the index is reproducible.
--
--   CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_agent_commissions_source_lookup
--     ON public.agent_commissions (source_id, source_type, club_id)
--     WHERE source_id IS NOT NULL;
--
-- WHY: credit_agent_commission_from_rake short-circuits on
--   SELECT 1 FROM agent_commissions
--    WHERE source_id = $1 AND source_type = $2 AND club_id = $3 LIMIT 1
-- but the only candidate index was uq_agent_commissions_source
-- (user_id, source_id, source_type) — user_id LEADS and is not in the
-- predicate, so it could not be used. idx_agent_commissions_club_id was the
-- only usable one and club_id has 3 distinct values across 446,143 rows, so
-- every call scanned ~150k rows.
--
-- Profiled over 11 minutes of live settler traffic BEFORE the index:
--   fn_credit_agent_commissions_batch   54 calls  avg 6,461ms  total 348.9s  <- 76% of all settler time
--   fn_rakeback_recompute_periods       14 calls  avg 5,611ms  total  78.6s
--   fn_apply_rakeback_player_stats_batch 46 calls avg   800ms  total  36.8s
--
-- Commissions cost 13ms/item against 1.6ms/item for player stats — the same
-- shape of work, differing only by this lookup. After the index the plan is an
-- Index Only Scan, 5 shared buffers, 0 heap fetches, and the settler went from
-- 7.4x to 10x realtime.
--
-- This also permanently reduces steady-state database load: the same lookup
-- runs for every player of every raked hand, forever.
