-- BACKFILLED 2026-09-27 from supabase_migrations.schema_migrations.statements.
-- Applied to production as 20260417144418 "phase14_home_games_money_ledger"; the .sql file was never committed
-- at the time. Everything below this header is byte-exact to what ran:
-- md5 fbad77d172bfe6678dff109eaa51a0b3 of array_to_string(statements, chr(10)) || chr(10).
-- Do NOT re-apply; it is already live.

-- ══════════════════════════════════════════════════════════════════════
--  PHASE 14: HOME-GAMES MONEY LEDGER
-- ══════════════════════════════════════════════════════════════════════
--
--  "All-in-one home game": the host never leaves the platform to run the
--  night. Phase 14 adds the money-tracking foundation — buyins, rebuys,
--  addons, cashouts, computed settlements, and per-group payment links.
--
--  DESIGN NOTES
--
--  • Amounts stored in INTEGER CENTS, not numeric dollars. Avoids
--    floating-point drift during settlement math. $50.00 → 5000.
--
--  • Chip counts optional (INTEGER). Cash games often skip them; some
--    tournaments track them. When present, the client can show chip-level
--    detail; when absent, only dollars roll up.
--
--  • `commander_home_buyins.kind` is a text column with a CHECK constraint:
--      buyin    — initial buy-in
--      rebuy    — re-buy after busting (tournaments) or reloading (cash)
--      addon    — add-on at break (tournaments)
--      adjustment — manual correction (host typo, chop, etc.)
--
--  • `commander_home_cashouts` is separate from buyins rather than a
--    "cashout" kind on buyins, because it has different semantics:
--    a player can have many buyins but only one cashout per game.
--
--  • `commander_home_settlements` is computed output, not input. Host
--    calls fn_home_compute_settlements(game_id) which replaces all
--    rows for that game with a minimum-transaction settlement plan.
--    Each row then gets marked paid/disputed individually as payment
--    happens IRL.
--
--  • `commander_home_group_payment_links` per group, not per user —
--    it's the HOST's payment handles, so players know where to send.
--    (Per-user payment preferences would be per-user on a profile, not
--    in this table.)
--
--  AUTHORIZATION MODEL (enforced in RPCs, not via RLS)
--
--  • Staff (owner/admin of the group) can write all ledger rows for
--    any game in their group.
--  • Players can read their own ledger rows for games they attended
--    (RSVP is_confirmed=true).
--  • Settlement rows can be marked paid by EITHER the payer or payee
--    — whoever acknowledges first.
-- ══════════════════════════════════════════════════════════════════════

-- ── commander_home_buyins ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS commander_home_buyins (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id      uuid NOT NULL REFERENCES commander_home_games(id) ON DELETE CASCADE,
    user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    kind         text NOT NULL CHECK (kind IN ('buyin','rebuy','addon','adjustment')),
    amount_cents integer NOT NULL,
    chip_count   integer,
    note         text,
    recorded_by  uuid NOT NULL REFERENCES auth.users(id),
    recorded_at  timestamptz NOT NULL DEFAULT NOW(),
    created_at   timestamptz NOT NULL DEFAULT NOW(),
    updated_at   timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT commander_home_buyins_amount_nonneg
        CHECK (kind = 'adjustment' OR amount_cents >= 0)
);

CREATE INDEX IF NOT EXISTS idx_commander_home_buyins_game
    ON commander_home_buyins (game_id);
CREATE INDEX IF NOT EXISTS idx_commander_home_buyins_user
    ON commander_home_buyins (user_id);
CREATE INDEX IF NOT EXISTS idx_commander_home_buyins_game_user
    ON commander_home_buyins (game_id, user_id);

-- ── commander_home_cashouts ──────────────────────────────────────────
-- One row per player per game. Unique(game_id, user_id).
CREATE TABLE IF NOT EXISTS commander_home_cashouts (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id      uuid NOT NULL REFERENCES commander_home_games(id) ON DELETE CASCADE,
    user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    amount_cents integer NOT NULL CHECK (amount_cents >= 0),
    chip_count   integer,
    note         text,
    recorded_by  uuid NOT NULL REFERENCES auth.users(id),
    recorded_at  timestamptz NOT NULL DEFAULT NOW(),
    created_at   timestamptz NOT NULL DEFAULT NOW(),
    updated_at   timestamptz NOT NULL DEFAULT NOW(),
    UNIQUE (game_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_commander_home_cashouts_user
    ON commander_home_cashouts (user_id);

-- ── commander_home_settlements ───────────────────────────────────────
-- Computed rows: who pays whom, how much. Regenerated by the RPC.
CREATE TABLE IF NOT EXISTS commander_home_settlements (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id         uuid NOT NULL REFERENCES commander_home_games(id) ON DELETE CASCADE,
    payer_user_id   uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    payee_user_id   uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    amount_cents    integer NOT NULL CHECK (amount_cents > 0),
    status          text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','paid','disputed','waived')),
    paid_at         timestamptz,
    paid_via        text,        -- 'venmo' | 'zelle' | 'paypal' | 'cashapp' | 'cash' | 'other'
    paid_note       text,
    computed_at     timestamptz NOT NULL DEFAULT NOW(),
    updated_at      timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT commander_home_settlements_no_self_pay
        CHECK (payer_user_id <> payee_user_id)
);

CREATE INDEX IF NOT EXISTS idx_commander_home_settlements_game
    ON commander_home_settlements (game_id);
CREATE INDEX IF NOT EXISTS idx_commander_home_settlements_payer
    ON commander_home_settlements (payer_user_id, status);
CREATE INDEX IF NOT EXISTS idx_commander_home_settlements_payee
    ON commander_home_settlements (payee_user_id, status);

-- ── commander_home_group_payment_links ───────────────────────────────
-- Host's payment handles. Players tap to send via the linked app.
CREATE TABLE IF NOT EXISTS commander_home_group_payment_links (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id    uuid NOT NULL REFERENCES commander_home_groups(id) ON DELETE CASCADE,
    kind        text NOT NULL
                  CHECK (kind IN ('venmo','zelle','paypal','cashapp','revolut','other')),
    handle      text NOT NULL,  -- '@danbekavac', 'dan@example.com', etc.
    label       text,           -- optional human label
    sort_order  integer NOT NULL DEFAULT 0,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT NOW(),
    updated_at  timestamptz NOT NULL DEFAULT NOW(),
    UNIQUE (group_id, kind, handle)
);

CREATE INDEX IF NOT EXISTS idx_commander_home_group_payment_links_group
    ON commander_home_group_payment_links (group_id, is_active);

-- ══════════════════════════════════════════════════════════════════════
--  HELPER FUNCTIONS
-- ══════════════════════════════════════════════════════════════════════

-- Is caller staff of the group that owns this game?
CREATE OR REPLACE FUNCTION fn_home_caller_is_game_staff(p_caller uuid, p_game_id uuid)
RETURNS boolean
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_group_id uuid;
    v_owner    uuid;
    v_role     text;
    v_status   text;
BEGIN
    SELECT g.group_id INTO v_group_id
      FROM commander_home_games g WHERE g.id = p_game_id;
    IF v_group_id IS NULL THEN RETURN false; END IF;

    -- Owner short-circuit
    SELECT owner_id INTO v_owner FROM commander_home_groups WHERE id = v_group_id;
    IF v_owner = p_caller THEN RETURN true; END IF;

    -- Approved admin
    SELECT role, status INTO v_role, v_status
      FROM commander_home_members
     WHERE group_id = v_group_id AND user_id = p_caller;

    RETURN v_role IN ('owner','admin') AND v_status = 'approved';
END;
$$;

-- ── fn_home_record_buyin ─────────────────────────────────────────────
-- Host/admin records a buyin/rebuy/addon/adjustment for a player.
CREATE OR REPLACE FUNCTION fn_home_record_buyin(
    p_caller       uuid,
    p_game_id      uuid,
    p_user_id      uuid,
    p_kind         text,
    p_amount_cents integer,
    p_chip_count   integer DEFAULT NULL,
    p_note         text    DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_id uuid;
BEGIN
    IF NOT fn_home_caller_is_game_staff(p_caller, p_game_id) THEN
        RETURN jsonb_build_object('success', false, 'error', 'not authorized');
    END IF;

    IF p_kind NOT IN ('buyin','rebuy','addon','adjustment') THEN
        RETURN jsonb_build_object('success', false, 'error', 'invalid kind');
    END IF;

    IF p_kind <> 'adjustment' AND COALESCE(p_amount_cents, -1) < 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'amount must be non-negative');
    END IF;

    INSERT INTO commander_home_buyins (
        game_id, user_id, kind, amount_cents, chip_count, note, recorded_by
    ) VALUES (
        p_game_id, p_user_id, p_kind, p_amount_cents, p_chip_count, p_note, p_caller
    ) RETURNING id INTO v_id;

    RETURN jsonb_build_object('success', true, 'buyin_id', v_id);
END;
$$;

-- ── fn_home_record_cashout ───────────────────────────────────────────
-- Host/admin records a player's cashout. Upserts on (game_id, user_id).
CREATE OR REPLACE FUNCTION fn_home_record_cashout(
    p_caller       uuid,
    p_game_id      uuid,
    p_user_id      uuid,
    p_amount_cents integer,
    p_chip_count   integer DEFAULT NULL,
    p_note         text    DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_id uuid;
BEGIN
    IF NOT fn_home_caller_is_game_staff(p_caller, p_game_id) THEN
        RETURN jsonb_build_object('success', false, 'error', 'not authorized');
    END IF;

    IF COALESCE(p_amount_cents, -1) < 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'amount must be non-negative');
    END IF;

    INSERT INTO commander_home_cashouts (
        game_id, user_id, amount_cents, chip_count, note, recorded_by
    ) VALUES (
        p_game_id, p_user_id, p_amount_cents, p_chip_count, p_note, p_caller
    )
    ON CONFLICT (game_id, user_id) DO UPDATE
        SET amount_cents = EXCLUDED.amount_cents,
            chip_count   = EXCLUDED.chip_count,
            note         = EXCLUDED.note,
            recorded_by  = EXCLUDED.recorded_by,
            recorded_at  = NOW(),
            updated_at   = NOW()
    RETURNING id INTO v_id;

    RETURN jsonb_build_object('success', true, 'cashout_id', v_id);
END;
$$;

-- ── fn_home_game_totals ──────────────────────────────────────────────
-- Per-player totals for a game. Returns one row per user involved.
CREATE OR REPLACE FUNCTION fn_home_game_totals(p_game_id uuid)
RETURNS TABLE (
    user_id            uuid,
    total_buyin_cents  bigint,
    cashout_cents      bigint,
    net_cents          bigint,   -- cashout - buyin; positive=won, negative=lost
    chip_count         integer,
    username           text,
    display_name       text
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    WITH buyins AS (
        SELECT b.user_id, SUM(b.amount_cents)::bigint AS total_cents
        FROM commander_home_buyins b
        WHERE b.game_id = p_game_id
        GROUP BY b.user_id
    ),
    cashouts AS (
        SELECT c.user_id, c.amount_cents::bigint AS amt, c.chip_count
        FROM commander_home_cashouts c
        WHERE c.game_id = p_game_id
    ),
    universe AS (
        SELECT user_id FROM buyins
        UNION
        SELECT user_id FROM cashouts
    )
    SELECT
        u.user_id,
        COALESCE(b.total_cents, 0)                        AS total_buyin_cents,
        COALESCE(c.amt, 0)                                AS cashout_cents,
        COALESCE(c.amt, 0) - COALESCE(b.total_cents, 0)   AS net_cents,
        c.chip_count,
        p.username,
        COALESCE(p.display_name, p.full_name, p.username) AS display_name
    FROM universe u
    LEFT JOIN buyins   b ON b.user_id = u.user_id
    LEFT JOIN cashouts c ON c.user_id = u.user_id
    LEFT JOIN profiles p ON p.id      = u.user_id
    ORDER BY net_cents DESC;
END;
$$;

-- ── fn_home_compute_settlements ──────────────────────────────────────
-- Greedy minimum-transaction settlement. Wipes existing rows for the
-- game (any not-yet-marked paid ones) and recomputes.
--
-- Algorithm:
--   1. For every player, compute net = cashouts - buyins.
--   2. Split into creditors (net>0, owed money) and debtors (net<0).
--   3. Repeatedly pair the biggest debtor with the biggest creditor,
--      transfer min(|debt|, |credit|), until all zero.
--   This produces at most N-1 transactions for N nonzero players.
--
-- Preserves rows that are already paid/disputed/waived — the recompute
-- only overwrites the `pending` set.
CREATE OR REPLACE FUNCTION fn_home_compute_settlements(
    p_caller  uuid,
    p_game_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_total_buyin   bigint;
    v_total_cashout bigint;
    v_row_count     integer := 0;
    v_unbalanced    bigint;
    debtors         jsonb := '[]'::jsonb;
    creditors       jsonb := '[]'::jsonb;
    d_user          uuid; d_amt bigint;
    c_user          uuid; c_amt bigint;
    pay             bigint;
BEGIN
    IF NOT fn_home_caller_is_game_staff(p_caller, p_game_id) THEN
        RETURN jsonb_build_object('success', false, 'error', 'not authorized');
    END IF;

    -- Sanity: totals should balance (within rounding)
    SELECT COALESCE(SUM(amount_cents),0) INTO v_total_buyin
      FROM commander_home_buyins WHERE game_id = p_game_id;
    SELECT COALESCE(SUM(amount_cents),0) INTO v_total_cashout
      FROM commander_home_cashouts WHERE game_id = p_game_id;

    v_unbalanced := v_total_cashout - v_total_buyin;
    -- Allow imbalance — just note it; caller decides to treat as adjustment.

    -- Wipe pending settlement rows only (preserve paid/disputed/waived)
    DELETE FROM commander_home_settlements
     WHERE game_id = p_game_id AND status = 'pending';

    -- Collect nonzero nets from fn_home_game_totals
    SELECT
        COALESCE(jsonb_agg(jsonb_build_object('u', user_id, 'amt', -net_cents))
                 FILTER (WHERE net_cents < 0), '[]'::jsonb),
        COALESCE(jsonb_agg(jsonb_build_object('u', user_id, 'amt', net_cents))
                 FILTER (WHERE net_cents > 0), '[]'::jsonb)
      INTO debtors, creditors
      FROM fn_home_game_totals(p_game_id);

    -- Greedy settle
    WHILE jsonb_array_length(debtors) > 0 AND jsonb_array_length(creditors) > 0 LOOP
        -- Sort descending each pass (small N; cost is fine)
        debtors   := (SELECT COALESCE(jsonb_agg(e ORDER BY (e->>'amt')::bigint DESC), '[]'::jsonb) FROM jsonb_array_elements(debtors) e);
        creditors := (SELECT COALESCE(jsonb_agg(e ORDER BY (e->>'amt')::bigint DESC), '[]'::jsonb) FROM jsonb_array_elements(creditors) e);

        d_user := (debtors   -> 0 ->> 'u')::uuid;
        c_user := (creditors -> 0 ->> 'u')::uuid;
        d_amt  := (debtors   -> 0 ->> 'amt')::bigint;
        c_amt  := (creditors -> 0 ->> 'amt')::bigint;

        pay := LEAST(d_amt, c_amt);
        IF pay <= 0 THEN EXIT; END IF;

        INSERT INTO commander_home_settlements (
            game_id, payer_user_id, payee_user_id, amount_cents, status
        ) VALUES (
            p_game_id, d_user, c_user, pay::integer, 'pending'
        );
        v_row_count := v_row_count + 1;

        -- Rebuild arrays with updated first element removed if zeroed
        IF d_amt - pay > 0 THEN
            debtors := jsonb_set(debtors, '{0,amt}', to_jsonb(d_amt - pay));
        ELSE
            debtors := debtors - 0;
        END IF;
        IF c_amt - pay > 0 THEN
            creditors := jsonb_set(creditors, '{0,amt}', to_jsonb(c_amt - pay));
        ELSE
            creditors := creditors - 0;
        END IF;
    END LOOP;

    RETURN jsonb_build_object(
        'success', true,
        'game_id', p_game_id,
        'total_buyin_cents',   v_total_buyin,
        'total_cashout_cents', v_total_cashout,
        'imbalance_cents',     v_unbalanced,
        'settlements_created', v_row_count
    );
END;
$$;

-- ── fn_home_mark_settlement_paid ─────────────────────────────────────
-- Either payer or payee can mark paid (whoever acknowledges first).
CREATE OR REPLACE FUNCTION fn_home_mark_settlement_paid(
    p_caller         uuid,
    p_settlement_id  uuid,
    p_paid_via       text    DEFAULT NULL,
    p_paid_note      text    DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    v_payer uuid; v_payee uuid; v_status text;
BEGIN
    SELECT payer_user_id, payee_user_id, status
      INTO v_payer, v_payee, v_status
      FROM commander_home_settlements
     WHERE id = p_settlement_id;

    IF v_payer IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'settlement not found');
    END IF;
    IF p_caller NOT IN (v_payer, v_payee) THEN
        RETURN jsonb_build_object('success', false, 'error', 'only payer or payee can mark paid');
    END IF;
    IF v_status = 'paid' THEN
        RETURN jsonb_build_object('success', true, 'already_paid', true);
    END IF;

    UPDATE commander_home_settlements
       SET status = 'paid',
           paid_at = NOW(),
           paid_via = p_paid_via,
           paid_note = p_paid_note,
           updated_at = NOW()
     WHERE id = p_settlement_id;

    RETURN jsonb_build_object('success', true, 'settlement_id', p_settlement_id);
END;
$$;

-- Grants
GRANT EXECUTE ON FUNCTION fn_home_caller_is_game_staff(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION fn_home_record_buyin(uuid, uuid, uuid, text, integer, integer, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION fn_home_record_cashout(uuid, uuid, uuid, integer, integer, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION fn_home_game_totals(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION fn_home_compute_settlements(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION fn_home_mark_settlement_paid(uuid, uuid, text, text) TO authenticated, service_role;
