-- Repo copy of three migrations applied to production on 2026-08-30 via the
-- Supabase MCP (Claude/Cowork satellite audit, phases 1-3). Full executed SQL
-- lives in the applied migrations of the same names.
--
-- 1. satellite_overlays_become_acknowledged_baseline (~21:07 UTC)
--    Every completed satellite's overlay — guarantee shortfall, pre-#1935
--    cash overpayment, double-qualification back-pays — recorded as one row
--    per event in tournament_conservation_baseline (16 events, 4,132.50
--    chips, asserted at apply time). Precedent:
--    20260828082815_the_pre_funding_minting_becomes_an_acknowledged_baseline.
--    Decision: NOT chaseable, house-covered, no clawbacks.
--
-- 2. satellite_guarantees_sized_to_the_field (~21:10 UTC)
--    Sunday Deep Stack satellite templates resized to what their real fields
--    fund: $25 5 -> 3 seats, $10 2 -> 1 seat, $5 already 1. Copy updated to
--    match. OPEN events keep the guarantees their lobby copy advertised
--    (asserted); only future spawns pick up the new numbers.
--
-- 3. fn_satellite_conservation_audit (~21:14 UTC)
--    SECURITY DEFINER (service_role only) read-only audit the engine polls
--    from the FeeReconciler cycle: reports any completed satellite in the
--    window with UNPAID WINNERS (finisher inside the awardable count with
--    neither funded seat nor prize cash) or DISBURSED BEYOND THE PROMISE
--    (cash + seats x ticket beyond max(pool, awardable x ticket), net of
--    acknowledged baselines). Asserted clean over the reconciled week at
--    apply time.
--
-- REVOKE/GRANT applied: fn_satellite_conservation_audit is engine-only.
