-- APPLIED, SQL NOT PRESERVED (2026-09-27 migration backfill).
--
-- This migration WAS applied to production as 20260923173830 ("an_abandoned_crash_round_settles_itself"), but its SQL was
-- never committed and supabase_migrations.schema_migrations.statements is
-- NULL for it, so the exact SQL cannot be recovered from anywhere. Its effect
-- is whatever production holds; this file exists so the repository records
-- that the version ran instead of reporting a phantom gap for ever.
--
-- Do NOT invent SQL here and do NOT re-run anything.
-- @live-proof: EXISTS (SELECT 1 FROM supabase_migrations.schema_migrations WHERE version = '20260923173830')
SELECT 'applied 20260923173830: an_abandoned_crash_round_settles_itself (statements not preserved)' AS unrecoverable_backfill_note;
