-- Applied to prod 2026-08-22. Full text in the Supabase migration history
-- (20260822b_union_diamond_send_whitelist); mirror for the repo's ledger.
--
-- FIX: the diamonds branch of fn_union_send_to_member could never succeed.
-- Found by an end-to-end probe (impersonated union owner, rolled back): the
-- profiles guard trigger blocks every direct write to profiles.diamonds
-- except from service context or a call-stack-whitelisted function.
-- deduct_diamonds was whitelisted; fn_union_send_to_member was not, so every
-- diamond send from the union wallet UI raised 42501. Chips and promo were
-- verified good in the same probe (exact debits, double-entry ledger rows).
--
-- 1. fn_guard_profile_privileged_columns: whitelist
--    fn_union_send_to_member's stack frame alongside deduct_diamonds — the
--    branch is owner/co-owner/admin-gated, member-only, whole-number, capped,
--    and ledgered, which is the shape the guard's comment sanctions.
-- 2. fn_union_send_to_member re-issued with a 100,000-per-send diamond cap and
--    a warning against replacing the per-call idempotency key with a stable
--    client key: atomic_credit_wallet_and_log returns TRUE on a duplicate key,
--    so a retried stable-key call would debit the union wallet again, skip the
--    credit AND the refund branch, and destroy chips.
--
-- Post-fix probe: chips/promo/diamonds all success=true, rake debited exactly,
-- promo debited exactly, chip ledger 3 rows (debit + credit + promo),
-- diamond ledger 1 row; rolled back with zero residue.
