-- APPLIED TO PRODUCTION 2026-08-19 via Supabase MCP as
-- `rakeback_settler_batch_credit_rpcs`. Mirror only.
--
-- SETTLER THROUGHPUT — the daemon was LOSING GROUND, measured on production.
-- Over a 56-minute window the durable cursor advanced 14.1 minutes of history
-- while 56 minutes of new history arrived; the backlog grew 286,049 -> 287,786.
-- An earlier estimate that it would converge on its own was wrong.
--
-- The database was never the constraint. Each page of rake_records issued ONE
-- HTTP round trip PER PLAYER PER HAND, twice over (agent commission, then
-- player stats). A 2,000-row page at ~6 dealt-in players is ~24,000 sequential
-- PostgREST calls at a measured ~6/sec — over an hour of pure network latency
-- for a page whose SQL takes seconds.
--
--   fn_credit_agent_commissions_batch(p_items jsonb)
--   fn_apply_rakeback_player_stats_batch(p_items jsonb)
--
-- Both take the page as a jsonb array and loop server-side, calling the SAME
-- underlying per-item function, which is idempotent (agent commissions dedupe
-- on (user_id, source_id, source_type); player stats claim through
-- rakeback_stats_applied). Each element runs inside its own exception block so
-- a single bad element is isolated instead of aborting the batch — matching
-- the error isolation the per-call client loop had. service_role only.
--
-- VERIFIED live before wiring: replaying two ALREADY-credited items returned
-- ok=2 and left agent_commissions unchanged (1 row before, 1 after), and a
-- deliberately malformed third element returned failed=1 with its error text
-- while the other two still applied.
