-- ZERO-DRIFT PHASE 3B–F — SETTLEMENT CORRECTNESS CHECKS
-- (prod: ca_zero_drift_phase3_settlement_correctness +
--  ca_phase3_correctness_check_classifications fixup, 2026-08-31 ~19:12 UTC;
--  this mirror carries the corrected classifications inline:
--  cross_club_posting / reporting_mismatch.)
--
-- Standing 30-minute sweep fn_ca_settlement_correctness_check():
--   B. cross-club posting (chips moved directly between two clubs outside
--      treasury_transfer/pnl_settlement/horse_funding/correction)
--        -> warning 'cross_club_posting'
--   C1. rakeback over-attribution (attributions > rake collected)
--        -> warning 'incorrect_rakeback'
--   C2. rakeback over-payout (paid > player's entire contribution)
--        -> CRITICAL 'incorrect_rakeback'
--   C3. rakeback dual-write evidence gaps (paid with no linked wallet/chip tx)
--        -> warning 'reporting_mismatch'
--   D. ticket conservation (redeemed/cancelled without timestamps;
--      active non-positive value) -> warning 'reporting_mismatch'
--   E. insurance pair-match (net_result must equal payout - premium)
--        -> warning 'reporting_mismatch'
-- F. fn_ca_gdpr_financial_precheck(p_user_id): every financial reason an
--    account cannot be anonymized (balances, seats, pending rakeback,
--    outstanding tickets, agent balances/credit). Read-only.
-- Cron ca-settlement-correctness-30m; both functions + cron registered in
-- ca_guard_inventory and ca_money_rpc_registry; EXECUTE revoked from
-- anon/authenticated.
-- Canonical body: prod schema_migrations (byte-exact pull at bundle rebuild).
