-- Applied to production 2026-08-27 as `the_unused_index_detector_must_actually_run`.
--
-- `20260826_index_usage_snapshots_so_unused_can_be_proven.sql` built exactly the
-- right thing and then never scheduled it. ONE snapshot existed, taken
-- 2026-08-26 20:29:59, and that was the entire historical record.
--
-- Consequence found tonight: hand_history carries 8 indexes weighing 1,189 MB
-- against a 2,356 MB table, all maintained on 460,000 inserts a day. Two show
-- zero scans - but over 2.4 hours and a single snapshot, which proves nothing.
-- A nightly tournament report would look identical from here. So nothing was
-- dropped; the evidence starts accumulating instead.
--
-- uq_hand_history_global_hand_number also shows zero scans and must NEVER be
-- dropped on that basis: it is UNIQUE, so it is a CONSTRAINT enforced on every
-- insert, not an access path anyone queries.
--
-- Daily 04:41 UTC, a minute nothing else uses (stagger rule from
-- 20260823050000_stagger_maintenance_jobs_off_the_same_minute.sql). Database
-- maintenance, like the other 41 pg_cron jobs here - not application logic, so
-- CLAUDE.md section 11 routing to Open Claw does not apply.
