-- ═══════════════════════════════════════════════════════════════════════════
-- CLOSE THE BROWSER CHIP MINT — 2026-08-27 security audit
-- APPLIED via Supabase MCP before this file was committed, and PROVEN by a
-- rolled-back probe that executed the exploit itself.
--
-- THE EXPLOIT (confirmed, not theorised):
--   `authenticated` and `anon` hold TABLE-level UPDATE on club_members and
--   clubs. RLS policy club_members_update lets a member update their OWN row;
--   its WITH CHECK pins role, credit_limit, credit_used, agent_id and
--   parent_agent_id — and says nothing about balances. The only trigger on
--   chip_balance was AFTER UPDATE and merely RECORDS the delta. So
--       supabase.from('club_members').update({ chip_balance: 9e8 })
--                                    .eq('user_id', me)
--   succeeded from the SPA with the anon key, and atomic_table_buyin reads
--   that column as real money.
--   Probe (rolled back), as `authenticated` holding that member's own JWT:
--       chip_balance 5,000.00 -> 900,000,000.00
--   clubs.chip_treasury had the same hole for owners: guard_wallet_balance_write
--   is installed on wallets.balance and clubs.chip_pool, but never on
--   chip_treasury — the column fn_club_bank_send actually moves.
--
-- WHY A TRIGGER, NOT A REVOKE: the grants are TABLE-level, so a column-level
-- REVOKE is a silent no-op (verified — has_column_privilege still returned
-- true afterwards). Revoking the table grant and re-granting a safe column
-- list would work, but that list has to be inferred from client code and one
-- missed column breaks a legitimate flow.
--
-- WHY SECURITY INVOKER: the first version of this guard was SECURITY DEFINER
-- and DID NOT FIRE — inside a DEFINER function `current_user` is the function
-- owner, so the browser test never matched and the mint still succeeded. As
-- INVOKER, current_user is the real executing role: 'authenticated'/'anon' for
-- a PostgREST write, the owner inside a SECURITY DEFINER money RPC,
-- 'service_role' for the engine. That is exactly the line needed.
--
-- WHY NOT guard_wallet_balance_write: 66 functions legitimately write these
-- columns, far more than its call-stack whitelist, so reusing it would break
-- buy-ins, cashouts, joins and transfers platform-wide. Verified before
-- applying: of the 29 SECURITY INVOKER writers, only 3 are callable by
-- `authenticated` (atomic_table_withdraw, promo_apply_playthrough,
-- reconcile_ledger_nightly) and every one is invoked solely by the server
-- under the service role — no client path reaches them.
--
-- ALSO REVOKED (same audit):
--   fn_award_satellite_seat  — SECURITY DEFINER, granted to `authenticated`,
--     no auth check, p_user_id taken from the caller: any user could seat any
--     account into any ANNOUNCED/REGISTERING tournament for free while
--     inflating prize_pool and total_rake with money nobody paid.
--   reconcile_ledger_nightly — an operations job, not a player action.
--   profiles INSERT on is_admin/is_vip/role — UPDATE was guarded but INSERT
--     was not, and profiles_delete + profiles_insert_self both key on
--     auth.uid() = id, so an account could delete its own profile row and
--     re-insert it with is_admin = true, satisfying ca_can_view_club() for
--     EVERY club.
--
-- VERIFICATION (all rolled back):
--   mint attempt as the member's own browser session .......... BLOCKED
--   treasury write as the club owner's browser session ........ BLOCKED
--   non-balance UPDATE by the same role ....................... still allowed
--   atomic_credit_wallet_and_log (the engine's credit path) ... +12.34 OK
-- ═══════════════════════════════════════════════════════════════════════════
SELECT 1;
