-- APPLIED TO PRODUCTION 2026-08-20 via Supabase MCP as
--   `close_trust_leak_and_drop_stale_unreserved`
--   `retire_second_move_rake_to_chips_overload`
-- Mirror only.
--
-- Audit of my OWN change (rake now lands only in the Rake Treasury). Separating
-- the two accounts left two things behind that no longer made sense.
--
-- 1. TRUST LEAK. fn_union_move_rake_to_chips_atomic moves rake_wallet ->
--    chip_balance. Under the old nested model that merely "converted" held rake
--    into spendable form. Now that the treasury holds money in trust for the
--    clubs, it let a union admin move the clubs' 90% into the union's own bank
--    BEFORE the weekly close and spend it through fn_union_send_to_club_atomic
--    or fn_union_fund_bbj_pool (both draw on chip_balance) — after which the
--    close would hit 'insufficient_treasury' and pay nobody.
--
--    It is reachable in production: World Hub pages/api/club-arena/
--    union-wallet.js exposes action 'move_rake_to_chips'.
--
--    IMPORTANT: it had TWO overloads and the first fix only retired one —
--      (uuid, numeric, uuid, text, uuid)   <- retired first
--      (uuid, numeric, text, uuid, uuid)   <- the one the live route binds to
--    "I replaced the function" is not "the function is gone" when overloads
--    exist. Both refuse now; probed both signatures, balances untouched.
--
--    There is no legitimate use left: the weekly close moves the union's
--    retained share into the bank by itself, and that is the only rake the
--    union is entitled to.
--
-- 2. union_bank_unreserved (chip_balance - rake_wallet) described how much of
--    the bank was not earmarked. With the accounts separated it evaluated to
--    120,895.24 - 512,858.09 = -391,962.85. Removed from fn_club_money_panel
--    rather than left to mislead; every chip in the bank is unreserved now.
