-- Rank participants not the roster; align the union board.        2026-08-20
--
-- 1. ACTIVE-ONLY RANKING. The boards ranked EVERY player_stats row for the club,
--    including players with no activity in the selected period. Such a player
--    sits at profit 0, which on a weekly board places them ABOVE everyone who
--    lost money that week. Measured on Club JAQK profit/weekly: 575 ranked, 16
--    with zero activity, and the best-placed inactive player sat at rank 189 -
--    above 371 players who actually played and lost. "out of 575" also described
--    the roster rather than the participants.
--    Both boards now rank only rows with activity in the window (hands dealt,
--    tournaments won, or any chip movement - so a tournament-only player is not
--    dropped from the Tournaments Won board), and total_ranked is a window count
--    over that same filtered set, so the denominator cannot disagree with the
--    population being ranked. After: 559 rows, 559 total_ranked, 0 inactive.
--
-- 2. UNION ALIGNMENT. fn_union_leaderboard_period_v2 predated the pagination
--    work and returned neither rank, total_ranked, baseline_date nor
--    sum_big_blind, had no p_offset and no bb100. Unreferenced by the client,
--    which is exactly why it kept drifting from the two functions people look
--    at. Now identical in columns, arguments and semantics.
--
-- Part 1 was applied by rewriting the live definitions with asserted
-- substitutions (see 20260820b for why); part 2 is a full DROP/CREATE because
-- the return type changed. Verified: union bb100 board returns rank 1/2/3 with
-- total_ranked 566 and baseline_date 2026-08-13.
--
-- ROLLBACK: restore from 20260819j / 20260819k / 20260819l, then re-apply
--           20260820b.
