-- ═══════════════════════════════════════════════════════════════════════════
-- TOURNAMENT AUDIT (2026-08-15) — APPLIED TO PROD via Supabase MCP the same
-- day, probe-verified in rolled-back transactions (register: exact debit +
-- tournament_players row + wallet_transactions ledger row + rake_records fee
-- row + prize_pool/current_players bump; unregister: full reversal incl. fee
-- reversal row and pool decrement; near-start guard returns
-- too_close_to_start).
--
-- WHY: human tournament registration was IMPOSSIBLE. The client's only path
-- called atomic_tournament_register — service_role-only — so every browser
-- registration failed 42501; every "completed" tournament was horse-filled.
-- The client also rolled MYSTERY BOUNTY values in the browser (manipulable)
-- and attempted ~10 privileged writes that RLS rejects.
--
-- fn_register_for_tournament(p_tournament_id): SECURITY DEFINER, authenticated.
--   - cost derived server-side from the tournaments row (anti-mint rule)
--   - status / late-reg (current_level<=late_reg_levels, else started_at +
--     late_reg_mins) / full / duplicate enforced under FOR UPDATE row lock
--   - mystery bounty rolled server-side (same 60/25/10/4/1 ladder)
--   - debit via atomic_deduct_wallet_and_log (guarded, chip_transactions) +
--     player-facing wallet_transactions row via log_wallet_transaction
--   - entry FEE inserted into rake_records (is_tournament=true) — the ledger
--     the finalize settlement sums and credits to the union/club; human fees
--     were previously never credited anywhere
--   - prize_pool += buy_in, current_players += 1
--   - unique-violation race: refunds the exact debit, returns already_registered
--   NOTE (probe-caught): rake_records.table_id has an FK to tables — fee rows
--   carry the tournament ONLY in tournament_id; table_id stays NULL.
--
-- fn_unregister_from_tournament: now also reverses prize_pool and writes the
-- -fee rake_records row (it refunded the player but left the pool inflated
-- and the club owed a refunded fee).
--
-- The full function bodies live in the remote migration history
-- (fn_register_for_tournament, fn_register_tournament_fee_row_fk_fix, and the
-- in-place ledger patch). This file is the repo mirror per CLAUDE.md §2.
