-- APPLIED TO PRODUCTION 2026-08-20 via Supabase MCP as
-- `selftest_settler_lag_check`. Mirror only.
--
-- The settler fell ~2 days behind and NOTHING said so. Every existing check
-- asked whether money was WRONG; none asked whether it was LATE. Rake is
-- banked at hand time so nothing was lost, but per-player rakeback attribution
-- and agent-commission accrual silently stopped tracking reality for two days,
-- and it was only found because the cursor happened to get measured.
--
--   fn_settler_lag_check() — unhealthy when the durable cursor is more than
--   6 hours behind now(), or when no cursor has been saved in over an hour
--   while >1000 rows of backlog exist. Folded into
--   fn_union_treasury_selftest(), which the engine runs every settler cycle,
--   so a breach becomes a deduped critical financial_alerts row.
--
-- Either condition would have fired on 2026-08-17 rather than the 19th.
--
-- NOTE: this check is legitimately RED right now (lag ~60h, ~285k rows) while
-- the backlog drains; it is expected to clear on its own as the cursor catches
-- up, and the alert is deduped so it will not spam.
