-- Read/assert only. No lease, park, hand, financial or roster mutations.
BEGIN;
SET LOCAL lock_timeout='1s';
SET LOCAL statement_timeout='8s';
-- BEGIN CAPTURED MOVEMENT DEPENDENCIES
DO $movement_dependencies$
DECLARE actual jsonb;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('smarter_private.f06_receipt_guard()') AND md5(pg_get_functiondef(p.oid))='aaec65e9760efeaa6985eceecc08add9' AND md5(p.prosrc)='ae5b6eae7e5a55e1e6f810a2898a8911' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','smarter_private.f06_receipt_guard()'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_tournament_seat_move_receipts_append_only()') AND md5(pg_get_functiondef(p.oid))='7069f5e998da3a06889861446b7ae2e9' AND md5(p.prosrc)='85534593874dc5d908193ccbfc309719' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=public"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_tournament_seat_move_receipts_append_only()'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_ca_tournament_seat_move_receipt(uuid)') AND md5(pg_get_functiondef(p.oid))='4610936f3d1fd5935da9ae09c8e88001' AND md5(p.prosrc)='68813ee03e355e2eec053e15bf40f98d' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=public"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_ca_tournament_seat_move_receipt(uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_move_tournament_player(uuid,uuid,uuid,uuid,integer,uuid,text)') AND md5(pg_get_functiondef(p.oid))='1adbc87ee53a885ba9a161560aab9c55' AND md5(p.prosrc)='1bfea45e31dd3236c31966e4185dfbdb' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=public, pg_temp", "statement_timeout=30s"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_move_tournament_player(uuid,uuid,uuid,uuid,integer,uuid,text)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_resolve_committed_tournament_seat_move(uuid,uuid,uuid,uuid,uuid,integer,text)') AND md5(pg_get_functiondef(p.oid))='43c53a2b376cb28161584db487bfd17c' AND md5(p.prosrc)='f00ad0e9a08496d96f6375cbf6f30678' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=public, pg_temp", "statement_timeout=30s"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_resolve_committed_tournament_seat_move(uuid,uuid,uuid,uuid,uuid,integer,text)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.claim_tournament_lease_v2(uuid,text,text,uuid,integer)') AND md5(pg_get_functiondef(p.oid))='1d5fdcf284efb107c4f5e2a3be364fb0' AND md5(p.prosrc)='ee2e1143ea1bdff2395bb5cc6c5932f5' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=public, pg_temp"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.claim_tournament_lease_v2(uuid,text,text,uuid,integer)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_ack_cleanup(uuid,uuid,uuid,uuid,bigint,text)') AND md5(pg_get_functiondef(p.oid))='7b86ea417aadc35dd5805f1b7f3de4dc' AND md5(p.prosrc)='6d52f389b20e51eb82f54ed07fe3238e' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_ack_cleanup(uuid,uuid,uuid,uuid,bigint,text)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_begin_break(uuid,uuid,uuid,jsonb)') AND md5(pg_get_functiondef(p.oid))='efebd049c672b162c180bbed1fd41af0' AND md5(p.prosrc)='955e8e73b07988b55d8dcc870c902297' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_begin_break(uuid,uuid,uuid,jsonb)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_begin_hand(uuid,uuid,uuid,bigint,uuid,bigint,uuid)') AND md5(pg_get_functiondef(p.oid))='f50408947a84ee5901e2e59d0be61d94' AND md5(p.prosrc)='ee839b0fd6bac5601191118fee304980' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_begin_hand(uuid,uuid,uuid,bigint,uuid,bigint,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_break_state(uuid,uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='0d1d1f4404ca923cd36a86210ea0a92d' AND md5(p.prosrc)='65833666f7157904dbaee811fe45cce4' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_break_state(uuid,uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_claim_custody(uuid,uuid,uuid,uuid,bigint)') AND md5(pg_get_functiondef(p.oid))='f7c8c35f4bc8e68ac1c9463518069f98' AND md5(p.prosrc)='8370eedf9f3d7ac46d522f4b265bed60' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_claim_custody(uuid,uuid,uuid,uuid,bigint)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_close_break(uuid,uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='091073a6e7c4f195f4e974eee5e4d30f' AND md5(p.prosrc)='31a544987423c3da6648fb45f73a2ad1' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_close_break(uuid,uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_hand_number_state(uuid,uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='cfb6d1f8b0793c0e4ef4e0b5f147779c' AND md5(p.prosrc)='33b39b69d092879b6528851235a85397' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_hand_number_state(uuid,uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_f06_table_state(uuid,uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='912feb4ac2e7759d240ef1309d5ab4d0' AND md5(p.prosrc)='f4feed631cda151a3157f70066448b22' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_f06_table_state(uuid,uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_ca_lock_settlement_lane_for_tournament(uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='9877846ffabee004690e6b24a3ddcee2' AND md5(p.prosrc)='3acb4c1d763181905cf5b64287f8f28f' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=public, pg_temp"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_ca_lock_settlement_lane_for_tournament(uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('smarter_private.f06_authority(uuid,uuid,boolean)') AND md5(pg_get_functiondef(p.oid))='848b06c8e958ad739e0a60b388430f38' AND md5(p.prosrc)='939908ee892773e79e04fc73241c3f75' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','smarter_private.f06_authority(uuid,uuid,boolean)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('smarter_private.f06_generation_aborted(uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='3530559a94372866bf3baec006a8fd3c' AND md5(p.prosrc)='76f64dfc5436d6208c6afbed3ad7da53' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','smarter_private.f06_generation_aborted(uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('smarter_private.f06_immutable_identity()') AND md5(pg_get_functiondef(p.oid))='0fe40a0711ef6d196c6883d3b9e8b86f' AND md5(p.prosrc)='31329a1df4bec9c92e0517b38fd42b93' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','smarter_private.f06_immutable_identity()'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('smarter_private.f06_move_guard(uuid,uuid,uuid,uuid,integer,uuid,text,uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='67043ce7cbe35b5582b625aaea29d12b' AND md5(p.prosrc)='50e1279c8f5e1c22872350d5b712a8b3' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','smarter_private.f06_move_guard(uuid,uuid,uuid,uuid,integer,uuid,text,uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('smarter_private.f06_prefix(uuid,uuid,uuid[],uuid[])') AND md5(pg_get_functiondef(p.oid))='dae9d5b5f71a68362f202dfdf89c8fae' AND md5(p.prosrc)='d857e9d6270456d122ef385c751bc5f1' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','smarter_private.f06_prefix(uuid,uuid,uuid[],uuid[])'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('smarter_private.f06_source_guard()') AND md5(pg_get_functiondef(p.oid))='de1b25f96d2c08bf20213c0e194ae261' AND md5(p.prosrc)='97d26bf7859cc41d42752311d0b40d2f' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=pg_catalog, public, smarter_private"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','smarter_private.f06_source_guard()'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.fn_close_empty_tournament_table(uuid,uuid,uuid)') AND md5(pg_get_functiondef(p.oid))='0af954ab1264dc12ebce7741b7845343' AND md5(p.prosrc)='4abef1a7ccd6d56c2523fe6cb02396b6' AND pg_get_userbyid(p.proowner)='postgres' AND p.proacl::text='{postgres=X/postgres,service_role=X/postgres}' AND to_jsonb(p.proconfig)='["search_path=public, pg_temp"]'::jsonb) THEN RAISE EXCEPTION 'F06_MOVEMENT_DEPENDENCY_DRIFT: %','public.fn_close_empty_tournament_table(uuid,uuid,uuid)'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('smarter_private.f06_attempts') AND pg_get_userbyid(c.relowner)='postgres' AND c.relacl::text='{postgres=arwdDxtm/postgres}' AND c.relrowsecurity=true AND c.relforcerowsecurity=false) THEN RAISE EXCEPTION 'F06_MOVEMENT_RELATION_DRIFT: %','smarter_private.f06_attempts'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_amendment_id_key' AND pg_get_constraintdef(oid)='UNIQUE (amendment_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_amendment_id_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_break_id_user_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (break_id, user_id) REFERENCES smarter_private.f06_members(break_id, user_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_break_id_user_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_break_id_user_id_revision_key' AND pg_get_constraintdef(oid)='UNIQUE (break_id, user_id, revision)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_break_id_user_id_revision_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_check' AND pg_get_constraintdef(oid)='CHECK (((state = ''winner''::text) = (receipt IS NOT NULL)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_destination_seat_number_check' AND pg_get_constraintdef(oid)='CHECK (((destination_seat_number >= 1) AND (destination_seat_number <= 10)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_destination_seat_number_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_pkey' AND pg_get_constraintdef(oid)='PRIMARY KEY (request_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_pkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_predecessor_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (predecessor) REFERENCES smarter_private.f06_attempts(request_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_predecessor_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_predecessor_key' AND pg_get_constraintdef(oid)='UNIQUE (predecessor)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_predecessor_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_revision_check' AND pg_get_constraintdef(oid)='CHECK ((revision > 0))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_revision_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_attempts'::regclass AND conname='f06_attempts_state_check' AND pg_get_constraintdef(oid)='CHECK ((state = ANY (ARRAY[''active''::text, ''fenced''::text, ''winner''::text])))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_attempts_state_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='smarter_private.f06_attempts'::regclass AND tgname='f06_attempts_immutable' AND pg_get_triggerdef(oid)='CREATE TRIGGER f06_attempts_immutable BEFORE DELETE OR UPDATE ON smarter_private.f06_attempts FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_immutable_identity()' AND tgenabled='O' AND NOT tgisinternal) THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','f06_attempts_immutable'; END IF;
 SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) INTO actual FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='smarter_private.f06_attempts'::regclass AND a.attnum>0 AND NOT a.attisdropped; IF actual IS DISTINCT FROM '[{"name": "request_id", "type": "uuid", "notnull": true, "default": null}, {"name": "break_id", "type": "uuid", "notnull": true, "default": null}, {"name": "user_id", "type": "uuid", "notnull": true, "default": null}, {"name": "revision", "type": "integer", "notnull": true, "default": null}, {"name": "predecessor", "type": "uuid", "notnull": false, "default": null}, {"name": "amendment_id", "type": "uuid", "notnull": false, "default": null}, {"name": "amendment_payload", "type": "jsonb", "notnull": false, "default": null}, {"name": "destination_table_id", "type": "uuid", "notnull": true, "default": null}, {"name": "destination_seat_number", "type": "integer", "notnull": true, "default": null}, {"name": "generation", "type": "uuid", "notnull": true, "default": null}, {"name": "state", "type": "text", "notnull": true, "default": "''active''::text"}, {"name": "receipt", "type": "jsonb", "notnull": false, "default": null}]'::jsonb THEN RAISE EXCEPTION 'F06_MOVEMENT_COLUMNS_DRIFT: %','smarter_private.f06_attempts'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('smarter_private.f06_dispatch') AND pg_get_userbyid(c.relowner)='postgres' AND c.relacl::text='{postgres=arwdDxtm/postgres}' AND c.relrowsecurity=true AND c.relforcerowsecurity=false) THEN RAISE EXCEPTION 'F06_MOVEMENT_RELATION_DRIFT: %','smarter_private.f06_dispatch'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_dispatch'::regclass AND conname='f06_dispatch_pkey' AND pg_get_constraintdef(oid)='PRIMARY KEY (request_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_dispatch_pkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_dispatch'::regclass AND conname='f06_dispatch_request_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (request_id) REFERENCES smarter_private.f06_attempts(request_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_dispatch_request_id_fkey'; END IF;
 SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) INTO actual FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='smarter_private.f06_dispatch'::regclass AND a.attnum>0 AND NOT a.attisdropped; IF actual IS DISTINCT FROM '[{"name": "request_id", "type": "uuid", "notnull": true, "default": null}, {"name": "xid", "type": "bigint", "notnull": true, "default": null}, {"name": "occupancy_id", "type": "uuid", "notnull": true, "default": null}, {"name": "source_seat_id", "type": "uuid", "notnull": true, "default": null}, {"name": "lifecycle", "type": "bigint", "notnull": true, "default": null}]'::jsonb THEN RAISE EXCEPTION 'F06_MOVEMENT_COLUMNS_DRIFT: %','smarter_private.f06_dispatch'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('smarter_private.f06_hand_dispatch') AND pg_get_userbyid(c.relowner)='postgres' AND c.relacl::text='{postgres=arwdDxtm/postgres}' AND c.relrowsecurity=true AND c.relforcerowsecurity=false) THEN RAISE EXCEPTION 'F06_MOVEMENT_RELATION_DRIFT: %','smarter_private.f06_hand_dispatch'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_hand_dispatch'::regclass AND conname='f06_hand_dispatch_permit_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (permit_id) REFERENCES smarter_private.f06_hand_permits(permit_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_hand_dispatch_permit_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_hand_dispatch'::regclass AND conname='f06_hand_dispatch_pkey' AND pg_get_constraintdef(oid)='PRIMARY KEY (permit_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_hand_dispatch_pkey'; END IF;
 SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) INTO actual FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='smarter_private.f06_hand_dispatch'::regclass AND a.attnum>0 AND NOT a.attisdropped; IF actual IS DISTINCT FROM '[{"name": "permit_id", "type": "uuid", "notnull": true, "default": null}, {"name": "xid", "type": "bigint", "notnull": true, "default": null}]'::jsonb THEN RAISE EXCEPTION 'F06_MOVEMENT_COLUMNS_DRIFT: %','smarter_private.f06_hand_dispatch'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('smarter_private.f06_hand_permits') AND pg_get_userbyid(c.relowner)='postgres' AND c.relacl::text='{postgres=arwdDxtm/postgres}' AND c.relrowsecurity=true AND c.relforcerowsecurity=false) THEN RAISE EXCEPTION 'F06_MOVEMENT_RELATION_DRIFT: %','smarter_private.f06_hand_permits'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_hand_permits'::regclass AND conname='f06_hand_permits_pkey' AND pg_get_constraintdef(oid)='PRIMARY KEY (permit_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_hand_permits_pkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_hand_permits'::regclass AND conname='f06_hand_permits_state_check' AND pg_get_constraintdef(oid)='CHECK ((state = ANY (ARRAY[''reserved''::text, ''accepted''::text, ''never_started''::text, ''aborted_unsettled''::text])))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_hand_permits_state_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_hand_permits'::regclass AND conname='f06_hand_permits_table_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (table_id) REFERENCES tables(id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_hand_permits_table_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_hand_permits'::regclass AND conname='f06_hand_permits_table_id_hand_number_key' AND pg_get_constraintdef(oid)='UNIQUE (table_id, hand_number)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_hand_permits_table_id_hand_number_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='smarter_private.f06_hand_permits'::regclass AND tgname='f06_hand_permits_immutable' AND pg_get_triggerdef(oid)='CREATE TRIGGER f06_hand_permits_immutable BEFORE DELETE OR UPDATE ON smarter_private.f06_hand_permits FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_immutable_identity()' AND tgenabled='O' AND NOT tgisinternal) THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','f06_hand_permits_immutable'; END IF;
 SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) INTO actual FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='smarter_private.f06_hand_permits'::regclass AND a.attnum>0 AND NOT a.attisdropped; IF actual IS DISTINCT FROM '[{"name": "permit_id", "type": "uuid", "notnull": true, "default": null}, {"name": "tournament_id", "type": "uuid", "notnull": true, "default": null}, {"name": "table_id", "type": "uuid", "notnull": true, "default": null}, {"name": "lifecycle", "type": "bigint", "notnull": true, "default": null}, {"name": "hand_number", "type": "bigint", "notnull": true, "default": null}, {"name": "custody_id", "type": "uuid", "notnull": true, "default": null}, {"name": "generation", "type": "uuid", "notnull": true, "default": null}, {"name": "state", "type": "text", "notnull": true, "default": "''reserved''::text"}, {"name": "evidence_id", "type": "uuid", "notnull": false, "default": null}]'::jsonb THEN RAISE EXCEPTION 'F06_MOVEMENT_COLUMNS_DRIFT: %','smarter_private.f06_hand_permits'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('smarter_private.f06_members') AND pg_get_userbyid(c.relowner)='postgres' AND c.relacl::text='{postgres=arwdDxtm/postgres}' AND c.relrowsecurity=true AND c.relforcerowsecurity=false) THEN RAISE EXCEPTION 'F06_MOVEMENT_RELATION_DRIFT: %','smarter_private.f06_members'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_members'::regclass AND conname='f06_members_break_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (break_id) REFERENCES smarter_private.f06_operations(break_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_members_break_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_members'::regclass AND conname='f06_members_break_id_source_seat_id_key' AND pg_get_constraintdef(oid)='UNIQUE (break_id, source_seat_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_members_break_id_source_seat_id_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_members'::regclass AND conname='f06_members_occupancy_id_key' AND pg_get_constraintdef(oid)='UNIQUE (occupancy_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_members_occupancy_id_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_members'::regclass AND conname='f06_members_pkey' AND pg_get_constraintdef(oid)='PRIMARY KEY (break_id, user_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_members_pkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_members'::regclass AND conname='f06_members_source_seat_number_check' AND pg_get_constraintdef(oid)='CHECK (((source_seat_number >= 1) AND (source_seat_number <= 10)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_members_source_seat_number_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='smarter_private.f06_members'::regclass AND tgname='f06_members_immutable' AND pg_get_triggerdef(oid)='CREATE TRIGGER f06_members_immutable BEFORE DELETE OR UPDATE ON smarter_private.f06_members FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_immutable_identity()' AND tgenabled='O' AND NOT tgisinternal) THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','f06_members_immutable'; END IF;
 SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) INTO actual FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='smarter_private.f06_members'::regclass AND a.attnum>0 AND NOT a.attisdropped; IF actual IS DISTINCT FROM '[{"name": "break_id", "type": "uuid", "notnull": true, "default": null}, {"name": "user_id", "type": "uuid", "notnull": true, "default": null}, {"name": "source_seat_id", "type": "uuid", "notnull": true, "default": null}, {"name": "source_seat_number", "type": "integer", "notnull": true, "default": null}, {"name": "occupancy_id", "type": "uuid", "notnull": true, "default": null}]'::jsonb THEN RAISE EXCEPTION 'F06_MOVEMENT_COLUMNS_DRIFT: %','smarter_private.f06_members'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('smarter_private.f06_operations') AND pg_get_userbyid(c.relowner)='postgres' AND c.relacl::text='{postgres=arwdDxtm/postgres}' AND c.relrowsecurity=true AND c.relforcerowsecurity=false) THEN RAISE EXCEPTION 'F06_MOVEMENT_RELATION_DRIFT: %','smarter_private.f06_operations'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_operations'::regclass AND conname='f06_operations_boundary_id_key' AND pg_get_constraintdef(oid)='UNIQUE (boundary_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_operations_boundary_id_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_operations'::regclass AND conname='f06_operations_check' AND pg_get_constraintdef(oid)='CHECK (((state = ANY (ARRAY[''close_confirmed''::text, ''acknowledged''::text])) = (close_receipt IS NOT NULL)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_operations_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_operations'::regclass AND conname='f06_operations_ordinal_key' AND pg_get_constraintdef(oid)='UNIQUE (ordinal)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_operations_ordinal_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_operations'::regclass AND conname='f06_operations_pkey' AND pg_get_constraintdef(oid)='PRIMARY KEY (break_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_operations_pkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_operations'::regclass AND conname='f06_operations_source_table_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (source_table_id) REFERENCES tables(id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_operations_source_table_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_operations'::regclass AND conname='f06_operations_state_check' AND pg_get_constraintdef(oid)='CHECK ((state = ANY (ARRAY[''park_requested''::text, ''begun''::text, ''close_confirmed''::text, ''acknowledged''::text, ''withdrawn_before_manifest''::text])))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_operations_state_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='smarter_private.f06_operations'::regclass AND conname='f06_withdrawal_receipt' AND pg_get_constraintdef(oid)='CHECK (((state = ''withdrawn_before_manifest''::text) = (abort_receipt_id IS NOT NULL)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','f06_withdrawal_receipt'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='smarter_private.f06_operations'::regclass AND tgname='f06_operations_immutable' AND pg_get_triggerdef(oid)='CREATE TRIGGER f06_operations_immutable BEFORE DELETE OR UPDATE ON smarter_private.f06_operations FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_immutable_identity()' AND tgenabled='O' AND NOT tgisinternal) THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','f06_operations_immutable'; END IF;
 SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) INTO actual FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='smarter_private.f06_operations'::regclass AND a.attnum>0 AND NOT a.attisdropped; IF actual IS DISTINCT FROM '[{"name": "break_id", "type": "uuid", "notnull": true, "default": null}, {"name": "ordinal", "type": "bigint", "notnull": true, "default": null}, {"name": "tournament_id", "type": "uuid", "notnull": true, "default": null}, {"name": "source_table_id", "type": "uuid", "notnull": true, "default": null}, {"name": "lifecycle", "type": "bigint", "notnull": true, "default": null}, {"name": "boundary_id", "type": "uuid", "notnull": true, "default": null}, {"name": "origin_generation", "type": "uuid", "notnull": true, "default": null}, {"name": "state", "type": "text", "notnull": true, "default": "''park_requested''::text"}, {"name": "manifest", "type": "jsonb", "notnull": false, "default": null}, {"name": "revision", "type": "bigint", "notnull": true, "default": "0"}, {"name": "custody_id", "type": "uuid", "notnull": false, "default": null}, {"name": "custody_generation", "type": "uuid", "notnull": false, "default": null}, {"name": "cleanup_kind", "type": "text", "notnull": false, "default": null}, {"name": "close_receipt", "type": "jsonb", "notnull": false, "default": null}, {"name": "created_at", "type": "timestamp with time zone", "notnull": true, "default": "clock_timestamp()"}, {"name": "abort_receipt_id", "type": "uuid", "notnull": false, "default": null}]'::jsonb THEN RAISE EXCEPTION 'F06_MOVEMENT_COLUMNS_DRIFT: %','smarter_private.f06_operations'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class c WHERE c.oid=to_regclass('public.tournament_seat_move_receipts') AND pg_get_userbyid(c.relowner)='postgres' AND c.relacl::text='{postgres=arwdDxtm/postgres}' AND c.relrowsecurity=true AND c.relforcerowsecurity=false) THEN RAISE EXCEPTION 'F06_MOVEMENT_RELATION_DRIFT: %','public.tournament_seat_move_receipts'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_check' AND pg_get_constraintdef(oid)='CHECK ((source_table_id <> destination_table_id))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_check1' AND pg_get_constraintdef(oid)='CHECK ((source_seat_id <> destination_seat_id))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_check1'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_destination_seat_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (destination_seat_id) REFERENCES table_seats(id) ON DELETE RESTRICT' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_destination_seat_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_destination_seat_number_check' AND pg_get_constraintdef(oid)='CHECK (((destination_seat_number >= 1) AND (destination_seat_number <= 10)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_destination_seat_number_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_destination_table_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (destination_table_id) REFERENCES tables(id) ON DELETE RESTRICT' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_destination_table_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_pkey' AND pg_get_constraintdef(oid)='PRIMARY KEY (request_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_pkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_source_mode_check' AND pg_get_constraintdef(oid)='CHECK ((source_mode = ANY (ARRAY[''live_source''::text, ''closed_orphan''::text])))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_source_mode_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_source_seat_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (source_seat_id) REFERENCES table_seats(id) ON DELETE RESTRICT' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_source_seat_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_source_seat_number_check' AND pg_get_constraintdef(oid)='CHECK (((source_seat_number >= 1) AND (source_seat_number <= 10)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_source_seat_number_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_source_table_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (source_table_id) REFERENCES tables(id) ON DELETE RESTRICT' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_source_table_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_stack_check' AND pg_get_constraintdef(oid)='CHECK ((((stack)::text <> ALL (ARRAY[''NaN''::text, ''Infinity''::text, ''-Infinity''::text])) AND (stack > (0)::numeric)))' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_stack_check'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_tournament_id_fkey' AND pg_get_constraintdef(oid)='FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE RESTRICT' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_tournament_id_fkey'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid='public.tournament_seat_move_receipts'::regclass AND conname='tournament_seat_move_receipts_tournament_id_user_id_request_key' AND pg_get_constraintdef(oid)='UNIQUE (tournament_id, user_id, request_id)' AND convalidated) THEN RAISE EXCEPTION 'F06_MOVEMENT_CONSTRAINT_DRIFT: %','tournament_seat_move_receipts_tournament_id_user_id_request_key'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.tournament_seat_move_receipts'::regclass AND tgname='f06_bind_move_receipt' AND pg_get_triggerdef(oid)='CREATE TRIGGER f06_bind_move_receipt AFTER INSERT ON public.tournament_seat_move_receipts FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_receipt_guard()' AND tgenabled='O' AND NOT tgisinternal) THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','f06_bind_move_receipt'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.tournament_seat_move_receipts'::regclass AND tgname='tournament_seat_move_receipts_append_only' AND pg_get_triggerdef(oid)='CREATE TRIGGER tournament_seat_move_receipts_append_only BEFORE DELETE OR UPDATE ON public.tournament_seat_move_receipts FOR EACH ROW EXECUTE FUNCTION fn_tournament_seat_move_receipts_append_only()' AND tgenabled='O' AND NOT tgisinternal) THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','tournament_seat_move_receipts_append_only'; END IF;
 SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) INTO actual FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid='public.tournament_seat_move_receipts'::regclass AND a.attnum>0 AND NOT a.attisdropped; IF actual IS DISTINCT FROM '[{"name": "request_id", "type": "uuid", "notnull": true, "default": null}, {"name": "tournament_id", "type": "uuid", "notnull": true, "default": null}, {"name": "user_id", "type": "uuid", "notnull": true, "default": null}, {"name": "source_table_id", "type": "uuid", "notnull": true, "default": null}, {"name": "destination_table_id", "type": "uuid", "notnull": true, "default": null}, {"name": "source_seat_id", "type": "uuid", "notnull": true, "default": null}, {"name": "destination_seat_id", "type": "uuid", "notnull": true, "default": null}, {"name": "source_seat_number", "type": "integer", "notnull": true, "default": null}, {"name": "destination_seat_number", "type": "integer", "notnull": true, "default": null}, {"name": "source_mode", "type": "text", "notnull": true, "default": null}, {"name": "stack", "type": "numeric", "notnull": true, "default": null}, {"name": "moved_at", "type": "timestamp with time zone", "notnull": true, "default": null}]'::jsonb THEN RAISE EXCEPTION 'F06_MOVEMENT_COLUMNS_DRIFT: %','public.tournament_seat_move_receipts'; END IF;
-- money-trigger-ok: table_seats.a00_f06_source_seat because this asserts its retained enabled binding; the original trigger is not modified.
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.table_seats'::regclass AND tgname='a00_f06_source_seat' AND tgenabled='O' AND NOT tgisinternal AND pg_get_triggerdef(oid)='CREATE TRIGGER a00_f06_source_seat BEFORE INSERT OR DELETE OR UPDATE OF table_id, user_id, seat_number, left_at ON public.table_seats FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_source_guard()') THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','a00_f06_source_seat'; END IF;
-- money-trigger-ok: tournament_players.a00_f06_source_roster because this asserts its retained enabled binding; the original trigger is not modified.
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.tournament_players'::regclass AND tgname='a00_f06_source_roster' AND tgenabled='O' AND NOT tgisinternal AND pg_get_triggerdef(oid)='CREATE TRIGGER a00_f06_source_roster BEFORE INSERT OR DELETE OR UPDATE OF table_id, user_id, seat_number, status ON public.tournament_players FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_source_guard()') THEN RAISE EXCEPTION 'F06_MOVEMENT_BINDING_DRIFT: %','a00_f06_source_roster'; END IF;
END $movement_dependencies$;
-- END CAPTURED MOVEMENT DEPENDENCIES
DO $drained_dependencies$ BEGIN
IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='smarter_private.f06_movement_prior(uuid,uuid)'::regprocedure AND md5(prosrc)='97c4a1afeaa41512026d3dca6936364a' AND md5(pg_get_functiondef(oid))='438d2cbaad05751066393aeadf710228' AND pg_get_userbyid(proowner)='postgres' AND prosecdef AND proacl::text='{postgres=X/postgres}' AND proconfig=ARRAY['search_path=pg_catalog, public, smarter_private']) THEN RAISE EXCEPTION 'F06_DRAINED_DEPENDENCY_DRIFT: f06_movement_prior'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='smarter_private.f06_movement_permits(uuid,uuid,bigint)'::regprocedure AND md5(prosrc)='5588297eb169b5df9bab3f58047b3379' AND md5(pg_get_functiondef(oid))='2ddcf96913de8e87b858c1c207f57ed0' AND pg_get_userbyid(proowner)='postgres' AND prosecdef AND proacl::text='{postgres=X/postgres}' AND proconfig=ARRAY['search_path=pg_catalog, public, smarter_private']) THEN RAISE EXCEPTION 'F06_DRAINED_DEPENDENCY_DRIFT: f06_movement_permits'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='smarter_private.f06_prepared_hand_cancellations'::regclass AND tgname='f06_prepared_cancellation_immutable' AND tgenabled='O' AND pg_get_triggerdef(oid)='CREATE TRIGGER f06_prepared_cancellation_immutable BEFORE DELETE OR UPDATE ON smarter_private.f06_prepared_hand_cancellations FOR EACH ROW EXECUTE FUNCTION smarter_private.f06_prepared_cancellation_immutable()') THEN RAISE EXCEPTION 'F06_DRAINED_PREPARATION_BINDING'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='smarter_private.f06_prepared_cancellation_immutable()'::regprocedure AND md5(prosrc)='55b942212973a9f10ba6a6d3174bf048' AND pg_get_userbyid(proowner)='postgres' AND NOT prosecdef AND proacl::text='{postgres=X/postgres}' AND proconfig=ARRAY['search_path=pg_catalog']) THEN RAISE EXCEPTION 'F06_DRAINED_PREPARATION_GUARD'; END IF;
IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='smarter_private.f06_prepared_hand_cancellations'::regclass AND relrowsecurity AND NOT relforcerowsecurity AND pg_get_userbyid(relowner)='postgres' AND relacl::text='{postgres=arwdDxtm/postgres}') OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='smarter_private.f06_prepared_hand_cancellations'::regclass) OR (SELECT array_agg(attname::text||':'||format_type(atttypid,atttypmod)||':'||attnotnull::text ORDER BY attnum) FROM pg_attribute WHERE attrelid='smarter_private.f06_prepared_hand_cancellations'::regclass AND attnum>0 AND NOT attisdropped) IS DISTINCT FROM ARRAY['permit_id:uuid:true','tournament_id:uuid:true','generation:uuid:true','table_id:uuid:true','lifecycle:bigint:true','hand_number:bigint:true','custody_id:uuid:true','created_at:timestamp with time zone:true'] OR (SELECT array_agg(pg_get_constraintdef(oid) ORDER BY contype) FROM pg_constraint WHERE conrelid='smarter_private.f06_prepared_hand_cancellations'::regclass) IS DISTINCT FROM ARRAY['PRIMARY KEY (permit_id)','UNIQUE (table_id, hand_number)'] THEN RAISE EXCEPTION 'F06_DRAINED_PREPARATION_RELATION'; END IF;
END $drained_dependencies$;
CREATE FUNCTION public.fn_f06_assert_drained_manager_custody(
 p_tournament_id uuid,p_lease_generation uuid,p_origin_generation uuid,
 p_sources jsonb,p_expected jsonb DEFAULT NULL) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,smarter_private AS $$
DECLARE o smarter_private.f06_operations; l public.engine_tournament_leases;
 x jsonb; permit_row smarter_private.f06_hand_permits; u uuid; ids uuid[]; users uuid[]; terminal jsonb:='[]'; witness jsonb; prior jsonb; parks jsonb:='[]'; originals jsonb; pending jsonb; proof jsonb;
BEGIN
 IF auth.role() IS DISTINCT FROM 'service_role' OR p_tournament_id IS NULL
 OR jsonb_typeof(p_sources) IS DISTINCT FROM 'array' THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_SERVICE_REQUIRED' USING ERRCODE='42501'; END IF;
 IF p_lease_generation IS NOT NULL THEN
 PERFORM smarter_private.f06_authority(p_tournament_id,p_lease_generation);
 ELSE
 IF p_origin_generation IS NULL OR jsonb_array_length(p_sources)=0 OR p_expected IS NOT NULL THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_ORIGINAL_REQUIRED' USING ERRCODE='22023'; END IF;
 SELECT * INTO l FROM public.engine_tournament_leases WHERE tournament_id=p_tournament_id FOR KEY SHARE;
 IF FOUND AND (l.lease_generation IS DISTINCT FROM p_origin_generation OR l.protocol_version<>2
 OR l.heartbeat_at>=clock_timestamp()-interval '30 seconds') THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_LEASE_CHANGED' USING ERRCODE='55000'; END IF;
 END IF;
 -- Same lease -> event lane order as the owning F06 request. This function
 -- never writes a lease even when the former row is absent.
 PERFORM public.fn_ca_lock_settlement_lane_for_tournament(p_tournament_id);
 IF p_lease_generation IS NOT NULL THEN PERFORM smarter_private.f06_authority(p_tournament_id,p_lease_generation,false); END IF;
 -- Same sorted physical row order as f06_prefix, including the old-owner
 -- read-only branch where no current generation may be fabricated.
 IF p_lease_generation IS NULL THEN
 SELECT * INTO l FROM public.engine_tournament_leases WHERE tournament_id=p_tournament_id FOR KEY SHARE;
 IF FOUND AND (l.lease_generation IS DISTINCT FROM p_origin_generation OR l.protocol_version<>2
 OR l.heartbeat_at>=clock_timestamp()-interval '30 seconds') THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_LEASE_CHANGED' USING ERRCODE='55000'; END IF;
 END IF;
 SELECT COALESCE(array_agg((value->>'table_id')::uuid ORDER BY value->>'table_id'),'{}') INTO ids FROM jsonb_array_elements(p_sources);
 SELECT COALESCE(array_agg(DISTINCT user_id ORDER BY user_id),'{}') INTO users FROM public.table_seats
 WHERE table_id=ANY(ids) AND user_id IS NOT NULL;
 FOREACH u IN ARRAY users LOOP PERFORM pg_advisory_xact_lock(hashtextextended('table_cap:'||u::text,0)); END LOOP;
 PERFORM 1 FROM public.tournaments WHERE id=p_tournament_id AND upper(status)='RUNNING' FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'F06_DRAINED_CUSTODY_EVENT_CHANGED' USING ERRCODE='55000'; END IF;
 PERFORM 1 FROM public.tournament_players WHERE tournament_id=p_tournament_id AND user_id=ANY(users) ORDER BY user_id FOR UPDATE;
 PERFORM 1 FROM public.tables WHERE id=ANY(ids) ORDER BY id FOR UPDATE;
 PERFORM s.id FROM public.table_seats s JOIN public.tables tb ON tb.id=s.table_id
 WHERE tb.tournament_id=p_tournament_id AND (s.user_id=ANY(users) OR s.table_id=ANY(ids)) ORDER BY s.id FOR UPDATE OF s;
 IF (SELECT count(DISTINCT value->>'table_id') FROM jsonb_array_elements(p_sources))<>jsonb_array_length(p_sources)
 OR (SELECT count(DISTINCT value->>'break_id') FROM jsonb_array_elements(p_sources))<>jsonb_array_length(p_sources)
 OR (jsonb_array_length(p_sources)>0 AND p_origin_generation IS NULL) THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_SOURCE_CHANGED' USING ERRCODE='22023'; END IF;
 FOR x IN SELECT value FROM jsonb_array_elements(p_sources) ORDER BY value->>'table_id' LOOP
 PERFORM 1 FROM public.tables WHERE id=(x->>'table_id')::uuid AND tournament_id=p_tournament_id
 AND f06_lifecycle::text=x->>'lifecycle' AND lower(status)<>'closed' AND NOT COALESCE(is_deleted,false) FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'F06_DRAINED_CUSTODY_SOURCE_CHANGED' USING ERRCODE='55000'; END IF;
 SELECT * INTO o FROM smarter_private.f06_operations WHERE break_id=(x->>'break_id')::uuid FOR SHARE;
 IF NOT FOUND OR (o.tournament_id,o.source_table_id,o.lifecycle,o.origin_generation)
 IS DISTINCT FROM (p_tournament_id,(x->>'table_id')::uuid,(x->>'lifecycle')::bigint,p_origin_generation)
 OR o.state<>'park_requested' OR o.revision<>0 OR o.manifest IS NOT NULL
 OR o.custody_id IS NOT NULL OR o.custody_generation IS NOT NULL OR o.close_receipt IS NOT NULL
 OR o.cleanup_kind IS NOT NULL OR o.abort_receipt_id IS NOT NULL
 OR EXISTS(SELECT 1 FROM smarter_private.f06_members WHERE break_id=o.break_id)
 OR EXISTS(SELECT 1 FROM smarter_private.f06_attempts WHERE break_id=o.break_id) THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_NOT_PREMANIFEST' USING ERRCODE='55000'; END IF;
 -- The already-installed movement authority supplies the original completed
 -- source boundary, including its independent atomic and stack identities.
 prior:=smarter_private.f06_movement_prior(p_tournament_id,o.source_table_id);
 parks:=parks||jsonb_build_array(jsonb_build_object('park',to_jsonb(o),'prior',prior));
 END LOOP;
 SELECT COALESCE(jsonb_agg(to_jsonb(h) ORDER BY h.permit_id),'[]') INTO originals
 FROM smarter_private.f06_hand_permits h WHERE h.tournament_id=p_tournament_id AND h.state='reserved';
 SELECT COALESCE(jsonb_agg(id ORDER BY id),'[]') INTO pending FROM
 (SELECT DISTINCT h.table_id id FROM smarter_private.f06_hand_permits h
 WHERE h.tournament_id=p_tournament_id AND h.state='reserved') q;
 proof:=jsonb_build_object('parks',parks,'originals',originals);
 IF p_expected IS NOT NULL THEN
 IF jsonb_typeof(p_expected) IS DISTINCT FROM 'object' OR p_expected->'parks' IS DISTINCT FROM parks
 OR jsonb_typeof(p_expected->'originals') IS DISTINCT FROM 'array' THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_CHANGED' USING ERRCODE='55000'; END IF;
 IF (SELECT count(DISTINCT value->>'permit_id') FROM jsonb_array_elements(p_expected->'originals'))<>jsonb_array_length(p_expected->'originals')
 OR EXISTS(SELECT 1 FROM jsonb_array_elements(p_expected->'originals') e WHERE e->>'state' IS DISTINCT FROM 'reserved' OR e->'evidence_id' IS DISTINCT FROM 'null'::jsonb) THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_CAPTURE_INVALID' USING ERRCODE='22023'; END IF;
 FOR x IN SELECT value FROM jsonb_array_elements(p_expected->'originals') LOOP
 SELECT * INTO permit_row FROM smarter_private.f06_hand_permits WHERE permit_id=(x->>'permit_id')::uuid FOR SHARE;
 IF NOT FOUND OR permit_row.tournament_id IS DISTINCT FROM p_tournament_id
 OR (to_jsonb(permit_row)-'state'-'evidence_id') IS DISTINCT FROM (x-'state'-'evidence_id') THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_ORIGINAL_CHANGED' USING ERRCODE='55000'; END IF;
 IF to_jsonb(permit_row)=x THEN CONTINUE; END IF;
 witness:=NULL;
 IF permit_row.state='accepted' THEN
 SELECT jsonb_build_object('atomic',to_jsonb(a),'history_id',hh.id) INTO witness
 FROM public.hand_atomic_commits a JOIN public.hand_history hh ON hh.id=a.hand_id
 AND hh.table_id=a.table_id AND hh.hand_number=a.hand_number
 WHERE a.hand_id=permit_row.evidence_id AND a.table_id=permit_row.table_id AND a.hand_number=permit_row.hand_number
 AND a.post_commit_completed_at IS NOT NULL AND isfinite(a.post_commit_completed_at)
 AND a.post_commit_completed_at>=a.committed_at AND a.post_commit_result->'ok'='true'::jsonb
 AND a.post_commit_result->>'hand_id'=a.hand_id::text
 AND (a.post_commit_result->>'hand_number')::bigint=a.hand_number;
 ELSIF permit_row.state='never_started' THEN
 -- Only the immutable preparation receipt is supported here. A generic state
 -- or an old mutable park custody label cannot substitute for original proof.
 SELECT to_jsonb(c) INTO witness FROM smarter_private.f06_prepared_hand_cancellations c
 WHERE c.permit_id=permit_row.permit_id AND permit_row.evidence_id=permit_row.permit_id
 AND (c.tournament_id,c.generation,c.table_id,c.lifecycle,c.hand_number,c.custody_id)
 =(permit_row.tournament_id,permit_row.generation,permit_row.table_id,permit_row.lifecycle,permit_row.hand_number,permit_row.custody_id);
 ELSIF permit_row.state='aborted_unsettled' AND smarter_private.f06_generation_aborted(permit_row.tournament_id,permit_row.generation) THEN
 SELECT r.receipt INTO witness FROM (
 SELECT a.permit_id,a.receipt_id,a.tournament_id,a.generation,a.table_id,a.hand_number,a.expected,
 to_jsonb(a) receipt FROM smarter_private.f06_unsettled_hand_aborts a WHERE a.outcome='aborted_unsettled'
 UNION ALL
 SELECT a.permit_id,a.receipt_id,a.tournament_id,a.generation,a.table_id,a.hand_number,a.expected,
 jsonb_build_object('hand',to_jsonb(a),'receipt',to_jsonb(r)) FROM smarter_private.f06_generation_abort_hands a
 JOIN smarter_private.f06_generation_aborts r USING(receipt_id,tournament_id,generation) WHERE r.outcome='aborted_unsettled'
 UNION ALL
 SELECT a.permit_id,a.receipt_id,a.tournament_id,a.generation,a.table_id,a.hand_number,a.expected,
 jsonb_build_object('hand',to_jsonb(a),'receipt',to_jsonb(r)) FROM smarter_private.f06_mixed_abort_hands a
 JOIN smarter_private.f06_mixed_aborts r USING(receipt_id,tournament_id) WHERE r.outcome='aborted_unsettled') r
 WHERE (r.permit_id,r.receipt_id,r.tournament_id,r.generation,r.table_id,r.hand_number)
 =(permit_row.permit_id,permit_row.evidence_id,permit_row.tournament_id,permit_row.generation,permit_row.table_id,permit_row.hand_number)
 AND r.expected->'permit'=x;
 END IF;
 IF witness IS NULL OR EXISTS(SELECT 1 FROM smarter_private.f06_hand_dispatch WHERE permit_id=permit_row.permit_id) THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_TERMINAL_EVIDENCE_REQUIRED' USING ERRCODE='55000'; END IF;
 terminal:=terminal||jsonb_build_array(jsonb_build_object('permit',to_jsonb(permit_row),'evidence',witness));
 END LOOP;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(originals) h WHERE NOT EXISTS(
 SELECT 1 FROM jsonb_array_elements(p_expected->'originals') e WHERE e=h)) THEN
 RAISE EXCEPTION 'F06_DRAINED_CUSTODY_NEW_ORIGINAL' USING ERRCODE='55000'; END IF;
 proof:=p_expected;
 END IF;
 RETURN jsonb_build_object('ok',true,'tournament_id',p_tournament_id,'lease_generation',p_lease_generation,
 'recovery_required',jsonb_array_length(pending)>0,'pending_tables',pending,'proof',proof,'terminal_proof',terminal);
END $$;
REVOKE ALL ON FUNCTION public.fn_f06_assert_drained_manager_custody(uuid,uuid,uuid,jsonb,jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.fn_f06_assert_drained_manager_custody(uuid,uuid,uuid,jsonb,jsonb) TO service_role;
COMMIT;
