-- APPLIED TO PRODUCTION 2026-08-19 via Supabase MCP as
-- `union_treasury_selftest_and_ledger_completeness`. Mirror only.
--
-- 1. LEDGER COMPLETENESS: the weekly close debited rake_wallet by the full
--    period total but only wrote audit debit rows for the 90% payouts. The
--    retained 10% (+ self-club rake) now writes a paired rake_wallet DEBIT +
--    chip_balance CREDIT (tx_type rake_hold), and the catch-up close's missing
--    retained debit row (109,528.17, period 2026-04-01..2026-08-17) was
--    backfilled -- Sum(credits) - Sum(debits) now reconciles to the balance.
--
-- 2. fn_union_treasury_selftest(): conservation sentinel run by the engine
--    every settler cycle. Per union: non-negative wallets; rake_wallet <=
--    chip_balance (sub-account invariant); |rake_wallet - ledger| <= 150
--    (measured historical pre-atomic drift 122.14); zero duplicate BBJ
--    (pool,hand) pairs; retired pools hold zero; no fully-lapsed unclosed
--    week. Breaches insert deduped critical financial_alerts and are returned
--    to the caller. service_role only.
--
-- 3. NUMERIC HYGIENE: one-time round of union_wallets balances to cents (the
--    chip_balance had float dust); all write paths now round.
--
-- Live verification at apply time: fn_union_treasury_selftest() =>
-- {healthy: true, breaches: []}.
