-- BACKFILLED 2026-09-27 from supabase_migrations.schema_migrations.statements.
-- Applied to production as 20260820132249 "union_law_agent_commission_follows_player_not_table"; the .sql file was never committed
-- at the time. Everything below this header is byte-exact to what ran:
-- md5 b447dc7f08eeab3e08046d87f2adf416 of array_to_string(statements, chr(10)) || chr(10).
-- Do NOT re-apply; it is already live.


-- ============================================================================
-- UNION LAW — AGENT COMMISSION FOLLOWS THE PLAYER, NOT THE TABLE (2026-08-20)
--
-- REGRESSION CAUSED BY UNION HOSTING: both commission paths resolve the
-- player's agent with `club_members.club_id = <the table's club>`. Now that
-- every union game is hosted by the Midway house club, that lookup asks for an
-- agent link on a MIDWAY membership — and Midway has 327 members with ZERO
-- agent links, while the real links live on SHARK (94) and JAQK (90).
--
-- Effect: the entire agent economy stopped. Commissions ran ~17k/hour and fell
-- to zero once the last club-hosted table drained (last row 06:40). 68 agents
-- have been earning nothing since.
--
-- This is exactly the distinction PokerBros draws: an AGENT owns the PLAYER
-- relationship; the union only hosts the game. Rake generated by a player is
-- credited to that player's agent in that player's own club, no matter whose
-- table they are sitting at.
--
-- Fix: resolve the agent from the player's own member club — preferring the
-- club stamped on their seat (real play provenance), then any union member
-- club — and BOOK the commission against that club so club-level settlement
-- stays correct. Both entry points now share one resolver.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.fn_resolve_player_club_for_agent(p_user_id uuid, p_club_hint uuid DEFAULT NULL, p_table_id uuid DEFAULT NULL)
 RETURNS uuid
 LANGUAGE plpgsql STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_union uuid; v_club uuid;
BEGIN
  -- 1. The club stamped on the player's live seat is the truth: it is the club
  --    whose chips they are playing with.
  IF p_table_id IS NOT NULL THEN
    SELECT ts.club_id INTO v_club
      FROM table_seats ts
     WHERE ts.table_id = p_table_id AND ts.user_id = p_user_id AND ts.left_at IS NULL
       AND ts.club_id IS NOT NULL
     LIMIT 1;
    IF v_club IS NOT NULL THEN RETURN v_club; END IF;
  END IF;

  -- 2. The hint is usable only if it is a real member club for this player
  --    with an agent relationship (the union house club never is).
  IF p_club_hint IS NOT NULL AND EXISTS (
       SELECT 1 FROM club_members m
        WHERE m.user_id = p_user_id AND m.club_id = p_club_hint
          AND m.agent_id IS NOT NULL) THEN
    RETURN p_club_hint;
  END IF;

  -- 3. Otherwise fall back to a member club inside the same union that DOES
  --    carry an agent link.
  IF p_club_hint IS NOT NULL THEN
    SELECT COALESCE(uc.union_id, c.union_id) INTO v_union
      FROM clubs c LEFT JOIN union_clubs uc ON uc.club_id = c.id
     WHERE c.id = p_club_hint LIMIT 1;
  END IF;

  IF v_union IS NOT NULL THEN
    SELECT m.club_id INTO v_club
      FROM club_members m
      JOIN union_clubs uc2 ON uc2.club_id = m.club_id AND uc2.union_id = v_union
     WHERE m.user_id = p_user_id AND m.agent_id IS NOT NULL
     ORDER BY m.joined_at ASC NULLS LAST, m.club_id
     LIMIT 1;
    IF v_club IS NOT NULL THEN RETURN v_club; END IF;
  END IF;

  RETURN p_club_hint;
END $function$;

-- Entry point 1 -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.credit_agent_commission_from_rake(p_agent_user_id uuid, p_club_id uuid, p_rake_credit numeric, p_source_type text DEFAULT 'rake_settlement'::text, p_source_id uuid DEFAULT NULL::uuid, p_notes text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_agent_id          UUID;
  v_agent_user_id     UUID;
  v_commission_rate   NUMERIC;
  v_parent_agent_id   UUID;
  v_parent_user_id    UUID;
  v_parent_rate       NUMERIC;
  v_direct_commission NUMERIC;
  v_parent_commission NUMERIC;
  v_remaining         NUMERIC;
  v_book_club         UUID;
  v_inserted_direct   INTEGER := 0;
BEGIN
  IF p_source_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM agent_commissions
     WHERE source_id = p_source_id AND source_type = p_source_type
     LIMIT 1
  ) THEN
    RETURN;
  END IF;

  -- UNION LAW: the agent follows the PLAYER's club, not the table's club.
  v_book_club := public.fn_resolve_player_club_for_agent(p_agent_user_id, p_club_id, NULL);

  SELECT a.id, a.user_id, a.commission_rate, a.parent_agent_id
    INTO v_agent_id, v_agent_user_id, v_commission_rate, v_parent_agent_id
    FROM club_members cm
    JOIN agents a ON a.user_id = cm.agent_id AND a.club_id = cm.club_id AND a.status = 'active'
   WHERE cm.user_id = p_agent_user_id AND cm.club_id = v_book_club
   LIMIT 1;

  -- The caller may itself be an agent generating rake.
  IF v_agent_id IS NULL THEN
    SELECT id, user_id, commission_rate, parent_agent_id
      INTO v_agent_id, v_agent_user_id, v_commission_rate, v_parent_agent_id
      FROM agents WHERE user_id = p_agent_user_id AND status = 'active'
     ORDER BY (club_id = v_book_club) DESC
     LIMIT 1;
  END IF;

  IF v_agent_id IS NULL THEN RETURN; END IF;

  v_direct_commission := ROUND(p_rake_credit * COALESCE(v_commission_rate, 0), 2);
  v_remaining         := p_rake_credit - v_direct_commission;

  IF v_direct_commission > 0 THEN
    INSERT INTO agent_commissions (
      club_id, user_id, amount, commission_rate, source_type, source_id, notes
    ) VALUES (
      COALESCE(v_book_club, p_club_id), v_agent_user_id, v_direct_commission, v_commission_rate,
      p_source_type, p_source_id, COALESCE(p_notes, 'agent slice (accrual)')
    )
    ON CONFLICT (user_id, source_id, source_type) WHERE source_id IS NOT NULL
    DO NOTHING;
    GET DIAGNOSTICS v_inserted_direct = ROW_COUNT;

    IF v_inserted_direct > 0 THEN
      UPDATE agents SET
        weekly_rake_generated   = COALESCE(weekly_rake_generated, 0)   + p_rake_credit,
        lifetime_rake_generated = COALESCE(lifetime_rake_generated, 0) + p_rake_credit,
        last_active_at          = NOW(),
        updated_at              = NOW()
      WHERE id = v_agent_id;
    END IF;
  END IF;

  -- Super-agent override on the downstream volume (PokerBros model).
  IF v_parent_agent_id IS NOT NULL AND v_remaining > 0 THEN
    SELECT id, user_id, commission_rate
      INTO v_parent_agent_id, v_parent_user_id, v_parent_rate
      FROM agents WHERE id = v_parent_agent_id AND status = 'active'
     LIMIT 1;

    IF v_parent_agent_id IS NOT NULL AND v_parent_rate IS NOT NULL THEN
      v_parent_commission := ROUND(v_remaining * v_parent_rate, 2);
      IF v_parent_commission > 0 THEN
        INSERT INTO agent_commissions (
          club_id, user_id, amount, commission_rate, source_type, source_id, notes
        ) VALUES (
          COALESCE(v_book_club, p_club_id), v_parent_user_id, v_parent_commission, v_parent_rate,
          p_source_type, p_source_id, 'super-agent slice (accrual)'
        )
        ON CONFLICT (user_id, source_id, source_type) WHERE source_id IS NOT NULL
        DO NOTHING;
      END IF;
    END IF;
  END IF;
END;
$function$;

-- Entry point 2 -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.calculate_cascading_commission(p_hand_id uuid DEFAULT NULL::uuid, p_club_id uuid DEFAULT NULL::uuid, p_player_user_id uuid DEFAULT NULL::uuid, p_rake_amount numeric DEFAULT 0, p_rake_record_id uuid DEFAULT NULL::uuid, p_table_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_assignment    record;
  v_sub_agent     record;
  v_agent         record;
  v_club_owner_id uuid;
  v_remaining     numeric;
  v_slice         numeric;
  v_rate          numeric;
  v_results       jsonb := '[]'::jsonb;
  v_commission_id uuid;
  v_book_club     uuid;
  v_agent_from_member uuid;
BEGIN
  IF p_rake_amount IS NULL OR p_rake_amount <= 0 OR p_club_id IS NULL OR p_player_user_id IS NULL THEN
    RETURN jsonb_build_object('success', true, 'commissions', v_results, 'skipped', 'missing_inputs');
  END IF;

  v_remaining := p_rake_amount;

  -- UNION LAW: attribute to the player's own club, not the union house club.
  v_book_club := COALESCE(
    public.fn_resolve_player_club_for_agent(p_player_user_id, p_club_id, p_table_id),
    p_club_id);

  SELECT * INTO v_assignment
    FROM public.player_agent_assignments
   WHERE player_id = p_player_user_id AND club_id = v_book_club;

  IF FOUND THEN
    IF v_assignment.sub_agent_id IS NOT NULL THEN
      SELECT s.id, s.parent_agent_id, s.commission_pct, s.user_id
        INTO v_sub_agent
        FROM public.sub_agents s
       WHERE s.id = v_assignment.sub_agent_id AND s.status = 'active';

      IF FOUND THEN
        v_rate := CASE WHEN v_sub_agent.commission_pct > 1
                       THEN v_sub_agent.commission_pct / 100.0
                       ELSE v_sub_agent.commission_pct END;
        v_slice := ROUND(v_remaining * v_rate::numeric, 4);
        IF v_slice > 0 THEN
          INSERT INTO public.agent_commissions
            (club_id, user_id, amount, commission_rate, source_type, source_id, notes)
          VALUES
            (v_book_club, v_sub_agent.user_id, v_slice, v_sub_agent.commission_pct,
             'rake', COALESCE(p_rake_record_id, p_hand_id), 'sub_agent slice')
          RETURNING id INTO v_commission_id;
          v_results := v_results || jsonb_build_object('tier', 'sub_agent',
            'user_id', v_sub_agent.user_id, 'amount', v_slice, 'commission_id', v_commission_id);
          v_remaining := v_remaining - v_slice;
        END IF;

        SELECT id, user_id, commission_rate INTO v_agent
          FROM public.agents WHERE id = v_sub_agent.parent_agent_id AND status = 'active';
      END IF;
    ELSIF v_assignment.agent_id IS NOT NULL THEN
      SELECT id, user_id, commission_rate INTO v_agent
        FROM public.agents WHERE id = v_assignment.agent_id AND status = 'active';
    END IF;
  END IF;

  -- No explicit assignment row: use the club membership's agent link, which is
  -- how this platform actually records the agent/player relationship.
  IF v_agent.id IS NULL THEN
    SELECT cm.agent_id INTO v_agent_from_member
      FROM club_members cm
     WHERE cm.user_id = p_player_user_id AND cm.club_id = v_book_club
       AND cm.agent_id IS NOT NULL
     LIMIT 1;
    IF v_agent_from_member IS NOT NULL THEN
      SELECT id, user_id, commission_rate INTO v_agent
        FROM public.agents
       WHERE user_id = v_agent_from_member AND status = 'active'
       ORDER BY (club_id = v_book_club) DESC
       LIMIT 1;
    END IF;
  END IF;

  IF v_agent.id IS NOT NULL THEN
    v_rate := CASE WHEN v_agent.commission_rate > 1
                   THEN v_agent.commission_rate / 100.0
                   ELSE v_agent.commission_rate END;
    v_slice := ROUND(v_remaining * v_rate::numeric, 4);
    IF v_slice > 0 THEN
      INSERT INTO public.agent_commissions
        (club_id, user_id, amount, commission_rate, source_type, source_id, notes)
      VALUES
        (v_book_club, v_agent.user_id, v_slice, v_agent.commission_rate,
         'rake', COALESCE(p_rake_record_id, p_hand_id), 'agent slice')
      RETURNING id INTO v_commission_id;
      v_results := v_results || jsonb_build_object('tier', 'agent',
        'user_id', v_agent.user_id, 'amount', v_slice, 'commission_id', v_commission_id);
      v_remaining := v_remaining - v_slice;
    END IF;
  END IF;

  SELECT owner_id INTO v_club_owner_id FROM public.clubs WHERE id = v_book_club;
  IF v_club_owner_id IS NOT NULL AND v_remaining > 0 THEN
    INSERT INTO public.agent_commissions
      (club_id, user_id, amount, commission_rate, source_type, source_id, notes)
    VALUES
      (v_book_club, v_club_owner_id, v_remaining, NULL,
       'rake', COALESCE(p_rake_record_id, p_hand_id), 'club owner residual')
    RETURNING id INTO v_commission_id;
    v_results := v_results || jsonb_build_object('tier', 'owner',
      'user_id', v_club_owner_id, 'amount', v_remaining, 'commission_id', v_commission_id);
  END IF;

  UPDATE public.club_wallets
     SET period_commission_paid   = period_commission_paid   + p_rake_amount,
         lifetime_commission_paid = lifetime_commission_paid + p_rake_amount,
         updated_at = NOW()
   WHERE club_id = v_book_club;

  RETURN jsonb_build_object('success', true, 'hand_id', p_hand_id, 'club_id', v_book_club,
    'player_user_id', p_player_user_id, 'rake_amount', p_rake_amount, 'commissions', v_results);
END;
$function$;

