-- ═══════════════════════════════════════════════════════════════════════════
-- CHIP-REMOVAL AUTHORITY POLICY (binding, set by Dan 2026-08-15)
-- ═══════════════════════════════════════════════════════════════════════════
--   1. An AGENT may never remove chips from a downline player's account except
--      through a player-initiated cashout.
--   2. On a cashout REQUEST the chips leave the player's balance immediately
--      (escrow). Already satisfied by fn_request_cashout.
--   3. When the agent ACCEPTS, the chips land in the AGENT's wallet.
--      Previously credited clubs.chip_treasury instead -- fixed here.
--   4. A club OWNER/ADMIN may pull chips from anyone at any time.
--      No such path existed -- added here as fn_admin_remove_player_chips.
--
-- Applied to production via Supabase MCP on 2026-08-15 and verified with a
-- rolled-back probe on Club JAQK:
--   R2 escrow_immediate=PASS (player 5000->3800)
--   R3 to_agent_wallet=PASS  (agent  100->1300)
--   R1 agent_blocked=PASS
--   R4 admin_allowed=PASS    (player 3800->3300, club pool +500)
--
-- This file mirrors the applied migrations
--   cashout_credits_agent_wallet_and_admin_chip_removal
--   whitelist_admin_chip_removal_in_wallet_guard
-- See the Supabase migration history for the authoritative applied copies.

-- Rule 3: approval moves the escrowed chips to the APPROVING AGENT.
-- (Full body applied in migration `cashout_credits_agent_wallet_and_admin_chip_removal`.)
-- Key change vs the previous version:
--     -  UPDATE clubs SET chip_treasury = chip_treasury + amount ...
--     +  UPDATE club_members SET chip_balance = chip_balance + amount
--     +   WHERE club_id = <cashout club> AND user_id = <approving agent>
-- The player was already debited at request time, so this is the credit leg of
-- that same movement: club chips are conserved, never minted.

-- Rule 4: owner/admin-only chip removal. Agents are explicitly refused.
--   fn_admin_remove_player_chips(p_club_id, p_player_id, p_amount, p_reason)
--   - SECURITY DEFINER, actor derived from auth.uid() (unspoofable)
--   - requires club_members.role IN ('owner','co_owner','admin')
--   - row-locks the member, refuses on insufficient balance
--   - returns the chips to clubs.chip_pool
--   - writes a chip_transactions row (transaction_type 'admin_removal')
--   - GRANT EXECUTE TO authenticated, service_role

-- Guard: fn_admin_remove_player_chips writes clubs.chip_pool, which is protected
-- by the Phase 4.1.6a balance guard, so it (plus fn_approve_cashout_atomic and
-- fn_cancel_cashout_atomic) were added to guard_wallet_balance_write's whitelist
-- rather than bypassing the guard.
