-- 20260830b_alarm_grace_must_exceed_heal_grace.sql
-- APPLIED TO PRODUCTION 2026-08-30 via Supabase MCP
-- (migration: bbj_drift_grace_must_exceed_heal_grace). Body in the history.
--
-- THE LAST FALSE-ALARM SOURCE, found by the final check.
--
-- The window bug was already fixed (bbj_drift_since joins by hand id). What
-- remained was a GRACE MISMATCH between each alarm and its own healer:
--
--   bbj_drift_since             ignored hands younger than 2 minutes
--   fn_bbj_repair_unbanked      ignores hands younger than 5 minutes
--   fn_rake_bbj_invariants I5/I7 ignored hands younger than 5 minutes
--   fn_rake_repair_unbanked     ignores hands younger than 5 minutes
--
-- So hands in the 2-5 minute band (and, for the invariants, hands at exactly
-- the moment they first became repairable) were judged by an alarm while the
-- healer that exists to fix that very condition was deliberately not touching
-- them. On a fleet banking ~8,500 BBJ hands per 6 hours that band is never
-- empty, so the alarms fired routinely for money that was banked seconds
-- later. GameServer already repairs BEFORE auditing for exactly this reason;
-- the grace mismatch defeated that ordering.
--
-- AN ALARM MUST NEVER FIRE ON A CONDITION ITS OWN REPAIR IS STILL WAITING TO
-- ACT ON. bbj_drift_since -> 6 minutes (> the healer's 5). The two
-- self-healing invariants (I5 drop-not-banked, I7 raked-hand-never-banked)
-- -> 15 minutes, past the hourly healers' worst case. The RULE checks
-- (I1-I4, I6) keep the 5-minute grace: nothing heals a broken rule, so there
-- is nothing to wait for.
--
-- Real losses are still caught — they simply have to survive one heal cycle
-- first, which is the definition of "the net did not catch it".
--
-- Verified after: BBJ drift 0.00, all seven invariants 0, attribution drift
-- 0, fee queue 0, on live traffic.
SELECT 'applied via MCP as bbj_drift_grace_must_exceed_heal_grace' AS notice;
