-- Saved copy of the migration applied to production 2026-08-30 ~20:32 UTC via
-- Supabase MCP (name: complete_two_outage_stranded_tournaments).
--
-- COMPLETE THE TWO TOURNAMENTS THE 2026-08-30 OUTAGE STRANDED IN COMPLETING.
-- recoverStuckCompletingTournaments refused both on position collisions and
-- asked for review; this is that review, executed:
--
-- 1. 0dc034bc "20 Chip Spin NLH" (pool 40, winner-take-all): winner already
--    paid 40; the lone survivor finished 2nd (pays 0). No money moved.
-- 2. 56385309 "$100 Freeroll 6:00 AM" (pool 261): places 2..362 held except
--    350; places 2-9 already paid 182.70. Chip leader (3,994,298) took
--    place 1, paid 78.30 under the recovery watchdog's own idempotency key
--    (tourney:{id}:prize:place:1) — completing the pool at exactly 261.00.
--    The 5,000-chip survivor took the one open place, 350 (pays 0).
--
-- Both events flipped COMPLETED, tables closed. Guarded by pre-checks
-- (still COMPLETING, survivor sets unchanged, places 1/350 free) and
-- post-assertions (no survivors remain, freeroll prizes sum to the pool).
-- The full executed SQL lives in the applied migration of the same name.
