-- ===========================================================================
--  THE DIAMOND CASH FELT REOPENS
-- ===========================================================================
--
-- 20261006154844_the_diamond_cash_felt_reopens.sql. Version reserved by
-- scripts/new-migration.mjs against origin/main and every remote branch.
--
-- Poker Arena Diamond build programme, the release switch.
--
-- THE DECISION THIS CARRIES OUT. It is Dan's. He opened Diamond cash games
-- himself for his certified run in the early hours of 2026-10-06
-- (docs/evidence/diamond-phase-12/certified-run-2026-10-06.md, "Switches":
-- cash_games_enabled = true, "opened by Dan after the run").
-- 20261006021858_the_arena_cash_switch_returns_to_closed found the column true
-- at 02:12 UTC, could not trace who had set it, and closed it again. That was
-- a mistake: the open was Dan's. Later on 2026-10-06 Dan answered the list of
-- pending production steps, which included reopening Diamond cash games once
-- the rake path is live and a Diamond cash hand is proved to settle, with
-- "YES, GO AHEAD AND PROCEED".
--
-- THE CONDITIONS 20261006021858 SET, AND HOW EACH IS MET. It said cash should
-- open once B4 to B10 are answered and the engine sends the three stack keys.
--
--   B4 to B13   answered in ca_diamond_economics (20261005183028); every one
--               of the 17 Diamond cash stakes has its cap at all three
--               dealt-in brackets.
--   the keys    the engine sends contributed, dealt_in and hand_saw_flop on
--               every Diamond seat (#6268) and prices the hand by the owner's
--               settings (#6288). engine.smarter.poker/health serves release
--               9fdbf692, which contains both.
--   the door    20261006154344 lets a raked Diamond hand through the commit
--               door, which refused every one of them as
--               post_commit_fee_mismatch. This file refuses to open cash
--               unless that fix is live (step 1 below).
--
-- THE PROOF THAT A HAND SETTLES, run before this file was written. One real
-- NLH 1/2 hand was played by the engine's own HandController under
-- production's settings and handed to its own postHandTasks and
-- logHandHistory; their exact request was replayed against production in a
-- single ROLLED-BACK transaction, with 20261006154344 applied inside it and
-- cash opened only inside it: two 200-Diamond buy-ins through
-- atomic_table_buyin, a lease through claim_table_lease_v2, a hand number from
-- fn_next_hand_number, then fn_ca_retain_hand_submission and
-- fn_ca_commit_hand_submission, every deferred commit-time check forced. The
-- hand settled: pot 400, flop seen, rake 15 (the engine's number and the
-- settler's recompute agree), accrued 8 and 7 to its two payers by
-- WEIGHTED_CONTRIBUTED, stacks 0 and 385 in custody, receipts written, the
-- hand projected, both players cashed out to their wallets (2500 -> 2300 and
-- 2500 -> 2685), no chip rake or chip ledger row touched, and the sweep banked
-- the 15 to ca_diamond_house, the destination the owner settings name (B11).
-- The Diamond identity (players + house + arena custody and accrual, against
-- the register) read 0 at every step. Without the door fix the same request
-- was refused.
--
-- WHAT THIS DOES. One UPDATE of one column of one row, opening cash and
-- leaving tournaments alone. They are open on Dan's decision and players may
-- be using them, so the pre-image requires them true and the post-image
-- requires them still true. If cash is already true when this runs, this says
-- so and does nothing.
--
-- It defines no function, no trigger and no cron, and adds no watcher:
-- tests/only-a-person-moves-the-arena-switches.law.test.ts admits exactly
-- this - a migration's own statement, run once when a person applies it.
-- Do not edit this file. To close cash games, a forward migration sets the
-- column false, on Dan's word.
--
-- @live-proof: (SELECT cash_games_enabled FROM public.ca_arena_settings WHERE id = 1) = true
-- @live-proof: (SELECT tournaments_enabled FROM public.ca_arena_settings WHERE id = 1) = true
-- ===========================================================================

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

DO $mig$
DECLARE
  v_cash_before  boolean;
  v_tourn_before boolean;
  v_cash_after   boolean;
  v_tourn_after  boolean;
  v_rows         integer;
BEGIN
  -- 1. THE DOOR FIRST. Open cash on a commit door that still refuses every
  --    raked Diamond hand and the felt would deal hands it cannot settle.
  IF position('OR (v_diamond' IN pg_get_functiondef(
       'public.fn_ca_commit_hand_settlement(uuid,bigint,jsonb,numeric,numeric,text,numeric,jsonb,jsonb,text,uuid,jsonb)'::regprocedure)) = 0
     OR position('IF (NOT v_diamond AND (' IN pg_get_functiondef(
       'public.fn_ca_commit_hand_settlement(uuid,bigint,jsonb,numeric,numeric,text,numeric,jsonb,jsonb,text,uuid,jsonb)'::regprocedure)) = 0 THEN
    RAISE EXCEPTION 'the Diamond cash felt does not open: the commit door still refuses a raked Diamond hand; apply 20261006154344 first';
  END IF;

  -- 2. PRE-IMAGE. The row is taken for update first, so nothing moves it
  --    between the read and the write.
  SELECT cash_games_enabled, tournaments_enabled
    INTO v_cash_before, v_tourn_before
    FROM public.ca_arena_settings WHERE id = 1 FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'the Diamond cash felt does not open: no settings row with id = 1';
  END IF;

  -- Already open, by Dan's own hand or an earlier run of this file. Nothing
  -- to do, and that is not a failure.
  IF v_cash_before IS TRUE THEN
    RAISE NOTICE 'Diamond cash games are already open; nothing to do';
    RETURN;
  END IF;

  -- Tournaments are open on Dan's decision and this file must not disturb
  -- them. If they are not open, the board has moved in some way nobody
  -- expected; refuse and let a person look.
  IF v_tourn_before IS NOT TRUE THEN
    RAISE EXCEPTION 'the Diamond cash felt does not open: tournaments read % before the update and are expected open; refusing to act on a board nobody has looked at', v_tourn_before;
  END IF;

  -- 3. THE SWITCH. One row, one column.
  UPDATE public.ca_arena_settings
     SET cash_games_enabled = true
   WHERE id = 1 AND cash_games_enabled IS NOT TRUE;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows <> 1 THEN
    RAISE EXCEPTION 'the Diamond cash felt does not open: expected to move exactly 1 settings row, moved %', v_rows;
  END IF;

  -- 4. POST-IMAGE. Cash open, tournaments untouched, and still one row.
  SELECT cash_games_enabled, tournaments_enabled
    INTO v_cash_after, v_tourn_after
    FROM public.ca_arena_settings WHERE id = 1;

  IF v_cash_after IS NOT TRUE THEN
    RAISE EXCEPTION 'the Diamond cash felt does not open: cash reads % after the update and must be true', v_cash_after;
  END IF;
  IF v_tourn_after IS NOT TRUE THEN
    RAISE EXCEPTION 'the Diamond cash felt does not open: tournaments read % after the update and must still be true', v_tourn_after;
  END IF;
  IF (SELECT count(*) FROM public.ca_arena_settings) <> 1 THEN
    RAISE EXCEPTION 'the Diamond cash felt does not open: the settings table holds other than one row';
  END IF;

  RAISE NOTICE 'Diamond Arena cash games are open again, on Dan''s decision of 2026-10-06. Tournaments stay open.';
END
$mig$;

COMMIT;
