-- Applied to production 2026-08-26 as `baseline_the_unledgered_gap`,
-- `make_drift_check_fast_enough_to_run` and `drift_check_must_see_debits_too`.
--
-- 1,496 of 1,502 live-pool rows had NO ledger history. That cannot be
-- reconstructed, and inventing it would be fabricating an audit trail. So the
-- gap (121,186,345.42) is WRITTEN DOWN in ca_chip_baseline rather than smeared
-- into the ledger, and reconciliation runs forward from the line.
--
-- Two bugs of my own, both caught by the numbers refusing to be zero:
--   1. A LATERAL over an unindexed 88k-row chip_ledger timed out. A check
--      nobody can afford to run is a check nobody runs.
--   2. `coalesce(to_entity_id, from_entity_id)` identified the player. The new
--      trigger populates BOTH sides, so every DEBIT resolved to the club and
--      vanished: 80 members read as drifting, net -18,963, which was exactly
--      the buy-ins going unseen. Match on whichever side is player_wallet.
