-- APPLIED TO PRODUCTION 2026-08-19 via Supabase MCP as
-- `fn_club_money_panel_for_wallet_widget`. Mirror only.
--
-- WALLET PANEL AUDIT — one authoritative, permission-aware read for the
-- DynamicWallet widget, replacing three direct table reads plus a serial
-- second round trip.
--
-- The three defects it closes:
--
--  1. WRONG BY PERMISSION. `union_wallets` is RLS-restricted to union
--     owners/admins. A CLUB owner inside a union read nothing and the panel
--     printed "Union Bank 0.00 / Rake Treasury 0.00" as fact. The function
--     returns a `scope` ('union' | 'club' | 'member'), so the client renders
--     "—" for what it may not see instead of inventing a zero.
--
--  2. WRONG SOURCE. The union variant's "Clubs Wallet" read
--     clubs.chip_pool of the ONE selected club — the mint-and-distribute
--     ledger, not a union figure, and 0.00 for a union whose clubs hold 800k.
--     Now: SUM(chip_treasury) across member clubs.
--
--  3. REGRESSIBLE RULE. Union-first BBJ pool resolution lived in client code
--     and was removed by a merge (714738896). Since both club pools were
--     merged into the union pool and retired the same day, a club_id lookup
--     now finds a retired, permanently-zero row — a 0.00 jackpot on screen
--     with 14k in the pool. The rule now lives here, server-side, once.
--
-- Also returns what the money is FOR, which the panel had no way to say:
-- club_projected_rakeback (this club's 90% at the next close),
-- projected_clubs_share / projected_union_share, next_close_at, and
-- union_bank_unreserved (bank minus the rake treasury held inside it, so the
-- two can never be read as separate pots that sum).
--
-- Verified live against production with simulated identities:
--   union owner -> scope 'union', all figures present
--   plain member -> scope 'member', zero leakage of union_bank /
--                   rake_treasury / clubs_wallet / club rake
--   no auth     -> authorized:false
--
-- Full body lives in production (pg_get_functiondef); signature:
--   fn_club_money_panel(p_club_id uuid) RETURNS jsonb
--   STABLE SECURITY DEFINER, GRANT EXECUTE TO authenticated, service_role.
