-- UNRECOVERABLE STUB (2026-09-01 migration backfill).
--
-- This migration WAS applied to production at 20260830120000, but its SQL was not
-- committed and supabase_migrations.schema_migrations.statements is EMPTY for
-- it - the Supabase migration runner recorded the version with no statement
-- text, so the exact SQL cannot be recovered from anywhere. Its EFFECT is live
-- in the schema; this file exists only so the applied-migrations gate reflects
-- reality (version recorded) rather than flagging a phantom gap forever.
--
-- If you need to know what it did, read the schema objects it touched (the
-- name is the clue: "commerce_event_ordering_and_subscription_claims") against a nearby dated backup, or the PR that
-- carried it. Do NOT invent SQL here and do NOT re-run anything.
SELECT 'applied 20260830120000: commerce_event_ordering_and_subscription_claims (statements not preserved)' AS unrecoverable_backfill_note;
