-- CASHIER: the two features the Trade view was only PRETENDING to have
-- (Dan 2026-08-21: "finish up everything thats still pending and not finished").
-- Applied to production via Supabase MCP apply_migration on 2026-08-21.
--
-- 1. chip_requests    — a player asks their agent/owner for chips; approval
--    performs the same conserved club-ledger move as a cashier Send Out, so a
--    request can never create chips. Self-approval is refused. Agent-tier may
--    only answer requests addressed to them. Max 3 open requests per player.
-- 2. tournament_tickets — "Send Ticket" issues a real redeemable buy-in credit.
--    Issuing ESCROWS the value off the issuer immediately; redeeming credits
--    the holder; cancelling refunds the issuer. Chips conserved at every step.
--
-- Verified live 2026-08-21: issue 50 (issuer -50, holder unchanged), cancel
-- (issuer +50 back), self-approve refused, requester cancel works, net zero.
--
-- RLS: both tables are readable by the two parties and club staff; every write
-- goes through the SECURITY DEFINER RPCs (no insert/update policy exists).
--
-- ROLLBACK:
--   drop function public.fn_respond_chip_request(uuid, text);
--   drop function public.fn_request_chips(uuid, numeric, text);
--   drop function public.fn_redeem_tournament_ticket(uuid);
--   drop function public.fn_cancel_tournament_ticket(uuid);
--   drop function public.fn_issue_tournament_ticket(uuid, uuid, numeric, text);
--   drop table public.chip_requests; drop table public.tournament_tickets;
--
-- Full body as applied lives in the Supabase migration history under
-- `chip_requests_and_tournament_tickets`.
