-- Applied to production 2026-08-27 as `the_bot_flag_cannot_drift_again`.
--
-- 985 of 1,487 horses - 66% of the fleet, 74,572,743.02 chips - were flagged
-- club_members.is_bot = false while profiles.is_horse said true.
--
-- ROOT CAUSE, a missing line rather than bad logic: HorseOnboarding.ts inserted
-- the membership without is_bot at all, so the column took its `false` default.
-- Nothing anywhere had EVER written is_bot = true. The insert is fixed in the
-- same commit.
--
-- SAFE TO CORRECT, checked rather than assumed (the previous migration left it
-- alone precisely until this was done):
--   * ZERO application readers in either repo - no .eq('is_bot'), no branch.
--     Every consequential horse check keys on profiles.is_horse.
--   * fn_membership_starts_with_zero_chips is BEFORE INSERT and tests
--     `is_bot OR profiles.is_horse`; all 985 satisfy the second half already.
--   * fn_club_union_join_blockers excludes on BOTH flags, so it was never
--     fooled.
--
-- ONE REAL BEHAVIOUR CHANGE, called out rather than buried: mass_fund_horses
-- counts `is_bot AND is_active` and divides a FIXED p_amount across it. It now
-- sees 1,487 instead of 502, so a run spreads the SAME TOTAL in ~one-third
-- shares. It does not spend more, and funding the whole fleet is what the flag
-- always meant - but the per-horse figure changed. Manual admin RPC; nothing
-- happens until it is called.
--
-- Probed rolled-back first: 985 -> 0, and setting a horse back to false comes
-- back true.
