-- ═══════════════════════════════════════════════════════════════════════════════
-- BUG 009 FIX — Agent Commission Never Credited
-- ═══════════════════════════════════════════════════════════════════════════════
-- DISCOVERY (2026-04-15 live verification):
--   - 68 agents in DB, ZERO have any pending_commission / weekly_rake_generated
--     / lifetime_earnings despite $30,136.94 in rake recorded last 7 days
--   - server engine has ZERO references to queueCommissionCredits, agent_commissions,
--     pending_commission — the agent commission flow is in src/services/RakeService.ts
--     (CLIENT) and was never ported to server engine
--   - The existing increment_agent_rake RPC tries to UPDATE profiles.rake_generated
--     but that column DOES NOT EXIST (silent UPDATE 0 rows, no error thrown)
--
-- FIX:
--   Replace increment_agent_rake to update the correct table (agents) and the
--   correct columns (weekly_rake_generated + lifetime_rake_generated +
--   pending_commission). Also add a helper add_agent_commission_credit that
--   credits commission via integer-arithmetic-safe percentage of rake.
-- ═══════════════════════════════════════════════════════════════════════════════

-- 1. Replace increment_agent_rake to update the AGENTS table, not profiles
CREATE OR REPLACE FUNCTION public.increment_agent_rake(p_agent_id uuid, p_amount numeric)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_commission_rate NUMERIC;
  v_commission NUMERIC;
BEGIN
  -- Look up commission rate
  SELECT commission_rate INTO v_commission_rate
  FROM agents WHERE id = p_agent_id;

  IF v_commission_rate IS NULL THEN
    -- Agent doesn't exist or rate not set — silently no-op
    RETURN;
  END IF;

  -- Commission = rake credited × commission_rate (rate is fraction, e.g. 0.30)
  v_commission := ROUND(p_amount * v_commission_rate, 2);

  UPDATE agents SET
    weekly_rake_generated  = COALESCE(weekly_rake_generated, 0)  + p_amount,
    lifetime_rake_generated = COALESCE(lifetime_rake_generated, 0) + p_amount,
    pending_commission     = COALESCE(pending_commission, 0)     + v_commission,
    last_active_at         = NOW(),
    updated_at             = NOW()
  WHERE id = p_agent_id;
END;
$$;

COMMENT ON FUNCTION public.increment_agent_rake(uuid, numeric) IS
  'BUG 009 FIX (2026-04-15) — credits an agent with rake generated by their downline; '
  'updates weekly_rake_generated, lifetime_rake_generated, and pending_commission '
  '(= p_amount * commission_rate). Replaces the old broken version that targeted '
  'profiles.rake_generated (column did not exist, silent no-op).';

-- 2. Helper to also write to agent_commissions audit table
CREATE OR REPLACE FUNCTION public.credit_agent_commission_from_rake(
  p_agent_user_id uuid,
  p_club_id uuid,
  p_rake_credit numeric,
  p_source_type text DEFAULT 'rake_settlement',
  p_source_id uuid DEFAULT NULL,
  p_notes text DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_agent_id UUID;
  v_commission_rate NUMERIC;
  v_commission NUMERIC;
BEGIN
  SELECT id, commission_rate
  INTO v_agent_id, v_commission_rate
  FROM agents
  WHERE user_id = p_agent_user_id AND club_id = p_club_id AND status = 'active'
  LIMIT 1;

  IF v_agent_id IS NULL THEN
    RETURN; -- player not associated with an agent in this club
  END IF;

  v_commission := ROUND(p_rake_credit * COALESCE(v_commission_rate, 0), 2);
  IF v_commission <= 0 THEN
    RETURN;
  END IF;

  -- 1. Update agent accumulator (weekly + lifetime + pending)
  UPDATE agents SET
    weekly_rake_generated  = COALESCE(weekly_rake_generated, 0)  + p_rake_credit,
    lifetime_rake_generated = COALESCE(lifetime_rake_generated, 0) + p_rake_credit,
    pending_commission     = COALESCE(pending_commission, 0)     + v_commission,
    last_active_at         = NOW(),
    updated_at             = NOW()
  WHERE id = v_agent_id;

  -- 2. Audit row in agent_commissions
  INSERT INTO agent_commissions (
    club_id, user_id, amount, commission_rate, source_type, source_id, notes
  ) VALUES (
    p_club_id, p_agent_user_id, v_commission, v_commission_rate, p_source_type, p_source_id, p_notes
  );
END;
$$;

COMMENT ON FUNCTION public.credit_agent_commission_from_rake IS
  'BUG 009 FIX (2026-04-15) — credits an agent commission from a downline player''s '
  'rake. Updates agents.pending_commission + writes audit row to agent_commissions. '
  'NOTE: function renamed from credit_agent_commission to avoid collision with an '
  'existing single-arg version (uuid, numeric, text default).';

-- 3. Verify
SELECT
  'BUG_009_VERIFY' AS check,
  proname,
  CASE WHEN prosecdef THEN 'PASS' ELSE 'FAIL' END AS sec_def
FROM pg_proc
WHERE proname IN ('increment_agent_rake', 'credit_agent_commission_from_rake')
ORDER BY proname;
