-- EVERY CHIP OF UNION RAKE KNOWS WHICH CLUB'S PLAYER PAID IT
-- Chip Accounting Standard Phase 2.1, part two. Dan, 2026-09-03 (binding):
-- "ITS NOT 90% OF THEIR OWN TABLES, ITS 90% OF THE RAKE GENERATED BY THE
-- PLAYERS INSIDE THE CLUB, WHILE PLAYING ON THE MIDWAY UNION CASH TABLES,
-- MTT'S, SPINS AND SIT N GO'S."
--
-- WHAT WAS WRONG. The union treasury's rake credits carry the TABLE's club.
-- Union tables belong to the union's house club, so the weekly close saw
-- 362,165 of 362,361 credits (1,136,306.50 of 1,137,573.70, week of 08-24)
-- as the union's own and would have shared 1,140.48 of a 962,179.99 week
-- with the two member clubs. The member clubs' players generated nearly all
-- of it.
--
-- WHERE THE PLAYER'S CLUB IS. A player sits at a union table THROUGH a club:
-- table_seats.club_id is stamped on every seat (40,273 of 40,274 seats
-- joined today carry it - 22,205 Club JAQK, 21,063 SHARK CLUB), and
-- tournament_players.club_id on every tournament entry (21,949 / 20,658
-- today). club_members cannot decide it: 399 of 401 players seen at union
-- tables in 24h are members of BOTH member clubs. rake_records carries each
-- player's pot contribution (player_contributions), which is the
-- "contributed rake" basis the union apps use.
--
-- WHY A TABLE, NOT A LOOKUP AT CLOSE TIME. Seat rows are mutable and
-- short-lived: for the week of 08-24, 264,505 of 347,445 union hands had no
-- seat row still covering the hand's timestamp (706,051.34 of 803,027.83
-- unattributable), while for hands played in the last hour a seat is found
-- for 89.5% of contributions by table and ~100% by player and time. The
-- attribution must therefore be captured while the seat is fresh - hourly -
-- and kept, so that the close reads a durable fact rather than a memory.
--
-- THE RULE:
--   ca_union_rake_attribution: one row per (rake record, contributing
--     player) at a union-owned table: the player's club (from the seat open
--     at the hand's time, same table preferred, else the player's latest seat
--     covering that instant), and the player's share of the hand's rake in
--     proportion to pot contribution. NULL club = unattributed; retried on
--     the next runs until the record is 6 hours old.
--   fn_ca_attribute_union_rake(p_hours): SECURITY DEFINER, service_role only,
--     idempotent upsert over the last p_hours of union-table rake records.
--     Writes attribution rows only. Moves nothing.
--   cron ca-union-rake-attribution-hourly at :20.
-- Tournament rake (MTT, SNG, spin) needs no table: the treasury credit names
-- the tournament and tournament_players names each entrant's club. The close
-- (next migration) splits each tournament credit by entries (1 + rebuys +
-- add-on) per club.
--
-- One transaction: table, index, function, grants, cron, a seed of the last
-- two hours, and a self-check.

BEGIN;

CREATE TABLE IF NOT EXISTS public.ca_union_rake_attribution (
  rake_record_id uuid        NOT NULL,
  user_id        uuid        NOT NULL,
  union_id       uuid        NOT NULL,
  table_id       uuid,
  hand_id        uuid,
  played_at      timestamptz NOT NULL,
  club_id        uuid,
  rake_share     numeric(14,4) NOT NULL DEFAULT 0,
  attempts       smallint    NOT NULL DEFAULT 1,
  attributed_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (rake_record_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_ca_union_rake_attr_union_played
  ON public.ca_union_rake_attribution (union_id, played_at);
CREATE INDEX IF NOT EXISTS idx_ca_union_rake_attr_open
  ON public.ca_union_rake_attribution (played_at) WHERE club_id IS NULL;

ALTER TABLE public.ca_union_rake_attribution ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ca_union_rake_attribution FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.ca_union_rake_attribution TO service_role;

CREATE OR REPLACE FUNCTION public.fn_ca_attribute_union_rake(p_hours integer DEFAULT 3)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_since timestamptz := now() - make_interval(hours => GREATEST(1, LEAST(COALESCE(p_hours, 3), 168)));
  v_rows int := 0; v_attributed int := 0; v_unattributed int := 0;
  v_records int := 0;
BEGIN
  IF COALESCE(auth.role(), 'service_role') <> 'service_role' THEN
    RAISE EXCEPTION 'service_role only' USING ERRCODE = '42501';
  END IF;

  /* the hands: rake at a table owned by a union's house club (tables.club_id
     = the union's id), in the window, either never attributed or still
     carrying an unattributed player under six hours old */
  CREATE TEMP TABLE _ura_hands ON COMMIT DROP AS
  SELECT r.id AS rake_record_id, r.hand_id, r.table_id, r.club_id AS union_id,
         r.created_at AS played_at, r.rake_amount, r.player_contributions
    FROM public.rake_records r
   WHERE r.is_tournament IS NOT TRUE
     AND r.rake_amount > 0
     AND r.created_at >= v_since
     AND r.player_contributions IS NOT NULL
     AND EXISTS (SELECT 1 FROM public.unions u WHERE u.id = r.club_id)
     AND (NOT EXISTS (SELECT 1 FROM public.ca_union_rake_attribution a WHERE a.rake_record_id = r.id)
          OR EXISTS (SELECT 1 FROM public.ca_union_rake_attribution a
                      WHERE a.rake_record_id = r.id AND a.club_id IS NULL
                        AND a.attempts < 6 AND r.created_at >= now() - interval '6 hours'));
  SELECT count(*) INTO v_records FROM _ura_hands;

  CREATE TEMP TABLE _ura_contrib ON COMMIT DROP AS
  SELECT h.rake_record_id, h.hand_id, h.table_id, h.union_id, h.played_at, h.rake_amount,
         (x.key)::uuid AS user_id, (x.value)::numeric AS contrib,
         sum((x.value)::numeric) OVER (PARTITION BY h.rake_record_id) AS total
    FROM _ura_hands h, jsonb_each_text(h.player_contributions) x
   WHERE (x.value)::numeric > 0;

  /* the seat covering the hand's instant: same table first, else the
     player's latest seat that covers it */
  CREATE TEMP TABLE _ura_attr ON COMMIT DROP AS
  SELECT c.rake_record_id, c.user_id, c.union_id, c.table_id, c.hand_id, c.played_at,
         COALESCE(
           (SELECT s.club_id FROM public.table_seats s
             WHERE s.table_id = c.table_id AND s.user_id = c.user_id
               AND s.joined_at <= c.played_at
               AND COALESCE(s.left_at, 'infinity'::timestamptz) >= c.played_at - interval '2 minutes'
               AND s.club_id IS NOT NULL
             ORDER BY s.joined_at DESC LIMIT 1),
           (SELECT s.club_id FROM public.table_seats s
             WHERE s.user_id = c.user_id
               AND s.joined_at <= c.played_at
               AND COALESCE(s.left_at, 'infinity'::timestamptz) >= c.played_at - interval '2 minutes'
               AND s.club_id IS NOT NULL
             ORDER BY s.joined_at DESC LIMIT 1)
         ) AS club_id,
         round(c.rake_amount * c.contrib / NULLIF(c.total, 0), 4) AS rake_share
    FROM _ura_contrib c;

  INSERT INTO public.ca_union_rake_attribution AS a
        (rake_record_id, user_id, union_id, table_id, hand_id, played_at, club_id, rake_share, attempts, attributed_at)
  SELECT rake_record_id, user_id, union_id, table_id, hand_id, played_at, club_id, COALESCE(rake_share, 0), 1, now()
    FROM _ura_attr
  ON CONFLICT (rake_record_id, user_id) DO UPDATE
     SET club_id       = COALESCE(EXCLUDED.club_id, a.club_id),
         rake_share    = EXCLUDED.rake_share,
         attempts      = a.attempts + 1,
         attributed_at = now();
  GET DIAGNOSTICS v_rows = ROW_COUNT;

  SELECT count(*) FILTER (WHERE club_id IS NOT NULL), count(*) FILTER (WHERE club_id IS NULL)
    INTO v_attributed, v_unattributed
    FROM _ura_attr;

  RETURN jsonb_build_object('since', v_since, 'records', v_records, 'rows', v_rows,
                            'attributed', v_attributed, 'unattributed', v_unattributed);
END $function$;

REVOKE ALL ON FUNCTION public.fn_ca_attribute_union_rake(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_ca_attribute_union_rake(integer) TO service_role;

-- hourly at :20, the same advisory-lock shape as the other ca-* jobs
SELECT cron.unschedule(jobid) FROM cron.job WHERE jobname = 'ca-union-rake-attribution-hourly';
SELECT cron.schedule('ca-union-rake-attribution-hourly', '20 * * * *',
  $cron$ SELECT CASE WHEN pg_try_advisory_lock(hashtext('ca-union-rake-attribution'))
       THEN (public.fn_ca_attribute_union_rake(3))::text ELSE 'locked' END; $cron$);

-- seed: the last two hours here (small, inside the migration's transaction);
-- the last 24 hours are seeded right after apply from a session with no
-- statement timeout, and the hourly job carries it from there
SELECT public.fn_ca_attribute_union_rake(2);

DO $$
DECLARE v_n bigint; v_att bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'ca-union-rake-attribution-hourly') THEN
    RAISE EXCEPTION 'the attribution job is not scheduled';
  END IF;
  SELECT count(*), count(*) FILTER (WHERE club_id IS NOT NULL) INTO v_n, v_att FROM public.ca_union_rake_attribution;
  IF v_n = 0 THEN RAISE EXCEPTION 'the seed wrote no attribution rows'; END IF;
  IF v_att < v_n * 0.5 THEN
    RAISE EXCEPTION 'fewer than half of the seeded contributions found a seat (% of %)', v_att, v_n;
  END IF;
  IF has_function_privilege('authenticated', 'public.fn_ca_attribute_union_rake(integer)', 'EXECUTE') THEN
    RAISE EXCEPTION 'fn_ca_attribute_union_rake is reachable from a browser role';
  END IF;
END $$;

COMMIT;
