-- APPLIED TO PRODUCTION 2026-08-20 via Supabase MCP as
--   `rake_lands_only_in_rake_treasury_not_union_bank`
--   `weekly_close_pays_from_treasury_and_sentinel_invariant`
-- Mirror only.
--
-- Dan, looking at the live panel: "RAKE IS STILL GOING TO THE UNION BANK
-- INSTEAD OF THE RAKE TREASURY." He was right.
--
-- Every rake credit incremented BOTH union_wallets.chip_balance (Union Bank)
-- and union_wallets.rake_wallet (Rake Treasury) — the treasury was modelled as
-- a sub-account INSIDE the bank, so the bank climbed with every raked hand.
-- The spec is that rake is held by the union ONLY under the Rake Treasury,
-- for the week, then 90% back to clubs and the union keeps 10%. That makes
-- them SEPARATE pots:
--
--   Rake Treasury = this week's rake, held in trust for the Monday close
--   Union Bank    = the union's OWN money (retained 10%, deposits)
--
-- Changed: atomic_distribute_rake, increment_union_wallet and
-- record_tournament_buyin_rake credit rake_wallet only; the weekly close now
-- pays the clubs OUT OF the treasury and moves only the retained share into
-- the bank, with its solvency guard on the treasury (where the chips are).
--
-- One-time correction, in the same transaction as the function swap so a
-- concurrent credit is either counted the old way before the row lock or the
-- new way after commit: chip_balance -= rake_wallet. Union Bank went
-- 630,802.14 -> 120,895.24; the removed 509,906.90 was never the union's to
-- spend. A union_wallet_transactions row records it.
--
-- The sentinel's "rake_wallet <= chip_balance" invariant described the old
-- nested model and would now fire on every healthy union; replaced with
-- non-negativity on both accounts.
--
-- VERIFIED LIVE over 2 minutes after the change: Union Bank moved 0.00 while
-- the Rake Treasury took +342.03, and BBJ main/backup kept funding.
