-- APPLIED TO PRODUCTION 2026-08-19 via Supabase MCP as
-- `union_weekly_close_selfhealing_and_index` +
-- `union_rakeback_period_alignment_guards`. Mirror only.
--
-- AUDIT PASS 2, DEFECTS #7 + #8:
--
-- #7 The engine weekly close attempted only the single most recent lapsed week
--    and its daemon watermark advanced even if the union close failed -- any
--    Monday outage lost that week's rakeback forever.
--    fn_union_weekly_rakeback_close_all(p_union_id default null) now closes
--    EVERY unclosed lapsed ISO week, resuming from MAX(period_end) in
--    union_rakeback_log (or the first treasury credit), jumping misaligned
--    legacy periods forward to the next Monday (never re-covering paid days),
--    stopping on a rejected close so it retries next run. The engine calls
--    this instead of per-week closes. fn_execute_union_rakeback (owner manual
--    trigger) now REJECTS non-ISO-week periods to keep the cadence aligned.
--    fn_union_weekly_rakeback_close gained a DROP TABLE IF EXISTS temp-table
--    guard and raises a durable financial_alerts row when a close is rejected
--    for insufficient treasury.
--
-- #8 CREATE INDEX idx_uwt_rake_credit_basis
--      ON union_wallet_transactions (union_id, created_at)
--      WHERE wallet='rake_wallet' AND direction='credit' AND tx_type='rake';
--    (the weekly-close basis scan had no serving index).
