-- ═══════════════════════════════════════════════════════════════════════
-- 20260820_spin_reserve_affordability_gate.sql
-- ═══════════════════════════════════════════════════════════════════════
-- TIER: 2  |  AFFECTS: fn_spin_draw_multiplier, fn_spin_settle_game,
--                      fn_spin_sweep_unbooked (new), v_spin_reserve_health (new)
-- IRREVERSIBLE: no  |  APPLIED: 2026-08-20
--
-- WHY — a real production defect found in the post-cutover audit:
--   The original gate only guarded 100x and 500x. But ANY tier above ~2.76x
--   pays out more than three buy-ins bring in: a 4x pays 4B against a 2.76B
--   contribution. On a pool without a cushion even a 4x is unaffordable.
--
--   In production this aborted fn_spin_settle_game on the non-negative CHECK
--   constraint, and because the engine treats settlement as best-effort the
--   game then ran UNBOOKED — no ledger row, no rake record. Exactly the class
--   of hole this system was built to close, reintroduced by an incomplete
--   gate. Observed on 3 live spins within 20 minutes of the cutover.
--
-- WHAT CHANGED:
--   1. fn_spin_draw_multiplier excludes any tier the pool cannot fund,
--      counting this game's own contribution as available. Jackpot thresholds
--      remain as a stricter gate on top. New params p_rake_rate, p_seats.
--   2. fn_spin_settle_game gains a graceful shortfall path: the pool is drawn
--      to exactly zero and the operator shortfall RECORDED, so the game is
--      booked and the gap is visible. Aborting was strictly worse — players
--      were paid either way, so it only deleted the evidence.
--   3. fn_spin_sweep_unbooked(mins): backstop that settles any spin that
--      slipped through. Idempotent, so it is safe to run on a schedule.
--   4. v_spin_reserve_health: per-club solvency, thin-pool flag, shortfall
--      count and unbooked-24h count. A draining pool does not error — its
--      ladder quietly collapses toward 2x/3x, which players feel long before
--      any exception fires.
--
-- The full applied SQL is recorded in the Supabase migration history under
-- the names `spin_reserve_affordability_gate` and
-- `spin_reserve_sweeper_and_health`. This file is the durable record of WHY.
--
-- POST-APPLY (all verified 2026-08-20):
--   SELECT * FROM v_spin_reserve_health;              -- 0 unbooked, 0 shortfalls
--   SELECT fn_spin_sweep_unbooked(240);               -- settled 0, failed 0
-- ═══════════════════════════════════════════════════════════════════════
