-- THE WEEKLY UNION CLOSE SHARES THE RAKE A CLUB'S PLAYERS GENERATED
-- Chip Accounting Standard Phase 2.1, part three. Dan, 2026-09-03 (binding):
-- "ITS NOT 90% OF THEIR OWN TABLES, ITS 90% OF THE RAKE GENERATED BY THE
-- PLAYERS INSIDE THE CLUB, WHILE PLAYING ON THE MIDWAY UNION CASH TABLES,
-- MTT'S, SPINS AND SIT N GO'S. MAKE SURE ITS DOWN EXACTLY LIKE THAT."
--
-- WHAT CHANGES. fn_union_weekly_rakeback_close computed each member club's
-- basis from the club stamped on the treasury credit, which is the TABLE's
-- club: at the union's own tables that is the union itself, so the clubs'
-- basis was the rake from their own tables only (1,267.20 of a 962,179.99
-- week, 08-24..08-31). The basis is now the rake the CLUB'S PLAYERS
-- generated at the union's games:
--   cash        ca_union_rake_attribution (part two): each contributing
--               player's share of each union-table hand's rake, by pot
--               contribution, with the club of the seat they sat through
--   tournaments each treasury credit that names a tournament (MTT, SNG,
--               spin - the credit carries "[tournament <id>]"), split
--               between the entrants' clubs by entries (1 + rebuys + add-on)
-- payout per club = trunc(basis x club_commission_rate) as before. The
-- period total is still everything the treasury received; the union keeps
-- the house club's players' rake and whatever could not be attributed, and
-- the settlement row records the basis per club. The money section, the
-- separate pots, the op keys and the conservation assert of part one are
-- untouched. A basis that exceeds the treasury (a data fault) refuses the
-- close before any movement.
--
-- Also: the attribution gains a third fallback. A torn-down table deletes
-- its seat rows, so a hand played minutes before the teardown had no seat
-- covering it (666.92 of 6,811.92 in the two-hour seed, players who were
-- demonstrably at that table and sit through the same club every day). The
-- club the player last sat through in the past seven days is the club they
-- play through.
--
-- IS THIS THE CLUBGG / POKERBROS MODEL? Yes. In those apps a union pays each
-- member club a negotiated percentage of the rake that club's players
-- generated at union games, computed on contributed rake per player, with
-- the union keeping the rest; jackpot drops are outside it. That is exactly
-- this: 90% (club_commission_rate) of the club's players' contributed rake
-- at the union's cash tables and tournaments, BBJ drops excluded because
-- they never enter the rake treasury. The one thing those apps do that this
-- does not is let a union set a different percentage per club and per game
-- type; club_commission_rate is per club already, and a per-game-type rate
-- would be a schema addition, not a rule change.
--
-- Two CREATE OR REPLACE statements, one transaction, and a self-check.

BEGIN;

CREATE OR REPLACE FUNCTION public.fn_ca_attribute_union_rake(p_hours integer DEFAULT 3)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_since timestamptz := now() - make_interval(hours => GREATEST(1, LEAST(COALESCE(p_hours, 3), 168)));
  v_rows int := 0; v_attributed int := 0; v_unattributed int := 0;
  v_records int := 0;
BEGIN
  IF COALESCE(auth.role(), 'service_role') <> 'service_role' THEN
    RAISE EXCEPTION 'service_role only' USING ERRCODE = '42501';
  END IF;

  /* the hands: rake at a table owned by a union's house club (tables.club_id
     = the union's id), in the window, either never attributed or still
     carrying an unattributed player under six hours old */
  CREATE TEMP TABLE _ura_hands ON COMMIT DROP AS
  SELECT r.id AS rake_record_id, r.hand_id, r.table_id, r.club_id AS union_id,
         r.created_at AS played_at, r.rake_amount, r.player_contributions
    FROM public.rake_records r
   WHERE r.is_tournament IS NOT TRUE
     AND r.rake_amount > 0
     AND r.created_at >= v_since
     AND r.player_contributions IS NOT NULL
     AND EXISTS (SELECT 1 FROM public.unions u WHERE u.id = r.club_id)
     AND (NOT EXISTS (SELECT 1 FROM public.ca_union_rake_attribution a WHERE a.rake_record_id = r.id)
          OR EXISTS (SELECT 1 FROM public.ca_union_rake_attribution a
                      WHERE a.rake_record_id = r.id AND a.club_id IS NULL
                        AND a.attempts < 6 AND r.created_at >= now() - interval '6 hours'));
  SELECT count(*) INTO v_records FROM _ura_hands;

  CREATE TEMP TABLE _ura_contrib ON COMMIT DROP AS
  SELECT h.rake_record_id, h.hand_id, h.table_id, h.union_id, h.played_at, h.rake_amount,
         (x.key)::uuid AS user_id, (x.value)::numeric AS contrib,
         sum((x.value)::numeric) OVER (PARTITION BY h.rake_record_id) AS total
    FROM _ura_hands h, jsonb_each_text(h.player_contributions) x
   WHERE (x.value)::numeric > 0;

  /* the seat covering the hand's instant: same table first, else the
     player's latest seat that covers it */
  CREATE TEMP TABLE _ura_attr ON COMMIT DROP AS
  SELECT c.rake_record_id, c.user_id, c.union_id, c.table_id, c.hand_id, c.played_at,
         COALESCE(
           (SELECT s.club_id FROM public.table_seats s
             WHERE s.table_id = c.table_id AND s.user_id = c.user_id
               AND s.joined_at <= c.played_at
               AND COALESCE(s.left_at, 'infinity'::timestamptz) >= c.played_at - interval '2 minutes'
               AND s.club_id IS NOT NULL
             ORDER BY s.joined_at DESC LIMIT 1),
           (SELECT s.club_id FROM public.table_seats s
             WHERE s.user_id = c.user_id
               AND s.joined_at <= c.played_at
               AND COALESCE(s.left_at, 'infinity'::timestamptz) >= c.played_at - interval '2 minutes'
               AND s.club_id IS NOT NULL
             ORDER BY s.joined_at DESC LIMIT 1),
           /* the seat row itself may be gone (a table torn down deletes its
              seats): the club the player last sat through in the past week
              is the club they play through */
           (SELECT s.club_id FROM public.table_seats s
             WHERE s.user_id = c.user_id
               AND s.joined_at <= c.played_at
               AND s.joined_at >= c.played_at - interval '7 days'
               AND s.club_id IS NOT NULL
             ORDER BY s.joined_at DESC LIMIT 1)
         ) AS club_id,
         round(c.rake_amount * c.contrib / NULLIF(c.total, 0), 4) AS rake_share
    FROM _ura_contrib c;

  INSERT INTO public.ca_union_rake_attribution AS a
        (rake_record_id, user_id, union_id, table_id, hand_id, played_at, club_id, rake_share, attempts, attributed_at)
  SELECT rake_record_id, user_id, union_id, table_id, hand_id, played_at, club_id, COALESCE(rake_share, 0), 1, now()
    FROM _ura_attr
  ON CONFLICT (rake_record_id, user_id) DO UPDATE
     SET club_id       = COALESCE(EXCLUDED.club_id, a.club_id),
         rake_share    = EXCLUDED.rake_share,
         attempts      = a.attempts + 1,
         attributed_at = now();
  GET DIAGNOSTICS v_rows = ROW_COUNT;

  SELECT count(*) FILTER (WHERE club_id IS NOT NULL), count(*) FILTER (WHERE club_id IS NULL)
    INTO v_attributed, v_unattributed
    FROM _ura_attr;

  RETURN jsonb_build_object('since', v_since, 'records', v_records, 'rows', v_rows,
                            'attributed', v_attributed, 'unattributed', v_unattributed);
END $function$;


CREATE OR REPLACE FUNCTION public.fn_union_weekly_rakeback_close(p_union_id uuid, p_period_start timestamp with time zone, p_period_end timestamp with time zone)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_wallet       public.union_wallets%ROWTYPE;
  v_period_total numeric := 0;
  v_payout_total numeric := 0;
  v_retained     numeric := 0;
  v_clubs_paid   integer := 0;
  v_club         record;
  v_new_rw       numeric;
  v_new_cb       numeric;
  v_rw_before    numeric;
  v_cb_before    numeric;
  v_clubs_before numeric := 0;
  v_clubs_after  numeric := 0;
  v_credit       jsonb;
  v_sref         text;
  v_sid          uuid;
  v_sstate       text;
  v_actor        uuid;
BEGIN
  -- EMERGENCY SETTLEMENT LOCK CHECK
  IF EXISTS (SELECT 1 FROM settlement_locks WHERE lock_type = 'GLOBAL_SETTLEMENT_FREEZE' AND is_active = true) THEN
    RAISE EXCEPTION 'EMERGENCY_PROFIT_DRIFT_LOCK';
  END IF;

  IF p_union_id IS NULL OR p_period_start IS NULL OR p_period_end IS NULL
     OR p_period_end <= p_period_start THEN
    RETURN jsonb_build_object('success', false, 'error', 'bad_params');
  END IF;

  IF EXISTS (SELECT 1 FROM public.union_settlement_floor f
              WHERE f.union_id = p_union_id
                AND p_period_start < f.earliest_period_start) THEN
    RETURN jsonb_build_object('success', false, 'error', 'before_settlement_floor');
  END IF;

  IF EXISTS (
    SELECT 1 FROM union_rakeback_log
     WHERE union_id = p_union_id
       AND period_start = p_period_start AND period_end = p_period_end
  ) THEN
    RETURN jsonb_build_object('success', false, 'error', 'already_executed');
  END IF;

  -- settlement walk: one row per (union, period), resumable after 'failed'
  v_sref := p_union_id::text || ':'
    || to_char(p_period_start at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') || '..'
    || to_char(p_period_end   at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"');

  SELECT id, state INTO v_sid, v_sstate
    FROM ca_settlements
   WHERE settlement_type = 'union_rakeback_close' AND external_ref = v_sref
   FOR UPDATE;
  IF v_sid IS NULL THEN
    INSERT INTO ca_settlements (id, settlement_type, external_ref, state, union_id, totals)
    VALUES (gen_random_uuid(), 'union_rakeback_close', v_sref, 'open', p_union_id, '{}'::jsonb)
    RETURNING id INTO v_sid;
  ELSIF v_sstate = 'final' THEN
    RETURN jsonb_build_object('success', false, 'error', 'already_executed', 'settlement_id', v_sid);
  ELSIF v_sstate = 'failed' THEN
    UPDATE ca_settlements SET state = 'open', error_detail = NULL WHERE id = v_sid;  -- resume
  ELSE
    -- intermediate states never persist (single transaction), so anything
    -- else here is a concurrent close of the same period. Refuse loudly.
    RETURN jsonb_build_object('success', false, 'error', 'close_already_in_state_' || v_sstate,
                              'settlement_id', v_sid);
  END IF;

  UPDATE ca_settlements SET state = 'locked_for_calculation' WHERE id = v_sid;

  SELECT * INTO v_wallet FROM union_wallets WHERE union_id = p_union_id FOR UPDATE;
  IF v_wallet.union_id IS NULL THEN
    UPDATE ca_settlements SET state = 'failed', error_detail = 'no_wallet' WHERE id = v_sid;
    RETURN jsonb_build_object('success', false, 'error', 'no_wallet', 'settlement_id', v_sid);
  END IF;

  /* THE PERIOD (unchanged): everything the rake treasury received. */
  DROP TABLE IF EXISTS _uwrb_credits;
  CREATE TEMP TABLE _uwrb_credits ON COMMIT DROP AS
  SELECT t.id, t.amount, t.notes, t.created_at,
         substring(t.notes from '\[tournament ([0-9a-f-]+)\]')::uuid AS tournament_id
    FROM union_wallet_transactions t
   WHERE t.union_id = p_union_id
     AND t.wallet = 'rake_wallet' AND t.direction = 'credit' AND t.tx_type = 'rake'
     AND t.created_at >= p_period_start AND t.created_at < p_period_end;

  /* THE BASIS (Dan, 2026-09-03): each member club's share is the rake ITS
     PLAYERS generated at the union's tables - cash from
     ca_union_rake_attribution (the seat the player sat through, captured
     hourly), tournaments / SNGs / spins from tournament_players (each
     treasury credit that names a tournament, split by entries: 1 + rebuys +
     add-on). The union's own house club and anything unattributed stay
     with the union. */
  DROP TABLE IF EXISTS _uwrb;
  CREATE TEMP TABLE _uwrb ON COMMIT DROP AS
  WITH cash AS (
    SELECT a.club_id, sum(a.rake_share) AS rake
      FROM ca_union_rake_attribution a
     WHERE a.union_id = p_union_id
       AND a.played_at >= p_period_start AND a.played_at < p_period_end
       AND a.club_id IS NOT NULL
     GROUP BY a.club_id
  ), tw AS (
    SELECT tp.tournament_id, tp.club_id,
           sum(1 + COALESCE(tp.rebuys, 0) + CASE WHEN tp.add_on THEN 1 ELSE 0 END)::numeric AS w
      FROM tournament_players tp
     WHERE tp.tournament_id IN (SELECT tournament_id FROM _uwrb_credits WHERE tournament_id IS NOT NULL)
     GROUP BY tp.tournament_id, tp.club_id
  ), tt AS (
    SELECT tournament_id, sum(w) AS total FROM tw GROUP BY tournament_id
  ), tourney AS (
    SELECT tw.club_id, sum(c.amount * tw.w / NULLIF(tt.total, 0)) AS rake
      FROM _uwrb_credits c
      JOIN tw ON tw.tournament_id = c.tournament_id
      JOIN tt ON tt.tournament_id = c.tournament_id
     WHERE tw.club_id IS NOT NULL
     GROUP BY tw.club_id
  ), basis AS (
    SELECT club_id, sum(rake) AS rake_in FROM (
      SELECT club_id, rake FROM cash
      UNION ALL
      SELECT club_id, rake FROM tourney) x
     GROUP BY club_id
  )
  SELECT b.club_id,
         round(b.rake_in, 2) AS rake_in,
         trunc(round(b.rake_in, 2) * COALESCE(uc.club_commission_rate, 0.90) * 100) / 100 AS payout
    FROM basis b
    JOIN union_clubs uc ON uc.union_id = p_union_id AND uc.club_id = b.club_id
   WHERE b.club_id <> p_union_id;

  SELECT round(COALESCE(SUM(amount), 0), 2) INTO v_period_total FROM _uwrb_credits;
  SELECT round(COALESCE(SUM(payout), 0), 2) INTO v_payout_total
    FROM _uwrb WHERE club_id IS NOT NULL AND club_id <> p_union_id;
  v_retained := round(v_period_total - v_payout_total, 2);

  /* a share can never exceed what the treasury received: the attribution is
     a view of the same credits, so this only trips on a data fault */
  IF v_payout_total > v_period_total THEN
    UPDATE ca_settlements SET state = 'failed', error_detail = 'attribution_exceeds_treasury' WHERE id = v_sid;
    RETURN jsonb_build_object('success', false, 'error', 'attribution_exceeds_treasury',
      'period_rake', v_period_total, 'payout', v_payout_total, 'settlement_id', v_sid);
  END IF;

  UPDATE ca_settlements
     SET state = 'calculated',
         totals = jsonb_build_object('period_rake', v_period_total, 'payout_total', v_payout_total,
                                     'retained', v_retained,
                                     'basis', 'players_of_the_club_at_union_tables',
                                     'basis_by_club', (SELECT COALESCE(jsonb_object_agg(club_id::text, rake_in), '{}'::jsonb) FROM _uwrb))
   WHERE id = v_sid;

  IF v_period_total <= 0 THEN
    INSERT INTO union_rakeback_log (union_id, period_start, period_end, total_rakeback, executed_at)
    VALUES (p_union_id, p_period_start, p_period_end, 0, now());
    UPDATE ca_settlements SET state = 'validated' WHERE id = v_sid;
    UPDATE ca_settlements SET state = 'ledger_posted' WHERE id = v_sid;
    UPDATE ca_settlements SET state = 'post_commit_verified' WHERE id = v_sid;
    UPDATE ca_settlements SET state = 'final' WHERE id = v_sid;
    RETURN jsonb_build_object('success', true, 'clubs_paid', 0,
      'period_rake', 0, 'total_rakeback', 0, 'union_retained', 0, 'note', 'no_rake',
      'settlement_id', v_sid);
  END IF;

  /* SEPARATE POTS (Phase 2.1). The rake treasury owes the whole period: the
     clubs' share leaves it as rakeback, the union's share leaves it for the
     general bank. The general bank is never a source. A treasury that cannot
     cover the period refuses the close whole - never partial, never from the
     bank - and says so. Who eats a short treasury is Dan's ruling
     (roadmap decision 4). */
  IF v_period_total > COALESCE(v_wallet.rake_wallet, 0) THEN
    UPDATE ca_settlements SET state = 'failed', error_detail = 'insufficient_rake_treasury' WHERE id = v_sid;
    PERFORM public.fn_ca_raise_drift_incident(
      'rakeback_close', 'incorrect_rakeback', 'critical',
      'rakeback-insufficient:' || p_union_id::text || ':' || to_char(p_period_start, 'YYYY-MM-DD'),
      v_period_total - COALESCE(v_wallet.rake_wallet, 0),
      v_period_total,
      COALESCE(v_wallet.rake_wallet, 0),
      'settlement', 'union', p_union_id, NULL, p_union_id,
      NULL, NULL, NULL, v_sid::text, NULL, NULL,
      'union rake treasury cannot cover the period it owes; close refused before any movement (the general bank is never a source)',
      true,
      jsonb_build_object('rake_wallet', v_wallet.rake_wallet,
                         'chip_balance', v_wallet.chip_balance,
                         'period_total', v_period_total,
                         'payout', v_payout_total, 'retained', v_retained,
                         'period_start', p_period_start, 'period_end', p_period_end));
    RETURN jsonb_build_object('success', false, 'error', 'insufficient_rake_treasury', 'retryable', true,
      'period_rake', v_period_total, 'payout', v_payout_total,
      'rake_wallet', v_wallet.rake_wallet, 'chip_balance', v_wallet.chip_balance,
      'settlement_id', v_sid);
  END IF;

  UPDATE ca_settlements SET state = 'validated' WHERE id = v_sid;

  -- ── guarded money section: all of it lands, or none of it does ────────────
  BEGIN
    /* One declaration for every balance write below. The union_wallets
       auto-ledger is skipped: the union side of each club credit is the
       from-leg of the club's own row, and the retained share is written
       explicitly. */
    PERFORM public.fn_ca_declare_ledger('rakeback', 'union_wallet', p_union_id, v_sid, NULL,
                                        ARRAY['union_wallets']);
    v_actor := COALESCE(auth.uid(), '2d1cd6c3-5700-4af9-a271-d4863fdab20d'::uuid);

    v_rw_before := round(COALESCE(v_wallet.rake_wallet, 0), 2);
    v_cb_before := round(COALESCE(v_wallet.chip_balance, 0), 2);
    SELECT round(COALESCE(SUM(c.chip_treasury), 0), 2) INTO v_clubs_before
      FROM clubs c
     WHERE c.id IN (SELECT club_id FROM _uwrb
                     WHERE club_id IS NOT NULL AND club_id <> p_union_id AND payout > 0);

    FOR v_club IN
      SELECT club_id, rake_in, payout FROM _uwrb
       WHERE club_id IS NOT NULL AND club_id <> p_union_id AND payout > 0
    LOOP
      v_credit := fn_credit_treasury(
        v_club.club_id, v_club.payout,
        'Union weekly rakeback ' || to_char(p_period_start, 'YYYY-MM-DD')
          || '..' || to_char(p_period_end, 'YYYY-MM-DD'),
        jsonb_build_object('union_id', p_union_id,
                           'period_start', p_period_start, 'period_end', p_period_end,
                           'rake_basis', v_club.rake_in, 'rate', 'club_commission_rate',
                           'settlement_id', v_sid),
        'union_close:' || v_sid::text || ':' || v_club.club_id::text
      );
      IF COALESCE((v_credit->>'success')::boolean, false) IS NOT TRUE THEN
        RAISE EXCEPTION 'treasury credit failed for club %: %', v_club.club_id, v_credit;
      END IF;
      v_clubs_paid := v_clubs_paid + 1;
    END LOOP;

    -- one debit per pot: the treasury pays the whole period; the retained
    -- share moves to the general bank
    UPDATE union_wallets
       SET rake_wallet       = rake_wallet - v_period_total,
           chip_balance      = chip_balance + v_retained,
           total_settlements = COALESCE(total_settlements, 0) + v_payout_total,
           updated_at        = now()
     WHERE union_id = p_union_id
     RETURNING round(rake_wallet, 2), round(chip_balance, 2) INTO v_new_rw, v_new_cb;

    INSERT INTO union_wallet_transactions
      (union_id, club_id, amount, tx_type, wallet, direction, balance_after, notes)
    SELECT p_union_id, club_id, payout, 'rakeback', 'rake_wallet', 'debit', v_new_rw,
           'Weekly rakeback to club at club_commission_rate (period '
             || to_char(p_period_start, 'YYYY-MM-DD') || '..'
             || to_char(p_period_end, 'YYYY-MM-DD') || ')'
      FROM _uwrb
     WHERE club_id IS NOT NULL AND club_id <> p_union_id AND payout > 0;

    IF v_retained > 0 THEN
      INSERT INTO union_wallet_transactions
        (union_id, amount, tx_type, wallet, direction, balance_after, notes)
      VALUES
        (p_union_id, v_retained, 'rake_hold', 'rake_wallet', 'debit', v_new_rw,
         'Union retained share + self-club rake, out of the rake treasury (period '
           || to_char(p_period_start, 'YYYY-MM-DD') || '..'
           || to_char(p_period_end, 'YYYY-MM-DD') || ')'),
        (p_union_id, v_retained, 'rake_hold', 'chip_balance', 'credit', v_new_cb,
         'Union retained share + self-club rake, into the general bank (period '
           || to_char(p_period_start, 'YYYY-MM-DD') || '..'
           || to_char(p_period_end, 'YYYY-MM-DD') || ')');

      INSERT INTO public.chip_ledger
        (performed_by, from_type, from_entity_id, to_type, to_entity_id,
         amount, category, union_id, description, idempotency_key, metadata)
      VALUES
        (v_actor, 'union_wallet', p_union_id, 'union_bank', p_union_id,
         v_retained, 'treasury_transfer', p_union_id,
         'Weekly union close ' || to_char(p_period_start, 'YYYY-MM-DD') || '..'
           || to_char(p_period_end, 'YYYY-MM-DD')
           || ': retained share ' || v_retained || ' of period rake ' || v_period_total
           || ' moves from the rake treasury to the general bank (clubs paid '
           || v_payout_total || ')',
         'union_close:' || v_sid::text || ':retained',
         jsonb_build_object('settlement_id', v_sid, 'period_start', p_period_start,
                            'period_end', p_period_end, 'period_rake', v_period_total,
                            'payout_total', v_payout_total, 'clubs_paid', v_clubs_paid));
    END IF;

    /* CONSERVATION, ASSERTED ON THE BALANCES THEMSELVES (not on the plan).
       What left the treasury must equal what the clubs and the bank received,
       to the cent, or none of it lands. */
    SELECT round(COALESCE(SUM(c.chip_treasury), 0), 2) INTO v_clubs_after
      FROM clubs c
     WHERE c.id IN (SELECT club_id FROM _uwrb
                     WHERE club_id IS NOT NULL AND club_id <> p_union_id AND payout > 0);

    IF round((v_new_rw - v_rw_before) + (v_new_cb - v_cb_before) + (v_clubs_after - v_clubs_before), 2) <> 0
       OR round(v_new_rw - v_rw_before, 2) <> round(-v_period_total, 2)
       OR round(v_clubs_after - v_clubs_before, 2) <> round(v_payout_total, 2)
       OR round(v_new_cb - v_cb_before, 2) <> round(v_retained, 2) THEN
      RAISE EXCEPTION 'conservation violation in the weekly union close: treasury % -> %, bank % -> %, clubs % -> %, period % payout % retained %',
        v_rw_before, v_new_rw, v_cb_before, v_new_cb, v_clubs_before, v_clubs_after,
        v_period_total, v_payout_total, v_retained;
    END IF;

    UPDATE ca_settlements
       SET state = 'ledger_posted',
           totals = totals || jsonb_build_object('clubs_paid', v_clubs_paid,
                                                 'retained', v_retained,
                                                 'rw_debit', v_period_total,
                                                 'conservation', 'asserted')
     WHERE id = v_sid;

    INSERT INTO union_rakeback_log (union_id, period_start, period_end, total_rakeback, executed_at)
    VALUES (p_union_id, p_period_start, p_period_end, v_payout_total, now());

  EXCEPTION WHEN OTHERS THEN
    -- every money movement above just rolled back to the section start
    UPDATE ca_settlements
       SET state = 'failed', error_detail = left(SQLERRM, 2000)
     WHERE id = v_sid;
    PERFORM public.fn_ca_raise_drift_incident(
      'rakeback_close', 'incorrect_rakeback', 'critical',
      'rakeback-close-failed:' || p_union_id::text || ':' || to_char(p_period_start, 'YYYY-MM-DD'),
      0, NULL, NULL,
      'settlement', 'union', p_union_id, NULL, p_union_id,
      NULL, NULL, NULL, v_sid::text, NULL, NULL,
      left('weekly rakeback close aborted mid-flight and rolled back cleanly: ' || SQLERRM, 500),
      true,
      jsonb_build_object('sqlstate', SQLSTATE,
                         'period_start', p_period_start, 'period_end', p_period_end,
                         'clubs_paid_before_abort', v_clubs_paid));
    RETURN jsonb_build_object('success', false, 'error', 'close_failed', 'retryable', true,
      'detail', SQLERRM, 'settlement_id', v_sid);
  END;

  UPDATE ca_settlements SET state = 'post_commit_verified' WHERE id = v_sid;
  UPDATE ca_settlements SET state = 'final' WHERE id = v_sid;

  RETURN jsonb_build_object('success', true,
    'clubs_paid', v_clubs_paid,
    'period_rake', v_period_total,
    'total_rakeback', v_payout_total,
    'union_retained', v_retained,
    'retained_to_bank', v_retained,
    'rake_wallet_after', v_new_rw,
    'chip_balance_after', v_new_cb,
    'conservation', 'asserted',
    'settlement_id', v_sid);
END $function$;


-- Not a browser door: the cascade and the cron call it as the engine or a union overseer.
REVOKE ALL ON FUNCTION public.fn_union_weekly_rakeback_close(uuid, timestamptz, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_union_weekly_rakeback_close(uuid, timestamptz, timestamptz) TO service_role;
REVOKE ALL ON FUNCTION public.fn_ca_attribute_union_rake(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_ca_attribute_union_rake(integer) TO service_role;

DO $$
DECLARE v_src text;
BEGIN
  SELECT prosrc INTO v_src FROM pg_proc
   WHERE proname = 'fn_union_weekly_rakeback_close' AND pronamespace = 'public'::regnamespace;
  IF v_src NOT LIKE '%FROM ca_union_rake_attribution a%' OR v_src NOT LIKE '%FROM tournament_players tp%' THEN
    RAISE EXCEPTION 'the close does not read the players'' clubs';
  END IF;
  IF v_src LIKE '%GROUP BY t.club_id, uc.club_commission_rate%' THEN
    RAISE EXCEPTION 'the close still shares by the table''s club';
  END IF;
  IF v_src NOT LIKE '%attribution_exceeds_treasury%' OR v_src NOT LIKE '%conservation violation in the weekly union close%'
     OR v_src NOT LIKE '%rake_wallet       = rake_wallet - v_period_total%' THEN
    RAISE EXCEPTION 'part one of the close did not survive part three';
  END IF;
  SELECT prosrc INTO v_src FROM pg_proc
   WHERE proname = 'fn_ca_attribute_union_rake' AND pronamespace = 'public'::regnamespace;
  IF v_src NOT LIKE '%s.joined_at >= c.played_at - interval ''7 days''%' THEN
    RAISE EXCEPTION 'the attribution has no last-seat fallback';
  END IF;
END $$;

COMMIT;
