-- BACKFILLED 2026-09-27 from supabase_migrations.schema_migrations.statements.
-- Applied to production as 20260820134040 "union_law_p2_agent_settlement_pays_club_wallet"; the .sql file was never committed
-- at the time. Everything below this header is byte-exact to what ran:
-- md5 cbc868cbcc68a8c9a398fad15a025dd5 of array_to_string(statements, chr(10)) || chr(10).
-- Do NOT re-apply; it is already live.


-- ============================================================================
-- P2 — AGENT SETTLEMENT PAYS INTO THE CLUB WALLET (2026-08-20)
--
-- An agent's commission is earned on rake generated by their players inside a
-- specific club, and it is funded from money the union returns to that club.
-- Paying it into the agent's global wallet moved value club -> global on every
-- settlement run, and left the agent with chips they could not use to fund
-- their own roster (agent chip transfers debit the CLUB balance).
--
-- The payout now lands in the agent's balance AT THE CLUB THE AGENT BELONGS TO,
-- falling back to the global wallet only if that membership does not exist.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.atomic_pay_agent_settlement(p_settlement_id uuid, p_agent_id uuid, p_amount numeric, p_period_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_agent_user_id uuid;
  v_agent_club    uuid;
  v_res           jsonb;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN RETURN; END IF;

  SELECT user_id, club_id INTO v_agent_user_id, v_agent_club
    FROM public.agents WHERE id = p_agent_id;
  IF v_agent_user_id IS NULL THEN
    RAISE EXCEPTION 'agent % not found', p_agent_id;
  END IF;

  -- UNION LAW: the commission was earned in a club and is funded by that
  -- club's treasury, so it is paid into that club's balance.
  v_res := public.fn_pay_player_chips(
    v_agent_user_id, p_amount, 'agent_settlement',
    'Agent commission payout (settlement ' || p_settlement_id::text
      || ', period ' || p_period_id::text || ')',
    v_agent_club, p_settlement_id);

  UPDATE public.agents
     SET lifetime_earnings = COALESCE(lifetime_earnings, 0) + p_amount,
         pending_commission = GREATEST(COALESCE(pending_commission,0) - p_amount, 0),
         updated_at        = NOW()
   WHERE id = p_agent_id;

  INSERT INTO public.audit_trail
    (actor_id, actor_role, action, target_type, target_id,
     amount, currency, reason)
  VALUES
    (v_agent_user_id, 'system', 'agent_settlement_payout', 'settlement',
     p_settlement_id, p_amount, 'CHIPS',
     'atomic_pay_agent_settlement RPC payout to '
       || COALESCE(v_res->>'source','global_wallet'));
END;
$function$;

