-- Repo copy of migration union_law_restored_into_weighted_rake, applied to
-- production 2026-08-31 ~00:15 UTC via the Supabase MCP (phase 1 of the
-- estate-wide completion plan). Full executed SQL lives in the applied
-- migration of the same name.
--
-- WHAT BROKE. Migration 20260829133816 (weighted_contributed_rake) rebuilt
-- FUNCTION public.atomic_distribute_rake and lost TWO union laws the
-- 2026-08-20 reapplication had pinned — fn_union_law_selftest had been
-- filing a critical alert about it daily:
--
--   1. PRIVATE-GAME ISOLATION: v_union_id came straight from
--      clubs.union_id, so a union club's PRIVATE game rake would route into
--      union numbers again. Measured exposure since the clobber: 0.00 chips
--      (no private table raked in the window).
--   2. TRUST-HELD TREASURY: the rework credited union_wallets.chip_balance
--      (the Union Bank) alongside rake_wallet on every hand. The law says
--      RAKE TREASURY ONLY until the weekly 90/10 close. 136,458+ chips of
--      wrongful Union Bank credits were reversed dynamically in the same
--      transaction that swapped the function (audit adjustment row written;
--      Union Bank 233,767.55 -> 97,346-region, rake_wallet untouched).
--
-- WHAT WAS KEPT. Everything the weighted rework added: rake_method,
-- rake_attributions per-player ledger, returned_uncalled, allocation
-- mismatch alerting, v_net club crediting. The function was replaced AT THE
-- LIVE SIGNATURE (p_returned_uncalled before p_rake_method) — a first
-- attempt with the parameters swapped would have created a shadow overload
-- and was aborted by its own single-function assertion.
--
-- PROOF. fn_union_law_selftest() returned healthy:true, breaches:[] inside
-- the migration (asserted), rake_records + rake_attributions continued
-- flowing within two minutes of the swap, and the standing critical alert
-- was marked resolved.
--
-- THE LESSON FOR THE NEXT REWRITER: fn_union_law_selftest greps this
-- function for 'UNION LAW' and 'v_is_private'. If you replace
-- atomic_distribute_rake, carry the private-game stamp routing AND the
-- trust-held treasury rule forward, or the daily selftest will page — and
-- this time the clobber also cost a five-figure bank correction.
