-- APPLIED TO PRODUCTION 2026-08-19 via Supabase MCP as
-- `selftest_v2_bbj_conservation_and_union_money_report`. Mirror only.
--
-- 1. fn_bbj_conservation_check() — computes the BBJ inflow/outflow/balance
--    identity and compares the gap to bbj_conservation_baseline. Healthy when
--    |gap - baseline| <= tolerance (1.00). Verified live: drift 0.00 while
--    inflow, outflow and balances all moved under traffic.
--
-- 2. fn_union_treasury_selftest() v2 — all prior checks (non-negative wallets,
--    rake_wallet <= chip_balance, rake ledger reconciliation, BBJ (pool,hand)
--    uniqueness, retired pools holding zero, no lapsed unclosed week) PLUS the
--    BBJ conservation drift check. Breaches raise deduped critical
--    financial_alerts. Run every settler cycle by the engine.
--
-- 3. fn_union_money_report(p_union_id default first union) — one call returning
--    the whole money picture: union bank / rake treasury / promo wallet,
--    lifetime rake and rakeback paid, rake booked this week, the projected
--    90/10 split at the next Monday close, BBJ pool state and split rule,
--    per-club rake + projected rakeback + treasury, the last 12 weekly closes,
--    open financial alerts, and the live selftest result. Granted to
--    authenticated (read-only, SECURITY DEFINER) so the union dashboard and the
--    money artifact can both read one authoritative source.
