-- Ties must share a rank.                                          2026-08-20
--
-- The boards ranked with row_number(), which forces a total order and breaks
-- ties on user_id. On metrics with a small value domain that is badly wrong:
-- the Tournaments Won board returns 200 rows with only 28 distinct values, so
-- 172 rows are tied - two players each on 3 wins could render as #12 and #47,
-- ordered by nothing more meaningful than their uuid.
--
-- rank() now decides the DISPLAYED rank (1, 2, 2, 4 - the usual sports and
-- poker convention). row_number() is retained purely for ordering and
-- LIMIT/OFFSET so pagination stays stable. rank_change is computed rank-to-rank,
-- so a tie group moving together reads as 0 rather than shuffling.
--
-- Verified after apply: rank 22 holds 4 players on 14 wins, rank 34 holds 7 on
-- 11 wins, and ranks skip by the group size. Three pages of 40 return 120 rows
-- and 120 distinct users - no overlap, no gaps. fn_user_rank_period agrees 3/3.
--
-- Applied by rewriting the LIVE definitions rather than restating ~13KB of SQL
-- by hand - that is how these three drifted apart in the first place. Each
-- substitution asserts that it matched, which is what caught the union
-- function's differing formatting and its missing rank column.
--
-- fn_union_leaderboard_period_v2 predates the pagination work and returns
-- neither rank nor total_ranked nor baseline_date, so only its rank_change
-- becomes tie-aware. Align its return shape before anything calls it; nothing
-- does today.
--
-- The exact DO block applied is in the migration of the same name in the
-- Supabase migration history (20260820b). It is intentionally not duplicated
-- here as literal text, because re-running a textual rewrite against
-- already-rewritten definitions would fail its own assertions - by design.
-- To reproduce on a fresh database, apply 20260819j/k/l and then this.
--
-- ROLLBACK: restore the three functions from 20260819j / 20260819k / 20260819l.
