-- ZERO-DRIFT PHASE 5 - PER-HAND STACK SETTLEMENT RPC (prod ~19:52 UTC;
-- canonical body in prod schema_migrations - export via
-- scripts/dev/export-applied-migrations.sh)
-- fn_ca_settle_hand_stacks(table, hand, hand_number, deltas jsonb, rake, bbj):
-- the engine syncStacks landing pad. Idempotent on settlement_idempotency_keys
-- (replay returns the stored result; stale in-flight claims may be taken
-- over); conservation-checked (sum(deltas)+rake+bbj = 0 to the cent, exact
-- 2dp, no negative stacks, no ghost seats - else FULL rollback + recorded
-- failure + conservation incident); walks ca_settlements open→final; stacks
-- only (wallets untouched; rake/BBJ still bank via atomic_distribute_rake).
-- Verified by rolled-back probes: happy path, replay, conservation reject,
-- negative-stack reject, ghost-seat reject. Engine adoption guide: doc 06.
