-- ============================================================================
-- THE DAILY AUDIT FITS ITS TIMEOUT, AND TWO DETECTORS STOP REPORTING SUCCESS
-- AS FAILURE (2026-09-05, from the 2026-09-04 daily horse audit analysis)
-- ============================================================================
--
-- 1. fn_run_horse_daily_audit could not finish inside the engine's window.
--    horse_job_runs: daily_audit claimed 2026-09-01 and 2026-09-02 and wrote
--    nothing; 09-03 and 09-04 were generated by the analysis task under an
--    explicit 180s session timeout. Called plainly it dies with 57014 at the
--    capture_coverage_gap loop. EXPLAIN ANALYZE of that one step on 09-04: a
--    parallel index scan of idx_hand_history_created over 681,878 rows with a
--    heap filter on pot_size, 700,896 buffers, 89.9 seconds, returning zero
--    rows. service_role runs at an 8s statement_timeout and the engine's
--    supabase client aborts at 15s; the SET statement_timeout '60s' on the
--    function does not help, because Postgres arms the timeout when the
--    statement STARTS and a GUC change inside the call does not re-arm it.
--    Every other step, measured on the same day: layer_silence 0.35s,
--    river_ev 0.24s, fleet_health 0.24s, receipts 0.12s, the rest below 0.05s.
--    The step is rewritten to answer its question from horse_daily_nets and
--    idx_hhr_played and to probe hand_history, LIMIT 50, only for a variant
--    with nets rows and zero reviews.
--
-- 2. fn_audit_layer_drift reported icm_legacy at zero as "a layer that was
--    executing and is not any more". icm_legacy is the degraded path; zero is
--    icm_real having covered every tournament decision (186,669 real,
--    122,973 spin_cev, 293 warming, 0 legacy on 09-04). Documented fallback
--    counters are now reported as info 'fallback_went_quiet'.
--
-- 3. fn_audit_data_receipts reported v40_made_* at 4.982% of decide_omaha
--    against a 5% floor on the day V40 merged at 17:51 UTC: six hours of
--    numerator over a full day of denominator. A receipt with fires and no
--    telemetry on any earlier day is now info 'receipt_first_day'; zero fires
--    with no history stays critical.
--
-- One transaction per the production DDL policy: three CREATE OR REPLACEs
-- coalesce into a single PostgREST schema reload.
-- ============================================================================

BEGIN;

CREATE OR REPLACE FUNCTION public.fn_run_horse_daily_audit(p_day date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
 SET statement_timeout TO '60s'
AS $function$
declare
  v_stats jsonb;
  v_findings jsonb := '[]'::jsonb;
  r record;
  v_day_hands bigint;
  v_base_hands bigint;
  v_base_days int;
  v_big_pots bigint;
  c_min_baseline_days constant int := 3;
begin
  select jsonb_build_object(
    'flagged_hands', count(*),
    'big_wins', count(*) filter (where is_win),
    'big_losses', count(*) filter (where not is_win),
    'net_bb_sum', round(coalesce(sum(net_bb), 0), 1),
    'by_variant', coalesce((select jsonb_object_agg(game_variant, cnt) from (select game_variant, count(*) cnt from horse_hand_reviews where played_at >= p_day and played_at < p_day + 1 group by game_variant) v), '{}'::jsonb),
    'by_format', coalesce((select jsonb_object_agg(format, cnt) from (select format, count(*) cnt from horse_hand_reviews where played_at >= p_day and played_at < p_day + 1 group by format) v), '{}'::jsonb),
    'decides', (select coalesce(sum(fires),0) from horse_brain_telemetry where day = p_day and feature = 'decide'),
    'net_bb_all_hands', (select round(coalesce(sum(net_bb),0),1) from horse_daily_nets where day = p_day)
  ) into v_stats from horse_hand_reviews where played_at >= p_day and played_at < p_day + 1;

  select count(*) into v_day_hands
    from horse_hand_reviews where played_at >= p_day and played_at < p_day + 1;

  select count(*), count(distinct played_at::date)
    into v_base_hands, v_base_days
    from horse_hand_reviews where played_at >= p_day - 7 and played_at < p_day;

  if v_base_days >= c_min_baseline_days and v_day_hands > 0 and v_base_hands > 0 then
    for r in
      with day_tags as (
        select tag, count(*) cnt
          from horse_hand_reviews, lateral unnest(leak_tags) tag
         where played_at >= p_day and played_at < p_day + 1
         group by tag
      ),
      tag_first_seen as (
        select tag, min(played_at)::date as first_day
          from horse_hand_reviews, lateral unnest(leak_tags) tag
         where played_at >= p_day - 30 and played_at < p_day + 1
         group by tag
      ),
      base_day_hands as (
        select played_at::date as d, count(*) as hands
          from horse_hand_reviews
         where played_at >= p_day - 7 and played_at < p_day
         group by 1
      ),
      base_tag_counts as (
        select tag, count(*) cnt
          from horse_hand_reviews, lateral unnest(leak_tags) tag
         where played_at >= p_day - 7 and played_at < p_day
         group by tag
      ),
      base_per_tag as (
        select f.tag,
               coalesce(sum(b.hands), 0)::bigint as hands,
               count(b.d)::int                   as days
          from tag_first_seen f
          left join base_day_hands b on b.d >= f.first_day
         group by f.tag
      )
      select d.tag,
             d.cnt,
             (d.cnt::numeric * 1000) / v_day_hands as day_rate,
             case when p.hands > 0
                  then (coalesce(c.cnt, 0)::numeric * 1000) / p.hands
             end                                  as base_rate,
             coalesce(p.days, 0)                   as tag_base_days,
             coalesce(p.hands, 0)                  as tag_base_hands
        from day_tags d
        left join base_per_tag  p using (tag)
        left join base_tag_counts c using (tag)
       where d.cnt >= 20
    loop
      if r.tag_base_days < c_min_baseline_days then
        v_findings := v_findings || jsonb_build_object(
          'severity','info','category','logic','code','leak_tag_detector_new',
          'title','Leak tag ' || r.tag || ' is too new to baseline',
          'evidence', jsonb_build_object(
            'tag', r.tag,
            'count', r.cnt,
            'rate_per_1k', round(r.day_rate, 2),
            'tag_baseline_days', r.tag_base_days,
            'required_days', c_min_baseline_days,
            'day_hands', v_day_hands),
          'recommendation','This detector has not been running long enough for a spike to mean anything, so no comparison was made. Its first few days establish the baseline; judge it from the day it has ' || c_min_baseline_days || ' full prior days.');
      elsif r.base_rate is not null
            and (r.base_rate = 0 or r.day_rate > r.base_rate * 1.5) then
        v_findings := v_findings || jsonb_build_object(
          'severity', case when r.base_rate = 0 or r.day_rate > r.base_rate * 2.5 then 'critical' else 'warn' end,
          'category','logic','code','leak_tag_spike',
          'title','Leak tag ' || r.tag || ' spiked',
          'evidence', jsonb_build_object(
            'tag', r.tag,
            'count', r.cnt,
            'rate_per_1k', round(r.day_rate, 2),
            'baseline_rate_per_1k', round(r.base_rate, 2),
            'baseline_days', r.tag_base_days,
            'day_hands', v_day_hands,
            'baseline_hands', r.tag_base_hands),
          'recommendation','Rates are per 1,000 captured hands on both sides and the baseline counts only days this detector was live, so this is neither a volume artifact nor a new-detector artifact. A spike after a deploy means the brain regressed on this pattern. Diff the day''s engine deploys against the tag definition and sample flagged hands carrying it.');
      end if;
    end loop;
  else
    v_findings := v_findings || jsonb_build_object(
      'severity','info','category','logic','code','leak_tag_spike_baseline_thin',
      'title','Leak spike detection stood down - ' || v_base_days || ' day(s) of baseline',
      'evidence', jsonb_build_object('baseline_days', v_base_days, 'required_days', c_min_baseline_days,
                                     'day_hands', v_day_hands, 'baseline_hands', v_base_hands),
      'recommendation','Needs ' || c_min_baseline_days || ' distinct prior days of capture before a spike means anything. This is the detector declining to guess, not a finding.');
  end if;

  for r in select horse_user_id, round(sum(net_bb),1) net, count(*) n from horse_hand_reviews
    where played_at >= p_day and played_at < p_day + 1 group by horse_user_id having sum(net_bb) < -400 order by sum(net_bb) asc limit 10
  loop
    v_findings := v_findings || jsonb_build_object('severity', case when r.net < -800 then 'critical' else 'warn' end,
      'category','gto','code','horse_big_pot_bleed','title','Horse lost ' || abs(r.net) || 'bb across ' || r.n || ' flagged pots',
      'evidence', jsonb_build_object('horse_user_id',r.horse_user_id,'alias',(select coalesce(alias,display_name,username) from profiles where id=r.horse_user_id),'net_bb',r.net,'hands',r.n,
        'tags',(select coalesce(jsonb_object_agg(tag,cnt),'{}'::jsonb) from (select tag,count(*) cnt from horse_hand_reviews, lateral unnest(leak_tags) tag where horse_user_id=r.horse_user_id and played_at>=p_day and played_at<p_day+1 group by tag) t)),
      'recommendation','Review this horse''s flagged hands. Repeated identical tags mean a style/dial problem for the self-tuner; scattered tags with big losses can be variance - check the hand count first.');
  end loop;

  for r in select matchup, bb100, stderr, illegal_actions from horse_league_results
    where run_date = (select max(run_date) from horse_league_results where run_date <= p_day + 1)
  loop
    if r.bb100 < 0 and abs(r.bb100) > 2 * r.stderr then
      v_findings := v_findings || jsonb_build_object('severity','critical','category','gto','code','league_layer_negative',
        'title','League matchup ' || r.matchup || ' resolves NEGATIVE','evidence', jsonb_build_object('matchup',r.matchup,'bb100',r.bb100,'stderr',r.stderr),
        'recommendation','A strategy layer is measurably losing money in self-play. Ablate it properly before tuning anything else.');
    end if;
    if r.illegal_actions > 0 then
      v_findings := v_findings || jsonb_build_object('severity','critical','category','logic','code','league_illegal_actions',
        'title','League matchup ' || r.matchup || ' produced illegal actions','evidence', jsonb_build_object('matchup',r.matchup,'illegal_actions',r.illegal_actions),
        'recommendation','The brain emitted a sizing the engine rejects. This reaches live tables as silent check/fold degradation - find the exact branch.');
    end if;
  end loop;

  -- ── capture_coverage_gap (rewritten 2026-09-05) ──────────────────────────
  -- This step used to scan the WHOLE DAY of hand_history (681,878 rows on
  -- 2026-09-04: 700,896 buffers through idx_hand_history_created with a heap
  -- filter on pot_size, 89.9 seconds measured) to answer a question whose
  -- normal answer is "nothing to report". It was the entire reason the
  -- engine's nightly daily_audit could not finish: service_role runs at an
  -- 8s statement_timeout and the engine client aborts at 15s, and the SET
  -- statement_timeout '60s' on this function cannot re-arm a timer that was
  -- armed at statement start. Every other step here runs in under a second.
  --
  -- The question is "did a variant deal big pots today and write NO review
  -- rows". Both halves are cheap without hand_history: the variants dealt
  -- come from horse_daily_nets (written per horse-hand at settlement, one
  -- small row per horse/variant/day), the variants reviewed come from
  -- idx_hhr_played. Only for a variant that has nets rows and no reviews -
  -- the abnormal case the finding exists for - is hand_history probed, and
  -- then with LIMIT 50: fifty big pots are enough to raise the finding and
  -- the scan stops the moment it has them.
  for r in
    select n.game_variant
      from (select distinct game_variant from horse_daily_nets where day = p_day and hands > 0) n
     where not exists (select 1 from horse_hand_reviews rv
                        where rv.game_variant = n.game_variant
                          and rv.played_at >= p_day and rv.played_at < p_day + 1)
  loop
    select count(*) into v_big_pots from (
      select 1 from hand_history h
       where h.created_at >= p_day and h.created_at < p_day + 1
         and h.game_variant = r.game_variant
         and h.pot_size >= 40 * h.big_blind
       limit 50) probe;
    if v_big_pots >= 50 then
      v_findings := v_findings || jsonb_build_object('severity','critical','category','schema','code','capture_coverage_gap',
        'title','Variant ' || r.game_variant || ' dealt at least ' || v_big_pots || ' big pots but wrote zero review rows',
        'evidence', jsonb_build_object('game_variant',r.game_variant,'big_pot_hands',v_big_pots,'probe_limit',50),
        'recommendation','recordHorseHandReviews is not firing for this variant''s settlement path. Read the engine logs for HorseHandReview reportError entries.');
    end if;
  end loop;

  select count(*) into r from horse_hand_reviews where played_at >= p_day and played_at < p_day + 1 and (hole_cards is null or board is null);
  if (r.count) >= 25 then
    v_findings := v_findings || jsonb_build_object('severity','warn','category','schema','code','evidence_payload_missing',
      'title',(r.count) || ' review rows missing hole_cards or board','evidence', jsonb_build_object('rows',r.count),
      'recommendation','parseCards rejected the payload shape, or preflop-only pots legitimately have no board. Sample the rows.');
  end if;

  for r in select id, horse_user_id, net_bb, game_variant from horse_hand_reviews
    where played_at >= p_day and played_at < p_day + 1
      and abs(net_bb) > (case when tournament_id is not null then 1500 else 500 end)
      order by abs(net_bb) desc limit 5
  loop
    v_findings := v_findings || jsonb_build_object('severity','warn','category','schema','code','net_outlier',
      'title','Review row with |net| of ' || r.net_bb || 'bb','evidence', jsonb_build_object('review_id',r.id,'horse_user_id',r.horse_user_id,'net_bb',r.net_bb,'variant',r.game_variant),
      'recommendation','Legitimate only for very deep stacks. If the stake caps make this impossible, the contribution/winner inputs disagree.');
  end loop;

  select count(*) into r from horse_hand_reviews where played_at >= p_day and played_at < p_day + 1 and not is_win and leak_tags = '{}';
  if (r.count) >= 200 then
    v_findings := v_findings || jsonb_build_object('severity','info','category','logic','code','untagged_losses',
      'title',(r.count) || ' big losses carry no leak tag','evidence', jsonb_build_object('rows',r.count),
      'recommendation','Not every big loss is a mistake - but if manual review keeps finding the same untagged flaw, add a detector.');
  end if;

  v_findings := v_findings || fn_audit_layer_silence_and_coverage(p_day);
  v_findings := v_findings || fn_audit_fleet_health(p_day);
  -- 2026-09-01: a claimed-but-empty nightly job, a stale league card,
  -- and a matchup whose two arms are identical. See
  -- 20260901_audit_a_lost_nightly_job_is_loud.sql.
  v_findings := v_findings || fn_audit_nightly_job_health(p_day);
  -- 2026-09-01: river aggression judged on EV across BOTH outcomes.
  v_findings := v_findings || fn_audit_river_aggression_ev(p_day);
  -- 2026-09-01: layers that stopped firing or collapsed, derived from
  -- what each layer has actually done - no hand-maintained watchlist.
  v_findings := v_findings || fn_audit_layer_drift(p_day);
  -- 2026-09-01: a conservation breach stays reported until a person
  -- explains it. The deploy gate forgets after four hours; this does not.
  v_findings := v_findings || fn_audit_supply_breaches(p_day);
  -- Phase 1 of the real-time build plan (2026-09-04): every ledger receipt
  -- judged against its expected share, every nightly source for freshness.
  v_findings := v_findings || fn_audit_data_receipts(p_day);

  insert into horse_daily_audit as a (day, generated_at, stats, findings)
  values (p_day, now(), coalesce(v_stats,'{}'::jsonb), v_findings)
  on conflict (day) do update set generated_at = now(), stats = excluded.stats, findings = excluded.findings;

  return jsonb_build_object('day', p_day, 'findings', jsonb_array_length(v_findings));
end
$function$;

create or replace function public.fn_audit_data_receipts(p_day date)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_findings jsonb := '[]'::jsonb;
  r record;
  v_fires bigint;
  v_denom bigint;
  v_ratio numeric;
  v_ledger_rows bigint;
  v_ledger_age interval;
  v_fresh boolean;
  v_table_exists boolean;
  v_prior_days bigint;
begin
  select count(*), now() - max(updated_at) into v_ledger_rows, v_ledger_age
    from horse_data_ledger;

  -- The ledger itself is a datum. No rows = the engine never synced it;
  -- an old sync = the running brain is not the one the ledger describes.
  if v_ledger_rows = 0 then
    v_findings := v_findings || jsonb_build_object(
      'severity', 'critical', 'category', 'schema', 'code', 'data_ledger_missing',
      'title', 'horse_data_ledger is empty - the engine has not synced its contract',
      'evidence', jsonb_build_object('rows', 0),
      'recommendation', 'HorseDataLedgerSync runs at engine boot. Either the engine has not restarted since the ledger shipped or the sync is failing (horse_error_log / container logs, context HorseDataLedgerSync).');
    return v_findings;
  end if;

  -- ── receipts: did each layer fire its expected share? ────────────────
  for r in
    select l.key, split_part(l.key, ':', 2) as feature, l.consumer, l.ratio_of, l.min_ratio, l.note, l.since
      from horse_data_ledger l
     where l.kind = 'receipt'
     order by l.key
  loop
    v_fires := fn_ledger_fires(p_day, r.feature);
    if r.ratio_of is null then
      -- table-mix dependent: only a zero against a big day is worth a line
      continue;
    end if;
    v_denom := fn_ledger_fires(p_day, r.ratio_of);
    if v_denom < 1000 then
      continue; -- the denominator itself is too small to judge anything
    end if;
    v_ratio := v_fires::numeric / v_denom;
    -- ── A LAYER'S FIRST DAY IS A PARTIAL DAY (2026-09-05) ──
    -- V40 merged at 17:51 UTC on 2026-09-04 and this check reported
    -- v40_made_* at 4.982% of decide_omaha against a 5% floor: six hours of
    -- numerator over twenty-four hours of denominator. A receipt that has
    -- fired today and has NO telemetry row on any earlier day is on its first
    -- (partial) day and cannot be judged by a whole-day ratio; it is reported
    -- as info and judged tomorrow. Zero fires with no history is NOT excused:
    -- that is a layer that has never executed, and stays critical.
    if r.min_ratio is not null and v_ratio < r.min_ratio and v_fires > 0 then
      select count(distinct t.day) into v_prior_days
        from horse_brain_telemetry t
       where t.day < p_day and t.fires > 0
         and case when right(r.feature, 1) = '*'
                  then t.feature like replace(left(r.feature, length(r.feature) - 1), '_', '\_') || '%'
                  else t.feature = r.feature end;
      if v_prior_days = 0 then
        v_findings := v_findings || jsonb_build_object(
          'severity', 'info', 'category', 'logic', 'code', 'receipt_first_day',
          'title', r.feature || ' fired ' || v_fires || ' times on its first (partial) day - ratio not judged',
          'evidence', jsonb_build_object(
            'feature', r.feature, 'fires', v_fires, 'ratio_of', r.ratio_of, 'denominator', v_denom,
            'ratio', round(v_ratio, 6), 'min_ratio', r.min_ratio, 'consumer', r.consumer, 'since', r.since),
          'recommendation', 'The layer deployed during this day, so its fires cover part of the day and the denominator covers all of it. The ratio is judged from its first full day.');
        continue;
      end if;
    end if;
    if r.min_ratio is not null and v_ratio < r.min_ratio then
      v_findings := v_findings || jsonb_build_object(
        'severity', case when v_fires = 0 then 'critical' else 'warn' end,
        'category', 'logic',
        'code', 'data_unread',
        'title', r.feature || ' fired ' || v_fires || ' times against ' || v_denom || ' ' || r.ratio_of ||
                 ' (' || round(v_ratio * 100, 3) || '%, ledger expects >= ' || round(r.min_ratio * 100, 3) || '%)',
        'evidence', jsonb_build_object(
          'feature', r.feature, 'fires', v_fires, 'ratio_of', r.ratio_of, 'denominator', v_denom,
          'ratio', round(v_ratio, 6), 'min_ratio', r.min_ratio, 'consumer', r.consumer, 'since', r.since),
        'recommendation', case when v_fires = 0
          then 'A registered consumer produced no receipt all day: the gate in front of ' || r.consumer || ' is closed (flag default, upstream condition, or the layer was removed without retiring its ledger row). Trace the gate in the source before touching the ratio.'
          else 'The consumer runs but far below the share the ledger expects. Either the fleet mix changed (then lower min_ratio in HorseDataLedger.ts with the evidence) or an upstream condition narrowed. ' || r.note end);
    end if;
  end loop;

  -- ── tables: is each nightly/boot source fresh? ───────────────────────
  for r in
    select l.key, split_part(l.key, ':', 2) as tbl, l.cadence, l.consumer, l.day_column, l.freshness_days
      from horse_data_ledger l
     where l.kind = 'table' and l.day_column is not null and l.freshness_days is not null
     order by l.key
  loop
    select exists (
      select 1 from information_schema.tables
       where table_schema = 'public' and table_name = r.tbl
    ) into v_table_exists;
    if not v_table_exists then
      v_findings := v_findings || jsonb_build_object(
        'severity', 'critical', 'category', 'schema', 'code', 'data_stale',
        'title', 'Ledger table ' || r.tbl || ' does not exist',
        'evidence', jsonb_build_object('table', r.tbl),
        'recommendation', 'The ledger names a table the schema does not have. Either the migration was never applied or the ledger row is wrong.');
      continue;
    end if;
    -- freshness: any row whose day column is within freshness_days of p_day
    -- (timestamps and dates both cast to date).
    execute format(
      'select exists (select 1 from public.%I where (%I)::date >= %L::date - %s)',
      r.tbl, r.day_column, p_day, r.freshness_days
    ) into v_fresh;
    if not v_fresh then
      v_findings := v_findings || jsonb_build_object(
        'severity', 'critical', 'category', 'schema', 'code', 'data_stale',
        'title', r.tbl || ' has no row within ' || r.freshness_days || ' day(s) of ' || p_day,
        'evidence', jsonb_build_object('table', r.tbl, 'day_column', r.day_column,
                                       'freshness_days', r.freshness_days, 'consumer', r.consumer, 'cadence', r.cadence),
        'recommendation', 'A source the brain or its compilers depend on stopped being written. ' || r.consumer || ' is reading stale memory. Find the writer (the ledger names the cadence) and its error log.');
    end if;
  end loop;

  return v_findings;
end
$function$;

CREATE OR REPLACE FUNCTION public.fn_audit_layer_drift(p_day date)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_findings jsonb := '[]'::jsonb;
  v_decides bigint;
  v_already text[];
  r record;
  /*
   * ── FALLBACK COUNTERS: SILENCE IS THE GOAL (2026-09-05) ──
   * Some counters name the DEGRADED path, not a layer: icm_legacy is the flat
   * heuristic used only when TournamentBrainContext arrives without stacks or
   * payouts (icm_real takes over the moment it has them), icm_warming is a
   * context that has not arrived yet, gto_depth_fallback and gto_miss_* are
   * the solver store having no cell for the spot. For these, zero fires on a
   * big day means the primary path covered everything - the six-day
   * icm_legacy migration to icm_real reached exactly zero on 2026-09-04 and
   * this function reported it as a layer that "was executing and is not any
   * more". Their silence is reported as info, with the reason, so the panel
   * can still see the step without a warning that says the opposite of what
   * happened. A fallback that starts firing AGAIN is caught by the ratio
   * checks in fn_audit_data_receipts, not here.
   */
  v_fallback_exact constant text[] := array['icm_legacy', 'icm_warming', 'gto_depth_fallback'];
  v_fallback_prefix constant text[] := array['gto_miss_'];
  v_is_fallback boolean;
begin
  select coalesce(sum(fires), 0) into v_decides
    from horse_brain_telemetry where day = p_day and feature = 'decide';

  if v_decides < 1000 then
    return v_findings;
  end if;

  select coalesce(array_agg(f->'evidence'->>'feature'), '{}')
    into v_already
    from jsonb_array_elements(fn_audit_layer_silence(p_day)) f
   where f->>'code' = 'layer_silent';

  -- 1. A layer that was firing and stopped.
  for r in
    with hist as (
      select feature,
             count(*) filter (where day < p_day and fires > 0) as prior_days,
             coalesce(max(fires) filter (where day = p_day), 0) as today,
             coalesce(sum(fires) filter (where day < p_day), 0) as prior_fires,
             max(day) filter (where day < p_day and fires > 0) as last_fired
        from horse_brain_telemetry
       where day between p_day - 7 and p_day and feature <> 'decide'
       group by feature
    )
    select * from hist
     where prior_days >= 2 and today = 0 and not (feature = any(v_already))
     order by prior_fires desc
  loop
    v_is_fallback := r.feature = any(v_fallback_exact)
      or exists (select 1 from unnest(v_fallback_prefix) p where left(r.feature, length(p)) = p);
    if v_is_fallback then
      v_findings := v_findings || jsonb_build_object(
        'severity', 'info',
        'category', 'logic',
        'code', 'fallback_went_quiet',
        'title', 'Fallback ' || r.feature || ' fired ' || r.prior_fires ||
                 ' times in the previous week and ZERO on ' || p_day || ' - the primary path covered every spot',
        'evidence', jsonb_build_object(
          'feature', r.feature,
          'prior_days_active', r.prior_days,
          'prior_fires', r.prior_fires,
          'last_fired', r.last_fired,
          'decide_fires', v_decides
        ),
        'recommendation',
          'This counter names a degraded path (the legacy ICM heuristic, a warming ' ||
          'context, a solver-store miss), so zero is the intended direction: the ' ||
          'primary path answered every spot the fallback used to answer. Nothing to ' ||
          'trace. If it starts firing again the receipts audit will say so.'
      );
      continue;
    end if;
    v_findings := v_findings || jsonb_build_object(
      'severity', 'warn',
      'category', 'logic',
      'code', 'layer_went_silent',
      'title', 'Layer ' || r.feature || ' fired ' || r.prior_fires ||
               ' times in the previous week and ZERO on ' || p_day,
      'evidence', jsonb_build_object(
        'feature', r.feature,
        'prior_days_active', r.prior_days,
        'prior_fires', r.prior_fires,
        'last_fired', r.last_fired,
        'decide_fires', v_decides
      ),
      'recommendation',
        'This layer was executing and is not any more. Trace the gate: a flag ' ||
        'default, an upstream condition that can no longer be true, or a newer ' ||
        'layer returning before it. A retired layer is a valid answer - if the ' ||
        'feature name no longer exists in the source it is not a regression, ' ||
        'and this finding should be answered by deleting the counter.'
    );
  end loop;

  -- 2. A layer that collapsed without going silent - REPORTED ON THE DAY OF
  --    THE STEP ONLY (2026-09-04).
  for r in
    with dec as (
      select day, sum(fires) filter (where feature = 'decide') as d
        from horse_brain_telemetry
       where day between p_day - 7 and p_day
       group by day
      having sum(fires) filter (where feature = 'decide') > 1000
    ),
    rate as (
      select t.feature, t.day, (t.fires::numeric * 1000) / dec.d as rate, t.fires
        from horse_brain_telemetry t
        join dec on dec.day = t.day
       where t.feature <> 'decide'
    ),
    cur  as (select feature, rate as cur_rate,  fires as cur_fires  from rate where day = p_day),
    prev as (select feature, rate as prev_rate, fires as prev_fires from rate where day = p_day - 1),
    base as (
      select feature,
             (percentile_cont(0.5) within group (order by rate))::numeric as med_rate,
             count(*) as n_days,
             sum(fires) as prior_fires
        from rate where day < p_day group by feature
    )
    select c.feature, c.cur_rate, c.cur_fires, b.med_rate, b.n_days, b.prior_fires,
           p.prev_rate, p.prev_fires
      from cur c
      join base b using (feature)
      left join prev p using (feature)
     where b.n_days >= 3
       and b.prior_fires >= 5000
       and b.med_rate > 0
       and c.cur_rate < b.med_rate * 0.40
       -- THE STEP MUST BE NEW. If yesterday was already below the line, this
       -- is the same step reported again - the median simply has not rolled
       -- past it yet. Reporting it daily for a week is what buried three real
       -- criticals under three false ones on 2026-09-01.
       and (p.prev_rate is null or p.prev_rate >= b.med_rate * 0.40)
       -- AND IT MUST ACTUALLY HAVE FALLEN. icm_legacy went 441 -> 641 fires
       -- and v16_unblocker 2,428 -> 2,512 on the day they were both reported
       -- as collapsing. A layer whose raw count rose is not collapsing today,
       -- whatever a median that straddles a deploy says.
       and (p.prev_fires is null or c.cur_fires < p.prev_fires)
     order by (1 - c.cur_rate / b.med_rate) desc
  loop
    v_findings := v_findings || jsonb_build_object(
      'severity', 'warn',
      'category', 'logic',
      'code', 'layer_fire_collapse',
      'title', 'Layer ' || r.feature || ' fell to ' ||
               round(100 * (1 - r.cur_rate / r.med_rate)) || '% below its usual rate',
      'evidence', jsonb_build_object(
        'feature', r.feature,
        'rate_per_1k_today', round(r.cur_rate, 2),
        'rate_per_1k_yesterday', round(coalesce(r.prev_rate, 0), 2),
        'rate_per_1k_median', round(r.med_rate, 2),
        'pct_drop', round(100 * (1 - r.cur_rate / r.med_rate)),
        'fires_today', r.cur_fires,
        'fires_yesterday', coalesce(r.prev_fires, 0),
        'prior_fires', r.prior_fires,
        'baseline_days', r.n_days,
        'step_day', p_day
      ),
      'recommendation',
        'Reported ONLY on the day the step happened: yesterday was still near ' ||
        'the median and the raw count fell today, so this is new rather than a ' ||
        'week-old change the median has not caught up with. Measured per 1,000 ' ||
        'decisions, so fleet volume is already divided out. Two innocent ' ||
        'explanations remain and both are worth confirming rather than ' ||
        'assuming: a SUPERSEDED layer legitimately declining (icm_legacy as ' ||
        'icm_real took over), and a newer layer that RETURNS EARLY displacing ' ||
        'the ones below it (V32 did exactly that to v16_reads_tell and ' ||
        'v16_unblocker on 2026-08-31). The third explanation is a broken gate.'
    );
  end loop;

  return v_findings;
end
$function$;

COMMIT;

-- Operator telemetry, all three: the engine's nightly job and the panel are
-- the only callers, and nothing pre-login may read a brain-layer audit. The
-- live ACLs were already closed to service_role before this migration (a
-- CREATE OR REPLACE keeps the function's grants); these lines declare it
-- where check-definer-authorization reads, and re-applying them is a no-op.
-- PUBLIC is named as well as the roles because anon inherits from PUBLIC.
REVOKE ALL ON FUNCTION public.fn_run_horse_daily_audit(date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_run_horse_daily_audit(date) TO service_role;
REVOKE ALL ON FUNCTION public.fn_audit_data_receipts(date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_audit_data_receipts(date) TO service_role;
REVOKE ALL ON FUNCTION public.fn_audit_layer_drift(date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fn_audit_layer_drift(date) TO service_role;
