-- GUARANTEE OVERLAY ALERT — ONE PER CLUB, NOT ONE PER TOURNAMENT (2026-08-27)
--
-- The negative-treasury alarm added with fn_apply_prize_guarantee fired on
-- every overlay funded while a club's treasury was under water. The events
-- that carry guarantees are RECURRING, so within a day one club produced five
-- alerts for "Sunrise Bounty", four for "Afternoon Bounty" and so on — 24 open
-- alerts describing a single fact: one club's treasury is negative.
--
-- Same failure shape as FeeReconciler (988 criticals, 93% noise) and the same
-- fix: the alert describes the CLUB's condition, so it dedupes on the club.
-- One open alert per club, refreshed with the running figure.
--
-- WORTH RECORDING PLAINLY — the alarm is not warning of insolvency. Since it
-- went live, clubs funded 4,841.50 chips of overlay while tournament rake
-- collected 9,887.88 in the same 24 hours. That rake goes to the UNION rake
-- wallet and returns to club treasuries at the weekly 90% rakeback close, so a
-- negative treasury mid-week is a CASH-FLOW TIMING artifact: guarantees are
-- paid daily, rake comes back weekly. The alert still earns its place — an
-- operator should know a treasury is under water, and a club whose guarantees
-- genuinely outran its rake would look identical until a weekly close failed
-- to cover it. That is the escalation condition, and it is written into the
-- alert's own context note.
--
-- (Body applied to production via Supabase MCP; see migration
--  `guarantee_overlay_alert_dedupes_per_club`. It replaces the alert block in
--  fn_apply_prize_guarantee with an UPDATE-then-INSERT keyed on
--  context->>'club_id', collapses the existing backlog to one row per club,
--  and asserts open_alerts <= distinct_clubs.)
