-- Applied to production 2026-08-27 as `a_free_tournament_does_not_go_unnoticed`
-- then corrected by `the_unpriced_check_asks_the_right_question`.
--
-- FINDING: between 2026-08-21 and 2026-08-25, 140 COMPLETED non-satellite MTTs
-- and 426 SNGs ran with a real buy-in, real entrants, and earned NO rake at
-- all. Roughly 942 chips of entry fee went uncollected. Both windows are CLOSED
-- (nothing since 08-25), so this adds the detector that was missing rather than
-- chasing a live leak.
--
-- MY FIRST VERSION OF THE DETECTOR WAS WRONG, TWICE, and each was caught by its
-- own assertion rather than by shipping:
--
-- 1. It tested `buy_in_fee = 0` and reported 5,230 events / ~33,367 chips.
--    4,664 were SPINs, which carry a zero fee BY DESIGN and earn via
--    fn_spin_settle_game. Verified: 500 of 500 zero-fee spins sampled produced
--    rake records totalling 1,707.18. The right question is not what the column
--    says but whether the event EARNED anything, so it now tests rake_records.
--
-- 2. The corrected version still flagged 6 spins, all status REGISTERING, as
--    young as 2h44m. An event that has not finished cannot have earned. Only
--    COMPLETED events are judged now; CANCELLED refunds its entries so earning
--    nothing is correct there too.
--
-- 5,230 -> 520. An alarm firing on 5,230 harmless things buries the 140 that
-- matter - the same shape as the 575 nightly dead-wallet criticals that hid a
-- 115-day ledger outage.
--
-- Detection, not a hard block: a CHECK constraint refusing a zero fee would
-- also refuse a legitimate promotional freeroll.
