/**
 * EVERY AVATAR IS DISPLAYED AT THE SAME HEIGHT.
 *
 * Dan 2026-08-26: "all avatars at the table should be roughly the same size
 * and height. The basketball squirrel is very tall." Then, when the
 * measurement route stalled: "just go from the avatar library and make sure
 * all avatars are displayed at the same height. Use CSS to ensure all heights
 * are exactly the same."
 *
 * WHAT WAS ACTUALLY WRONG. Library bust art is drawn on a 125x170 canvas, and
 * the character inside occupies anywhere from 64% to 100% of it. That is what
 * `--sp-bust-gain` corrects: a per-character multiplier, generated by
 * scripts/measure-bust-art.py, that scales each character so its SUBJECT is a
 * common share of the slot. Sound, and it worked.
 *
 * The break was the containment clamp:
 *
 *     min(var(--sp-bust-gain, 1), var(--sp-bust-gain-max, 99))
 *
 * with `--sp-bust-gain-max: 1` on the whole top row. A clamp on the
 * CORRECTION is not a uniform reduction — it removes each character's
 * correction by however much that character needed, so a character measured
 * at 1.317 lost 24% of its height in a top seat while its 0.844 neighbour lost
 * nothing. Identical art, different heights, depending only on where you sat.
 *
 * The clamp is gone, and the checked-in gains were REGENERATED: measured
 * against the current library they had all drifted (the median share moved
 * 84.4% -> 88.8%), and `basketball` — the squirrel Dan named — carried 1.087
 * against an art file that measures 0.953, so it drew 23% taller than every
 * other character. Rendered through the real stylesheet, five characters
 * spanning the whole gain range now land on one subject height to within
 * 0.04%, on the normal row and the top row alike.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { BUST_ART_GAIN } from '../../src/components/table/bustArtGain';

const CSS = readFileSync(resolve(__dirname, '../../src/components/table/SeatSlot.css'), 'utf8');
/* Comments quote the deleted clamp at length so the next reader knows why it
   went. Strip them, or the history is mistaken for the code. */
const CODE = CSS.replace(/\/\*[\s\S]*?\*\//g, '');

describe('no per-character clamp singles an avatar out', () => {
  it('the composed scale is the global scale times the gain, and nothing else', () => {
    expect(CODE).toMatch(
      /--sp-bust-effective-scale:\s*calc\(\s*var\(--sp-bust-scale[^)]*\)\s*\*\s*var\(--sp-bust-gain[^)]*\)\s*\)/
    );
  });

  it('the gain is never clamped', () => {
    expect(CODE, 'a min() around the per-character gain is back').not.toMatch(
      /min\(\s*var\(--sp-bust-gain/
    );
    expect(CODE, '--sp-bust-gain-max is being set again').not.toMatch(/--sp-bust-gain-max\s*:/);
  });
});

describe('the art is fitted, never stretched', () => {
  it('uses object-fit: contain so a correction cannot distort the character', () => {
    const bustImg = CODE.slice(
      CODE.indexOf('.seat__avatar--bust .seat__avatar-img'),
      CODE.indexOf('}', CODE.indexOf('.seat__avatar--bust .seat__avatar-img'))
    );
    expect(bustImg).toMatch(/object-fit:\s*contain/);
  });

  it('does not pretend a max-height can contain a transform', () => {
    /* A `max-height` cap was tried and removed: the gain is applied with
       `transform: scale()`, which does not participate in layout, so the cap
       bounds the pre-transform box and the scale multiplies it afterwards.
       Measured at the time — it changed nothing. A cap here would read as a
       guarantee it cannot make. */
    expect(CODE).not.toMatch(/--sp-bust-max-h/);
  });
});

describe('the per-character gains are a sane, bounded correction', () => {
  const gains = Object.values(BUST_ART_GAIN);

  it('covers the whole shipped library', () => {
    expect(gains.length).toBeGreaterThanOrEqual(90);
  });

  it('no character is corrected so hard it towers over the others', () => {
    /* The generator normalises to the library median, so the spread is the
       spread of the ART. A value far outside this band means the measurement
       is stale against a re-drawn asset — exactly what had happened to
       `basketball` — and nothing downstream can detect that, so fail here,
       next to the numbers. Regenerate with:
         python3 scripts/measure-bust-art.py <hub>/public/avatars/table */
    for (const [name, g] of Object.entries(BUST_ART_GAIN)) {
      expect(g, `${name} has an implausible gain`).toBeGreaterThan(0.6);
      expect(g, `${name} has an implausible gain`).toBeLessThan(1.6);
    }
  });

  it('the median character is left alone', () => {
    // gain = median share / this share, so the median must land on ~1.
    const sorted = [...gains].sort((a, b) => a - b);
    const median = sorted[Math.floor(sorted.length / 2)];
    expect(median).toBeGreaterThan(0.95);
    expect(median).toBeLessThan(1.05);
  });
});
