/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  EVERY SHIPPED SOUND IS TRACEABLE TO A SOURCE AND A LICENCE (phase 1)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Dan, 2026-09-06: "FIND A OPEN SOURCE SFX LIBRARY WE CAN USE FOR SOUND
 * EFFECTS AND VOICES." The library is named in the plan (3.3.1): Kenney's CC0
 * packs, Freesound filtered to CC0, Sonniss GDC for the cinematic layer, and
 * Chatterbox (MIT) for the spoken lines. The manifest is the record of which
 * file came from where; this is the check that nothing gets in without one.
 *
 * A sound with no provenance is the one asset class where being wrong is
 * invisible until somebody else's lawyer notices, so the rule is mechanical:
 * a cue is EITHER a file whose manifest row names an allowed licence, OR a
 * declared placeholder that names the legacy recipe playing in its place.
 * There is no third state, and "it sounded fine" is not one.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';

import {
  THROWABLE_CUE_MANIFEST,
  THROWABLE_CUE_ALLOWED_LICENSES,
} from '../../src/throwables/cueManifest.generated';
import { allSpecs } from '../../src/throwables/registry';

const repo = process.cwd();
const manifestPath = path.join(repo, 'scripts/audio/throwable-cues.manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
const soundsDir = path.join(repo, manifest.outputDir);

describe('the cue manifest', () => {
  it('allows only licences that permit commercial use with no attribution', () => {
    // CC0 (public domain), the Sonniss GDC bundles (royalty free, commercial,
    // no attribution), our own recordings, and cues we SYNTHESISE ourselves.
    // Nothing NC, nothing ND, and nothing lifted from the PokerBros captures.
    //
    // 'Own-Synthesis' was added in phase 2 (2026-09-06) for the three cues no
    // CC0 sample pack has - a rising firework whistle, a low rumble and a
    // champagne fizz bed - and it is a DIFFERENT claim from 'Own-Recording':
    // nothing was recorded, an ffmpeg expression in the manifest generates the
    // file. That expression is the provenance, which is why the source rule
    // below demands a recipe from a synth source and a URL from every other.
    expect(THROWABLE_CUE_ALLOWED_LICENSES).toEqual([
      'CC0-1.0',
      'Sonniss-GDC-Royalty-Free',
      'Own-Recording',
      'Own-Synthesis',
    ]);
    for (const [key, src] of Object.entries<any>(manifest.sources)) {
      expect(THROWABLE_CUE_ALLOWED_LICENSES, `source '${key}'`).toContain(src.license);
      expect(src.author, `source '${key}' names an author`).toBeTruthy();
      if (src.kind === 'synth') {
        // Nothing was downloaded, so there is no URL to record. What has to be
        // recorded instead is HOW it is made, or the cue is unreproducible.
        expect(src.recipe, `synth source '${key}' records how it is generated`).toBeTruthy();
        expect(src.license, `a synth source cannot claim someone else's licence`).toBe(
          'Own-Synthesis'
        );
      } else {
        expect(src.url, `source '${key}' records where it came from`).toMatch(/^https?:\/\//);
      }
    }
  });

  it('a synthesised cue names its ffmpeg expression on every layer', () => {
    // A synth layer with no expression would build silence and nothing would
    // say so - the same shape as the cue drops the phase-1 verification pass
    // found in ThrowableSoundService.
    for (const [name, cue] of Object.entries<any>(manifest.cues)) {
      if (cue.placeholder) continue;
      for (const [i, layer] of (cue.layers || []).entries()) {
        const src = manifest.sources[layer.source || cue.source];
        if (src?.kind !== 'synth') continue;
        expect(layer.lavfi, `cue '${name}' layer ${i} is synth but names no lavfi`).toBeTruthy();
        expect(
          layer.file,
          `cue '${name}' layer ${i} is synth and must not name a file`
        ).toBeFalsy();
      }
    }
  });

  it('is generated, not hand-written', () => {
    const generated = fs.readFileSync(
      path.join(repo, 'src/throwables/cueManifest.generated.ts'),
      'utf8'
    );
    expect(generated).toMatch(/GENERATED by scripts\/audio\/build-throwable-cues\.mjs/);
    expect(generated).toMatch(/DO NOT EDIT/);
  });

  it('has a row for every cue in the JSON, and every row is one of the two states', () => {
    for (const [name, entry] of Object.entries(THROWABLE_CUE_MANIFEST)) {
      expect(manifest.cues[name], `cue '${name}' is not in the manifest JSON`).toBeTruthy();
      if (entry.placeholder) {
        expect(entry.fallback, `placeholder '${name}' names no legacy recipe`).toBeTruthy();
      } else {
        expect(entry.license, `cue '${name}' has no licence`).toBeTruthy();
        expect(THROWABLE_CUE_ALLOWED_LICENSES, `cue '${name}'`).toContain(entry.license!);
      }
    }
  });

  it('ships both containers for every non-placeholder cue', () => {
    // Opus for everything, AAC for Safari. A cue with only one of the two is
    // silent for half the userbase, which is worse than a placeholder because
    // nothing counts it.
    for (const [name, entry] of Object.entries(THROWABLE_CUE_MANIFEST)) {
      if (entry.placeholder) continue;
      for (const ext of ['webm', 'm4a']) {
        const f = path.join(soundsDir, `${name}.${ext}`);
        expect(fs.existsSync(f), `${name}.${ext} is not built`).toBe(true);
        expect(fs.statSync(f).size, `${name}.${ext} is empty`).toBeGreaterThan(256);
      }
    }
  });

  it('publishes CREDITS.md, even though CC0 does not require it', () => {
    const credits = fs.readFileSync(path.join(soundsDir, 'CREDITS.md'), 'utf8');
    expect(credits).toMatch(/Kenney/);
    expect(credits).toMatch(/CC0-1\.0/);
    for (const [name, entry] of Object.entries(THROWABLE_CUE_MANIFEST)) {
      if (entry.placeholder) continue;
      expect(credits, `${name} is not credited`).toContain(`\`${name}\``);
    }
  });

  it('every placeholder names a recipe the legacy service actually has', () => {
    const svc = fs.readFileSync(path.join(repo, 'src/services/ThrowableSoundService.ts'), 'utf8');
    for (const [name, entry] of Object.entries(THROWABLE_CUE_MANIFEST)) {
      if (!entry.placeholder) continue;
      expect(svc, `placeholder '${name}' falls back to unknown recipe '${entry.fallback}'`).toMatch(
        new RegExp(`\\b${entry.fallback}:\\s*\\(\\)`)
      );
    }
  });

  it('records how many cues are still placeholders, so the number can only fall', () => {
    // Phase 1 ships four real cues from Kenney CC0 and four placeholders that
    // need a Freesound CC0 take (phase 6). This number is a ratchet: raising
    // it means a rig started depending on a sound nobody has sourced.
    const placeholders = Object.values(THROWABLE_CUE_MANIFEST).filter((e) => e.placeholder).length;
    expect(placeholders, 'more placeholder cues than phase 1 shipped').toBeLessThanOrEqual(4);
  });

  it('no spec asks for a cue that is neither built nor declared', () => {
    for (const s of allSpecs()) {
      for (const cue of s.audio) {
        expect(
          THROWABLE_CUE_MANIFEST[cue.sample],
          `${s.id} names unknown cue '${cue.sample}'`
        ).toBeTruthy();
      }
    }
  });
});
