\set ON_ERROR_STOP on

DO $roles$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN BYPASSRLS;
  END IF;
END;
$roles$;

CREATE SCHEMA auth;
CREATE SCHEMA cron;

CREATE TABLE auth.users (
  id uuid PRIMARY KEY
);

CREATE TABLE public.clubs (
  id uuid PRIMARY KEY
);

CREATE TABLE public.tournaments (
  id uuid PRIMARY KEY,
  status text NOT NULL
);

CREATE TABLE public.tables (
  id uuid PRIMARY KEY,
  tournament_id uuid
);

CREATE TABLE public.tournament_players (
  id uuid PRIMARY KEY,
  tournament_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status text NOT NULL,
  chips numeric NOT NULL DEFAULT 0,
  table_id uuid,
  seat_number integer
);

CREATE TABLE public.table_seats (
  id uuid PRIMARY KEY,
  table_id uuid NOT NULL,
  user_id uuid,
  seat_number integer NOT NULL,
  stack numeric NOT NULL DEFAULT 0,
  left_at timestamptz
);

CREATE TABLE public.chip_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE OR REPLACE FUNCTION public.fn_entry_purchases_frozen()
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path TO 'public','pg_temp'
AS $function$
  SELECT true;
$function$;

CREATE TABLE cron.job (
  jobid bigint PRIMARY KEY,
  schedule text NOT NULL,
  command text NOT NULL,
  nodename text NOT NULL,
  nodeport integer NOT NULL,
  database text NOT NULL,
  username text NOT NULL,
  active boolean NOT NULL,
  jobname text NOT NULL
);

CREATE TABLE cron.job_run_details (
  jobid bigint NOT NULL,
  job_pid integer,
  database text,
  username text,
  command text NOT NULL,
  status text NOT NULL,
  return_message text,
  start_time timestamptz NOT NULL,
  end_time timestamptz
);

CREATE OR REPLACE FUNCTION cron.alter_job(
  job_id bigint,
  schedule text DEFAULT NULL,
  command text DEFAULT NULL,
  database text DEFAULT NULL,
  username text DEFAULT NULL,
  active boolean DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE cron.job AS j
     SET schedule=COALESCE($2,j.schedule),
         command=COALESCE($3,j.command),
         database=COALESCE($4,j.database),
         username=COALESCE($5,j.username),
         active=COALESCE($6,j.active)
   WHERE j.jobid=$1;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'probe cron job % does not exist', $1;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION cron.unschedule(job_id bigint)
RETURNS boolean
LANGUAGE plpgsql
AS $function$
DECLARE
  v_rows integer;
BEGIN
  DELETE FROM cron.job AS j WHERE j.jobid=$1;
  GET DIAGNOSTICS v_rows=ROW_COUNT;
  RETURN v_rows=1;
END;
$function$;

INSERT INTO cron.job(
  jobid,schedule,command,nodename,nodeport,database,username,active,jobname)
VALUES
  (9001,'*/5 * * * *',
   'SELECT public.fn_ca_eliminate_absent_tournament_players()',
   'localhost',5432,'postgres','postgres',true,
   'ca-eliminate-absent-players'),
  (9002,'*/5 * * * *',
   'SELECT public.fn_ca_release_broke_seats()',
   'localhost',5432,'postgres','postgres',true,
   'ca-release-broke-seats');
