name: Run SQL
on:
  push:
    branches:
      - chore/run-sql
jobs:
  run-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Run SQL 1
        run: psql "postgres://postgres:215SlalomCt%21%21@db.kuklfnapbkmacvwxktbh.supabase.co:5432/postgres" -f supabase/migrations/20260821_leaderboard_by_dates_rpcs.sql
